### ISSUE TITLE
More recent legacy downloads for client files

### ISSUE THREAD

**Issue by Fevix** [EpochModTeam/Epoch#1012]
I started a server on nitrado, and the most recent version they have is 1.3.2. I cannot find this version for download anywhere. The Epoch downloads page jumps from 1.3.3 to 1.2-something.

**Comment by Abe1100** [comment]
If the server hasn't loaded then client or servers files for your version you want to install, you may have to upload the files yourself using their recommended file transfer method, I stopped using server providers for that same reason

**Comment by Fevix** [comment]
I tried this and now it's saying that my files aren't signed by accepted keys or something

**Comment by Ignatz-HeMan** [comment]
Make sure you have also added the epoch133.bikey into your servers keys folder.
You can find the key within the client files (@epoch\keys)

**Comment by Fevix** [comment]
I've done that.

**Comment by Ignatz-HeMan** [comment]
But?
Maybe you should join our Discord and discuss it there. 
Upload your Server and Client logs there and we can have a look on them.
Would be much easier...
https://discord.gg/0k4ynDDCsnMzkxk7
