### ISSUE TITLE
Gas Station Bug...

### ISSUE THREAD

**Issue by ByPretendersDev** [EpochModTeam/Epoch#1013]
Hello ... I was playing Mod Epoch Arma 3 "version EpochModTeam 1.3.3.1546", Find a Car ... I noticed it and stopped by the gas station and filled it up, I couldn't get out of the gas station, I lock the steering wheel and the car doesn't move more ... and the noise of filling gasoline makes ...
Thank you...

**Comment by Ignatz-HeMan** [comment]
This sounds like an Arma Bug, not related by EpochMod.
Sorry, but we are unfortunately not able to fix this :(
