### ISSUE TITLE
[QUESTION] No NPC spawning

### ISSUE THREAD

**Issue by Parkos** [EpochModTeam/Epoch#1014]
Hi!

Is my first time setting up a dedicated server and i chose to rent a nitrado one. I supposely have configured Epoch with Ryan Zombies and Demons, the server loads it but the map is empty, just the loot, no NPCS.

Any help for a newbie?

**Comment by Abe1100** [comment]
For setting up a server, ask your question on discord, and or search Google for Epoch forums, There are alot of helpful tips etc. 
https://epochmod.com/

**Comment by Ignatz-HeMan** [comment]
The upcoming update (EpochMod 1.3.3.1) will have a build in Zombie Spawner for RyanZ.
We are going to push it within in the next few days! 
If there are still any issues then, let us know...
