### ISSUE TITLE
Arma 3 CBA bug

### ISSUE THREAD

**Issue by SamuelLiasam** [EpochModTeam/Epoch#1015]
Whenever I try to launch my Arma 3 via A3sync or the launcher I get this message;
file x/cba/addons/ee/config.cpp, line 12: 'Cfgvehicles/B_W_Story_Protagonist_01_F.XEH_ENABLED': ';' encountered instead of '='
Can anyone please help me?

**Comment by morgoth0** [comment]
Not an Epoch issue...

**Comment by SamuelLiasam** [comment]
To who do I need to write instead?

**Comment by Ignatz-HeMan** [comment]
Sounds like a CBA issue?!
https://github.com/CBATeam/CBA_A3

**Comment by SamuelLiasam** [comment]
Thank you kindly!
