### ISSUE TITLE
Question: How To adjust trader pricelist

### ISSUE THREAD

**Issue by hbeni** [EpochModTeam/Epoch#1021]
Hello,
is there a way to configure the baseline price level of all traders?
I want to make the traders more expensive right from the start (i know the tax config option, but this is not what i need).

Especially the black market traders, I want to make them more expensive right from the start.

**Comment by Ignatz-HeMan** [comment]
You can adjust an overall tax for the trader price here:
https://github.com/EpochModTeam/Epoch/blob/d063b49de3f51068321ed069ae3fe1e51823d04e/Server_Install_Pack/%40epochhive/epochconfig.hpp#L155

And you can set the multi for the black market prices here:
https://github.com/EpochModTeam/Epoch/blob/d063b49de3f51068321ed069ae3fe1e51823d04e/Sources/epoch_config/Configs/CfgBlackMarket.hpp#L10

Or you can also define your own black market prices here:
https://github.com/EpochModTeam/Epoch/blob/d063b49de3f51068321ed069ae3fe1e51823d04e/Sources/epoch_config/Configs/CfgBlackMarket.hpp#L20

**Comment by hbeni** [comment]
Thank you for your answer.
If I understand right, I need to bundle a new epoch mod pack for clients and server if i change this, correct?

or can i overwrite the black market multipliers in the overall config where the tax variable is also set?

**Comment by Ignatz-HeMan** [comment]
You have to unpbo your mission file, make your changes in the files and repack it.
For more Infos, you will get faster responce in our Discord, I think…
https://discord.gg/0k4ynDDCsnMzkxk7
