### ISSUE TITLE
Duping still possible

### ISSUE THREAD

**Issue by Nasdero** [EpochModTeam/Epoch#103]
Hi folks,

I don't know how ecxactly, but I know, that you can dupe clothes when you killed the AI whith the drone mission! I guess you will find out how it is done, but for sure it is possible.

Kind Regards,
Nasdero

**Comment by Nasdero** [comment]
Ok guys, I know now how it works, did not tested it, but I know that it works.

So wear a Ghillie, kill a NPC, replace your Ghillie with the clothes form the NPC, the NPC drops 2 Ghillies.

**Comment by vbawol** [comment]
Custom traders? I don't think we have any non civilian units as traders for this reason.

**Comment by Nasdero** [comment]
What do you mean with custom traders? I wasn't talking about traders, I was talking about the three NPC when a drone triggers you.

**Comment by vbawol** [comment]
uniform duping is a know issue and will require some fixes from BI.
- [ ] Open Ticket with BI

**Comment by vbawol** [comment]
I think this was addressed with 1.44, if not reopen.
