### ISSUE TITLE
M107 accuracy at distance

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/Epoch#106]
Issue: Currently the M107 accuracy is terrible at range, even in prone position and pausing breath, the bullet is extremely off at ie. 800m.

Propose improving the accuracy at range

**Comment by LaggedToDeath** [comment]
What Scope where you using ?, I've noticed that with some gun's and some scopes you need to drop or increase the Zeroing to where the bullet is landing.

I hope this makes sense

**Comment by ZNUfisk** [comment]
No, I am aware of zeroing and bullet drop, this is a bullet spread-effect, ie. the bullet lands unpredictably off target at longer distances - similar to an assault rifle if you know what I mean.

**Comment by LaggedToDeath** [comment]
Have you noticed that the new Epoch Weapons each have two Versions on Good one (No Rust on weapon model), and a rusty Version of that Weapon (lots of rust on weapon model).

To date Ive noticed that these weapons M4A3, M16, M14 (Green and Red), and M107 all have two version as listed above.

I,m yet to delve in to file to see how much difference there is in the Stats for the Non-rusty vs the Rusty version of these weapons

**Comment by ZNUfisk** [comment]
Also, M107 makes the same level of sound at 800m as it does at 50m :S

**Comment by vbawol** [comment]
0.3 should fix this, reopen if not,
