### ISSUE TITLE
I can sell a nearly empty magazine and I'll get the full price

### ISSUE THREAD

**Issue by Nasdero** [EpochModTeam/Epoch#108]
Hi folks,

when I sell a nearly empty magazine and I'll get the full price, same with energy packs, when I buy it back, I have to pay the 10% extra charge and I got a full magazine or ebergy pack.

Lower the price for used items, a energy pack with only 1 of 10 left, should not bring the same when I sell it.

Kind Regards,
Nasdero

**Comment by orangesherbet** [comment]
maybe, but the way it was dealt with was to increase the purchase price to buy it back- perhaps the price for magazines just needs to be up a bit more

**Comment by vbawol** [comment]
ammo is taxed higher on the purchase price due to this that 10% is the restocking fees and is controllable via the server it.
