### ISSUE TITLE
Vehicle farming with the chopper

### ISSUE THREAD

**Issue by Nasdero** [EpochModTeam/Epoch#109]
Hi folks,

what I saw on different server (also on A2 Dayz Epoch), that ppl lift all the cars on the map (mostly after the serverrestart) and sell them, so that other ppl without chopper or car can not find other cars.

You can disable lifting, or you can do a timer on lifted vehicles, so that vehicle that has been lifted in the last 30 mins for example, can't be sold and maybe are not able to lock (for the story, the paint of the car is now bad cause of lifting / the locks are broken cause of the lifting). That will prevent, that single player with a chopper can farm the cars on the map that quick.

Kind Regards,
Nasdero

**Comment by vbawol** [comment]
This should be resolved in the engine now if I am not mistaken as BI added a check to disallow lifting though objects.
