### ISSUE TITLE
Desync with Debug Menu

### ISSUE THREAD

**Issue by Mystykall** [EpochModTeam/Epoch#11]
I can see this being able to be abused in other ways, but when the server is desynced out and I was breaking down a trash pile and was able to run up 30+ soiled from the trash pile without destroying it. If other things are recorded similar than you can spam during desync.

**Comment by vbawol** [comment]
While we are still working to optimize, Debug Menu is client side and cannot have an impact on server performance or desync. Sounds like this issue is related to something else. Make sure your server FPS is higher than 15 even if that means  reducing player count.
