### ISSUE TITLE
Modular building

### ISSUE THREAD

**Issue by Nasdero** [EpochModTeam/Epoch#111]
Hey Folks,

I like this kind of building, but I guess it needs a bit tweaking.

- 1st of all, the free mode, the parts still try to snap or arrange when other buildings around, I hope you can change this, it should be 100% free, then it would be perfect, maybe a option to make it vertical (like horizontal with q), or better, a option to change the angle, would be very nice!

- snap mode, so far so good, when I build a base from scratch and when I follow some "rules", then it works nice, but if you have to replace a part, cause it is gone, or you have a wooden stair, you will run into probs. It would be nice, if you can choose during building, which side of the part should snap

Just build a wooden floor on foundation, place a wooden stair on it, upgrade it, now try to build stud walls around the stairs, you should run into probs.

Or build first 4 stud walls on that floor and try then to place a upgraded stair between that walls.

I run also into probs when I placed a cinder wall on a wooden floor and a stud wall around the corner.

- I'd be also good, if you can place a wooden stair on an other wooden stair.

Keep up the good work! I hope we can get soon some sandbags or other cool stuff :D.

P.S.: I hope we can soon brake down the buildings parts, so if I have a wall, I can brake it down and get the parts back, or brake it down and store it into my backpack, or just a option to brake it down without a refund. It would be also nice to move (empty) tippies / shelf and the jammer like walls after they are placed.

Kind Regards,

Nasdero

**Comment by vbawol** [comment]
Thanks for the feedback! We are going to be reworking the objects and code for base building in for 0.3.
