### ISSUE TITLE
Glitching through wall still possible

### ISSUE THREAD

**Issue by Nasdero** [EpochModTeam/Epoch#112]
Hi folks,

I heard, that you can still glitch through wall, it is the same like it was with "h" when you run in front of a wall, but I will not write it here. So I will write Axle a privat message on http://epochmod.com/forum/ .

or just write me a mail when you got a question nasdero(at)gmx.de

Kind Regards,
Nasdero

**Comment by nerdalertdk** [comment]
You can holster your weaspon and run while going prone throu metal gates, we are having a lot of glitching on our server

**Comment by LaggedToDeath** [comment]
maybe when a player runs into some thing ie. player built Wall, buildings, trees or vehicles, the player should  get knocked  backwards and deal some amount of damage to said player

**Comment by vbawol** [comment]
There is only so much we can do without causing more issues. The best way to solve this would be to push for Arma to make it so the player cannot phase though objects. You can even walk right though a stock Arma 3 H barrier so there is certainly a issue with it.
