### ISSUE TITLE
expiresBuilding should be 8 dayz

### ISSUE THREAD

**Issue by Nasdero** [EpochModTeam/Epoch#115]
Hi,

I guess 8 days makes more sence, with 7 days, if I do a maintain on Monday 18:00, I have to do the next latest Monday 18:00 plus time to next restart, with 8 days I have at least time to 24:00 on Monday.

Regards,
Nasdero

**Comment by nerdalertdk** [comment]
the server owner can change this, we have 21 days on our server
not a bug IMHO

**Comment by Nasdero** [comment]
I know:
expiresBuilding = "604800"; => 7 days
expiresBuilding = "691200"; => 8 days

And I know that it is not a bug, but we post here also our suggestion.
I would prefer 8 days as standart in the server files.

**Comment by vbawol** [comment]
can be easily changed
