### ISSUE TITLE
[Suggestion] Food and Drink replenish health

### ISSUE THREAD

**Issue by scrmjt** [EpochModTeam/Epoch#121]
Similar to Arma 2 Epoch, it would be beneficial to be able to regenerate health slowly when thirst and hunger were maximized (or close to maximum). At this point they seem to serve little purpose beyond preventing fatigue (assuming you don't starve or dehydrate to death).

**Comment by vbawol** [comment]
Thanks for the suggestion, To heal from damage you still need a first aid kit or to be healed with the multi gun attachment. You do die from thirst or hunger now and provided your not hungry or thirsty your your vitals do improve like blood pressure. More will be done to tie each stat to proper effects.
