### ISSUE TITLE
[Bug][v0.3 testing] Sappers exploding outside of range from any player

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#124]
Sappers have been exploding a few minutes after spawning- not near any player.
Recreated this issue a few times, multiple users reporting

**Comment by andgregor** [comment]
The sapper is set to explode if he gets stuck. We could spawn another if this happens ? I have seen him get stuck in a bush and certain buildings. He got frustrated and took it out on the bush.
