### ISSUE TITLE
[Suggestion][v0.3]  Shipping Containers should spawn fewer backpacks, more variety

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#125]
With the increase of backpacks in the environment- the need for backpacks in containers has diminished- would also like to see more variety of the items that spawn in containers

**Comment by Tigah** [comment]
Might be too many guns now. Out of just 3 containers we saw 12-15 guns. which is way too many considering guns already spawn everywhere in the world.

**Comment by vbawol** [comment]
Should be good now, also testing new loot bias system. should be 90% building items 10% weapons

**Comment by orangesherbet** [comment]
tested w/ 5 containers so far, similar building loot- no weapons yet
