### ISSUE TITLE
[Suggestion][v0.3 testing] respawn kick and gender selection 

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#126]
The respawn kick would be confusing for players I believe and gender selection is somewhat annoying to do every time you die. If there was some way to give you the option to choose (as part of a menu) a gender selection or not, that I think would be better, rather than being forced to choose your gender every time.

**Comment by Oshydaka** [comment]
Maybe just add gender selection on ArmA 3 configure menu, where you choose your head ?

So, you will have "men heads", and "women heads"
