### ISSUE TITLE
[Bug][v0.3 testing] No Cultist sighting yet

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#127]
I was on for about 4 day/night cycles yesterday and saw no Cultists at all whilst looting heavily in towns.

**Comment by Tigah** [comment]
this seems to be working now, had a cultist encounter. Damaged and killed.as well.

**Comment by vbawol** [comment]
Thanks for confirming @Tigah!

**Comment by Pmba79** [comment]
Confirmed working aswell.. Got killed at the Center spawn trader..
(Bloody hell they got a lot of HP)
