### ISSUE TITLE
[Bug][v0.3 testing] Removing base pieces during simulation countdown timer

### ISSUE THREAD

**Issue by Philanthropy1** [EpochModTeam/Epoch#128]
When trying to remove a piece while the simulation countdown timer is still ticking down, it will stall it for a few seconds. Then have to enter and exit build mode once the timer has finished to be able to use the remove option. (The timer while the piece is being placed, and still has physics)

**Comment by vbawol** [comment]
please test this again with the latest files

**Comment by Philanthropy1** [comment]
Still stalls the countdown for a while, possibly a little longer though never timed it before. Once that goes can remove it fine though

**Comment by Philanthropy1** [comment]
It is for 15 seconds, then the piece sets, and can remove it as soon as it's set

**Comment by vbawol** [comment]
https://github.com/eltexonline/EPOCHMOD/issues/621
