### ISSUE TITLE
[Suggesiton][v0.3 testing] Weight of clothing may need changing

### ISSUE THREAD

**Issue by Philanthropy1** [EpochModTeam/Epoch#132]
Tried to put the jacket and shorts into a completely empty carry all and it wouldn't fit in.
![2015-02-09_00008](https://cloud.githubusercontent.com/assets/10912691/6110468/ca4fcad8-b079-11e4-8ee5-820c930980f2.jpg)

**Comment by Philanthropy1** [comment]
Just found another jacket and shorts clothing and it went in fine, hardly any weight at all. The original ones that wouldn't fit were reclaimed from my dead body and so may be duped. There was the same clothing where an AI I killed was and not sure which was the original. Will try to recreate

**Comment by Philanthropy1** [comment]
Couldn't replicate this issue - not sure how to delete it

**Comment by Skaronator** [comment]
> not sure how to delete it

just close it ;)
