### ISSUE TITLE
[Bug][v0.3 testing] Vehicle duped on server restart

### ISSUE THREAD

**Issue by Philanthropy1** [EpochModTeam/Epoch#135]
Bought a truck from the spawn trader for 1100 and got in it. Went about 500m down the road and the server restarted. When it cam back up, I was back in the spawn. Had my crypto back, the truck was back in the trader, but the one I spawned in was also back where it spawned when I bought it. Not recreated as seems to be done timed with server going down.

**Comment by vbawol** [comment]
This must be fixed since we have not heard any more reports about it since.
