### ISSUE TITLE
Attn: axeman (script errors during missions)

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#139]
Animal Control http://i.imgur.com/RpJ5UuL.jpg
after sapper has been brought back I get this error

VIP Chauffeur http://i.imgur.com/2TPhnhY.jpg
sometimes after starting the mission I get this error

**Comment by andgregor** [comment]
Animal Control: Did you perform this mission on your own or with help ? Is possible if somebody else triggered the sapper then the sapper fsm can not be reached by the person who triggered the mission. This is required to disable his bomb. Also, did he blow up after being caged ?

VIP Chauffeur: Should be fixed, putting  a PULL request in, with a bunch of bug fixes, shortly.

**Comment by orangesherbet** [comment]
The sapper was stuck in a shipping container near the trader- had spawned there from the track a raider mission.  The sapper exploded and I got that error
