### ISSUE TITLE
Sound from Cultist Fireballs and fire places

### ISSUE THREAD

**Issue by BooNDocKk** [EpochModTeam/Epoch#14]
After getting attacked by the Cultist the sound from the fireball is constant and will not go away unless you relog into the server.  This also occurs with the noises from a fireplace.  I dunno if this is an arma sound issue or something you guys could do about it.

Sorry if this is a duplicate thread im new to using github but figured id at least help out if i could lol

Version 0.1.0.1

**Comment by vbawol** [comment]
fixed by removing the sounds for fireplace for now.
