### ISSUE TITLE
[Bug][v0.3 testing] Mission Rewards Script kick #0 (Axeman)

### ISSUE THREAD

**Issue by Philanthropy1** [EpochModTeam/Epoch#145]
Two of us have been doing the pike's peak mission. When you get clothes in the reward, if you try to put them in your backpack get a script kick #0. Reproduced three times with different clothing.

**Comment by Philanthropy1** [comment]
This also includes vests

**Comment by Philanthropy1** [comment]
Just completed the VIP mission, and the sash bandoleer that was a reward from that gave the same kick.

**Comment by vbawol** [comment]
@andgregor script kick #0 sounds like a BIS function

**Comment by vbawol** [comment]
fixed
