### ISSUE TITLE
[Bug?][v0.3 testing] Accepting Pike's Peak mission removes Crypto

### ISSUE THREAD

**Issue by Philanthropy1** [EpochModTeam/Epoch#146]
Not sure if this is by design, but each time I take on the Pike's Peak mission any crypto I have on me is instantly removed. Have tried 5/6 times with varying amounts, and with the debug open can see the crypto drop to 0 instantly.

**Comment by andgregor** [comment]
Not by design for sure. Will check, Tbh have noticed I have zero crypto on my local dev server most of the time.

**Comment by vbawol** [comment]
fixed
