### ISSUE TITLE
[Feedback] AI missions

### ISSUE THREAD

**Issue by crazymike10** [EpochModTeam/Epoch#148]
So I was trying the AI missions, these are a mixture of bugs and feedback.

Pikes Peak Express: Works fine. Only bug (if at all) would that it detects group member when scanning.

Animal Control: The Sapper spawns regardless of you moving and searching for anyone. Sometimes the Sapper won't spawn at all. 

Track a Raider: Currently does not work. Will not give you the tools in order to begin the mission.

VIP Chaufeur: The AI personal (if spawned) has trouble getting into the vehicle and/or trouble following the person on foot. When at the point of destination, the mission does not complete. For the times when you need to pick up the person, the person is not at the meeting point. When the mission states that it will mark the point on the map, it does not mark it. 

All missions, in my opinion, should be able to be active once per trader. Or at least a time between when you are able to the missions. Ones like Animal Control, could be abused very easily by doing them over and over. The loot in all missions available is pretty good loot.

**Comment by andgregor** [comment]
Pikes Peak: What do you mean, it detects members of your group for what ?

Animal Control: No spawning is going on in the mission. You have to trigger a sapper and then lure it back to the trader.

Track a Raider will put a UAV Terminal in your inventory, if inventory is full we are currently not handling that, there is a hint on one of the Pikes Peak mission dialogues that if you have a full inventory try again later. You should get a message saying, along the lines of, 'You must be busy, come back later' on the UAV mission if you don't accept.

Chauffeur I have completed fully, the map locations do need some work. If it is stating that it will mark the map, there is a newer version out now.

AI missions are a once only deal at the same trader, I have found that you can start a mission at one trader and then another at a new trader. To be worked on.

**Comment by crazymike10** [comment]
Pikes Peak: It will say it will have a drone to follow you, and one thing it will say is that "it detects someone in your area so be careful" - member of your group is the one it's talking about.

Animal Control: You can just stand there and eventually a Sapper MAY spawn. We were trying it at the same trader multiple times, so this could be the issue of the Sapper not always spawning. But twice, the sapper just spawned as I stood in one place not doing nothing.

Track a Raider: Inventory not full, no terminal is placed in inventory. The message "you must be busy, come back later" does come up, but i thought it was just because i took to long to open the terminal.

Chauffeur: we finally got the AI in the car, went to location it said (no markings on map) and the AI didn't get out of the car and the mission was not completed. 


I am about to try all missions here again in a few minutes, if i run into any problems, I'll post my results. By the way, these missions are awesome idea. They seem not too easy, yet a great way to gain inventory. Awesome work.

**Comment by crazymike10** [comment]
Here is a small video - maybe you can let me know what i'm doing wrong - https://www.youtube.com/watch?v=Jqzdptc-5pU

**Comment by andgregor** [comment]
Have put a fix in for the vip not getting in the car. Map locations need updating, 028 is actually 280. Can't zoom the Vid am on my phone. UAV terminal uses additemtovest, should go into first pack, don't know if it will automatically use backpack, probably not. To be added.

**Comment by Tigah** [comment]
for the "Track a Raider" mission, scrolling on terminal then clicking on "open terminal" gives script restriction #54

**Comment by vbawol** [comment]
ref
 [Feedback][v0.3 testing] Missions #176

**Comment by vbawol** [comment]
closing as this is outdated, as of 0.3.9 we are using Axemans new task based system.
