### ISSUE TITLE
[Bug] Land Sharks

### ISSUE THREAD

**Issue by crazymike10** [EpochModTeam/Epoch#149]
As it's less common, Land sharks is still a thing.

http://imgur.com/K5dT6NL

Happened 1 out of 9 sharks i had spawn in.

**Comment by andgregor** [comment]
Occurs when wrecks are close to the shore, if the shark spawns on land it will 'land swim' in the direction it first starts off in. Not designed to spawn on land, deciding the best way to handle this.

**Comment by vbawol** [comment]
added a check to dispose of any sharks that make it to land
