### ISSUE TITLE
[Bug] Foundation and Floors

### ISSUE THREAD

**Issue by crazymike10** [EpochModTeam/Epoch#150]
Hey,

Logged into today and floors and foundations were gone:  http://imgur.com/pA93zOc

So i tried rebuilding and realized foundations do not snap anymore. Tried snapping during the first build, and tried snapping after the foundation was already built. The problem is that you cannot move the foundation after it's placed. 

Today i will and fiddle around with building today to find any other bugs. (02/16/15 2:21 MTN Time)

**Comment by vbawol** [comment]
How long ago did you build them?

need to remove Move option as only remove will work with foundations for now: https://github.com/eltexonline/EPOCHMOD/issues/626

foundation snapping is a known issue and will be fixed: https://github.com/eltexonline/EPOCHMOD/issues/627

**Comment by crazymike10** [comment]
Built 5 days ago

Melly just maintained 2 days ago.

Snapping of the foundations did work a week ago (the links you have provided don't work so i can't read)

**Comment by vbawol** [comment]
https://github.com/EpochModTeam/Epoch/issues/137
