### ISSUE TITLE
[Suggestion] v0.3 Moving and Removing Jammers

### ISSUE THREAD

**Issue by crazymike10** [EpochModTeam/Epoch#152]
Just a suggestion, but would it be possible so that the person that places the jammer down (the group creator) could move or remove the jammer after it's built. 

Problem would be, a person needs a jammer to build. so person puts a jammer down. Begins building, but now has to somewhat work around his/her jammer because he/she cannot move it. If it was movable, or removable, he/she could fix this issue. Would also help with those people who accidentally place the jammer and not be the group creator. 

I'm no coder, but i would think that the jammer is tagged with that player's GUID, so if Jammer A GUID = player A then you should be able to have a special menu pop up for moving and removing? maybe.

**Comment by orangesherbet** [comment]
problem is that you would have the ability to build anywhere, then move the jammer and not worry about the base parts that could be close to where the jammer was. I know that pieces clean up every 7 days but I think that there would be the unintended consequences of base pieces on their own in the middle of roads and that sort of thing. (which occurs in the current version.) Perhaps a way to remove the freq jammer and get half of the materials back. It's a tricky one, and I agree that there should be some method to help those who want to move / remove their jammer but obviously I dont have the answer....
