### ISSUE TITLE
[Bug][v0.3 testing] "Toxicity" / "Wet" Stats not updating in water

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#153]
tested while swimming with no clothing or vest on: Wet remains at zero, Toxicity does not go down- only temperature is affected while treading water or swimming.  Tested for up to 10 minutes in the water and reproduced. Same effect (no change in stats) if you are wearing clothing or rebreather, other vests

**Comment by vbawol** [comment]
should be fixed now
