### ISSUE TITLE
CBA compatibility error

### ISSUE THREAD

**Issue by DarthRogue** [EpochModTeam/Epoch#154]
As discussed on the forums here  there are some errors relating to Epoch working correctly with CBA.  Here is the error that appears to be holding things up:

9:25:48 Attempt to override final function - bis_functions_list
 9:25:48 Attempt to override final function - bis_functions_listpreinit
 9:25:48 Attempt to override final function - bis_functions_listpostinit
 9:25:48 Attempt to override final function - bis_functions_listrecompile
 9:25:48 Attempt to override final function - bis_fnc_missiontaskslocal
 9:25:48 Attempt to override final function - bis_fnc_missionconversationslocal
 9:25:48 Attempt to override final function - bis_fnc_missionflow
 9:25:48 [22806,26.146,0,"XEH: PreInit Started. v1.0.9.140907. MISSINIT: missionName=__cur_mp, worldName=Bornholm, isMultiplayer=true, isServer=false, isDedicated=false"]
 9:25:48 Error in expression <pile = true };

if (BIS_fnc_init && {!_recompile}) exitWith {};  

;

if >
 9:25:48   Error position: <&& {!_recompile}) exitWith {};  

;

if >
 9:25:48   Error &&: Type code, expected Bool
 9:25:48 File x\cba\addons\common\init_functionsModule.sqf, line 22
 9:25:48 Error in expression <pile = true };

if (BIS_fnc_init && {!_recompile}) exitWith {};  

;

if >
 9:25:48   Error position: <&& {!_recompile}) exitWith {};  

;

if >
 9:25:48   Error Generic error in expression
 9:25:48 File x\cba\addons\common\init_functionsModule.sqf, line 22

Looking at that file line(s) notated in the error we see this code:

GVAR(fncInitTest) = {
		if (isNil "BIS_fnc_areEqual_uiNamespace") then { BIS_fnc_areEqual_uiNamespace = uiNamespace getVariable "BIS_fnc_areEqual"; };
		if (isNil "BIS_fnc_init_uiNamespace") then { BIS_fnc_init_uiNamespace = uiNamespace getVariable "BIS_fnc_init"; }; 
		// It seems that in A3 the missionNamespace copy of BIS_fnc_init and all other funcs are delayed in their inits (not available for the Briefing or XEH PreInit Phase. -VM
		
		if (isNil "CBA_fnc_globalExecute") then { diag_log [diag_frameNo, diag_tickTime, time, "CBA_fnc_globalExecute(missionNamespace) is nil!"]} else { //TRACE_1("",CBA_fnc_globalExecute); };
		
		if (isNil "BIS_fnc_areEqual") then { diag_log [diag_frameNo, diag_tickTime, time,"BIS_fnc_areEqual(missionNamespace) is nil!"]};
		
		if (isNil "BIS_fnc_areEqual_uiNamespace") then { diag_log [diag_frameNo, diag_tickTime, time,"BIS_fnc_areEqual(uiNamespace) is nil!"]};
		if (isNil "BIS_fnc_init") then { diag_log [diag_frameNo, diag_tickTime, time,"BIS_fnc_init(missionNamespace) is nil!"]};
		if (isNil "BIS_fnc_init_uiNamespace") then { diag_log [diag_frameNo, diag_tickTime, time,"BIS_fnc_init(uiNamespace) is nil!"]} else { TRACE_1("",BIS_fnc_init_uiNamespace) };
	};

In Epoch a3_epoch_code\compile\bis_functions\initFunctions.sqf we find this code:

RscDisplayLoading_progressMission = nil;

//--- Get existing lists (create new ones when they doesn't exist)
private ["_functions_list","_functions_listPreInit","_functions_listPostInit","_functions_listPreStart","_functions_listRecompile","_file","_cfgSettings","_listConfigs","_recompileNames"];

_functions_listPreStart = [];
_functions_list = call (uinamespace getvariable ["bis_functions_list",{[]}]);
_functions_listPreInit = [call (uinamespace getvariable ["bis_functions_listPreInit",{[]}]),[]];
_functions_listPostInit = [call (uinamespace getvariable ["bis_functions_listPostInit",{[]}]),[]];
_functions_listRecompile = call (uinamespace getvariable ["bis_functions_listRecompile",{[]}]);

//--- When not forced, recompile only mission if uiNamespace functions exists
if (typename _recompile != typename 1) then {
	_recompile = if (count _functions_list > 0) then {3} else {0};
};

//--- When autodetect, recognize what recompile type is required
if (_recompile == 0 && !isnil {uinamespace getvariable "bis_fnc_init"}) then {_recompile = 3;};
if (_recompile == 3 && !isnil {missionnamespace getvariable "bis_fnc_init"}) then {_recompile = 4;};

_file = gettext (configfile >> "cfgFunctions" >> "file");
_cfgSettings = [
	[	configfile,		_file,		0	],	//--- 0
	[	campaignconfigfile,	"functions",	1	],	//--- 1
	[	missionconfigfile,	"functions",	1	]	//--- 2
];
	
_listConfigs = switch _recompile do {
	case 0: {
		[0,1,2];
	};
	case 1: {
		_functions_list = [];
		uinamespace setvariable ["bis_functions_list",_functions_list];
		_functions_listPreInit = [[],[]];
		uinamespace setvariable ["bis_functions_listPreInit",_functions_listPreInit];
		_functions_listPostInit = [[],[]];
		uinamespace setvariable ["bis_functions_listPostInit",_functions_listPostInit];
		_functions_listRecompile = [];
		uinamespace setvariable ["bis_functions_listRecompile",_functions_listRecompile];
		[0,1,2];
	};
	case 2: {
		[0];
	};
	case 3: {
		[1,2];
	};
	case 4: {
		[1,2];
	};
};

Based off what I've seen in the RPT file, the two appear to be fighting with each other, and Epoch always wins.  CBA uses Extended Event Handlers which are depended upon by many mods and addons to be able to run properly, specifically the indoor and distant sound effects with JSRS.  I've also seen the same error server side when trying to use ASR_AI3 mods for added AI realism, so this problem is not limited to clients alone.  

As we know, SQF errors tend to be layered, fixing one problem allows more functions down the line to load, thereby revealing more errors, so there may be more errors present which we won't know about until this particular one is "fixed".  Then we can see what else pops up.

**Comment by vbawol** [comment]
This should not be an issue any longer as we do not change any BIS functions related to this. If you still have issues with CBA and Epoch please reopen.
