### ISSUE TITLE
Land_MPS_EPOCH can't spawn under water

### ISSUE THREAD

**Issue by nerdalertdk** [EpochModTeam/Epoch#155]
Hi

I'm trying to create a treasure hunt water mission and when I'm creating Land_MPS_EPOCH under it will not spawn

```
_mps=createVehicle["Land_MPS_EPOCH",_treasure_pos,[],0.2,"CAN_COLLIDE"];
_mps setVariable["Crypto",ai_crypto_bomb,true];
```
code should be okay ?

**Comment by vbawol** [comment]
might need to use a setposATL to get it exactly where you want it.
