### ISSUE TITLE
[Bug][v0.3 testing] Group System, Player names not displaying in group menu

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#156]
After adding someone as mod in a group, their name will be replaced with "Dead Player" if they disconnect from the server

**Comment by vbawol** [comment]
this should be fixed as of 0.3.8.0438 we now get the name from the database if the player is not online.|

https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_server/compile/epoch_group/EPOCH_server_updatePlayerGroup.sqf#L61-L69
