### ISSUE TITLE
[Suggestion] Walls w/ Windows(requires glass panes)

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#160]
This may be a stretch, but in the future- being able to collect sand from the beach with an improvised tool, collected into jars or a larger receptacle?  This sand could be used to make mortar buckets as well as glass panes with a fire source. The bit about upgrading walls is a little more difficult- perhaps use the glass pane on a corrugated wall to upgrade it? I just think having vision through your base is an essential part of protecting it in the future

**Comment by Pmba79** [comment]
Nice crafting ideas and the walls with windows is indeed needed..

**Comment by vbawol** [comment]
Thanks for the suggestions more focus will be on base building as we get closer to 0.4
