### ISSUE TITLE
(Bug) Uniform glitch

### ISSUE THREAD

**Issue by Pmba79** [EpochModTeam/Epoch#165]
Playing a female char, wearing a female ghillie suit.
Picking up the uniform of a dead male char (AI bandit) and putting it in to the backpack.
A blank slot will appear in the inventory and a duplicate female ghillie will apear on the ground.

Can be recreated..

Video of it : http://youtu.be/N_-_H3bGqRE

**Comment by Philanthropy1** [comment]
I've had this with male clothes as well

**Comment by vbawol** [comment]
If this is still an issue please reopen, will likely need a follow up with BI if so.
