### ISSUE TITLE
[Bug][v0.3 testing] Antagonists spawns seem low

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#166]
Tested for about 4 hours today. I came across 2-3 sappers (including 1 boss sapper) the whole time during looting and no cultists through a whole night cycle. We were heavily looting in towns and military areas. The day before we encountered a lot more cultists, sappers and drones. Came across a couple of drones. Soiled level was at 100.

**Comment by Pmba79** [comment]
Cultist seems to work now..
Got killed by a cultist at the center spawn trader..
(bloody hell they have alot of HP)

"Sry for the wrongly placed post"

**Comment by nerdalertdk** [comment]
@Pmba79 hehe you can't kill inside the spawn trader :)

**Comment by Pmba79** [comment]
I thought of it right after I uploaded :p 
But in that case, shouldn't they somehow be keept out of the trader areas or at least be harmless there ?
