### ISSUE TITLE
[Suggestion] Shoes for female camo wetsuit

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#167]
Poulmba's suggestion: Female should in theory be wearing shoes with the camo wetsuit as a complete camo set because if someone was going to be in camo, they would want their feet covered as well.

**Comment by nerdalertdk** [comment]
+1

**Comment by Pmba79** [comment]
:+1:

**Comment by nerdalertdk** [comment]
@Tigah 

did you chagne the orginal text ?

**Comment by Tigah** [comment]
@nerdalertdk just took v0.3 out as its not necessarily required for this patch but as a suggestion for when they get around to it.

**Comment by orangesherbet** [comment]
the wetsuit has flippers as it is meant to be worn in the water no?

**Comment by Pmba79** [comment]
"the wetsuit has flippers as it is meant to be worn in the water no?"

Not the army style Camo.
It would have boots like the male variant..


.
