### ISSUE TITLE
[suggestion] Eject body from vehicle

### ISSUE THREAD

**Issue by Pmba79** [EpochModTeam/Epoch#169]
If you are in a vehicle that explodes, you will loose all your gear..
How about getting the body to eject from the vehicle if the vehicle explodes ?

**Comment by nerdalertdk** [comment]
Wait til it despawns and relog you, then you can see your body

**Comment by Pmba79** [comment]
Oh ok, didn't know that..
That's kinda new right ?

**Comment by nerdalertdk** [comment]
nope since 0.2.5.1 I think, the always remember to relog, if you don't you can not see your body,
