### ISSUE TITLE
p2p trade rifle with ammo, ammo gone

### ISSUE THREAD

**Issue by Nasdero** [EpochModTeam/Epoch#17]
Hey folks,

I traded a rifle with an other player, there was ammo in that rifle, the other player received the rifle, but the ammo was gone.

Kind regards,
Nasdero

**Comment by vbawol** [comment]
(Pending: A3 command to manipulate weapons + attachments in cargo space)
tracking here: https://github.com/EpochModTeam/Epoch/issues/411
