### ISSUE TITLE
[Feedback][v0.3 testing] Loot 

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#170]
Containers: Need to be a mixture I think of weapons and building materials. Maybe a rare item i.e lockbox with low spawn chance. 

Shipwrecks: seem good for loot but found few unique gems, mainly gold nuggets, gold ore. silver blocks.

Tool Racks: Did not find any sledge hammers or chainsaws on tool racks. 

Pelican Cases: Need to see more weapons spawning in Pelican cases. Sometimes just grenades or weapon clips. Would be nice to see more weapons as they were not found too often in other furniture as well.

Food and drink: seemed plentiful. Kind of makes jars of water and raw meat less of a necessity. In saying that though, perhaps in a survival world you would want the main food and drink sources to be in the towns anyway to help draw people into the towns and people who choose to live outside of the towns would be able to survive buy killing animals and refilling jars of water. Lots of snooters!

Other loot hard to find: Mortar, Vehicle attachment, revive attachment, GPS

Rewards for Missions: I realize it's still WIP but way too much loot is given as reward for the missions. The missions are not that hard IMO, so I can see a lot of trader camping and groups overpowering single players to gain and hoard loot from these missions.

**Comment by vbawol** [comment]
Loot has been tweaked, looking forward to more feedback on this in future patches.
