### ISSUE TITLE
[Suggestion] Vehicle textures 

### ISSUE THREAD

**Issue by Pmba79** [EpochModTeam/Epoch#174]
Well, my opinion straight out, is that the vehicles (all vehicles) should be re-textured to look older-- 
Thinking that it's after the huge apocalypse, so there would be no new vehicles at all,.. right ?
Just the paintjob... they wouldn't give a **** about the looks of the paint..
Should imo look much older, rusted, bruised and battered

(Madmax idea with vehicles, throw *** together and see what works..)

**Comment by vbawol** [comment]
Thanks for the suggestion.
