### ISSUE TITLE
[Feedback][v0.3 testing] Missions 

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#176]
I can't help but wonder if the missions are somewhat "simple but involved", meaning there are many components to the missions and completing them but they are very simple in concept.

Gamers are very helpless creatures. They don't like to read stuff, they want to look at a map or beacon or something that indicates where they need to go. The messages popping up are in very small font and hard to read, especially in the heat of battle, I can see a lot of players scratching their heads and wondering around with half-achieved missions. So in other words, possibly need fewer, simple messages, slightly larger text and in a different color (perhaps green?). Also I believe missions need to be more time critical. I believe there should be at least 10 mins or more between each mission taken to ensure less load on server performance.

There should be less reward for missions (too easy to achieve) and encourages trader camping and hoarders.Even with less loot, having a higher risk factor and value attached to traders makes the traders more vulnerable to being killed off and less player interaction with traders to sell/buy IMO.

Other than that the VIP and Animal control missions are very cool on how they are executed and completing them makes it even more fulfilling.. 

Just thought I would give my 2 cents after a week or so of testing the missions now.

**Comment by andgregor** [comment]
That's great, am working on some updates, hopefully some additions too.
