### ISSUE TITLE
[Bug][0.2.5.2] Magical Carpet ( Fly Glitch )

### ISSUE THREAD

**Issue by splitx0** [EpochModTeam/Epoch#179]
http://epochmod.com/forum/index.php?/topic/32604-magical-carpet-fly-glitch/

Hi everyone i was playing on unnamed server as player and accidentaly i was able to fly with build mode and wooden floor ( If you think this must kill you then you are wrong. You just have to do it properly.. ).

I wanted it post on youtube.com but i didn't record it. So as an ADMIN i recorded it ( on another server ) with similar conditions but as you can see i have GOD Mode in this time...
 
I was able to get up to 4000 meters up in the sky and with proper training this bug can be used as FLY GLITCH. Using HOME or END will get you from fly.
 
https://www.youtube.com/watch?v=vgz7R03C0pI

**Comment by Pmba79** [comment]
I have seen this before..
We recorded this a fair bit ago :

http://youtu.be/Yl4FoMWviBQ?t=48s

**Comment by vbawol** [comment]
0.3 should be better with this. if not reopen.
