### ISSUE TITLE
[suggestion] Building: Object rotate with more manipulation and angle options 

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#181]
Possibly a bit late for this update but later down the line perhaps? it would be great to be able to rotate the building objects with more options on angles and positions in order for you to manipulate building pieces. For example. Being able to rotate a floor in a vertical position or on a 45 degree angle, without having to use other means ot get the building pieces to sit in those positions.

**Comment by vbawol** [comment]
@Tigah Thanks for the feedback! tracking #583 here.
