### ISSUE TITLE
[Suggestion] v0.3 Looting results in multiple of the same items (antagonist, furniture, trash piles)

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#183]
Version 0.3

Bug Description: Looting results in multiple copies of the same item. i.e. kill a sapper receive 3 whiskey noodle

Severity: Medium

Steps to Reproduce: Loot a trash pile, furniture, or antagonist

Actual Behavior:  Clothing / vests, food/drink, backpacks in trash piles, all items on sappers / cultists seem to show up in multiples

Expected Behavior: More variety in the loot from trash, furniture, antagonists

Troubleshooting/Testing Steps Attempted: Several hours of looting / killing antagonists

Workaround
N/A

**Comment by vbawol** [comment]
fixed
