### ISSUE TITLE
[Bug][v0.3 testing] Jack not able to be used without freq jammer present

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#184]
Versions
0.3

Bug Description
Jack cannot be placed without a frequency jammer in range

Severity
Medium

Steps to Reproduce
Attempt to use Jack without a freq jammer in range

Actual Behavior
Does not work without frequency jammer present

Expected Behavior
Use anywhere in the world without restriction, except near someone elses' frequency jammer

Troubleshooting/Testing Steps Attempted
N/A

Workaround
N/A

**Comment by vbawol** [comment]
fixed
