### ISSUE TITLE
Player movement stuck after respawn

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#185]
After dying and loading back in, a player chooses their gender and it's right then when sometimes the players movement is stuck. You can get out of the stuck position by volting but just seems like a little bug. Have had this issue occur multiple times.

**Comment by Pmba79** [comment]
Confirmed, happened several times..

**Comment by Ignatz-HeMan** [comment]
I think this issue is already fixed / gone.
Not happened for a long time for us.

**Comment by vbawol** [comment]
Thanks for confirming @Ignatz-HeMan
