### ISSUE TITLE
[Bug][v0.3 testing] Boat spawning on land

### ISSUE THREAD

**Issue by Pmba79** [EpochModTeam/Epoch#187]
Bought a boat from the center spawn trader twice, it spawned on land both times, even with a smoke grenade marking the spot..

http://imgur.com/a/X30EH

"Sherb confirmed."

**Comment by vbawol** [comment]
ref 
[Bug][v0.3 testing] Boat not finding water #134

**Comment by vbawol** [comment]
Fixed in 0.3.4
