### ISSUE TITLE
[Suggestion] Player / Supply / Demand based economy

### ISSUE THREAD

**Issue by scrmjt** [EpochModTeam/Epoch#189]
Player based economy / trader.

Pricing based on supply and demand, the more items that are sold to traders, the lower the cost, the more items that are purchased from traders the higher the cost.

Pricing could also be based on total trader inventory. Or spawn %, pickup % etc.

Also see the pricing spreadsheet I delivered to Quish :)

**Comment by vbawol** [comment]
thanks for the suggestion! this will be taken into consideration for future updates.
