### ISSUE TITLE
[Bug] After creating a party Hexes do not appear

### ISSUE THREAD

**Issue by scrmjt** [EpochModTeam/Epoch#191]
Created a new party, invited three other players. No other players displayed hexes for the party leader, but players could see each other's hexes (minus the party leader's hex).

0.3 RC

**Comment by Pmba79** [comment]
Old bug, relog..

**Comment by vbawol** [comment]
can anyone confirm if this is still an issue?

**Comment by Ignatz-HeMan** [comment]
Not always, but sometimes.
Confirm

**Comment by Ignatz-HeMan** [comment]
Should be fixed in Experimental

**Comment by vbawol** [comment]
Can confirm that you fixed it, Good job @Ignatz-HeMan !
