### ISSUE TITLE
[Suggestion] Crypto Phone Blink

### ISSUE THREAD

**Issue by scrmjt** [EpochModTeam/Epoch#195]
Crypto seems a little hard to find for me (personally) -- a cool touch would be a blinking cell phone screen or maybe a ringer? to help find it on the ground.

**Comment by Ignatz-HeMan** [comment]
It is not only hard to find. If the Phone lays on a Wooden Floor, you are not able to get the menu "take Krypto".
For that, we have disabled this function completely and I set a Serverside Krypto Variable on the Corpse after death. Then you have an spacebar menu "search for Krypro" on the Corpse.

**Comment by vbawol** [comment]
@Ignatz-HeMan That sounds like a good idea. I have added this for 0.4 
- remove phone and add crypto to player body.
- Use dynamic action menu for take option on dead player bodies.

Please check if I missed anything: 
https://github.com/EpochModTeam/Epoch/commit/4ea5404cd5c805cf076270bc8f0f023f79c240b2

**Comment by Ignatz-HeMan** [comment]
@vbawol, looks good, but...
I propose to give the Action Menu, also if the dead body has no Crypto.
Often the Corpse is hard to get in target and if the Action Menu only comes up, if the body have crypto, the Player will try very often.
So if there are no Crypto, yust give a message "No Crypto found"

**Comment by vbawol** [comment]
Ya sounds good, this commit should accomplish just that: https://github.com/EpochModTeam/Epoch/commit/e2d621a4c8894ca9ab2a17aae9c1820419f3fb71

**Comment by vbawol** [comment]
Going to close this issue as we are now dealing with a new set of parameters now with the changes due in 0.4. Please feel free to post any pull requests or issues about this.
