### ISSUE TITLE
[Bug][v0.3] Trash pile spawns helicopter as loot

### ISSUE THREAD

**Issue by Pmba79** [EpochModTeam/Epoch#196]
Version 0.3

Bug Description: Heli spawn as loot in trash piles, explodes on spawn,..

Severity: Medium

Steps to Reproduce: Loot a trash pile.

Actual Behavior: Spawns in as regular loot, but detonates on object collision on spawn

Expected Behavior: Kiling the player immediately.

Testing Steps Attempted: Looted atleast 100 trash piles, happened twice..

Workaround: ?

http://imgur.com/a/DxZkv

**Comment by vbawol** [comment]
a workaround has been added to the current server build to prevent this issue,
