### ISSUE TITLE
[Suggestion][v0.3/1.40 RC testing] Too many Sappers?

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#198]
Although I enjoy the constant trolling by Sappers, they will drive players off servers in droves, the rage quits will be plenty IMO. Also boss sappers a little too common. I got killed by probably 3 sappers today, one because I didn't have time to recoup fast enough from running from one sapper so ended up dying when I couldn't shake my fatigue and a boss Sapper took me down.

**Comment by Pmba79** [comment]
I hate to agree, but it's kinda wild..
1 Sapper pr 3-4 trash piles is a bit extreme...

**Comment by DarthRogue** [comment]
No!!  MORE sappers please!  There needs to be a feel of constant danger, otherwise it's no longer a survival sim.

**Comment by Pmba79** [comment]
Not gonna work out in the long run..
It still needs to be playable or the community will go totally apeshit if they can't get the game started.. (talking about getting killed before you manage to loot up)
- 1 sapper pr. 3-4 trash piles are just to many..
You loot a scrap metal, a coke and a vehicle rep part and then you'll have to kill a sapper, then you loot 3-4 more and have to kill another one, all while the drone fly above and the cultist is creaping up on you.. 
It's just to much for the regular players..

**Comment by Skaronator** [comment]
We will change the way how you trigger it. Currently is it on looting, new system will be a loop with some conditions like:
* being in a city
* shots fired

and some more

**Comment by DarthRogue** [comment]
Avoiding multiple sappers isn't that hard. You just have to play tactically and watch your ingress and egress points. If you learn how to move around properly you can easily dodge several at once. I had three on me the other night while I was unarmed and managed to escape just fine. It was pretty exciting for a while though.

**Comment by vbawol** [comment]
mells house has new antagonist spawn bias system can you report if this has improved.

should be about a 50% for UAV's and 20/20 sapper/culistis(if at night) and the Boss sapper and Phantom should be more rare at about 5%

**Comment by Tigah** [comment]
Sounds much better, I'll check it out and report back.

**Comment by scrmjt** [comment]
Seems slightly better -- the spread of encounter types is fine. I would still say the likelyhood of encounter could be tuned back 50% and still spice things up. (e.g. half as many sappers/drones/etc.)

**Comment by scrmjt** [comment]
An additional comment, UAV's seem to be VERY frequent in cities. I believe it's further exacerbated by the fact that you have to shoot in a city to kill a UAV, thus spawning another UAV... especially in a group. We had 4-5 UAVs in a 10 minute period. Can there be a global minimum timer for antagonist spawns... 1 every 10 minutes would be a lot.

**Comment by Pmba79** [comment]
I have been spending a bit time expanding the base and it seems like a
sapper is spawning every 5 to 10 min around the base area..
Is this the "anti-camping-thingy" or am I just a sapper-magnet ?

2015-03-16 1:22 GMT+01:00 scrmjt <notifications@github.com>:

**Comment by vbawol** [comment]
This should be mostly resolved for 0.3.0.4
