### ISSUE TITLE
[BUG] v0.3 SR-25 missing texture error

### ISSUE THREAD

**Issue by DarthRogue** [EpochModTeam/Epoch#200]
Got this error while running around this morning on Mell's.  Did not find an SR-25 anywhere around though, despite looting a few furniture items in nearby buildings.  Could have been carried by another player and I just didn't see them.

http://i.imgur.com/snlRLcf.png

**Comment by Pmba79** [comment]
Axeman got that error aswell yesterday..

**Comment by vbawol** [comment]
Should be fixed with current dev build, please make sure you delete @epoch and install fresh from bit sync.
