### ISSUE TITLE
[Bug] 0.3.0 - Inventory items disappearing

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/Epoch#201]
Video report of it happening
http://www.twitch.tv/tobiassolem/c/6220401

Game-mechanic: Looting system
Description: The interaction and storage of looting items into vests and backpacks from corpses or loot containers. 

Server: Mells 
Date: 2015-02-28
Player name: Tobias Solem
Time: 20:15 (CET)
Connection status: 111ms, stable connection (50 server fps) no desync

Experienced behavior: While looting my old corpse or other containers, the items disappeared regardless whether I dragged and dropped or right-clicked. Weapons transferred as intended. Tried to transfer items from several types.

Expected behavior: Looting items from a corpse or container transfers the intended items.

**Comment by Pmba79** [comment]
I have had items disapearing like this aswell, but only on the dev server while testing..

**Comment by vbawol** [comment]
Reports are that this is a bug with Arma 1.40 and should be fixed with the 1.40 hotfix.

**Comment by vbawol** [comment]
please reopen if not fixed
