### ISSUE TITLE
[BUG] 0.3.0 L85A2 ammo not working

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/Epoch#202]
Video report of it happening
http://www.twitch.tv/tobiassolem/c/6220550

Game-mechanic: Inventory handling/weapon-magazines
Description: The ammunition spawning and handling in different weapon-types, in this instance the pink L85A2.

Server: Mells
Date: 2015-02-28
Player name: Tobias Solem
Time: 20:35 (CET)

Connection status: 98ms, stable connection (50 server fps) no desynch

Experienced behaviour: When looting the pink L85 it spawned with an "invisible" 30 round 5.56 NATO magazine that disappeared as I placed it into inventory. 30 round 5.56 STANAG did not work.

Expected behaviour: L85 should spawn without a magazine, and IF it should spawn with magazines they should be of the appropriate type.

**Comment by vbawol** [comment]
[Fixed] rvmat texture path issues with Pink L85A2
[Changed] SR-25 and L85a2 use existing ammo now.
