### ISSUE TITLE
[Suggestion] 0.3.0 - UAV spawning

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/Epoch#203]
Current behaviour: UAV has a chance of spawning when you press inventory button on a container

Suggested behaviour: UAV has a chance of spawning when you enter an area, or randomly in cities.

Reasoning: It kind of breaks immersion when you hear the UAV spawn just as you press "I", you get aware that the two are connected. By disconnecting them the spawning mechanism of the UAV will appear as more organically melded into the game.

**Comment by Skaronator** [comment]
relevant to: https://github.com/EpochModTeam/Epoch/issues/198

**Comment by vbawol** [comment]
This has been resolved as we now persist antagonist spawn values and only spawn one randomly every 10 minutes as of 0.3.0.4.
