### ISSUE TITLE
[Suggestion] 0.3.0 - Adding a strict loot table philosophy

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/Epoch#204]
I think Epoch needs a strict loot table philosophy, meaning that a category of containers at a category of buildings/locations should only spawn a certain group of items, and those items only.

For example:
In playing on 0.3.0 I found a L85A2 inside a filing cabinet, and later a range finder inside a trash pile at an industrial site.

Reasoning:
I think weapons and items should not be found in certain containers, simply because they would either not fit there AND because it's immersion breaking. How a full length weapon can be found in a drawer escapes me.

Some basic suggestions:

Military buildings = 6.5 caliber and higher weapons, optics, military uniforms, NV-goggles, military rations and similar gear

Civilian buildings = Rollins rifles, pistols, civilian clothing, canned food, honey etc.

Industrial buildings = Tools, scrap metal, jerry cans, etc.

Fridge = Only food and consumable drink items
Filing cabinet = Only papers, or possibly office related gear
Civilian bed = Civilian weapons, or maybe a semi-auto 5.56 assault rifle or pistol

**Comment by Pmba79** [comment]
I must say that I don't agree on this..
This will only make people head directly to the military areas and make the rest of the map more or less deserted..

**Comment by ZNUfisk** [comment]
Only if they do not want to find enough to eat or drink or build, and only if they play the game to run around with weapons and facing likely starvation. Going into cities will still be lucrative because there's where you find most of your food, industry materials and similar. Whereas military sites will be an opportune place for those who primarily seek tools to combat with and others who do the same.

Plus, it makes no damn sense to find a Lynx with several magazines in some random desolate civilian building.

**Comment by vbawol** [comment]
This is in the works and the loot system in place should soon accomplish this exact issue.

**Comment by ZNUfisk** [comment]
There still is not a system where you have buildings separated into (ie.):

Civilian/Residential
Industrial
Military

**Comment by vbawol** [comment]
more changes have been made to better focus the types of loot and where it can be found. Closing this issue but will still push for more improvements.
