### ISSUE TITLE
v0.2.5.2 - Wrong entrys in (configFile / cfgWeapons) for Epoch weapons.

### ISSUE THREAD

**Issue by KiloSwiss** [EpochModTeam/Epoch#205]
The EPOCH weapons have wrong categories defined in their config files or iterate from the wrong parent class.
In fact, they are all listet as "Assault Rifles", that includes the M107, the M249, the Chainsaw, etc.

More Details can be found in the Forum: http://epochmod.com/forum/index.php?/topic/32239-howto-get-available-weapons-mod-independent/?p=212186

Before You add new weapons, please fix the issues with the current ones, because continuing on this faulty base of configfiles is definitely not the right way to go!

**Comment by vbawol** [comment]
Thanks for the input, I will see about fixing the base classes on the mg's and sniper rifles but the the chainsaws and others will likely stay as is
