### ISSUE TITLE
Epoch Launcher Feedback

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#207]

**Comment by Pmba79** [comment]
What do you need, how can we help ?

**Comment by vbawol** [comment]
Just use it and report any issues you find

**Comment by HB-Soundy** [comment]
Added a Luncher Issue

**Comment by HB-Soundy** [comment]
And.. Symantec (Norton Internet Security) dedected as a virus:
WS.Reputation.1
http://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99

**Comment by Morphy2k** [comment]
Saving from the window size would be great :-)

**Comment by splitx0** [comment]
http://i.imgur.com/NCVFDnC.png

Look at my screenshot... I have increased my text/buttons size to 125%...

**Comment by splitx0** [comment]
Added issue: #209

**Comment by splitx0** [comment]
Added issue: #210

**Comment by Pmba79** [comment]
Have had a crash on the launcher and an install error,

Don't know what caused this crash : 
![launcher error](https://cloud.githubusercontent.com/assets/11094851/6478900/775245b6-c23c-11e4-8ed6-fac41a5ca615.png)
Error report linked further down.

After 100% download of the mod I tried to install it, but it just gave me this error :
![launcher error2](https://cloud.githubusercontent.com/assets/11094851/6478903/7e81700a-c23c-11e4-89bd-98d3928132e3.png)

--
************** Exception Text **************
MonoTorrent.Common.TorrentException: A hashcheck can only be performed when the manager is stopped. State is: Error
   at MonoTorrent.Client.TorrentManager.<>c__DisplayClassa.<HashCheck>b__9()
   at MonoTorrent.Client.MainLoop.DelegateTask.Execute()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34014 built by: FX45W81RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34239 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
EpochLauncher
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Poul/AppData/Local/Apps/2.0/7Q76915A.EZ3/852V4W2M.JGN/epoc..tion_0000000000000000_0001.0000_c031e4f5a3a3374f/EpochLauncher.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MetroFramework
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Users/Poul/AppData/Local/Apps/2.0/7Q76915A.EZ3/852V4W2M.JGN/epoc..tion_0000000000000000_0001.0000_c031e4f5a3a3374f/MetroFramework.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
MetroFramework.Fonts
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Users/Poul/AppData/Local/Apps/2.0/7Q76915A.EZ3/852V4W2M.JGN/epoc..tion_0000000000000000_0001.0000_c031e4f5a3a3374f/MetroFramework.Fonts.DLL
----------------------------------------
QueryMaster
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Poul/AppData/Local/Apps/2.0/7Q76915A.EZ3/852V4W2M.JGN/epoc..tion_0000000000000000_0001.0000_c031e4f5a3a3374f/QueryMaster.DLL
----------------------------------------
MonoTorrent
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0
    CodeBase: file:///C:/Users/Poul/AppData/Local/Apps/2.0/7Q76915A.EZ3/852V4W2M.JGN/epoc..tion_0000000000000000_0001.0000_c031e4f5a3a3374f/MonoTorrent.DLL
----------------------------------------
MonoTorrent.Dht
    Assembly Version: 0.70.0.0
    Win32 Version: 0.70
    CodeBase: file:///C:/Users/Poul/AppData/Local/Apps/2.0/7Q76915A.EZ3/852V4W2M.JGN/epoc..tion_0000000000000000_0001.0000_c031e4f5a3a3374f/MonoTorrent.Dht.DLL
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------

**Comment by vbawol** [comment]
try going here first and see if it can check your .net 
epochmod.com/EpochLauncher/publish.htm

**Comment by Monegaskeren** [comment]
Installed the launcher with newest aia pack and epoch 0.3 already installed. Got error when joining saying files in documents/arma3 need another key. Then deleted all epoch and aia folders from arma3 main and documents/arma3 and reinstalled with launcher. When trying to join Mells house chernarus through launcher I am dropping out right before I should be entering lobby. It loads some things but I end up in main menu with no error. When joining from the serverlist on EpochMod.com everything works fine. I like your work very much and thank you for your efforts!
