### ISSUE TITLE
EPOCH Launcher -> Multi click on server issue

### ISSUE THREAD

**Issue by splitx0** [EpochModTeam/Epoch#210]
Informace o vyvolání ladění JIT najdete na konci této zprávy,
nikoli v tomto dialogovém okně.

************** Text výjimky **************
System.ComponentModel.Win32Exception (0x80004005): Systém nemůže nalézt uvedený soubor
   v System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   v System.Diagnostics.Process.Start()
   v System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   v System.Diagnostics.Process.Start(String fileName, String arguments)
   v EpochLauncher.frmMain.joinServer(DataGridViewCellEventArgs e, Boolean justLaunch)
   v EpochLauncher.frmMain.gridServers_CellContentDoubleClick(Object sender, DataGridViewCellEventArgs e)
   v System.Windows.Forms.DataGridView.OnCellContentDoubleClick(DataGridViewCellEventArgs e)
   v System.Windows.Forms.DataGridView.OnCommonCellContentClick(Int32 columnIndex, Int32 rowIndex, Boolean doubleClick)
   v System.Windows.Forms.DataGridViewCell.OnMouseUpInternal(DataGridViewCellMouseEventArgs e)
   v System.Windows.Forms.DataGridView.OnCellMouseUp(DataGridViewCellMouseEventArgs e)
   v System.Windows.Forms.DataGridView.OnMouseUp(MouseEventArgs e)
   v System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   v System.Windows.Forms.Control.WndProc(Message& m)
   v System.Windows.Forms.DataGridView.WndProc(Message& m)
   v System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   v System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   v System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Načtená sestavení **************
mscorlib
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
System
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34239 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
EpochLauncher
    Verze sestavení: 1.0.0.0
    Verze Win32: 1.0.0.0
    Základ kódu (CodeBase): file:///C:/Users/SpiRe/AppData/Local/Apps/2.0/RZNC60DE.TD1/0DA1DVKV.B10/epoc..tion_0000000000000000_0001.0000_c031e4f5a3a3374f/EpochLauncher.exe
----------------------------------------
System.Windows.Forms
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MetroFramework
    Verze sestavení: 1.3.0.0
    Verze Win32: 1.3.0.0
    Základ kódu (CodeBase): file:///C:/Users/SpiRe/AppData/Local/Apps/2.0/RZNC60DE.TD1/0DA1DVKV.B10/epoc..tion_0000000000000000_0001.0000_c031e4f5a3a3374f/MetroFramework.DLL
----------------------------------------
System.Data
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34230 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Numerics
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
MetroFramework.Fonts
    Verze sestavení: 1.3.0.0
    Verze Win32: 1.3.0.0
    Základ kódu (CodeBase): file:///C:/Users/SpiRe/AppData/Local/Apps/2.0/RZNC60DE.TD1/0DA1DVKV.B10/epoc..tion_0000000000000000_0001.0000_c031e4f5a3a3374f/MetroFramework.Fonts.DLL
----------------------------------------
System.Windows.Forms.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
QueryMaster
    Verze sestavení: 1.0.0.0
    Verze Win32: 1.0.0.0
    Základ kódu (CodeBase): file:///C:/Users/SpiRe/AppData/Local/Apps/2.0/RZNC60DE.TD1/0DA1DVKV.B10/epoc..tion_0000000000000000_0001.0000_c031e4f5a3a3374f/QueryMaster.DLL
----------------------------------------
mscorlib.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.0.30319.34209 built by: FX452RTMGDR
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Ladění JIT **************
Aby bylo povoleno ladění JIT, musí konfigurační soubor
pro tuto aplikaci nebo počítač (machine.config) mít
v oddílu system.windows.forms nastavenou hodnotu njitDebugging.
Aplikace rovněž musí být kompilována s povoleným
laděním.

Příklad:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Je-li ladění JIT povoleno, budou všechny neošetřené výjimky
odeslány ladicímu programu JIT, který je registrován v počítači,
a nebudou zpracovány tímto dialogovým oknem.

**Comment by vbawol** [comment]
Thanks for feedback, we may release another version at a later date.
