### ISSUE TITLE
[Bug] Died on spawn in the clone room

### ISSUE THREAD

**Issue by Pmba79** [EpochModTeam/Epoch#213]
Version 0.3

Bug Description: Died on spawn in the clone room.

Severity: Low

Steps to Reproduce: Can't reproduce, happened twice on 50 respawns.

Actual Behavior: Spawns in and dies immediately.

Expected Behavior: Spawning normally

Testing Steps Attempted: Respawning, didn't reproduce.

Workaround: ?

http://imgur.com/a/C1LOW

**Comment by vbawol** [comment]
please test 0.3.0.1 and update this issue if it happens again.

**Comment by vbawol** [comment]
closing as we have not had any other reports since.
