### ISSUE TITLE
[Suggestion] Traders Too Full

### ISSUE THREAD

**Issue by scrmjt** [EpochModTeam/Epoch#216]
Since the trader inventory is persistent it would be nice if when any of the trader's items are at maximum capacity, upon server reset, a percentage of those items would be cleared out so that additional items can be sold. Otherwise common items like electronic parts will build up in your bag, unable to be sold.

Alternatively, items could be sold regardless of vendor inventory, with the purchasable inventory never greater than 100.

Thanks for listening :)

**Comment by vbawol** [comment]
Thanks for the suggestion. The idea is to push players around the map by not letting them constantly sell to the same trader.
