### ISSUE TITLE
[Bug] Interplayer Direct Trade Crypto Disappears

### ISSUE THREAD

**Issue by scrmjt** [EpochModTeam/Epoch#217]
Trade between two players.

Person receiving Crypto opens trade window and hits accept.

Player giving Crypto opens trade window, enters Crypto and hits accept.

Crypto leaves player 2's account, but does not transfer to player 1.

**Comment by Pmba79** [comment]
Had this bug today on Mells house Chernarus.

**Comment by vbawol** [comment]
lomg since fixed
