### ISSUE TITLE
bug V0.3.0.1: maul fatigue and weapon vanishing

### ISSUE THREAD

**Issue by moufette** [EpochModTeam/Epoch#218]
-I used a maul (the crafted sledgehammer), and got fatigue to the max (1) and it wouldn't get down.
i had good health and stamina, i drank a few sodas, even tried to use a medikit, but nothing worked. Had to suicide.
- lost a gun while swapping for another one from a cupboard.

**Comment by vbawol** [comment]
thanks for the reports, sounds like you got sick and ran a fever or it was cold. The gun bug is an arma one.
