### ISSUE TITLE
Traders spawn vehicles right on top of themselves

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/Epoch#221]
Description:

If you buy any vehicle, it will spawn it straight on top of the trader, the car will then explode and kill the player and of course the trader.

Expected behaviour:

Traders should not spawn any vehicle unless there is a smoke grenade or chemlight nearby.

**Comment by Pmba79** [comment]
Then what if you don't have a smoke grenade or chemlight ?
Then you can't buy a vehicle or ?

They need to spawn it anyway, just need to fine tune the spawning.

**Comment by ZNUfisk** [comment]
IF the traders spawn like they do now, there simply is no way of doing it without wasting a lot of time, better yet is to just have the player throw a smoke or chemlight and have the vehicle there or have the trader give you an actual chemlight to throw.
