### ISSUE TITLE
Trader spawn locations

### ISSUE THREAD

**Issue by Pmba79** [EpochModTeam/Epoch#223]
Traders seems to spawn quite close to eachother, sometimes within a few feet.
Perhaps there should be a minimum range on how close to another trader the new one can spawn..
Like 500m or 1Km -ish..
That would also send the players around the map when looking for traders, now you can find 4-5 traders in the same small town..
Just a thought.

http://i.imgur.com/5iPtk8O.jpg

**Comment by vbawol** [comment]
https://github.com/EpochModTeam/Epoch/issues/489
