### ISSUE TITLE
[Suggestion] Craftable crude energy packs

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/Epoch#225]
I think we should be able to craft two different types of crude energy packs by gathering certain items:

Recipe one (Electrolyte driven crude battery):
 (circuit boards, electrolyte mix, 2 water filled glass jars and circuitry). 

Recipe two (Solar power panel ("infinite" energy))
(stud wall + solar cell fragments, circuitry, circuit board, large energy cell)
+Whacking a solar panel with the sledge to extract solar cell fragments

Usage for these things are to power a frequency "jammer" (see separate suggestion for frequency jammer)

**Comment by splitx0** [comment]
It should be fine to store energy from player ...
Craft energy packs with just player energy + new item capacitor

**Comment by vbawol** [comment]
Added a similar recipe: 
```
nearby[] = { { "fire", { "ALL" }, 3, 1, "Fire", "fire" } };
recipe[] = { { "CircuitParts", 1 }, { "water_epoch", 1 } };
```
