### ISSUE TITLE
[Suggestion] Frequency jammer power and limitations

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/Epoch#226]
Description:

Instead of having frequency jammers just do what they do infinitely, force players to use energy sources and make frequency jammers dependent on power (such as craftable energy packs, gas powered generators or solar panel generators) to power the frequency jammer, the type of power source will then affect three things:

1. Range of the frequency jammer in meters
2. Amount of maintainable buildables within that range
3. Maintenance "costs"

Then there are three tiers of energy sources:

A gas fueled generator will naturally generate more power output (which will affect the range of the frequency jammer, and the amount of parts it can sustain) but needs to be fueled by fossil fuels ie. once every 72hrs. Costs for maintaining the entire base is also cheaper with this type of power source.

A solar panel power source will generate less power output (which will affect the range of the frequency jammer, and the amount of parts it can sustain) but does not need to be fueled by any external fuels, this makes the frequency jammer last "forever" but the costs for maintaining the entire base becomes a lot more expensive. 

A crafted battery cell will generate the least amount of power, but lasts longer than a gas fueled generator and is the cheapest way to build a base. Crafted crude battery needs to be replaced entirely every 6 days.

This gives the players the choice of:

a) Building a large base, which will require a moderate sum of crypto to maintain and the power source needs to be refueled every 72 hours

b) Building a medium sized base, which will require a large sum of crypto to maintain, but with an essentially infinite power source. 

c) Building a small sized base, which will be dirt cheap to maintain but needs to have its batteries replaced every 6 days.

**Comment by vbawol** [comment]
@ZNUfisk Thanks for the feedback, I will be looking at adding more in game attributes like energy. 
tracking here for now #583
