### ISSUE TITLE
[Bug] Spawning with 5-6k crypto

### ISSUE THREAD

**Issue by Shunon** [EpochModTeam/Epoch#229]
Happens to all in our squad, we die and spawn with crypto.

**Comment by Yarwood** [comment]
Can confirm this is happening on the WTP Server.
Three of us in a group respawned within the same 120 seconds and we had the same amount of Crypto.

**Comment by vbawol** [comment]
Looking into this now, hopefully we can just issue a server build to fix the issue.

**Comment by Monegaskeren** [comment]
It seems random how much money you spawn with. Sometimes you spawn with the same amount you died with. That would maybe be ok but then it seems silly that you can find the same amount of crypto dropped next to the dead body of your previous self.

**Comment by Yarwood** [comment]
AWOL released a new server patch today, hopefully this will resolve the issue.

**Comment by Yarwood** [comment]
This is back again @vbawol

**Comment by Shunon** [comment]
Yep one in our squad spawned with 20k today O_O server currency is fcked atm.

**Comment by vbawol** [comment]
What server Shunon?

**Comment by Shunon** [comment]
Its on the wtp server.

**Comment by vbawol** [comment]
Ok, I think I found the last remaining cause for this issue, a hotfix will be pushed to our test servers today.
