### ISSUE TITLE
[Suggestion] AI at Spawn points

### ISSUE THREAD

**Issue by crazymike10** [EpochModTeam/Epoch#231]
Is it possible to set spawn points not to spawn AI within a certain range (ie 300m). We are having situations of AI soldiers spawning at spawn points and this will not allow new spawns to leave the spawn area.

**Comment by andgregor** [comment]
Yep, I suggest we do it at the unit spawn level to control all antagonists. Maybe sharks would be ok, for the coastal spawn. Will take a look later.

**Comment by vbawol** [comment]
this should be in already, if not please report back.
