### ISSUE TITLE
Item dissappearing when bought if not room enough

### ISSUE THREAD

**Issue by Monegaskeren** [EpochModTeam/Epoch#232]
Server: Mells House
Version: arma 1.40, Epoch 0.3.0.1
Last happened: yesterday (march 18. 2015)
Map: Chernarus

When buying stuff from traders and not having room enough, the item(s) dissappears completely, also from the traders inventory.

**Comment by Pmba79** [comment]
I confirm this, tested it on Mells House yesterday.

**Comment by vbawol** [comment]
Will likely need a client update for this so it will be marked for 0.3.0.2

**Comment by vbawol** [comment]
fixed in 0.3.5
