### ISSUE TITLE
Cannot loot corpses under water

### ISSUE THREAD

**Issue by Monegaskeren** [EpochModTeam/Epoch#233]
Server: Mells House
Version: arma 1.40, Epoch 0.3.0.1
Last happened: yesterday (march 18. 2015)
Map: Chernarus

When players or antagonists dies in water so deep that you have to dive to recover their gear/loot you cannot access the inventory menu while swimming. This also happens while wearing rebreather.

**Comment by Pmba79** [comment]
This is an Arma problem, not epoch.
