### ISSUE TITLE
Suggestion - "take all" - option

### ISSUE THREAD

**Issue by Monegaskeren** [EpochModTeam/Epoch#234]
In many cases it seems a waste of time to have to keep right-clicking loot you know you have room for - e.g. when chopping down trees and picking up the wood. It would be awesome with a "Take all" option!

**Comment by vbawol** [comment]
We have one for underwater looting, I will be adding it as an option as soon as we have tested it more.

**Comment by vbawol** [comment]
will be adding this soon, tracking here: #583
