### ISSUE TITLE
Cannot move after spawning

### ISSUE THREAD

**Issue by Milano9** [EpochModTeam/Epoch#235]
Sometimes you cannot move for a while if you spawn, unless you press V (vault).

(I did search for this issue and could not find it, so apologies if previously reported or resolved)

**Comment by andgregor** [comment]
Is on the radar. You can also 'break out' of it by going into your inventory.

**Comment by LaggedToDeath** [comment]
or by using acton Stepover

**Comment by vbawol** [comment]
dup of https://github.com/EpochModTeam/Epoch/issues/185
