### ISSUE TITLE
[Bug][v0.3.0.1] Snapping doesn't work properly once moved/removed

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#237]
If you remove or move a building piece once it has been placed, it doesn't snap back in properly or won't snap at all. It's happened to me multiple times with different building pieces.

**Comment by 82ndAB-Parts** [comment]
I have had to remove all other base pieces around the one I want to put back then rebuild the base around it. It is very inconvenient especially when I accidently hit move when I meant to hit upgrade. Lol

**Comment by Pmba79** [comment]
I do belive that the snapping works as intended, to me it looks more like a item conflict..
Like the already set base piece pushes the new base piece away..
(I might be wrong)

**Comment by vbawol** [comment]
Will be revisiting this more soon.
