### ISSUE TITLE
[0.3.0.1_b5] Players sometime spawn fresh without dying

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/Epoch#239]
Description:

Sometimes when you log off and log back on later, you will log back on as a fresh spawn, and removed from your group. This has happened to me and my admin friends several times now, so it may be related to the players in question being admins. This is logging off well (1 hour) prior to restart.

Expected behavior:

Your gear, position, and group affiliation is saved when you log off, and restored as you log back on.

**Comment by vbawol** [comment]
Axle's server admins have reported this also, looking into it.

**Comment by vbawol** [comment]
Should be fixed, if not please reopen.
