### ISSUE TITLE
[Issue] [0.3.0.1_b5] Performance issues

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/Epoch#240]
0.3.0.1 definitely uses a lot more resources than 0.2-branch. We currently have the following situation:

1. 2900 buildables
2. 120 vehicles
3. 62 players
4. Server FPS: 9

We have tried running the server on two different hardware setups with similar player counts, and with little or no yield in performance. Strange issues occur with this performance, and I believe the mod is in some dire need of optimization if we are not to drastically reduce allowed amount of buildables and vehicles (which, in my opinion is not an option). 

We have been running several trials and done comparisons to other hosts running 0.3.0.1, and the performance really has tanked as of late.

**Comment by vbawol** [comment]
As we discussed some of this maybe from Arma, but we are looking into everything and will optimize where we can.
