### ISSUE TITLE
Allow disabling building with a easy to control variable

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#244]
LunchboxCharlie:
Allow me to add places to the map to disable building, like the old canbuild variable. So when using my own custom map, I can customize the areas I don't want people to build

**Comment by splitx0** [comment]
+ add option to dissable / edit current locations ( mission config file? )

**Comment by splitx0** [comment]
EPOCH_isBuildingAllowed.sqf:

if (getNumber (missionConfigFile >> "CfgEpochClient" >> "buildingNearbyCapitals") == 0) then {
_restrictedLocations = nearestLocations [player, ["NameCityCapital"], 300];
if !(_restrictedLocations isEqualTo []) then {
	_buildingAllowed = false;
	0 = ["<t size = '0.8' shadow = '0' color = '#99ffffff'>Building Disallowed: Protected Frequency</t>", 0, 1, 5, 2, 0, 1] spawn bis_fnc_dynamictext;
};
};

if (getNumber (missionConfigFile >> "CfgEpochClient" >> "buildingInRestrictedAreas") == 0) then {
_myPosATL = getPosATL player;
{
	if ((_x select 0) distance _myPosATL < (_x select 1)) exitWith {
		_buildingAllowed = false;
		0 = ["<t size = '0.8' shadow = '0' color = '#99ffffff'>Building Disallowed: Protected Frequency</t>", 0, 1, 5, 2, 0, 1] spawn bis_fnc_dynamictext;
	};
} forEach (getArray(missionConfigFile >> "EpochBaseBuilding" >> worldname >> "blockedArea"));
};
_buildingAllowed

**Comment by splitx0** [comment]
description.ext:

class CfgEpochClient
{
  buildingInRestrictedAreas = 1; //1 to allow building in Banned Areas
  buildingNearbyCapitals = 1; //1 to allow building in Capital Cities
  
	buildingNearbyMilitary = 1; //1 to allow building nearby
	buildingNearbyMilitaryRange = 300; //Define radius of blocked area  // default radius 300

	buildingRequireJammer = 0; // 1 = to allow building without a jammer 
	buildingCountLimit = 400; // how many objects can be built within range of a jammer 
	buildingJammerRange = 100; // jammer range in meters
};

**Comment by vbawol** [comment]
this should be added for the most part
