### ISSUE TITLE
[BUG]Trash piles, bins and other world objects not lootable on Bornholm

### ISSUE THREAD

**Issue by DarthRogue** [EpochModTeam/Epoch#245]
This may extend to other maps as well, but currently the trash piles, wheelie bins, trash bins, etc. are not lootable.  If you walk up to them and hit your inventory key nothing happens.  There is no animation nor confirmation on screen that the item was looted.  I've used M3Editor to place several of them around the map using the Epoch classnames but they don't work at all.

**Comment by vbawol** [comment]
this should be fixed, if not please propose a pull request to change this config
https://github.com/EpochModTeam/Epoch/blob/master/Sources/mpmissions/epoch.Bornholm/description.ext#L83-L191
