### ISSUE TITLE
[Bug] Wheeled choppers immediately explode when landing on a base piece

### ISSUE THREAD

**Issue by 82ndAB-Parts** [EpochModTeam/Epoch#246]
This is different then the exploding choppers when you first enter them. As soon as the wheel of a chopper touches a base piece it immediately explodes. It doesn't matter how gently you touch down. Skidded choppers are not a problem. My guess is that for some reason the wheels glitch through the base piece and then takes massive damage. It has been a problem from the beginning up to the 0.3.0.1 patch. I just park the skidded choppers on my base for now, but it would be nice to be able to park a wheeled chopper on the roof eventually.

**Comment by vbawol** [comment]
Is this still an issue? if so please re-open
