### ISSUE TITLE
[Bug] 0.3.0.1 SR25 & L85A2 RPT errors (animations problem)

### ISSUE THREAD

**Issue by DarthRogue** [EpochModTeam/Epoch#248]
Under the new release 0.3.0.1 I get an RPT error on the L85A2 and SR25.  See below.

8:00:46 Warning: rightHandIKCurve, wrong size (size<2||size>=4) in \x\addons\a3_epoch_weapons\data\handanims\sr25_reload.rtm
 8:00:46 Warning: rightHandIKCurve, wrong size (size<2||size>=4) in \x\addons\a3_epoch_weapons\data\handanims\sr25_reload_prone.rtm
 8:00:46 Warning: rightHandIKCurve, wrong size (size<2||size>=4) in \x\addons\a3_epoch_weapons\data\handanims\L85A2_Reload_anim.rtm
 8:00:46 Warning: rightHandIKCurve, wrong size (size<2||size>=4) in \x\addons\a3_epoch_weapons\data\handanims\L85A2_RIS_Reload_anim_prone.rtm
 8:00:46 Warning: rightHandIKCurve, wrong size (size<2||size>=4) in \x\addons\a3_epoch_weapons\data\handanims\L85A2_UGL_Reload_anim.rtm
 8:00:46 Warning: rightHandIKCurve, wrong size (size<2||size>=4) in \x\addons\a3_epoch_weapons\data\handanims\L85A2_RIS_Reload_anim_prone.rtm
 8:00:46 Warning: rightHandIKCurve, wrong size (size<2||size>=4) in \x\addons\a3_epoch_weapons\data\handanims\L85A2_RIS_Reload_anim.rtm
 8:00:46 Warning: rightHandIKCurve, wrong size (size<2||size>=4) in \x\addons\a3_epoch_weapons\data\handanims\L85A2_RIS_Reload_anim_prone.rtm

Haven't noticed an issue in game as of yet though, so it's probably a minor problem.

**Comment by vbawol** [comment]
just warnings, unless they cause a problem it should be fine.
