### ISSUE TITLE
0.3.0.1b17 HC load time +30sec ( gender selection )

### ISSUE THREAD

**Issue by splitx0** [EpochModTeam/Epoch#249]
Hello it seems that HC is loading slower because of 30sec waiting time for gender selection.

**Comment by vbawol** [comment]
Is is safe to say that all headless clients with be joining with the typeOf HeadlessClient_F?

**Comment by Silens1** [comment]
Not sure if it always uses the actual HC slot/unit, you could also check UID, headless client UIDs always starts with HC####

**Comment by vbawol** [comment]
This should be fixed with 0.3.4 thanks to @dayzai (Face) adding the hasInterface. checks to the login system.
