### ISSUE TITLE
Trader Item List

### ISSUE THREAD

**Issue by Oshydaka** [EpochModTeam/Epoch#25]
Hey gentlemen !

A really quick but very usefull suggestion

Could you stack items in trader list ?

Cause a list with 20 or more of one item is a pain to find what you look for.

So it could be show like this :
- MXM x3
- Orange Sherbet x14
- Binocular x19

etc...

When you click on a item, it'll ask you how many do you wan't to buy, like the little dropdowncombo in crafting

And having a search bar to write down what you're looking for could be awesome too ^^

**Comment by vbawol** [comment]
this has been added for trader inventory

**Comment by Oshydaka** [comment]
Good to read :+1: 

:D
