### ISSUE TITLE
Jammer maintenance not working right

### ISSUE THREAD

**Issue by Pmba79** [EpochModTeam/Epoch#251]
The metal Shelf's disapear as they please, loosing HUGE amounts of gear this way..

I maintain the base as usual every 5 days to not miss a payment and 2 days later 7 out of 9 shelfs where gone..
Not the first time I lost gear on disapering shelfs, so ergo this issue rep..
(Lost alot of mags and weapony, not to mention literally hundreds of drinks and food items)

-
 
Version 0.3.0.1

Bug Description: Base items disapearing.

Severity: High

Steps to Reproduce: Wait.

Actual Behavior: Removing the shelf's as the jammer had not been maintained.

Expected Behavior: Leaving the base items in place.

Testing Steps : Build alot of shelfs and waited.

Workaround: No idea.

**Comment by Tigah** [comment]
Poulmba, out of curiosity, did you access all the shelving during this time? items such as storage, vehicles etc will disappear if not accessed within 7 days I believe..so essentially, if you didn't have any interaction with the shelves (the ones that disappeared specifically) within the 7 days, then they will disappear.

However if you did access the shelves within the 7 days then this could indeed be a bug.

**Comment by Pmba79** [comment]
I'm 100% sure I have interacted with them in that time..
But never the less, if the shelf and vehicles anre within the jammer range shouldn't they then be protected by the jammer ?
If not and the jammer ONLY targets the direct base items, then the jammer is quite useless...

**Comment by Tigah** [comment]
No, the jammer, when maintained, will only protect the base pieces now.
Which is not useless really because it prevents hoarding and keeps players
active, rather than the servers getting flooded with unnecessary items when
players just base somewhere and don't come back for a week.And if you've
had vehicles blow up randomly inside your base, that could be because they
will also disappear if there is no interaction within 7 days.

**Comment by Tigah** [comment]
oops delete that

**Comment by Pmba79** [comment]
Well, differ of opinions I guess..
I don't agree at all...

Still, the items in question here have been used almost on a daily basis..

**Comment by vbawol** [comment]
So basically we need to make it maintain all objects and not just base objects, should not be an issue.

**Comment by DarthRogue** [comment]
This should include the jammer itself as well.

**Comment by Pmba79** [comment]
Well, as Tigah said, as it is now it prevents hoarding.
So perhaps make it an Admin option on how much should be maintained (base items, shelfs, tipi's,gear)..
And also, if maintaining all (inc gear on the shelfs), the costs of maintaining the jammer/base should be high..

**Comment by DarthRogue** [comment]
If a player is maintaining their stuff then they should be able to keep what they have.  Having unused items in the world is what the cleanup is for.  If shelves, tipis and jammers are included in the maintenance routine but the maintenance isn't done, they will still disappear at the end of the maintenance period just like they do now.  

Don't get me wrong, I'm as against hoarding as the next admin, but having players' gear get wiped when they are properly maintaining their base is a great way to turn players off to the whole mod.

**Comment by 82ndAB-Parts** [comment]
I have lost teepees this way along with metal shelves. I was looking at the gear regularly to try to prevent this but that didn't work. It seems you have to take something off the shelf or teepee and put it back to prevent this. If they could be added to the plot pole that would be nice.

**Comment by vbawol** [comment]
@82ndAB-Parts That would be correct currently.
