### ISSUE TITLE
[Bug/Suggestion] Random skinned vehicles changing skins on restarts

### ISSUE THREAD

**Issue by DarthRogue** [EpochModTeam/Epoch#252]
I've added the M-900 to my server and I've noticed that the skins are assigned at random when the vehicle spawns into the world, as it should.  But then it also assigns a new random skin on every consecutive restart.  The skin should "stick" once the vehicle is spawned into the world and be the same for the life of the vehicle until it's destroyed or sold.  This could be solved by adding a "skin" data field to the database when a vehicle is saved.  The same should also apply to the trucks, although if I recall correctly I think they save correctly and have the same skin.

**Comment by vbawol** [comment]
What is the M-900? We have persistence of textures however they require config.

**Comment by DarthRogue** [comment]
Civil Hummingbird.  There's about 15 different skins for it.  No weapons.  Classname = "C_Heli_Light_01_civil_F"

**Comment by vbawol** [comment]
Nice not sure how we missed adding that, will make it a happen for 0.3.0.2.

**Comment by vbawol** [comment]
added to 0.3.1
