### ISSUE TITLE
[Suggestion] LootSystem improvements

### ISSUE THREAD

**Issue by splitx0** [EpochModTeam/Epoch#253]
EPOCH_masterLoop.sqf:

//Jammer lootspawn restriction settable via description.ext
_jammer = nearestObjects [_lootLoc, ["PlotPole_EPOCH"], 300];
to:
_range = getNumber (missionConfigFile >> "CfgEpochClient" >> "lootSpawnJammerRange");
_jammer = nearestObjects [_lootLoc, ["PlotPole_EPOCH"], _range];

// since i was having troubles with original loot system on map Like Bornholm and on Altis where you go somewhere and where is about 4 buildings then spawn 1 loot object and dont spawn another....
// DELETE THIS: 

//_others = _pos nearEntities[["Epoch_Male_F", "Epoch_Female_F"], 15];
//if (_others isEqualTo[]) then {

//_nearObjects = nearestObjects[_pos, ["WH_Loot", "Animated_Loot"], 35];
//if (_nearObjects isEqualTo[]) then {

Since this modification i also set every building to have 100% chance to have loot ( lootBias ) and let lootBiasPos and lootMultiplier original. And i must say i have really god results with this. Because even with that you just dont spawn loot in every building because it depends on travelled distance and direction. So when you are patient and looting longer you will spawn more loot also it fixed the problem when going nearby military or somewhere and spawn 1 object and nothing else. I also lowered antagonist chance with this.

In the end i must say that current loot system have to many restrictions.

**Comment by vbawol** [comment]
Sounds like we should expose this variable for edit via config as what works on Altis may not work on less dense maps.

**Comment by vbawol** [comment]
cfgbuildinglootpos can now be changed via the mission file and this is where the lootBiasPos variable exists.
