### ISSUE TITLE
Deploying weapon under floor results to bug into the base above the floor

### ISSUE THREAD

**Issue by splitx0** [EpochModTeam/Epoch#257]
.... You can rape base from the inside and if you deploy weapon and bug above the floor you can easily kill players and when turn deploying off you are again under floor.... You will remain above floor only in case when you try to move.

**Comment by eedijs** [comment]
I've tried this and actually could get above floor and start moving - if it was a base then I would be inside it easily.

**Comment by vbawol** [comment]
Not really sure what we can do that isn't just a hacky workaround. So, for now we are going to leave this as a known issue.

**Comment by Ignatz-HeMan** [comment]
We could try it with something like this in DisplayaddEH:
if (_dik == ???) then {
_intersect = lineIntersects [ eyePos player, [(eyePos player) select 0,(eyePos player) select 1,((eyePos player) select 2)+0.5]];
if (_intersect then {_handled = true};
};
If I have a bit more time, I can try it...
