### ISSUE TITLE
0.3.0.1-0.3.0.2b3 Vehicle disappearing on restart / ingame

### ISSUE THREAD

**Issue by splitx0** [EpochModTeam/Epoch#259]
Players were complaining about vehicle disappearing after restart since 0.3.0.1 and while i was deleteing some entries in DB i found out that some vehicles wont save properly sometimes... http://oi59.tinypic.com/116mm94.jpg

Something similar player captured on video: https://www.youtube.com/watch?v=Gd8ZkZ2gW6k
He told me that he was carying stuff from his vehicle to shelves and when go back all what have been captured on video happend... From my point of view when he approached the vehicle it was already gone but the player didnt received the data for some time... I saw similar thing with helicopter... Helicopter was on the base and on restart was still there but when player deal some damage to it it disappeared....

I am not sure why sometimes vehicle disappear and sometimes disappear after a while...

**Comment by vbawol** [comment]
Please provide more information on how to reproduce this with epoch files. Closing for now, please re-open if you have more information.
