### ISSUE TITLE
0.3.0.2 b3 BE kick tracker

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#260]
Kick # 25 line 26 add: 
```
!="if !(player canAdd (_x select 0)) exitWith {};\nplayer addMagazine[_x select 0, _x select 1];"
```

Kick # 40 - line 41 add:
```
!="createDialog \"QuickTake\";"
```

**Comment by Tigah** [comment]
We have applied fix for kick# 40 on 82ndAB server and it works perfectly, no more kicks for take all from treasure loot.
