### ISSUE TITLE
0.3.0.2 b3 Rahim and Zafir can not be charged with their magazine

### ISSUE THREAD

**Issue by NDS-Ares** [EpochModTeam/Epoch#262]
- since update 0.3.0.1 to 0.3.0.2 after A3 update to 1.42

**Comment by ZNUfisk** [comment]
This is an ARMA-bug.

**Comment by NDS-Ares** [comment]
Just read. They have probably changed the type. In the editor everything works ...

**Comment by secondcoming** [comment]
The new ammo is '150Rnd_762x54_Box' where previous it was '150Rnd_762x51_Box'
