### ISSUE TITLE
[0.3.0.2_b3] Damage issues

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/Epoch#266]
Something in Epoch is seriously off concerning the damage model. I think it might be your modification to the bullet resistance on the vests and gear. My players keep hitting their enemies and only small amounts of damage register. 

I just witnessed a close range firefight between four parties, 1 x MX200, 1xMk20 and 1xM16 vs a guy with a Zafir, the guy with the M16 and the guy with the MX200 hit the guy with the Zafir three times in total (judging by him flinching) (he took 0.23333 damage in total) and then the Zafir dude wiped the three guys out. 

Right now 5.56 ammo and even 6.5 ammo are doing way too little damage to players, especially at range.

**Comment by nerdalertdk** [comment]
If he had body armor on he can take 4 x 5.56 in the chest with losing hp,

**Comment by nerdalertdk** [comment]
You should look up the arma 3 body armor video on YouTube

**Comment by ZNUfisk** [comment]
No, that's not it, Epoch modifies it. 

Here's the video from our test:

https://www.youtube.com/watch?v=TE4cazDTTzI

**Comment by ZNUfisk** [comment]
Our perception from testing is that if you are fully uniformed, and with a plate carrier rig or similar, you will have a distinct upper hand in fire fights if you are using 7.62 vs. 6.5 or lower caliber guns. You will be able to take 4-6 rounds of 6.5, 10-12 rounds of 5.56 and an infinite amount of 9mm.

**Comment by ZNUfisk** [comment]
Here's the video showing the information from the first report:

https://www.youtube.com/watch?v=mzuMA6w5MwQ

(The players who got killed left our server for another, because they believed this was related to our server only)

**Comment by ZNUfisk** [comment]
There seriously needs to be something done about this :/

https://www.youtube.com/watch?v=8wMa46MTJU0&feature=youtu.be

**Comment by ZNUfisk** [comment]
I suggest removing all damage resistance from skins, and scaling down the resistance slightly on rigs

**Comment by vbawol** [comment]
WIll give it a try next client release

**Comment by ZNUfisk** [comment]
Another player who has this damage weirdness, check from 3 minutes and forward, keep an eye on his health percentage (symbolized by a broken bone) - https://www.youtube.com/watch?v=1d31obgEc14&feature=youtu.be

**Comment by vbawol** [comment]
should be fixed in 0.3.0.4
