### ISSUE TITLE
[Suggestion] Configurable max wallet amount

### ISSUE THREAD

**Issue by DarthRogue** [EpochModTeam/Epoch#268]
It would be nice for server owners to be able to set the max amount of Crypto players can carry on their clone.  The current max amount is 25000, but I've seen some suggestions on the forums stating that due to some custom stuff they are doing that 25K is not enough.  Having a setting that's configurable in description.ext would be a help for these types of scenarios.   

Example:

MaxCarryCrypto = 50000;

**Comment by vbawol** [comment]
added for 0.3.0.4
