### ISSUE TITLE
Replace Default IP Board Icon with Epoch Icon on forum ;)

### ISSUE THREAD

**Issue by Uro1** [EpochModTeam/Epoch#269]
Would better define between IP board forums, would brand the forums as epoch in web browsers :)

**Comment by Dwarfer** [comment]
http://epochmod.com/favicon.ico

http://epochmod.com/forum/favicon.ico

**Comment by KamikazeXeX** [comment]
I think many users would benefit from being able to distinguish whether they are actually on the epoch forums or not, this needs to be fixed!

**Comment by vbawol** [comment]
should be sorted soon
