### ISSUE TITLE
[0.3.0.2_b15] Player not Authenticated R2 BAN

### ISSUE THREAD

**Issue by Dwarfer** [EpochModTeam/Epoch#270]
Hi,

I have tried this on my dev box also a "fresh" box.

http://epochmod.com/forum/index.php?/topic/34963-0302-b15-player-not-authenticated-r2-ban/

and

http://epochmod.com/forum/index.php?/topic/34954-updating-to-epoch-server-0302-b16-epochmodcom-autoban-r2-problems/

**Comment by RC-Robio** [comment]
Can confirm the same on b15/b16.

**Comment by Dwarfer** [comment]
Should confirm only happens with none EpochAH admins

**Comment by vbawol** [comment]
Is it every player that is not admin or just some?

**Comment by Dwarfer** [comment]
Every.

**Comment by vbawol** [comment]
Please try build 17 http://epochmod.com/download_server.php

**Comment by Dwarfer** [comment]
Tested B17 and all seems to be fine from the R2 BAN POV, Will check to make sure nothing else is astray but I would say this issue is closed.
