### ISSUE TITLE
[0.3.0.2_b18] epoch_linux_startscript.sh EOL Unix

### ISSUE THREAD

**Issue by Dwarfer** [EpochModTeam/Epoch#272]
Hi,

looks like the epoch_linux_startscript.sh has managed to change to Windows EOL not unix.  you can use a simple 
dos2unix epoch_linux_startscript.sh
on the file but probably should do it in the package

**Comment by vbawol** [comment]
Roger that, thanks for the report.

**Comment by Dwarfer** [comment]
Tested the file from the Epoch_Server_0.3.0.2_b19.zip looks good

Epoch_Server_0.3.0.2_b18.zip
file epoch_linux_startscript.sh | grep ASCII
epoch_linux_startscript.sh: Bourne-Again shell script, ASCII text executable, with CRLF line terminators

Epoch_Server_0.3.0.2_b19.zip
file epoch_linux_startscript.sh | grep ASCII
epoch_linux_startscript.sh: Bourne-Again shell script, ASCII text executable
