### ISSUE TITLE
[Suggestion] Crypto sinks to prevent inflation

### ISSUE THREAD

**Issue by ModeZt** [EpochModTeam/Epoch#273]
At the moment the total amount of Crypto generated by the traders is constantly growing. 
There should be much more activities requiring Crypto then base maintenance.
I am thinking about blueprints sold by NPCs (advanced building blocks blueprints for example)
Better clones with more stamina for extra crypto.
UAV terminals at traders with per-minute charge.

**Comment by vbawol** [comment]
Thanks for the suggestion, we will look into this.
