### ISSUE TITLE
NM.338 ammunition does not spawn in loot and is not trade-able

### ISSUE THREAD

**Issue by ModeZt** [EpochModTeam/Epoch#274]
Ammo boxes for the NATO SPMG from the Marksmen DLC do not spawn as a separate item.
You can find this ammo only together with the gun but it never spawns without a gun.
And if you have this ammo you cannot sell it to a trader.

The NAVID 9.3 ammo boxes do spawn in loot and can be sold to a trader.

**Comment by vbawol** [comment]
please reopen if this was not fixed with 0.3.0.3
