### ISSUE TITLE
[Suggestion] LInux ASM - epoch_linux_startscript.sh

### ISSUE THREAD

**Issue by Dwarfer** [EpochModTeam/Epoch#275]
Hi,

I have modified my epoch_linux_startscript.sh to auto start the ASM tool if its found and executable. if its not found or not executable it does not run. This also works with the epoch "serverRestart" I have found that you cannot just leave the ASM running in the back ground with the Linux version you have to restart it every time the server process restarts

You can see how I have done this on the forum 
http://epochmod.com/forum/index.php?/topic/34942-wiphowto-linux-centos-70-epoch-server/
but essentially.

#Keeps ASM running if found and executable
if [ -x "${ARMA_DIR}/asm" ]; then
	echo >>${LOGFILE} "WATCHDOG ($$): [$(date)] Starting ASM"
	killall -9 asm 1> /dev/null 2>/dev/null
	$ARMA_DIR/asm -s &>$ARMA_DIR/asm.out &
fi

However If you think its a good idea I can tidy the script a little more and use a PID instead of the brute force killall :-)

Let me know your thoughts

**Comment by Ecphrasis** [comment]
Thanks for this, I added your code to my startscript and it works perfectly ! It's so much better than screen ! Making it official would be the best...
Thanks again !

**Comment by vbawol** [comment]
@Dwarfer if you would like, please make a pull request to add this.
