### ISSUE TITLE
[0.3.0.2_b19] With 1.44 BE SetVariable Value Restriction #8

### ISSUE THREAD

**Issue by Dwarfer** [EpochModTeam/Epoch#277]
Hi,
Clean server / New Build with 0.3.0.2_b19 the following happen
 
05.05.2015 17:40:28: [DMR]Dwarfer (37.152.xx.xx:2304) XXXX- Value Restriction #8 "last_targeter" = B Alpha 1-1:1 ([DMR]Dwarfer) REMOTE 2:2501 CinderWallHalf_EPOCH
 
Reproduce (Admin and Player)
 
1) Place a Jammer Down
2) Build a half cinder wall
3) once built try and move it

http://epochmod.com/forum/index.php?/topic/35040-0302-b19-with-144-be-setvariable-value-restriction-8

**Comment by Dwarfer** [comment]
even setting the line to 

1 "" !=(Offer|Accept|BUILD_SLOT|TRADE_ACTIVE|last_targeter) !="bis_fnc_objectvar_var"

Ends with the same kick

**Comment by ZNUfisk** [comment]
FIX: In setpublicvariableval.txt, change line #9 from 5 to 1

**Comment by Dwarfer** [comment]
Tested 0.3.0.2_b20 BE update and this fixed it
