### ISSUE TITLE
 BattlEye #0 "BIS_fnc_objectVar_obj2_1431" = C Alpha 1-1:1 (NAME) REMOTE

### ISSUE THREAD

**Issue by Andranovic** [EpochModTeam/Epoch#278]
Gives me this error in publicVariables

**Comment by Dwarfer** [comment]
What does the line say in the publicvariable.log as they normally have more information than that. Is that just from the BEC window ? if so go and look in publicvariable.log

**Comment by Andranovic** [comment]
no. It is in pubblicVariab.log

**Comment by Dwarfer** [comment]
This should be fixed with the !="BIS_fnc_objectVar_obj2_[0-9]{1,10}" from the 0.3.0.3b4 filters

**Comment by Skaronator** [comment]
yup fixed in newest build
