### ISSUE TITLE
[Bug] v0.3.0.3 - Snap Height 2nd Floor

### ISSUE THREAD

**Issue by crazymike10** [EpochModTeam/Epoch#279]
Snap height once reached to the 2nd floor don't go to the right height.

http://imgur.com/nfoTGiq

![image](https://cloud.githubusercontent.com/assets/10988339/7487159/f86a2944-f36e-11e4-8973-f5039d127bfc.png)

There is also issue with general snapping when building large base (ie floors). Let me know if you want more pics and dedicated reports for each.

**Comment by Gezzunder** [comment]
In the image, your timber frames have snapped on top of the wooden floor while your cinders have snapped to the side of the floor.  To get around this, I build the ground floor first, snap the ground walls to the floor, snap the 1st floor walls on top, then the ceiling/floor, then the final roof.

**Comment by vbawol** [comment]
the floors snap above other floors, I will look at this for 0.4.
