### ISSUE TITLE
Still get kicked by Battleye #0

### ISSUE THREAD

**Issue by Hygeliak** [EpochModTeam/Epoch#280]
publicvariable.log: #0 "BIS_fnc_objectVar_obj2_1" = C Alpha 1-1:1 (xxxxxx) REMOTE

Used BE Filters from Epoch_Server_0.3.0.3_b2.

**Comment by vbawol** [comment]
Try to use:

```
!="BIS_fnc_objectVar_obj2_[0-9]{1,10}" 
```

**Comment by Hygeliak** [comment]
Works! Thank you..
