### ISSUE TITLE
[ARMA 3 1.44, Epoch 0.3.0.3] After disconnection and reconnection, empty backpacks that were placed inside the player's currently equipped backpack disappear.

### ISSUE THREAD

**Issue by txapollo243** [EpochModTeam/Epoch#281]
This is a variation of #276 which was recently closed. The empty backpacks disappear after disconnection and reconnection. They remain in the sub-inventory of the equipped backpack throughout the session.

**Comment by vbawol** [comment]
Know issue we currently do not persist the items inside of other items. We maybe able to so I have marked this for 0.5.

**Comment by vbawol** [comment]
Actually I misread your issue, will look into this.

**Comment by vbawol** [comment]
Is this still an issue with 1.46? if so please reopen
