### ISSUE TITLE
Variations of trader types

### ISSUE THREAD

**Issue by DarthRogue** [EpochModTeam/Epoch#283]
I think traders need broken up into class types.  Some traders sell weapons, some sell vehicles, some sell food and clothes, etc., just like it was in A2 Epoch.  This will help encourage player interaction since players will be forced to go to certain traders to buy or sell certain items.  As it sits now, especially on low pop servers, players can easily avoid other players by going to any trader and selling and buying nearly anything they want.  Having the items consolidated by trader class would force players to visit higher traffic areas to do their business, resulting in more exciting situations.

**Comment by ZNUfisk** [comment]
Yeah, I've suggested this too, I also requested limits to how many of certain items actually are bought.

**Comment by vbawol** [comment]
Thanks for the suggestion, we may get around to adding something like this for 0.4. 

Note to @raymix: 
- [ ] Traders would need a way to restrict certain types of items from being sold to the trader, thus making them only deal in say Vehicles, Weapons, Food, etc. This would likely need to be integrated into the new trader menu.
- [ ] We can then make the traders markers on the map a different color based on what they specialize in.
- [ ] server would define this trader type via a simple global public variable on the unit.
