### ISSUE TITLE
Base Objects Disappear After Maintaining

### ISSUE THREAD

**Issue by maca134** [EpochModTeam/Epoch#286]
Player maintains base AFTER TTL has been passed in REDIS but server hasn't restarted.

Please assume the maintaining went correctly but when the server restarts, objects have disappeared.

**Comment by maca134** [comment]
More info: http://epochmod.com/forum/index.php?/topic/35248-redis-ttl-base-objects-disappearing-issue/?p=239827

**Comment by vbawol** [comment]
Thanks for the report, build 6 should fix it https://github.com/EpochModTeam/Epoch/releases/tag/0.3.0.36
