### ISSUE TITLE
Bornholm trader heli-spawn-pad floating at 90m height

### ISSUE THREAD

**Issue by Rob-2** [EpochModTeam/Epoch#288]
Helipad at bornholm center spawn is floating in the air.
Spawned vehicles die from fall damage.

a3_epoch_server_settings.pbo => configs => maps => bornholm.h
{ "Land_HelipadCircle_F",{ 14152.4,11356.6,92.9393},0.100796 } to
{ "Land_HelipadCircle_F",{ 14152.4,11356.6,0.00000},0.100796 }

BR
Rob

**Comment by vbawol** [comment]
Thanks, this was added a while back.
