### ISSUE TITLE
Some enterable buildings on bornholm have no loot spots?

### ISSUE THREAD

**Issue by Rob-2** [EpochModTeam/Epoch#289]
Hello,

I think some enterable bornholm buildings have no loot positions, yet.

I think it's called 2st-house / bo_Dum_mesto2

http://picload.org/view/iacdagi/2015-05-13_00002.jpg.html

Please see also:
http://epochmod.com/forum/index.php?/topic/35249-bornholm-buildings-not-in-loot-table/

BR
Rob

**Comment by vbawol** [comment]
Fixed in experimental
