### ISSUE TITLE
Add a setting to display temperature in degrees Celsius instead of Fahrenheit

### ISSUE THREAD

**Issue by txapollo243** [EpochModTeam/Epoch#290]
Body, air, water and other temperatures in various places are in Fahrenheit. This makes it difficult for players not used to the Fahrenheit system, to understand the consequences of temperature extremes and when to act upon them (when to apply cold/heat packs. find a fireplace, seek shelter from weather elements, e.t.c.). Add a setting to change the temperature units on player demand.

**Comment by IntelOut** [comment]
+1

**Comment by Bloodyyy** [comment]
+1
Perfect idea for European players

**Comment by Skaronator** [comment]
maybe change it completly to celsius since..

![](http://i.imgur.com/3ZidINK.png?1)

**Comment by vbawol** [comment]
lol, ya

**Comment by Bloodyyy** [comment]
OK! Now it knows :-)

**Comment by IntelOut** [comment]
C = 5/9*(F-32)

**Comment by Pmba79** [comment]
Not that hard to figure out, but changing it would defenetly be easier for most players out there...

http://www.asknumbers.com/CelsiusToFahrenheitConversion.aspx

**Comment by IntelOut** [comment]
btw its also will be good if weight system could be switched to metric instead of imperial.
(kgs instead lbs and so on)

**Comment by Halvhjearne** [comment]
i think the problem is arma choosing the settings based on languge rather than region and does not have any settings afaik for using either metric or imperial.

so basicly any player that chooses to use english languge, will also have imperial system by default instead of metric system.

**Comment by vbawol** [comment]
thanks for the feedback! added for 0.3.8+,
[Added] Display temperatures in both Fahrenheit and Celsius.

Also @IntelOut where in A3 Epoch does it show the weight in lbs?

**Comment by IntelOut** [comment]
i forgot.
will check lately...
