### ISSUE TITLE
[bug] AI trader inventories not clearing

### ISSUE THREAD

**Issue by MGTDB** [EpochModTeam/Epoch#291]
Problem: epochconfig.hpp - expiresAIdata is not functioning. Have tested clearup settings down to 1 day and trader inventories are still not being cleaned.

Result: Vehicles get sold to traders and remain in traders inventory, reducing the vehicles on the map over time, no new vehicles spawn as they're still in the traders data.

**Comment by Flosstradamus** [comment]
+1 can confirm

**Comment by KamikazeXeX** [comment]
I personally run a custom trader system thus not having this issue but a few other groups I have been talking to also experience the same issue

**Comment by infiSTAR** [comment]
yes, I think I saw something on Epochboard about that as well

**Comment by MatijsVDG** [comment]
+1

**Comment by Dwarfer** [comment]
+1
I've had a look around the DB and cannot seem to find anything that is tracking the date of objects. Does this work on the whole trader stock or just single items ?

**Comment by vbawol** [comment]
Please show your epochconfig.hpp setting.

I just tested this and it works properly. If you have not wiped since we added the expiry to AI_DATA then you may just need to delete the extra keys. Any new AI_DATA keys since then do use the expiry settings defined in epochconfig.hpp

**Comment by Dwarfer** [comment]
AI_DATA ?
I don't have this. This is on a clean server as well.

**Comment by DarthRogue** [comment]
I don't have nor do I ever recall seeing an AI_DATA table. Even on my test server which I frequently wipe for testing purposes I've never seen that.

**Comment by DarthRogue** [comment]
Only AI and AI_ITEMS present.

**Comment by secondcoming** [comment]
Yep, can confirm. No AI_DATA here either.

**Comment by MGTDB** [comment]
from my config file
expiresAIdata = "259200"; which is 3 days

I've deleted the AI and AI_ITEMS keys a few times since it was introduced and it still doesn't clear their inventory after 3 days (my setting as above)

**Comment by vbawol** [comment]
it is AI_ITEMS and I can confirm that its it working here.

**Comment by DarthRogue** [comment]
There is no date or time stamp in any keys in my AI_ITEMS tables either.

**Comment by MGTDB** [comment]
It's never worked for us, the only way to clear them is to do it manually. This is after 5 days at one trader http://bit.ly/1IJsKVV

Even on my test server it isn't clearing.

**Comment by vbawol** [comment]
Do you touch the AI_ITEMS with any custom code? It seems like something is resetting the TTL constantly.

I can see from your screen shot that key has a TTL of 259074 sec. You should see this number decrease as time goes by all the way to 0 then it is removed.

**Comment by MGTDB** [comment]
No custom code touching that no

**Comment by Dwarfer** [comment]
So it works on the KEY TTL ?

That would explain it.. Does the TTL get updates on a new TRADE and or a simple read ?

**Comment by vbawol** [comment]
The TTL on this key is extended every time a trader data is saved.

**Comment by MGTDB** [comment]
So a player making a trade resets the countdown to deletion timer?

**Comment by Dwarfer** [comment]
Tested, Yes..

**Comment by DarthRogue** [comment]
This is where some documentation would come in real handy. Had no idea what that number was or how it was significant.

**Comment by MGTDB** [comment]
So our traders that are used frequently will never clear?

**Comment by Dwarfer** [comment]
This is why my main traders have 100 (max items) in stock then :-(.. Back to running custom purge down for now then.

Can we look to change this is some way. Not sure I have the answer but does seem kinda pointless at the moment unless we drop to like 1hr maybe but then no items in stock unless we use pre load items..

Just my thoughts obviously

**Comment by MGTDB** [comment]
For example, on my Altis map at central spawn traders, there is always at least 3 players there buying or selling, this would mean that those AI inventories would never be cleared unless it was set at 1 second!

**Comment by vbawol** [comment]
Yes that is correct it only expires data that is not in use. I would suggest setting the value lower. 

The expiry is actually unrelated to this issue and it is working as intended. I will look at adding other ways to help manage and the AI trader data.

**Comment by MGTDB** [comment]
The main purpose for us is to clear vehicles from the trader after xx time as eventually the vehicles on the map reduce too far. The other items such as guns and ammo are not as critical.

**Comment by DarthRogue** [comment]
Vehicles in trader inventories shouldn't count towards the max vehicle limit anyways. But that's a separate discussion.

**Comment by vbawol** [comment]
If they didn't you either would not be able to spawn purchased vehicles due to max limit or you would exceed the max vehicle limits and that is a good way to destroy performance. I think we can add some basic logic to keep inventory on vehicles under control.

**Comment by donkeypunchepoch** [comment]
hey guys I made a post in the forums about an easy way to clear the vehicles. I found it by accident.
simply run a test server, set your Traders to 0 in the config,  use the same database as the main server.
Start the test server, upon restart of the main server all the traders will reset their vehicles placing them back on the map. This was discovered after several days of doing testing like this for the custom traders and people kept asking what I did cause the vehicles were everywhere...

Good luck with this info,

Btw, the custom trader now being used will never take a vehicle away from the restarts and you can buy and sell backpacks, hope that helps until epoch devs can figure out a proper way to utilize their new trader system and new Redis dB  and correct their issues, until then they are dropped on DP.  To be honest no epoch Traders gave us a bump in performance.

If you want to keep the vehicles under control just delete them once sold, this would put em back on the map every restart and I'm sure that's what everyone here is getting at, wanting enough vehicles every restart to keep their communities happy

**Comment by Dwarfer** [comment]
Maybe not the place but I have some PHP code that does this is people want. vbawol if this is not the right place delete this please :-)

http://epochmod.com/forum/index.php?/topic/32124-wipunofficial-php-epochredis-tools/

**Comment by DarthRogue** [comment]
At the very least all vehicles in the vehicles table need to spawn on every restart. Those should always take priority. If that means that some vehicles need to be deleted from trader inventories in order to stay under the vehicle cap then that would be fine.

**Comment by MGTDB** [comment]
Ok just tested. AI data clear is set to 180 seconds
Sold trader an SUV. Checked Redis and watched timer go down to 0, key then becomes null and that trader disappears from Redis. Ingame, the trader still has the SUV.
Purchasing the SUV takes crypto and says item purchased but no SUV spawns.

**Comment by secondcoming** [comment]
I would suggest by default to have an array of items in epochconfig.hpp which are not to be cleared from the server each day and for a daily routine to run to clear all items not in that array.

**Comment by MGTDB** [comment]
You can't run Redis commands without shutting down Redis process first afaik.

**Comment by secondcoming** [comment]
I run php trader cleardown scripts every restart (using Dwarfers code) while the arma3server.exe is not running and it works perfectly.

**Comment by DarthRogue** [comment]
I think some of the disparity comes with the fundamentals of how Redis works, since sometimes changes get stored to memory before they get written to disk. When Epoch reads trader data is it reading it from memory or from what's actually saved on disk?  Depending on how that works it could mean that what you can or can't do and see in game isn't an accurate representation of what's really available.

**Comment by MGTDB** [comment]
Ok, im now clearing AI data every 10800 seconds, new traders now have this from the config http://pastebin.com/p0WGfzXY

**Comment by BTDisabled** [comment]
Still not wiping....

**Comment by MGTDB** [comment]
@BTDisabled it starts the timer from the last time that specific trader was used.

**Comment by vbawol** [comment]
This is not an issue with the way the expires works, if the trader is in use it should never clear the inventory.
