### ISSUE TITLE
[Suggestion] Blocking anti camping UAV's from Frequency Jammer radius

### ISSUE THREAD

**Issue by MercianUK** [EpochModTeam/Epoch#292]
Hi, 
Could I ask if the "anti camping" UAV be excluded from the radius of the Frequency Jammer in line with the loot spawn blocking.
Problem is when building or in base areas the UAV's tend to be relentless.

Thanks for considering this request.

**Comment by vbawol** [comment]
restriction have been put in place, please let us know if this is still an issue.
