### ISSUE TITLE
Vehicle Spawn Problem

### ISSUE THREAD

**Issue by secondcoming** [EpochModTeam/Epoch#293]
I am in the process of setting up a test server running Esseker.

I have got most things working okay but there seems to be an issue with vehicle spawning.

Starting with a blank database after several minutes there are about 200 vehicle deaths in the database (ie. they spawned in and exploded immediately).

They seem to be spawning in mid air at about 500m above ground at around map coord 2000,2000.

This is using the current a3_epoch_server.pbo on github, reverting back to the 0.3.0.3b6 version it works fine

**Comment by Skaronator** [comment]
Esseker is not offical supported yet, we will look into it

**Comment by Uro1** [comment]
I've messaged the map author advising him to change the Z height in his map config for centerPosition.  This will fix this issue. 

Can probably be closed @Skaronator

**Comment by Skaronator** [comment]
alright cool
