### ISSUE TITLE
Water building issues: 1.44, Epoch 0.3.0.3

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#294]
These are not urgent issues but issues non-the-less. 

Admin menu: unable to remove building parts in water.

Player: 
- Unable to access inventory underwater. (A3 & epoch issue apparently)
- Unable to access building controls (space - remove, move, upgrade) Underwater  (1, 2, 3 seem to work fine)
- Unable to maintain, move, remove or build jammer underwater
-Unable to snap foundations onto floors. - although not the intention of foundations, it would be helpful to have this option for stacking and layering when required.
- Need the ability to be able to stack & snap foundations to achieve more length.

The biggest one is definitely the accessing inventory under water. If you die you lose all your gear. If you need to get more building materials, you have to continuously go back and forth to where your building materials are since you cannot access your inventory. 

I'm still testing this extensively. My first attempt was an epic fail since I couldn't maintain jammer.

**Comment by vbawol** [comment]
Thanks for the feedback Tigah, got something cool in the works for this.
