### ISSUE TITLE
Suggestion: Diver propulsion vehicle

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#295]
![gavin_scooter_dab](https://cloud.githubusercontent.com/assets/10912575/7741610/4446d5fc-ffd5-11e4-81dd-2d1793f16bae.jpg)

Perfect for those long swims or needing to get somewhere quick and going through water to get there.

**Comment by Pmba79** [comment]
Nice Tigah, I asked for this several month ago ;)

**Comment by IntelOut** [comment]
it also will be nice if simple depth gauge, shown underwater with rebreather on, would be introduced in future builds.

Same as simple altimeter with parachute on.

**Comment by vbawol** [comment]
Thanks for the suggestion
