### ISSUE TITLE
Weapons Suggestion

### ISSUE THREAD

**Issue by DarkSideSixOfficial** [EpochModTeam/Epoch#296]
We all know a little more choice wouldn't hurt. I am aware that the awesome Epoch Dev's have their hand full creating this one of a kind mod, and improving the experience for everyone. They don't quite.have time to create a whole lot of weapons. Now, of course the DLC added 7 new guns. But that's 7 guns perhaps some people can't use. Not only that, but there still could be a few more unique choices added to the game. A mod called SMA, or Specialist Military Arms, is a mod made for the ASOR community, it's a great weapons mod that adds a handful of great new weapons. They're working on finishing up version 2 of the mod right now, that will provide variety of a lot of folk's favorite weapons.

I didn't suggest this mod just because of the guns, but because of the Quality. The Quality is what i call ArmA 3 quality. Meaning it's good enough to where i would have thought that they belonged to Vanilla ArmA 3 if i didn't know it was a mod. It's that balanced. The guys making SMA are great, and don't mind letting anyone else use their sweat arsenal for other mods as well. The best part, is that the quality of SMA out does what ever weapon pack Overpoch is using, which could draw players over to regular Epoch more. I found that Overpoch does something to it's traders that makes the experience less desirable, which means that a majority of players are returning to the environment that's much more Dynamic. Add in a few more weapons choices, with better quality, and you have them.

So to cut it short, SMA is soon to release V2 of the mod. The weapons that will be available are as follows.

- AUG
- HK 416/417
- MSAR E4
- SAR 21
- SCAR L/H
- MK.18
- M4
- MM 23 EK
- ACR remington (Adaptive Combat Rifle)
- SRS Sniper
- THALES F90 
- Beretta ARX 160
- AAC blackout

2035? All of these weapons fit that theme too. This is my suggestion. When V2 comes out, you guys should think about using this weapons mod, at least as a place holder until you reach the weapons that you guys seek to be in your mod. Thank's for reading.

**Comment by ZNUfisk** [comment]
EpochMod for ARMA3 has followed the principle that it will not use content not created by BiS or the development team themselves. I believe they will not deviate from this principle, given that it would also require them to change their license.

**Comment by DarkSideSixOfficial** [comment]
I suppose you're right. Thanks for the insight. However, it would be great to hear from a DEV for confirmation that using such a mod is confirmed, never going to happen.

**Comment by ZNUfisk** [comment]
Does not stop you from adding it in for your own server. It just won't be distributed with the mod itself.

**Comment by vbawol** [comment]
We will also be adding more weapons to Epoch mod as we get the time.
