### ISSUE TITLE
Several Marksmen DLC guns can not be sold to traders

### ISSUE THREAD

**Issue by Styreta** [EpochModTeam/Epoch#297]
The ASP Black MAR-10, and Mk14 camo cannot be sold to vendors. Might be more. Weird thing is, they are actually in the config files. Seems to be baked into Epoch.

**Comment by MGTDB** [comment]
Yes, this is true, just checked the CfgPricing.hpp and there is indeed classes missing.

**Comment by vbawol** [comment]
Please post the classnames if you find there still are missing classes.
