### ISSUE TITLE
TP on Stratis for regular players

### ISSUE THREAD

**Issue by Ecphrasis** [EpochModTeam/Epoch#298]
Regular players take the teleport to the center of the map, but after around 20 seconds, they been brought back to the incubator. Looks like the redis key can't be writable and the hive replace the player when she have to update the key on the dump.rdb. AHL-LOG :  2015-05-23 09:16:05 Ecphrasis (765611xxxxxxxxxxxx): [TEST] TP from [1719.93,5124.49,0.233422] to [4089.82,4597.71,0], 2437 meters, now at [4089.82,4597.71,0]. The map is unplayable, only admins can play on it..

**Comment by vbawol** [comment]
fixed for 0.3.0.4
