### ISSUE TITLE
[Suggestion] Safe and possibility to craft it.

### ISSUE THREAD

**Issue by IntelOut** [EpochModTeam/Epoch#299]
Please add a safe, same model as in DayZ. It will look great as interior storeage items in any private house built.
Also possibility of crafting would be nice feature. (Example recipe: 5 x Lockboxes, 3 x electronic parts, 5 x Large metal salvage, require Fire).
Should it be undestructable - i don't know. Up to you.

**Comment by Bloodyyy** [comment]
+1

**Comment by donkeypunchepoch** [comment]
They already have it, it was available on the admin tools during 0.1.0.3 and 0.2
however it did not have any function, you only got the examine option not build.

They also had keys then too

**Comment by vbawol** [comment]
Thanks for the suggestion, stay tuned for more updates.
