### ISSUE TITLE
[Bug][0.3.0.4 Testing] Chopping Wood is broken

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#300]
Versions
0.3.0.4 (Arma 1.44)

Bug Description
Hatchet, Improvised Hatchet, Chainsaw all are broken

Severity
High

Steps to Reproduce
Use hatchet on tree or bush with no effect and script error

Actual Behavior
Cannot chop trees / bushes

Expected Behavior
Be able to chop down trees and bushes

Troubleshooting/Testing Steps Attempted
Tried both types of hatchets / chainsaws

Workaround
N/A

Image link for script error: http://imgur.com/6PKu2g1,6Gj2qf0

**Comment by vbawol** [comment]
This should now be fixed, please test

**Comment by orangesherbet** [comment]
Confirmed working with hatchet to chop down trees and bushes!
