### ISSUE TITLE
[Suggestion][0.3.0.4] Trader markers inaccurate as to their position 50% of the time

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#302]
Traders are marked on the map with an orange marker, however since they are roaming their "home" location is obscured from the the player so you will have to hunt them down 50% of the time i.e. they are not where the dot suggests. Perhaps turning on the home markers is needed or another method so people can find them. Or a light shaded circle in which people would have to search? This would probably clutter the map too much.

**Comment by Pmba79** [comment]
Tested at 5 traders today, only 1 where where to be expected, 2 where about 50m from location and I never found the last 2 traders..

**Comment by ckelly227** [comment]
I have been at trader dots where the trader is not visible.  I was able to turn in a Pike's Peak, but was unable to see the Trader in the Building.

**Comment by Korwiin** [comment]
Server admins can set "forceStaticTraders = true;" inside the under @epochhive\epochconfig.hpp  (line 75).   Even with that setting forced, are the markers still wrong?

**Comment by orangesherbet** [comment]
Roaming Traders are disabled in the test build for Epoch until the issue can be remedied

**Comment by vbawol** [comment]
will rework the trader AI to make this work better.
