### ISSUE TITLE
[Bug][0.3.0.4 Testing] Strange Clustered Vehicle Spawns 

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#303]
Versions
0.3.0.4 (Arma 1.44)

Bug Description
Vehicles Spawning in extreme clusters (several in one spot)

Severity
Medium

Steps to Reproduce
Player Frosty discovered several vehicles in one place presumably all spawned on the same spot- some overlapping one another

Actual Behavior
At least 10 vehicles spawned in one spot, not near a city. Is this the center point of the map? 108, 106

Expected Behavior
Vehicles spawning in a random pattern, near cities and boats randomly on the coast

Troubleshooting/Testing Steps Attempted
N/A

Workaround
N/A

Image link
http://imgur.com/a/6nx0L

As this image suggests there are many vehicle spawns that happened in one spot
This is on Mells House server at approx location 108,106 I think.

**Comment by vbawol** [comment]
confirmed fixed by Axle and my self
