### ISSUE TITLE
[Bug][0.3.0.4 Testing] Items still disapear when buying from traders

### ISSUE THREAD

**Issue by Pmba79** [EpochModTeam/Epoch#304]
Items still disapear when buying from traders, if there ain't enough room in your inventory.
It says, "not enough room" but the item is gone from the trader menu..

Forgot the damn headline..

**Comment by orangesherbet** [comment]
Confirmed that when you buy something without the space it removes the item from the trader and the crypto from your player

**Comment by Pmba79** [comment]
Just tested it again, still up..

**Comment by vbawol** [comment]
This should be fixed with the unification of the Epoch_additemOverflow function. If not please reopen an issue with a ref to this one.
