### ISSUE TITLE
Gaps between base parts after server restart

### ISSUE THREAD

**Issue by ModeZt** [EpochModTeam/Epoch#306]
Epoch 3 has still the same issue like Epoch 2, that the building parts snap to a 10cm grid at server restart, when building at areas that are more than 10000m away from map center. (Note: Y-database-coordinate does not matche the ingame map).
 
The cause is, that in the database the coordinates are stored with 6 digits. For example 9424.68/2156.76 (m). Or another example 1243.57/536.567.
 
The problem is, when you build more than 10km away from the database coordinate center, it only save 15365.2/21564.5 (m). With that alle objects snap to a 10cm grid on the next restart of the server.
 
 
Is there a good cause that the system is not using at least 7 digits?
 
 
In Epoch2 there was a server side script, that fixed the issue, by converting the coordinates to a string before putting them into the database: http://epochmod.com/forum/index.php?/topic/15813-release-v104-precise-base-building-persistent-bases-after-restart-updated-021114/
 
Maybe that format would be an option, if there is a hardcoded limit to 6 digits. However, I dont know how big the performance impact is.
 
reposted from: http://epochmod.com/forum/index.php?/topic/35280-gaps-between-base-parts-after-server-restart/

**Comment by vbawol** [comment]
This is something I am asking BI adds to the engine as the cost of calculating this might be a bit more overhead than we can afford. 

If I do add this It ill likely an optional setting so we can best compare the results.

**Comment by vbawol** [comment]
I actually found a fast way to fix this and is already in testing in the 0.3.1 patch first signs show that is has indeed fixed the shifting.
