### ISSUE TITLE
[Bug][0.3.0.4] Script Error

### ISSUE THREAD

**Issue by DarthRogue** [EpochModTeam/Epoch#307]
When looting trash piles I got the following error.  Only happened once.

19:16:28 Error in expression <2,random 2,10];

sleep 120;
if (!isNull _x) then {
deleteVehicle _x;
};
if (!isN>
19:16:28   Error position: <_x) then {
deleteVehicle _x;
};
if (!isN>
19:16:28   Error Undefined variable in expression: _x

My client RPT did not list a file that contained the error.

**Comment by vbawol** [comment]
@andgregor This is from the sapper nest code from the looks of it.
