### ISSUE TITLE
config animation cause memory crash since 1.46

### ISSUE THREAD

**Issue by RoyDodd** [EpochModTeam/Epoch#308]
Several (3) players have crashed their clients so far in the 2.5 hours since we updated our Epoch server to v1.46 when 'searching' a gun case. It seems to be a memory error but I don't have any better data yet. I will update when I can get more useful data about what is crashing.

This appears to be the memory crash caused by lootable animations. I am seeing the same exit code (0xC0000005/ -1073741819).

**Comment by vbawol** [comment]
We have reported this to BI, and are working with them to get it fixed.

**Comment by donkeypunchepoch** [comment]
Vbawol, this is BATTLEYE related to updating battleye to vb1.232.  They need to open the game with the included arma launcher and make sure the battleye client loads properly as well as can update.

Had several players experience this and this was the resolution.

I do have another player with a slightly different error but had to do with test signing on.
simply run a command prompt as admin and "bcdedit -set TESTSIGNING OFF"

**Comment by tuco86** [comment]
I had these crashes yesterday when searching a weapon box.. crashed immediately when i relogged several times.. Then I tried to set graphics to low and it worked.. but the weapon box was also gone.. so either one fixed my problem.. set graphics to high again later and had no such problems since.

**Comment by vbawol** [comment]
perf v2 seems to have fixed this so we will revert the build 9 changes after its pushed out as stable.

**Comment by Korwiin** [comment]
FYI the temp fix for this breaks looting chests underwater.   Items are dropped to the ocean floor instead, and not available to the special underwater "loot all" script popup.

**Comment by donkeypunchepoch** [comment]
So even with server side perf v3 and client side  v3 still getting crashes on clients.

Wow we are approaching 5 weeks with this gamebreaking bug from BIS
