### ISSUE TITLE
Instant Kick by BattleEye "SetVariable Restriction #0" 

### ISSUE THREAD

**Issue by Bloodyyy** [EpochModTeam/Epoch#310]
setvariable.log: [ESF]_Bloodyyy (##############) GUID - #0 "last_targeter" = B Alpha 1-1:2 ([ESF]_Bloodyyy) REMOTE 2:2583 CinderWallHalf_EPOCH

setvariable.txt: 5 "" !=(Offer|Accept|BUILD_SLOT|TRADE_ACTIVE|last_targeter) !="bis_fnc_objectvar_var"

Since the last update of Arma 3 to 1.46 with HotFix

**Comment by vbawol** [comment]
if this is setvariable value restriction make sure you updated your setvariableval.txt
