### ISSUE TITLE
[Bug][0.3.0.4] Fresh spawn vehicle floating

### ISSUE THREAD

**Issue by Philanthropy1** [EpochModTeam/Epoch#311]
Noticed a vehicle floating in the air, a couple hundred meters up. As I go closer it dropped and when I arrived it was ok with no damage. Was a freshly spawned vehicle with loot;

Floating vehicle - http://i.imgur.com/WnT4Edm.jpg
Falling vehicle - http://i.imgur.com/wdXpAMk.jpg
On ground undamaged - http://i.imgur.com/LxOY759.jpg

**Comment by MGTDB** [comment]
If this is near Drimea on Altis it happens to us too, it also happens on Chernarus at Novy Sobor.

**Comment by vbawol** [comment]
should be fixed in experimental, if not reopen,
