### ISSUE TITLE
Server multiple crashes

### ISSUE THREAD

**Issue by simon1603** [EpochModTeam/Epoch#313]
Server running build 9, hosted by swiftNode, had no issues with scripts, now for last week or so server is crashing, not all the time, often when doing missions. Included is the mdmp file, hope i have done this correctly. 

<a href=http://www.filedropper.com/arma32015-06-1717-30-34><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >file backup online</a></div>

**Comment by MGTDB** [comment]
That shows a client crash on arma3.exe http://postimg.org/image/r60s91dxj/

**Comment by simon1603** [comment]
My apologies it appears i may have sent you my admins client report, I have included the server mdmp, my apologies again, we believe we had located the issue when I started removed script one at a time, A3AI and blceagl mission system seemed to be the culprits (never had a single issue previously). 
Unfortunately the server crashed again with the same error report, hope this is useful and that you can help. 

I have concidered just wiping the server and starting fresh (already have build 9 installed) incase it was a bad install, but with 0.3.0.4 looming, but if it isnt going to be released soon, should I maybe just go ahead and try a reinstall.

https://www.dropbox.com/s/1z9hq6pw3w8d6g0/arma3server_2015-06-25_01-00-08.mdmp?dl=0

Thanks in advance
Simon

**Comment by simon1603** [comment]
Hi I also obtaind a stackwalk from my hoster SwiftNode

Simon,

Ryan and I have reviewed the latest crash dump, here is a stackwalk to report to the devs. I'm looking into the BEC messages again now.

Stackwalk
Operating system: Windows NT
6.1.7601 Service Pack 1
CPU: x86
GenuineIntel family 6 model 62 stepping 4
8 CPUs

Crash reason: EXCEPTION_ACCESS_VIOLATION_READ
Crash address: 0x73f8d0ce

Thread 0 (crashed)
0 ntdll.dll + 0x330bd
eip = 0x76f230bd esp = 0x00b8f450 ebp = 0x00b8f45c ebx = 0x00000000
esi = 0x00c80000 edi = 0xffffffff eax = 0x843532b0 ecx = 0x73f8d0be
edx = 0x00000000 efl = 0x00210206
Found by: given as instruction pointer in context
1 arma3server.exe + 0xe03acf
eip = 0x020d3acf esp = 0x00b8f464 ebp = 0x00b8f470
Found by: previous frame's frame pointer
2 arma3server.exe + 0xdf28d8
eip = 0x020c28d8 esp = 0x00b8f478 ebp = 0x00b8f47c
Found by: previous frame's frame pointer
3 arma3server.exe + 0xc8a36d
eip = 0x01f5a36d esp = 0x00b8f484 ebp = 0x0000003d
Found by: previous frame's frame pointer
4 arma3server.exe + 0xc89a40
eip = 0x01f59a40 esp = 0x00b8f494 ebp = 0x0000003d
Found by: stack scanning
5 arma3server.exe + 0x74f61e
eip = 0x01a1f61e esp = 0x00b8f4a0 ebp = 0x0000003d
Found by: stack scanning
6 arma3server.exe + 0x74dfc7
eip = 0x01a1dfc7 esp = 0x00b8f4b8 ebp = 0x0000003d
Found by: stack scanning
7 arma3server.exe + 0x2f1fa8
eip = 0x015c1fa8 esp = 0x00b8f4d0 ebp = 0x0000003d
Found by: stack scanning
8 arma3server.exe + 0x1ded9a
eip = 0x014aed9a esp = 0x00b8f4d8 ebp = 0x0000003d
Found by: stack scanning
9 arma3server.exe + 0x85989f
eip = 0x01b2989f esp = 0x00b8f4e0 ebp = 0x0000003d
Found by: stack scanning
10 arma3server.exe + 0x87e7c4
eip = 0x01b4e7c4 esp = 0x00b8f504 ebp = 0x0000003d
Found by: stack scanning
11 arma3server.exe + 0x8734b3
eip = 0x01b434b3 esp = 0x00b8f520 ebp = 0x0000003d
Found by: stack scanning
12 arma3server.exe + 0x10f8308
eip = 0x023c8308 esp = 0x00b8f54c ebp = 0x0000003d
Found by: stack scanning
13 arma3server.exe + 0x895abf
eip = 0x01b65abf esp = 0x00b8f554 ebp = 0x0000003d
Found by: stack scanning
14 arma3server.exe + 0x8bf63c
eip = 0x01b8f63c esp = 0x00b8f58c ebp = 0x0000003d
Found by: stack scanning
15 arma3server.exe + 0xc8a359
eip = 0x01f5a359 esp = 0x00b8f5ec ebp = 0x0000003d
Found by: stack scanning
16 arma3server.exe + 0xd41c88
eip = 0x02011c88 esp = 0x00b8f5f0 ebp = 0x0000003d
Found by: stack scanning
17 arma3server.exe + 0xcfd825
eip = 0x01fcd825 esp = 0x00b8f604 ebp = 0x0000003d
Found by: stack scanning
18 arma3server.exe + 0xcec087
eip = 0x01fbc087 esp = 0x00b8f624 ebp = 0x0000003d
Found by: stack scanning
19 arma3server.exe + 0xf5a988
eip = 0x0222a988 esp = 0x00b8f62c ebp = 0x00b8f640
Found by: stack scanning
20 0xcd0e10
eip = 0x00cd0e10 esp = 0x00b8f648 ebp = 0x0222a234
Found by: previous frame's frame pointer
21 arma3server.exe + 0xfa6d3c
eip = 0x02276d3c esp = 0x00b8f658 ebp = 0x0222a234
Found by: stack scanning

----
Calvin Judy
Founder & CEO
Swiftnode.net - High Performance
You rated this response
