### ISSUE TITLE
Temp Fix for Anim Crash breaks looting shipwrecks underwater

### ISSUE THREAD

**Issue by Korwiin** [EpochModTeam/Epoch#315]
Animation crash bug noted/reported here:
http://epochmod.com/forum/index.php?/topic/35797-temp-lootfix-for-animation-crash-arma-146/page-2

Github Issue: https://github.com/EpochModTeam/Epoch/issues/308

Temp fix for above mentioned bugs has a unintended consequence of causing chests from shipwrecks looted under water to dump their contents onto the ocean floor, and inaccessible to the player from the epoch "loot all" feature for underwater chests. 

Here is a video showing how the underwater "loot all" feature used to work. 
https://www.youtube.com/watch?v=GlXKBQsy6d4

**Comment by vbawol** [comment]
Known issue, 1,48 and 0.3.0.4 will resolve this,
