### ISSUE TITLE
duping report.

### ISSUE THREAD

**Issue by andgregor** [EpochModTeam/Epoch#316]
http://epochmod.com/forum/index.php?/topic/36315-duping-with-trade-request/

Players can duplicate items with trade request:
when player stay in vehicle another player stay outside, then who outside send request for trade to player in veh. ,  place items or gold for giving him , and wait when him exit from vehicle,then confirm request and items duplicated. it can be fixed ?

**Comment by vbawol** [comment]
I will take a look as I thought I had checks to make sure the target was not in a vehicle.

**Comment by vbawol** [comment]
fixed in experimental
