### ISSUE TITLE
vehicles smoke-, flare- launcher and lasermarker ammo are refilled on each restart (bug or intended?)

### ISSUE THREAD

**Issue by Halvhjearne** [EpochModTeam/Epoch#317]
this isnt exatly a gamebreaking bug i just thought i would let you know that using magazinesAmmo does not return smoke-, flare-launcher and lasermarker ammo from vehicles you will need to use magazinesturret to find these.
this means that on each restart these are refilled/reset to default amounts on all vehicles.

i dont have any suggestions as to how to fix it as there is currently no command/function afaik that returns all the ammo types including the above mentioned not to mention there is no way to figure out what turret/weapon they are in or what magazine has wich amount of ammo without reloading them one by one and checking (wich would also reqire a unit to do so or it wouldnt even work).

**Comment by Halvhjearne** [comment]
actually, its not even saving magazines correctly ... but i guess its a bug with magazinesAmmo tbh

spawned a brand new ghosthawk as an example.

magazinesAmmo will return 1 magazine with 2000 bullets, when in fact it has one magazine with 2000 bullets in each side if you check using magazinesTurret.

this will only save to database as 1 magazine for next restart so again not really that important since it cannot be used for achiving anything, only magazines lost (that most players wont even notice).

**Comment by vbawol** [comment]
We have not actually added support for armed vehicles as we don't spawn them. I have some of the code to do this commented out I will look over it again and give it a test.

**Comment by Halvhjearne** [comment]
i think its related to the problem most commands to return ammo from vehicles suffer from, if theres more than one turret using same ammo/weapon, magazinesAmmo will only return ammo from one turret.

im working on a new type of service station where players can rearm, hence how/why i discoverd this.
i made a function to illustrate what i mean, however there is currently no way to check current bulletcount in each magazines like this (it could possibly be optimized, but it was a quick rewrite of what i used for the service station):

http://pastebin.com/7zJnv7eY

**Comment by Halvhjearne** [comment]
in fact, the way vehicles are spawned in epoch now, it is actually replenishing a magazine in turret [2] of all ghosthawks, on each restart.

**Comment by vbawol** [comment]
Is that not just the default loadout of that vehicle? If so we could make a Epoch version so we can empty out magazines from the configs or just remove them via code on the time of loading.

**Comment by Halvhjearne** [comment]
im not sure what you mean, you can check the example i provided on pastebin for the ghost hawk, you can see what i mean.

especially if you spawn a ghosthawk, run:
{object removemagazine _x}forEach magazines object;

now magazines/magazinesAmmo will return [].
however gettng in turret [2] will reveal a hidden magazine left behind, loaded into the weapon only shown using magazinesTurret or simmular.

**Comment by vbawol** [comment]
// remove ammo from turrets
					
					_mags = _vehicle magazinesTurret [0];
					{
						_object removeMagazinesTurret [_x, [0]];
					} forEach _mags;

					_mags = _vehicle magazinesTurret [-1];
					{
						_object removeMagazinesTurret [_x, [-1]];
					} forEach _mags;
					...

**Comment by Halvhjearne** [comment]
i almost forgot to say this, but as far as i have tested, any magazine in turret [2] wil not be detected by magazines/magazinesAmmo/magazinesAmmoFull.
afaik anything else in all other turrets are detected correctly.

personally i just added a few lines to remove all magazine in turret [2] on restarts to avoid duping issues, cause im now allowing my players to sell the magazine with my new service stations.

regarding your code, i think you might want to add exclusions for flare/chaff/smoke, if you do it like that or those will be removed aswell.
i think this is all of them:
["Laserbatteries","SmokeLauncherMag_boat","SmokeLauncherMag","300Rnd_CMFlare_Chaff_Magazine","168Rnd_CMFlare_Chaff_Magazine","192Rnd_CMFlare_Chaff_Magazine","240Rnd_CMFlare_Chaff_Magazine","120Rnd_CMFlare_Chaff_Magazine","60Rnd_CMFlare_Chaff_Magazine","240Rnd_CMFlareMagazine","120Rnd_CMFlareMagazine","60Rnd_CMFlareMagazine"]

btw, allTurrets works well to find all turrets in a vehicle, only turret [-1] is omitted.

**Comment by Halvhjearne** [comment]
i just wanted to let you know about the new command magazinesAllTurrets, wich is awsome for info about vehicle magazines, what turret they are loaded into and how many bullets are left in the magazine:
https://community.bistudio.com/wiki/magazinesAllTurrets

**Comment by Ignatz-HeMan** [comment]
Here the most important Weapons to be removed.
If worldname == Tanoa is to prevent magazine error on all clients, if they have not Apex.

```
        _allvehicles = allmissionobjects "Landvehicle" + allmissionobjects "Air" + allmissionobjects "Ship" + allmissionobjects "Tank";
        {
            if (!isnull _x) then {
                if !(((_x getvariable ["Ignatz_VehicleType",""]) isequalto "Hardcore-PvP")) then {
                    _x removeMagazinesTurret ["24Rnd_missiles",[-1]];
                    _x removemagazinesturret ["200Rnd_40mm_G_belt",[0]];

                    _x removeWeaponGlobal "missiles_DAR";
                    _x removeWeaponGlobal "gatling_30mm";
                    _x removeWeaponGlobal "gatling_20mm";
                    _x removeWeaponGlobal "missiles_DAGR";
                    _x removeWeaponGlobal "cannon_30mm_Plane_CAS_02_F";
                    _x removeWeaponGlobal "Missile_AA_03_Plane_CAS_02_F";
                    _x removeWeaponGlobal "Missile_AGM_01_Plane_CAS_02_F";
                    _x removeWeaponGlobal "Rocket_03_HE_Plane_CAS_02_F";
                    _x removeWeaponGlobal "Rocket_03_AP_Plane_CAS_02_F";
                    _x removeWeaponGlobal "Bomb_03_Plane_CAS_02_F";
                    _x removeWeaponGlobal "Bomb_04_Plane_CAS_01_F";
                    _x removeWeaponGlobal "Rocket_04_AP_Plane_CAS_01_F";
                    _x removeWeaponGlobal "Rocket_04_HE_Plane_CAS_01_F";
                    _x removeWeaponGlobal "Missile_AGM_02_Plane_CAS_01_F";
                    _x removeWeaponGlobal "Missile_AA_04_Plane_CAS_01_F";
                    _x removeWeaponGlobal "Gatling_30mm_Plane_CAS_01_F";
                    _x removeWeaponGlobal "GBU12BombLauncher_Plane_Fighter_03_F";
                    _x removeWeaponGlobal "missiles_ASRAAM";
                    _x removeWeaponGlobal "missiles_SCALPEL";
                    _x removeWeaponGlobal "Twin_Cannon_20mm";
                    _x removeWeaponGlobal "missiles_Zephyr";
                    _x removeWeaponGlobal "rockets_skyfire";

                    if (worldname == 'Tanoa') then {
                        _x removeWeaponGlobal "gatling_30mm_vtol_02";
                    };
                };
            };
        } forEach _allvehicles;
```

**Comment by Ignatz-HeMan** [comment]
Removes the Heavy Weapons / Magazines for:
- Hellcat Armed
- Orca Black&White
- Hummingbird armed
- HMG Boats
- Kajman
- Blackfoot
- VTOL
- XIAN
- some Jets
- And more...

**Comment by vbawol** [comment]
I believe this has now been addressed with https://github.com/EpochModTeam/Epoch/pull/688 if not please open a new issue referencing this issue.
