### ISSUE TITLE
config error with sapper

### ISSUE THREAD

**Issue by waynewr1** [EpochModTeam/Epoch#318]
Gaming on Altis dev server 1.48rc/dev build.
"No entry 'bin\config.bin.Smokeshell white" after killing boss sapper (repeatable)

Not sure if you are asking for Dev build bugs here, so i will just post this one untill i hear back.
Cheers.

**Comment by orangesherbet** [comment]
Didn't see this one, did kill a boss sapper but I had gone to lobby as the explosion killed me- good catch! And yes definitely critical to have bug reports like this :)

**Comment by 82ndab-Bravo17** [comment]
Doesn't seem to be only related to the Boss Sapper, have got it with ordinary sapper as well.

**Comment by vbawol** [comment]
fixed in experimental
