### ISSUE TITLE
[Bug][0.3.X RC Build Testing] Cinder Blocks paying out Metal Scraps

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#319]
Bug Report
Cinder Blocks paying out metal scraps

Date Seen
7/16/15

Versions
0.3.X
Server: Arma 1.48-RC Windows Server  Access Code: Arma3Update148RC
192.99.21.102:2302 

Bug Description
When swinging maul at the yellow cinder block pallets, it is paying out 2 Metal Scraps (no script error attached)

Severity
Minor

Steps to Reproduce
Tried with a few different cinder blocks, used the maul both times- same result

Actual Behavior
Pays out 2 Metal Scraps

Expected Behavior
Pay out 1 or 2 Cinder Blocks

Troubleshooting/Testing Steps Attempted
Tried with multiple pallets to reproduce- did not try with Sledgehammer (will produce same result I am assuming)

Workaround
N/A

**Comment by Korwiin** [comment]
Looks like the new description.ext has an array listing all the possible wrecks (that generate scraps?) and included in that list are some indfnc_*.p3d objects that I am going to guess are the yellow pallets.   Around line # 213.   I don't see a section that would be just for cinder blocks.   You may try experimenting with removing those items from the array and checking if they start dropping cinder blocks again.

**Comment by CPK001** [comment]
Confirmed, I tried with sledge hammer and metal scraps were produced when hitting cinder block stacks

**Comment by 82ndab-Bravo17** [comment]
Issue is in EPOCH_mineRocks.sqf, where a static lootable has been changed for a more dynamic one, and cinderblocks_f.p3d no longer returns in index of 0. Somewhere there is a wreck type that will be dispensing cinderblocks instead of metal scraps!

**Comment by vbawol** [comment]
Known issue, will fix for next build

**Comment by AltisTalesDusk** [comment]
Looks like this is still happening. Reported by players and tested myself. We're still getting metal scraps out instead of cinder. 

Interestingly though when I tested it before the update they were always dropping in pains. This time they dropped in both singles and pairs. Probably doesn't mean anything but I thought I'd mention it.

**Comment by vbawol** [comment]
fixed for next patch
