### ISSUE TITLE
Source for client folder (@Epoch) for dedicated server install

### ISSUE THREAD

**Issue by RoyDodd** [EpochModTeam/Epoch#320]
Love having the client files available on the Steam Workshop for automatic updating (including the Epoch Experimental branch) everyone's clients but it's a royal pain to get the @Epoch folder uploaded to our dedicated server from the current sources.

Could you add a repository here on GitHub for the client side files as well? This would greatly improve my server update workflow.

**Comment by Korwiin** [comment]
Alternatively, is it possible to use the steamCMD to pull the client files?   What would the app id number be?

**Comment by vbawol** [comment]
That would be ideal, we do have http download links on the site as last night and ModDB was updated on release as well as armaholic shortly after play with six updated.

Not sure if github would allow us to host a 1.2+Gb file if so then I wouldn't mind doing it this way.

**Comment by vbawol** [comment]
Also, Not sure if they have pushed the update yet but I did notify them: https://a3cdn.com/launcher/download/ServerUpdater/ServerUpdater.zip

**Comment by vbawol** [comment]
@Korwiin I think that would be the number at the end of the link (421839251), most other games support this way but I am not certain BI has.

http://steamcommunity.com/sharedfiles/filedetails/?id=421839251

**Comment by jsd1710** [comment]
"Not sure if github would allow us to host a 1.2+Gb file if so then I wouldn't mind doing it this way."
You could use Github's new feature: https://git-lfs.github.com/
I don't think it's available to the public quite yet for their own storage providing, but if you host the files from a server you have available then you can utilize the LFS feature no problem AFAIK.

**Comment by vbawol** [comment]
I will be pushing this script next build that works pretty well at downloading from the workshop using steamcmd.
```
@ECHO OFF
SE```T STEAMUN=admin@youremail.net
SET STEAMPW=chamgeme
SET ARMASVRPATH=C:\Arma3Server
SET ARMAAPPID=107410
:: Workshop IDs: EpochExperimental = 455221958, Normal Epoch = 421839251
SET ARMAWORKSHOPID=421839251
:: remove mod folder
rd /s/q "%ARMASVRPATH%\@Epoch"
:: remove cache C:\Users\Administrator\Downloads\steamcmd\steamapps\workshop
del "steamapps\workshop\appworkshop_%ARMAAPPID%.acf"
:: update workshop mod
START "" /WAIT steamcmd.exe +login %STEAMUN% %STEAMPW% +workshop_download_item %ARMAAPPID% %ARMAWORKSHOPID% +quit
:: copy files back to server 
xcopy /s/e/y/q/i "steamapps\workshop\content\%ARMAAPPID%\%ARMAWORKSHOPID%" "%ARMASVRPATH%\@Epoch"
```
