### ISSUE TITLE
Server update 0.3.0.4 missing data

### ISSUE THREAD

**Issue by LucyDemooon** [EpochModTeam/Epoch#321]
hey have updated:
@epoch
@epochhive
mission.sqf
description.sqf

23:12:46 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.A3_epoch_config
23:12:46 Mission Epoch Mod read from bank.
23:12:46 Missing addons detected:
23:12:46   A3_epoch_config

**Comment by vbawol** [comment]
check your mission file and that you do not have any sqf errors.
