### ISSUE TITLE
0.3.0.4 @EpochServer - No weather sounds

### ISSUE THREAD

**Issue by moosemilker** [EpochModTeam/Epoch#323]
Players can hear gun sounds, shooting, grenades, coughing, walking, church bells, but no wind, rain, weather.

Example at: http://moosemilker.com - running 4 maps.

Also see this Epoch forum thread: http://epochmod.com/forum/index.php?/topic/36522-0304-build-1-no-weather-rain-or-wind-sounds/

**Comment by zambiandude** [comment]
just having a look around and found this...

// Enable/disable environmental effects (ambient life + sound).
enableEnvironment false;

located in @Epoch\Addons\a3_epoch_code\compile\setup\EPOCH_clientInit.sqf

**Comment by vbawol** [comment]
Fixed for 0.3.1
