### ISSUE TITLE
Can't open shipping containers

### ISSUE THREAD

**Issue by waynewr1** [EpochModTeam/Epoch#325]
Getting error "Script A3/Structures_F\Scripts\Door_open.sqf not found"
Noticed this on the 1.48rc Altis Exp build before the update today and also since the update on Axeman's server Pianosa map.

Only seemed to give the error once. You still get the open door icon and the "search" text , but cant open the containers.

**Comment by andgregor** [comment]
Function has been renamed to fn_DoorOpen.sqf

**Comment by vbawol** [comment]
fixed for next build
