### ISSUE TITLE
Jammer problems since 3.0.4

### ISSUE THREAD

**Issue by WURS5000** [EpochModTeam/Epoch#326]
Since the new update following problems on all bases:

move parts of my base , message: "Building Disallowed: Protected Frequency"
build new parts , message: "Building Disallowed: Protected Frequency"
place a "new" jammer, message: "Building Disallowed: Existing Jammer Signal"

For unknown reasons, it's possible to disassemble base/remove building parts and  lock/unlock all doors if your the jammerowner.

**Comment by vbawol** [comment]
Check for any errors in your RPT and report back.
