### ISSUE TITLE
150 round 7.62 ammo does not work with Zafir 7.62 machine gun 

### ISSUE THREAD

**Issue by moosemilker** [EpochModTeam/Epoch#329]
This happened before in previous Epoch updates. The weapon is probably defined as mismatched to the wrong ammo type.

**Comment by wismerheal** [comment]
i can confirm but usually with the tracer bullets, you cannot laod them into the gun.

**Comment by donkeypunchepoch** [comment]
Marksman DLC changed the rounds on several wweapons including the Zafir.
http://feedback.arma3.com/view.php?id=23409
The Zafir was recently changed from 7.62x51 to 7.62x54R in the configs, but on the visual model, particularly in first person view, it's easy to see the ammunition casings which is still stamped with 7.62x51.

**Comment by vbawol** [comment]
This was fix already if I am not mistaken. If not please provide more information like the classnames.
