### ISSUE TITLE
Traders with no loot

### ISSUE THREAD

**Issue by 82ndab-Bravo17** [EpochModTeam/Epoch#331]
We seem to be getting traders appearing with no loot, Cannot be sure if they never get loot when they are first created, or whether the somehow lose it later. There seems to be no entry for them in the AI_ITEMS table, so I'm thinking that either they don't get loot when they are created, or their whole entry in the table somehow gets deleted.

We just had 32 traders in the AI table but only 20 entries in the AI_ITEMS table.

Just noticed that we also seem to have entries in the AI_ITEMS table with no corresponding entry in the AI table. As you can see from the attached image, most of these entries seem to be single digit traders, so maybe there is a character being lost in translation sometimes?

![rediserror](https://cloud.githubusercontent.com/assets/558672/8767953/765f6190-2e3c-11e5-80dc-269fcf6ee8c7.jpg)

**Comment by donkeypunchepoch** [comment]
Starting loot is in epoch config. Hpp

Static AI will only have an ai items in the db as their locations are saved in the corresponding map.h file

**Comment by 82ndab-Bravo17** [comment]
That could explain (I'll check later)  the AI_ITEMS without corresponding AI entry, but not the AI entries without an AI_ITEMS entry

**Comment by 82ndab-Bravo17** [comment]
Still happening in 0.3.4.0

**Comment by vbawol** [comment]
I did some work on this issue for 0.3.5, please report back after its released
