### ISSUE TITLE
New Battleye Scripts.txt changes

### ISSUE THREAD

**Issue by eltexonline** [EpochModTeam/Epoch#332]
Scripts.txt is now able to filter with no character limits and because of this they enabled logging only mode. Now that this change has been made we will be updating our filters to better make use of this new change. You may pastebin your Epoch related scripts.txt logs here and we will review them.

**Comment by RC-Robio** [comment]
Epoch Exp 0.3.1-1.48
http://pastebin.com/qZBzWFtY

**Comment by Cavemanpve** [comment]
Scripts.log
https://drive.google.com/file/d/0B6AWMU-g9WsbOGFSejhnZ0tTZU0/view?usp=sharing

**Comment by vbawol** [comment]
should be sorted for 0.3.1.0, please report any additional logs here. Next update will enable kicking //new2

**Comment by briankgregory** [comment]
I am still getting huge script.log files after the patch. I am not sure what exactly you are looking for here, but after patching yesterday with only about 10 people on my script.log went up to over 200mb. There was only one kick issue but I resolved. 

Here is a sample from last night: https://drive.google.com/open?id=0B_HUuS7AY7bQTmVKWEV4azU1UTA

**Comment by vbawol** [comment]
If you are using the latest scripts.txt from the 0.3.1.0 release then we are looking for the logs

**Comment by briankgregory** [comment]
disregard for the moment then and let me verify my scripts.txt is right. Thanks!

**Comment by rizlaman** [comment]
Agree with briankgregory here, since the update the scripts.log is being spammed and filled very quickly

**Comment by briankgregory** [comment]
OK, definitely running the new scripts.txt for 0.3.1.0. The sample is about an hour of server uptime.

https://drive.google.com/open?id=0B_HUuS7AY7bQTmVKWEV4azU1UTA

**Comment by vbawol** [comment]
Just checked and it seems most what is in your logs are from custom scripts. I will be comparing yours to our own dev servers.

**Comment by GalianFuria** [comment]
@briankgregory, might we know what custom scripts you using? I m having the same problem with the 0.3.1.0, and was wondering if we share an addon that causes the problem.
My main scripts are:
-LootSpawner
-AISSP 0.90
-Earplugs

Also just as info, we are using RHS addons in a Panthera map.

**Comment by briankgregory** [comment]
Ummm, you are going to have to a little more specific on which error you are referring to. I am running about 10 scripts.

**Comment by GalianFuria** [comment]
Script.log problem might have something to do with custom scripts we are ussing, according with vbawol. So maybe we are both using a script that causes the problem.

**Comment by vbawol** [comment]
#346 [0.3.1.0] DLCContentBrowser Script.txt log

**Comment by vbawol** [comment]
Please open a new issue for any stock scripts.txt kicks
