### ISSUE TITLE
Player above another has aim advantage. Can be fixed with:

### ISSUE THREAD

**Issue by donkeypunchepoch** [EpochModTeam/Epoch#336]
First time I'm adding a possible enhancement.
Player above another can aim down on player below at a greater angle then the player below can aim above, this should solve it.
Found on another git suggestion. Some edits might be needed if incorporated.

class CfgVehicles
{
                                class B_Soldier_base_F;
                class MylittleSoldier : B_Soldier_base_F
                {
                    minGunElev = -80; // Allows you to look more down 
                    maxGunElev = 80; // Allows you to look more up (Used to be 60, BI standard)
                    side = 1;
                    scope = 2;
                    audible = .05;
                    accuracy = 0.25;
                    camouflage = 1.4;
                    weapons[] = {"Throw","Put"};
                    respawnweapons[] = {"Throw","Put"};
                    magazines[] = {};
                    respawnmagazines[] = {};

**Comment by Pmba79** [comment]
If you change the angle to be able to fire up at an 80 degree angle, the drones will be way to easy to get rid of and the AI will never spawn as you can easily gun down the drone way to easily..
As it is now, you'll have to move location to fire at the drone, when it's close / above you and that way make it more interesting..

(I'd rather see a chop of both to 70 degrees, if they just absolutely have to be equal)

I'd say; leave it as it is..

**Comment by donkeypunchepoch** [comment]
Leave it as is has virtually perfect angle down while player below only has 60 degree range up, that sounds far from realistic and shows that another player has an advantage from within the coding, which is not how competitive should be, maybe PvE we could care less, but epoch deals with alot of PvP.

As mentioned it was found, not my work and some edits might be needed(configure with all aspects in mind I'd considered).

**Comment by vbawol** [comment]
I have put this change in for 0.3.7 so we will see how the feedback is after release.
