### ISSUE TITLE
anti teleport, teleporting player back into the air (with no parachute) after halo or parachute jumps

### ISSUE THREAD

**Issue by Halvhjearne** [EpochModTeam/Epoch#338]
idk if you remeber we talked about this?
anyway i thought i would post it here, just in case you forgot.

my guess is something like:

&& animationState player != "halofreefall_non"

would possibly fix it?

**Comment by vbawol** [comment]
If you could propose a fix for this we would certainly consider adding it as I would not be able to confirm the fix as easily. At first thought that might add a way to bypass the teleport check by simply going above 300m to induce the freefall anim.



https://github.com/EpochModTeam/Epoch/blob/master/Sources/epoch_server/init/server_securityfunctions.sqf

**Comment by Ghostrider-DbD-** [comment]
Possibilities that I see are:
add a setting to disable the TP AH;
add a time-stamp when the player spawns and skip the anti-TP check for some time thereafter, say 60 seconds;
add a check for the player altitude and skip the anti-TP action where altitude is greater than some value and the player vehicle == player or a chute (which has some vulnerability in theory).

**Comment by vbawol** [comment]
looking more into this, the code doesn't perform its checks if you are in a vehicle so it should only be when you are in that freefall state that it could be triggered. 

So ya, either we ignore it if the animation state is animationState player != "halofreefall_non" like @Halvhjearne  said or we work out the maximal speed the player can travel and make the 10 here https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_server/init/server_securityfunctions.sqf#L885 more dynamic to account for the increased distance traveled.

**Comment by vbawol** [comment]
tracking here: #583 

Will leave this open pending testing of any changes.

**Comment by vbawol** [comment]
I did some testing and it seems that just increasing the range alittle may fix this issue so I did that for b626. If this is an issue again please update this issue.
