### ISSUE TITLE
Unify auto refuel behavior between all maps

### ISSUE THREAD

**Issue by briankgregory** [EpochModTeam/Epoch#340]
Version: 0.3.1
ArmA Server Version: 1.48

On the Esseker map pulling up to the a gas pump does not trigger the autofuel function. Proximity does not seem to be an issue as a vehicle can be parked up against the pump and still not receive fuel. However, if I move my perspective so the pump is in the center of the view an action item comes up to refuel, however selecting this does not fuel the vehicle either.

**Comment by briankgregory** [comment]
This behavior was the same with .0.3.0.4 Build 1 and Build 2

**Comment by vbawol** [comment]
We actually need to unify this behavior between all maps, Altis, Stratis have auto fueling built into the map objects, esseker and other maps do not.

Changing the title to: Unify auto refuel behavior between all maps

**Comment by Vampurica** [comment]
The below code should disable all Altis/Stratis/Tanoa pumps from autorefuel.
```
_pumps = ['Land_fs_feed_F','Land_FuelStation_Feed_F','Land_FuelStation_01_pump_F','Land_FuelStation_02_pump_F'];
_allPumps = (epoch_centerMarkerPosition nearObjects EPOCH_dynamicVehicleArea) select {(getFuelCargo _x > 0) AND (typeof _x in _pumps)};
{_x setFuelCargo 0;} foreach _allPumps;
```

Not sure where it would be best to put it.

**Comment by vbawol** [comment]
Thanks @SMVampire case closed here 👍

**Comment by Vampurica** [comment]
My code is not working on experimental. setFuelCargo must be executed on each client to work.
Not sure that we want to put this code on the client. Maybe store all the pump objects the server finds in a publicVariable and have each client run the code on spawn? Issue needs reopened.

Need advised.

**Comment by vbawol** [comment]
That sounds fine @SMVampire , https://community.bistudio.com/wiki/setFuelCargo says it has global effect if the object is local, but I guess all the static buildings are local to each player and not the server?

**Comment by vbawol** [comment]
As per this comment https://epochmod.com/forum/topic/44293-auto-refuel-still-working-in-experimental/?do=findComment&comment=296977 that last change got it. Thanks for the help on this @SMVampire .
