### ISSUE TITLE
Server Error 03 installing Server 0.3.1.0 on 4 servers 

### ISSUE THREAD

**Issue by moosemilker** [EpochModTeam/Epoch#341]
I tried to run vanilla server files 0.3.1.0 with the current Redis DB server set up I already have, but players kept receiving Server Error 03 on connect. I tried upgrading every part of my server system down through the Redis files. I read and re-read the install and readme notes, but nothing helped.

I had to roll back to 0.3.0.4 and everything works.

**Comment by RC-Robio** [comment]
Maybe this will help. http://epochmod.com/forum/index.php?/topic/35063-server-not-ready-error-03/?p=237668

**Comment by moosemilker** [comment]
I closed this because I did not see there was an accompanying Epoch 0.3.1.0 client download as well... I maser the mistake of checking Armaholic for a client update and found it still states the client files at 0.3.0.4, but other download locations show 0.3.1.0.

**Comment by RC-Robio** [comment]
Client files are available on Steam and use the
https://github.com/EpochModTeam/Epoch/blob/master/Tools/Install/InstallEpoch.cmd
to install them for your server.

**Comment by moosemilker** [comment]
I manually got then from another place that was not Armaholic. All systems firing now. Thanks!
