### ISSUE TITLE
Player Revive Feedback

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#342]
#337 Being revived makes you loose weapon and ammos
#250 player revive causing dupe bug
#130 [Bug][v0.3 testing] killed and kicked once revived bug
#119 Hitting escape or trying to type while dead can prevent revives bug
#32 	Duplicating target's primary weapon after Multi-Tool Revive Player Kit.

**Comment by eedijs** [comment]
Is the heal attachment bugged? We have to fire several shots until it heals.

**Comment by Pmba79** [comment]
You always had to fire several shots to heal up.. 
Belive it's 4-5 shots..

**Comment by ScaRR-ZA** [comment]
We have had two incidents where revived players become invincible, taking no damage when shot. It doesn't seem to happen all the time but occasionally.

**Comment by sirkro** [comment]
This seems to be worse now. (Almost) all the time, the player will be invincible when revived. Not from green sappers and or crashing in helies

**Comment by StianKruger** [comment]
I have found the solution for it.

In the @epochhive\addons\a3_epoch_server\compile\epoch_player\EPOCH_server_revivePlayer.sqf, line 256 I added the following, then the player is no longer invisible and can be killed by AI

// Final Push
**_newPlyr allowDammage true; //added by ScaRR**
_token = _newPlyr call EPOCH_server_setPToken;

**Comment by vbawol** [comment]
oh ya, not sure why we even have this anymore, we don't do it in the login unit creation so I will remove and it should have the same effect. 

```
_newPlyr allowDammage false;
```
