### ISSUE TITLE
loots.h file still has old Rahim ammo listed (10Rnd 762x51 should x54) (line 680 in v0.3.1.0)

### ISSUE THREAD

**Issue by RoyDodd** [EpochModTeam/Epoch#344]
class SniperRifleAmmo
	{
		items[] = {
				{ { "20Rnd_762x51_Mag", "magazine" }, 1 },
				{ { "SniperRifleAmmo_5Rnd_127x108_Mag", "CfgLootTable" }, 1 },
				{ { "7Rnd_408_Mag", "magazine" }, 1 },
				{ { "10Rnd_762x51_Mag", "magazine" }, 1 },
				{ { "10Rnd_338_Mag", "magazine" }, 1 },
				{ { "10Rnd_93x64_DMR_05_Mag", "magazine" }, 1 },
				{ { "10Rnd_127x54_Mag", "magazine" }, 1 }

**Comment by vbawol** [comment]
Fixed for next build. Thanks!
