### ISSUE TITLE
0.3.1.0 bugs

### ISSUE THREAD

**Issue by rc162** [EpochModTeam/Epoch#345]
Boss Sapper does not produce green smoke when killed.
 
Some vehicles still appear to blow up on spawn in.
 
Cinder walls still require 4 cinder blocks.
 
Yellow Pallets giving scrap metal instead of cinder blocks,

**Comment by donkeypunchepoch** [comment]
Can't confirm sapper or pallets, However vehicle damaged on restarts yes.

Cinder walls req I ring 4 cinder might be caused by your own custom CfgCrafting file mission side.

**Comment by rc162** [comment]
Ok, thanks.

**Comment by rc162** [comment]
Removed custom crafting but no change unfortunately.

**Comment by AltisTalesDusk** [comment]
I can also confirm - Yellow Pallets giving scrap metal instead of cinder blocks.

One of our players logged in to two vehicles exploding and another reported a floating quad bike on load up. Dropping to the floor luckily didn't case enough damage to explode it though.

**Comment by rc162** [comment]
Just an update to confirm it is indeed the the custom crafting causing the cinder block issue I had not removed it properly.

**Comment by vbawol** [comment]
closing this bulk issue, please post in similar issues or post one issue per post if you still have issues to report.
