### ISSUE TITLE
No teleporters in spawn/cloning room.

### ISSUE THREAD

**Issue by JediChris816** [EpochModTeam/Epoch#348]
Updated to 0.3.1.0 today.  Didn't change any files or alter any code in the process.  Now when players login, they spawn in the cloning room however there are no teleporters on the floor, or in the room at all. 

![2015-08-02_00001](https://cloud.githubusercontent.com/assets/6133804/9028152/6430ae40-3934-11e5-9643-9302cfd3e415.jpg)

![2015-08-02_00002](https://cloud.githubusercontent.com/assets/6133804/9028153/6672481c-3934-11e5-848b-44d263f077a1.jpg)

**Comment by RC-Robio** [comment]
http://epochmod.com/forum/index.php?/topic/36621-bornholm-spawns/

**Comment by SirDice** [comment]
There are no sewer covers in 0.3.2.0 either. All the suggestions from the mentioned thread didn't help. Markers are correct on the map but there's no way out of the clone room :(

**Comment by donkeypunchepoch** [comment]
You changed both your Bornholm .h file as well as your mission.sqm?
There is a link to dl the new Bornholm. H file and a code change out for your mission  file

Others are reporting success with these modifications and even before they were open about adding in support for custom maps, those changes were what was needed to get up and running.

**Comment by JediChris816** [comment]
The answer to the teleporters is here, http://epochmod.com/forum/index.php?/topic/36621-bornholm-spawns/?p=256406.  I used it.

**Comment by SirDice** [comment]
It worked for me on 0.3.1.0, with the mission.sqm unedited. I did had to edit bornholm.h using post #15 http://epochmod.com/forum/index.php?/topic/36621-bornholm-spawns/?p=256406

This morning I updated everything to 0.3.2.0. Figured I didn't have to edit anything anymore. But alas, no sewer covers. I then tried the same telePos[] positions but unfortunately still no sewer covers. 

As far as I know the mission.sqm Markers are correct, they appear to be in the right place on the map. And I never modified them.

**Comment by vbawol** [comment]
Please reopen if this is still an issue.

**Comment by SirDice** [comment]
This is not fixed yet. This should work:
```
@@ -55,9 +55,12 @@ class Bornholm : Default
			{ 19819.5, 22216.8, 0.0780932 }
	};
	telePos[] = {
			{ "Transport_C_EPOCH", { -0.415527, -7.05298, -10.3098 }, "", { 14121.2, 11331.5, 0.000305176 } },
			{ "Transport_W_EPOCH", { -14.4316, 0.112793, -10.3098 }, "", { 1322.18, 8733.92, 0.0136757 } },
			{ "Transport_E_EPOCH", { 13.5127, 0.410156, -10.3098 }, "", { 15639.3, 191.995, 0.000153065 } }
			// { "Transport_C_EPOCH", { -0.415527, -7.05298, -10.3098 }, "", { 14121.2, 11331.5, 0.000305176 } },
			// { "Transport_W_EPOCH", { -14.4316, 0.112793, -10.3098 }, "", { 1322.18, 8733.92, 0.0136757 } },
			// { "Transport_E_EPOCH", { 13.5127, 0.410156, -10.3098 }, "", { 15639.3, 191.995, 0.000153065 } }
			{ "Transport_C_EPOCH", { -0.415527, -7.00298, -09.5098 }, "", { 14121.2, 11331.5, 0.000305176 } },
			{ "Transport_W_EPOCH", { -7.4316, 0.112793, -09.8598 }, "", { 1322.18, 8733.92, 0.0136757 } },
			{ "Transport_E_EPOCH", { 8.5127, 0.410156, -09.9398 }, "", { 15639.3, 191.995, 0.000153065 } }
	};
	propsPos[] = {
			{ "ProtectionZone_Invisible_F", { 13818.4, 6886.48, 0.278801 }, 0.17135 },
```
