### ISSUE TITLE
JetSki sinking?

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#351]
http://epochmod.com/forum/index.php?/topic/36956-jetskis-sink/

**Comment by RC-Robio** [comment]
Can confirm this across 3 different servers. They are not sinking but they already sunk on server.
Some are taking damage a few are just sunk with no damage.
10:42:16 "Class: jetski_epoch Damage: 0.367034 Hitpoints: [0.036898,0.0366507,0.305299,0.0995334]"
10:42:16 "BEFORE jetski_epoch: [0.367034,0.367034,0.367034,0.367034] Total Damage: 0.367034"
10:42:16 "AFTER jetski_epoch: [0.036898,0.0366507,0.305299,0.0995334] Total Damage: 0.367034"
10:42:17 "Class: jetski_epoch Damage: 0.268458 Hitpoints: [0.0266577,0.0270063,0.222577,0.0728266]"
10:42:17 "BEFORE jetski_epoch: [0.268458,0.268458,0.268458,0.268458] Total Damage: 0.268458"
10:42:17 "AFTER jetski_epoch: [0.0266577,0.0270063,0.222577,0.0728266] Total Damage: 0.268458"
10:42:17 "Class: jetski_epoch Damage: 0 Hitpoints: [0,0,0,0]"
10:42:17 "BEFORE jetski_epoch: [0,0,0,0] Total Damage: 0"
10:42:17 "AFTER jetski_epoch: [0,0,0,0] Total Damage: 0"
![2015-08-05_00002](https://cloud.githubusercontent.com/assets/6058597/9090432/da6649a8-3b5f-11e5-970d-5aacd189ece1.jpg)

**Comment by vbawol** [comment]
Fixed in 0.3.3
