### ISSUE TITLE
0.3.2.0 Exp build: food.

### ISSUE THREAD

**Issue by waynewr1** [EpochModTeam/Epoch#355]
Characters cannot eat or drink. Clicking on items just brings up "Examine or cancel" with no option to "use".

**Comment by mer8771** [comment]
I have that, but with med kits. It's not all the time, and I can't find a trigger for it either. Me and my friends have had that for a while. I just thought it was just us, and not the mod. :) Glad to know it's not us. If we wait a short while we can use them like normal. It's not every time just, some of the time. Is you food the same way or is it all the time?

**Comment by waynewr1** [comment]
i think this has just happened on the Experimental build 0.3.2.0 since it was patched in the last few hours, if this is happening to you on 0.3.1.0, you may want to submit a bug report.

**Comment by mer8771** [comment]
Yeah it's on not on this patch. It does it on every map, but I'm not too worried about it. I did 3 reinstall's but it's not stopped. We can live with it. Just close inventory and move a good 25 meters and then it works.

**Comment by SirDice** [comment]
Update to build 011 and the latest server files. That should fix the issue. The error was probably due to work being done on the interface.

**Comment by vbawol** [comment]
was fixed
