### ISSUE TITLE
0.3.2.0 BE kick tracker

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#357]
Post all stock BE filter kicks here

**Comment by D0vev** [comment]
After the update, some players are reporting kicks because of "CreateVehicle Restriction #1". BE Filters are updated, too.

**Comment by dnk-paul** [comment]
Using the admin menu 'Loot buildings (25m) kicks you with (publicvariable):
01.09.2015 22:08:39: Paul (IP:2304) #####- Value Restriction #2 "EPAH_hqtaygu" = ["Spawn Loot (25) for 3 Buildings (2 Container)",0,B Alpha 1-3:2 (Paul) REMOTE,"xynybdkbf"]

**Comment by Kakysas666** [comment]
Got kicked from Mell's House, script variable restriction #36. Was just driving a truck and got kicked..

**Comment by Kakysas666** [comment]
Constantly getting kicked for script restriction #48 in Mell's House server. Always am in a vehicle at a time, either heli or a car. 

It is kind of related (long shot guess) to approaching other vehicles, because in all cases when got kicked, other vehicles were nearby.
