### ISSUE TITLE
Server stucks on receiving data (linux)

### ISSUE THREAD

**Issue by unpure** [EpochModTeam/Epoch#358]
Hey there.
I'm currently having trouble with my epoch server.
The server is running the latest epoch files.
Everyone is stuck on receiving data while connecting.
Using the backup of my database fixes this problem, but only for a short time.
After 2h playtime the exact same problem happens again.
Everything is explained here:
http://epochmod.com/forum/index.php?/topic/37212-server-stuck-at-receiving-data/?p=259764

Serverlog: http://pastebin.com/n0TjnB5G

Here are some client rpt's after trying to connect to the server:
client #1: http://pastebin.com/txdWqNSi
client #2: http://pastebin.com/2mLJAthL
client #3: http://pastebin.com/9wVmajXw

**Comment by vbawol** [comment]
Can you try the epochserver.so from the 0.3.1 build?
https://github.com/EpochModTeam/Epoch/releases/tag/0.3.1.0

**Comment by unpure** [comment]
Yes i had this working with 0.3.1 but the problem occured on 0.3.1 the first time so this is nothing about 0.3.2 even if the problem still persist on 0.3.2.

Here is the server output log after starting the server and trying to connect: 
http://pastebin.com/LJfcg5Rd

**Comment by vbawol** [comment]
If you start with a fresh database how long before this issue starts up again? Also are you using any custom scripts that you can remove for now just to narrow this down. Also if you can please send me your dump.rdb that is having issues so I can examine it.

**Comment by vbawol** [comment]
please reopen if neeed
