### ISSUE TITLE
Found a IR-Laserpointer in a garbage heap, was not able to get it, it disappeared

### ISSUE THREAD

**Issue by Nasdero** [EpochModTeam/Epoch#36]
Found a IR-Laserpointer in a garbage heap, was not able to get it, it disappeared when I was trying to put in on my katiba. I tried also to put in my backpack, I closed the inventory and opened it again, the IR-laserpointer was gone.
We lost yesterday also some mags.

**Comment by vbawol** [comment]
please reopen if this is still an issue.
