### ISSUE TITLE
Undefined variable _find

### ISSUE THREAD

**Issue by SirDice** [EpochModTeam/Epoch#361]
On the latest experimental branch I'm getting a lot of error messages when loading vehicles:

21:43:13 Error in expression <e]);
_limit = _spawnPositionSize select _find select 1;

if (_limit > _nearBy) t>
21:43:13   Error position: <_find select 1;

if (_limit > _nearBy) t>
21:43:13   Error Undefined variable in expression: _find
21:43:13 File x\addons\a3_epoch_server\compile\epoch_vehicle\EPOCH_spawn_vehicles.sqf, line 148

Looking at the code in EPOCH_spawn_vehicles.sqf it appears the following line is missing:
_find = _allowedTypes find(getText(_selectedCity >> "type"));
Adding it just above _limit = ..... (and adding _find to the private variables) seems to fix it.

**Comment by Skaronator** [comment]
should be fixed, thanks

**Comment by SirDice** [comment]
Unfortunately, it isn't :(

**Comment by vbawol** [comment]
Please check again I just pushed the fix for this server side. Update epoch_server pbo

**Comment by SirDice** [comment]
Commit 113e8a6f3f6c1a413132799c23515c79bb019f35 fixed it. Thanks!
