### ISSUE TITLE
Unable to lock Lockboxes

### ISSUE THREAD

**Issue by D0vev** [EpochModTeam/Epoch#362]
I am having trouble to lock lockboxes on my server if I have opened them.

Information:
Lockbox owner: Another Player
Is owner in my group? Yes
I am logged in as AntiHack Admin.

Happens most time if the lockboxes are next to others and placed on wodden floor.

Epoch version: 0.3.2.0
Arma Version: 1.50 (tested in prev. version, too)

**Comment by vbawol** [comment]
not an issue that I could reproduce at this time, please reopen if you still have issues
