### ISSUE TITLE
on kitplotpole pro user id and on kitplotpole pro groups id

### ISSUE THREAD

**Issue by serveratze** [EpochModTeam/Epoch#363]
hey epoch team fix this please ! it annoys the user can build any more as a jammer! which also refers to the groups! my suggestion: on kitplotpole pro user id and on kitplotpole pro groups id ... there are always players who are trying to build 4 bases . Build limit in the new players have no chance to build up a base.

**Comment by vbawol** [comment]
Ill take this as a suggestion to limit number of jammers per group. If not please elaborate.

**Comment by serveratze** [comment]
ok that was just an idea of ​​mine. if it is too expensive , they leave it
