### ISSUE TITLE
Blue Tarp loot spawns on top of roofs

### ISSUE THREAD

**Issue by 82ndab-Bravo17** [EpochModTeam/Epoch#365]
I have noticed a lot of the Blue Tarp loot items spawning on rooftops. It is possible to 'search' them from the ground, but it doesn't seem to be possible to loot them.
![bluetarploot](https://cloud.githubusercontent.com/assets/558672/9563955/b64ebf84-4e63-11e5-8120-71c84e61aa80.jpg)

I have also seem the Black Guncases spawn on the roof of the office inside the warehouse buildings, but this is a lot rarer, and also it is possible to loot them from the ground.

**Comment by Pmba79** [comment]
This is done on purpose, just ask Axles ;)
(No joke)

**Comment by vbawol** [comment]
Might be more accessable now that I changed the weapon holder proxy location, we will likely redo these placements again soon.

**Comment by 82ndab-Bravo17** [comment]
Still seems to be impossible to loot the Blue Tarps, if the building is raised at all it is also seems to be impossible to even 'search' them.
