### ISSUE TITLE
0.3.2.0 Build areas

### ISSUE THREAD

**Issue by dnk-paul** [EpochModTeam/Epoch#366]
As detailed in my thread in the install help forum (http://epochmod.com/forum/index.php?/topic/37280-0320-restricted-build-areas/) it looks like the 'Restricted Build Areas' isn't working correctly.

I have set 'Build near military' to 1 (to allow building near military), and have commented out all of the restricted zones in the Altis.hpp file, but you're still unable to build in any of the build zones (I have tried the bit military base north of the central spawn point, and at Kavala Castle). Config files can be found here to save a mile long post: http://epochmod.com/forum/index.php?/topic/37318-0320-restricted-build-areas/

Paul

**Comment by vbawol** [comment]
Please reopen if this is still an issue, the new way is a bit different please see this post http://epochmod.com/forum/index.php?/topic/38540-building-restrictions/
