### ISSUE TITLE
Stealing uniforms from AI in backpack

### ISSUE THREAD

**Issue by JCae2798** [EpochModTeam/Epoch#367]
When trying to take uniform while wearing DLC sniper one (LUSH), i cannot take them and put them in my backpack.  Maybe an ARMA issue, but thought i'd bring it up for others to test and verify?

**Comment by mer8771** [comment]
My server does that as well. I just take off my suit and put it on the ground, and then pick up the new one, then put my old one back on. Make sure it's not a female suit going on to a male. That did happen once and the server crashed. On restart everyone's gear in their suit was empty, and the suit was missing from everyone. I do have an AI mission on my server.

**Comment by vbawol** [comment]
as of 0.3.9 the Epoch Militia soldiers should now not drop any uniforms as they are for the wrong side hence the inability to pick them up.
