### ISSUE TITLE
Error: Script x\addons\a3_epoch_code\System\EPOCH_callSapperMigration.sqf not found

### ISSUE THREAD

**Issue by phm-a3e** [EpochModTeam/Epoch#368]
I've been building and playing totally vanilla servers for about 2 months now and see this probably on 20% of sapper spawns.  Sometimes, I never see it.  Other times, it happens constantly.

Happens currently in 0.3.2.0

**Comment by andgregor** [comment]
Sorry, thought this was closed. Sqf is in compile folder. Will update.

**Comment by vbawol** [comment]
It the path issue should already be sorted for 0.3.3
