### ISSUE TITLE
Consuming first aid kit inside of vehicle does not heal, but first aid kit disappears from inventory

### ISSUE THREAD

**Issue by phm-a3e** [EpochModTeam/Epoch#369]
First Aid kits work as expected if you stop and consume it outside of the vehicle.  This isn't practical in a helicopter. :-)

**Comment by vbawol** [comment]
I put a fix in for this for 0.3.3

**Comment by phm-a3e** [comment]
Thank you!  And I put in a $40 donation today.

**Comment by vbawol** [comment]
Can you confirm, you can now heal inside a vehicle?

**Comment by phm-a3e** [comment]
Yes, will check tonight and let you know.

**Comment by phm-a3e** [comment]
I can confirm that using a first aid kit in a vehicle now heals the player.

Thanks!!!
