### ISSUE TITLE
issue when getAllHitPointsDamage returns []

### ISSUE THREAD

**Issue by Halvhjearne** [EpochModTeam/Epoch#373]
its nice to see you use of the new command :+1: , but i think you forgot a check to see if the object actually has any hitpoints.

in some cases it will return [], and will create a problem when you just use something like:

_hitpoints = (getAllHitPointsDamage _vehicle) select 2;

so far it only happends with pods for me, but just to let you know the problem is there ...

 0:27:08 Error in expression <_hitpoints = _arr select 3;

if ((count _actualHitpoints) == (count _hitpoints))>
 0:27:08   Error position: <_actualHitpoints) == (count _hitpoints))>
 0:27:08   Error Undefined variable in expression: _actualhitpoints
 0:27:08 File x\addons\a3_epoch_server\compile\epoch_vehicle\EPOCH_load_vehicles.sqf, line 67

my guess is a something like this can fix it:

_hitpoints = getAllHitPointsDamage _vehicle;
if !(_hitpoints isEqualTo [])then{

the problem will also arise when saving vehicles cause of new code.

**Comment by vbawol** [comment]
I must admit we only tested this with the default Epoch vehicles. I would have thought that it would return [[],[],[]] instead but this should be easy to account for ill get a server side hotfix out soon for this.

**Comment by vbawol** [comment]
just adding a check added check for getAllHitPointsDamage returning a blank array when loading buildings. https://github.com/EpochModTeam/Epoch/releases/tag/0.3.3.037
