### ISSUE TITLE
Epoch v3.3 - Mells House - Revive Bug

### ISSUE THREAD

**Issue by crazymike10** [EpochModTeam/Epoch#374]
Have tried a few times:

Player kills admin -> Revive -> works fine.

Admin Kills player -> Revive -> Player gets kicked for Token Check. Logs back in fine. 

Couldn't check it with player vs player, but pretty sure it would do the same thing.

**Comment by vbawol** [comment]
Fixed with build 4
https://github.com/EpochModTeam/Epoch/releases/tag/0.3.3.039
