### ISSUE TITLE
0.3.3.0 - Can't craft any of the new items

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#375]
They just don't show up in the recipes and even none of the solar generator items offer "Craft".
I can build plywood walls though (with lockable doors).

**Comment by vbawol** [comment]
Update your cfgCrafting config to the latest from our files, if using a custom one it is likely out of date.

**Comment by eedijs** [comment]
I don't know where that file can be found, I'm just a player, not an admin. Epochmod got updated for me automatically through steam workshop.

**Comment by vbawol** [comment]
Simply inform the server admin they may need to update the server,
