### ISSUE TITLE
0.3.3.0 - vehicle repair parts don't work, the kit does

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#377]
Someone posted this on forums, might help you find the issue:

This error is with small repair parts

}forEach ((getAllHitPointsDamage _vehicles) select >
19:52:02   Error position: <getAllHitPointsDamage _vehicles) select >
19:52:02   Error Allgemeiner Fehler in Ausdruck
19:52:02 File x\addons\a3_epoch_code\compile\EPOCH_consumeItem.sqf, line 205

**Comment by vbawol** [comment]
Found the issue, a client side hotfix will be issued for this.
