### ISSUE TITLE
0.3.3.0 Update removal of move function

### ISSUE THREAD

**Issue by Facey22** [EpochModTeam/Epoch#383]
1. Being able to move full height cinder walls over a metal door to stop door glitching was a big advantage against glitchers.
2. Removing the move function also prevents you from flopping cinder walls over on there side to make a cinder roof.
3. Removing this function you can no longer recover car jacks once they have collided with a vehicle by moving them to get the pickup option back.
4. Usually one or two base objects do not get covered by the maintain function and remain damaged, by moving this onject you can refresh it.

4 reasons to re-introduce the move option :)

Also any chance you can make metal doors bulletproof?

**Comment by vbawol** [comment]
Thanks for the feedback, I will be working on this more for the next patch.
