### ISSUE TITLE
EPOCH_server_repairVehicle.sqf script error

### ISSUE THREAD

**Issue by ScaRR-ZA** [EpochModTeam/Epoch#384]
I am getting the follow script errors in my rpt file.

17:37:40 Error in expression <20) exitWith{};

if ((_value select 0) == "ALL") then {
_vehicle setDamage 0;
}>
17:37:40   Error position: <== "ALL") then {
_vehicle setDamage 0;
}>
17:37:40   Error Generic error in expression
17:37:40 File x\addons\a3_epoch_server\compile\epoch_vehicle\EPOCH_server_repairVehicle.sqf, line 11

**Comment by vbawol** [comment]
fixed in 0.3.3.1

**Comment by vbawol** [comment]
Actually scratch that, do you have any other errors?

**Comment by vbawol** [comment]
Fixed, for next version

== changed to isEqualTo 
since this array now has numbers and strings it was incorrect to use ==

**Comment by ScaRR-ZA** [comment]
Sorry for the late reply, no other errors. Thank you very much for all your effort and hard work.
