### ISSUE TITLE
Wood floor moves after placing it

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#386]
I'm not sure if this is intended but sometimes when I place a floor on a foundation it snaps into place and stays in ghost mode, but mostly it stays in ghost mode until I place it and then physics start doing it's thing like shifting the floor or even throwing it up in the air, like it happened yesterday.

**Comment by vbawol** [comment]
This should be better since 0.3.5, but will continue to work on improving the snap checks.
