### ISSUE TITLE
Zero divisor error - Server Build: 0.3.3.1 for Arma 3 v1.50+

### ISSUE THREAD

**Issue by ScaRR-ZA** [EpochModTeam/Epoch#391]
This has been popping up in my rpt file.
12:19:55 Error in expression <
EPOCH_chargeRate = ceil(_totalCapacity / (count _players));
EPOCH_nearPower = t>
12:19:55   Error position: </ (count _players));
EPOCH_nearPower = t>
12:19:55   Error Zero divisor
12:19:55 File x\addons\a3_epoch_code\compile\setup\EPOCH_masterLoop.sqf, line 493

**Comment by vbawol** [comment]
Thanks for the report, fixed for 0.3.5
