### ISSUE TITLE
oneachframe error, client side rpt

### ISSUE THREAD

**Issue by ScaRR-ZA** [EpochModTeam/Epoch#394]
I get the following in my client side rpt.

13:56:22 Error in expression < (alive _x && isPlayer _x) then { _name pushBack(name _x) }} count crew vehicle >
13:56:22   Error position: <pushBack(name _x) }} count crew vehicle >
13:56:22   Error Type Number, expected Bool
13:56:22 File x\addons\a3_epoch_code\compile\EPOCH_onEachFrame.sqf, line 187

**Comment by Skaronator** [comment]
Should be fixed for the next patch, ty

**Comment by ScaRR-ZA** [comment]
Thank you
