### ISSUE TITLE
Sapper spawning causes lag

### ISSUE THREAD

**Issue by ScaRR-ZA** [EpochModTeam/Epoch#396]
Multiple reports and experience this myself on multiple servers. A 2 to 3 second lag spike is experienced when a sapper spawns near a player.

**Comment by thebigcarp321** [comment]
Thought it was just our server. Not complaining about the early warning system, but does kind of take the element of surprise out of the equation hehe.

**Comment by vbawol** [comment]
This is a known issue, if the players are displaying the main menu splash screen the sapper should be preloaded and not cause the issue.

**Comment by vbawol** [comment]
Not really fixed but we now spawn a sapper at the server startup to force a preload of the unit prior to players spawning one, hopefully this helps.
