### ISSUE TITLE
Crafting menu opening and closing

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#400]
We're not able to craft anything because the menu opens and closes instantly. Sometimes it works but mostly not.

**Comment by Pmba79** [comment]
What server ?

I tested on Mells House yesterday, worked fine..

**Comment by eedijs** [comment]
I'm playing on MGT Epoch Altis at the moment.

**Comment by Pmba79** [comment]
Ok, That might be tha issue then..
Can't say what MGT might have F***** up on their servers..

**Comment by vbawol** [comment]
It is random for the most part, we do know of this issue and will be working on a fix.

**Comment by eedijs** [comment]
I know I should suggest elsewhere, but the crafting times in our opinion is not good - it was better when you could instantly craft stuff. Other than that it looks good.

**Comment by Pmba79** [comment]
Well, IMO it's not really realistic to be able to craft instantly..
I know it can be annoying to have to wait, but it does add to the realism of the gameplay..

**Comment by vbawol** [comment]
The timer is there to stay but we will be lowering some of the times based on feedback.

**Comment by raymix** [comment]
admins can lower crafting times. Current values are development defaults
gear instantly closes when player moves, will soften this one by allowing to walk 1m or so.

**Comment by LenneRoijmans** [comment]
@Pmba79 Sad that you have to instantly draw conclusions in your hatred towards MGT. Try to stay objective when it comes to bug reports. @vbawol Good to know you guys are on the case.

**Comment by eedijs** [comment]
While we're here - can I ask if the lockboxes are bugged? We've always had problems with locking it - it just doesn't lock.

**Comment by Pmba79** [comment]
@LenneRoijmans It's not that I'm just drawing conclusions when it comes to MGT, but they have, in the past, made changes to EpochMod on thier own servers, and that does have sideeffects...

**Comment by kingchills** [comment]
We have noticed on our server (trhgaming.com) which is running vanilla epoch, no other mods, that this problem will occur on occasion as well.  There are times where every time you open the crafting menu it will close, but running around a bit or moving then trying again will often allow you to use the menu.  We have also noticed that using the movement keys (WASD) in the search box will on occasion cause the menu to close as well, for instance searching for water in the box will on occasion cause it to close as well. If you would like more information please let me know and I'll see what I can provide.

**Comment by raymix** [comment]
yeah, same issue, it closes dialog if player moved more than 0 meters, this will be fixed in next patch

**Comment by orangesherbet** [comment]
^^^ good deal, I was scratching my head to figure out how to reliably recreate this issue

**Comment by vbawol** [comment]
fixed for 0.3.5
