### ISSUE TITLE
Safe is not lockable

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#401]
We built it outside (no base) and we're not able to lock it because there is no option for that, but we are able to store items in it.

**Comment by thebigcarp321** [comment]
We applied the patch yesterday, thanks for the fix!

**Comment by orangesherbet** [comment]
safe should be lockable- tested in current version and exp build- new UI for this as well which is nice! feel free to close this issue if it is working

**Comment by eedijs** [comment]
It's working now, thanks!
