### ISSUE TITLE
Current  client build shows "Epoch Experimental" in Arma 3 main screen icon tooltip

### ISSUE THREAD

**Issue by RoyDodd** [EpochModTeam/Epoch#402]
I keep current with Epoch via Steam Workshop. When I start Arma 3 with Epoch, the icon above the DLC row for Epoch shows "Epoch Experimental" without a version number when you hover over it. I do subscribe to the Experimental branch also but I haven't used or enabled it yet.

**Comment by vbawol** [comment]
Thanks for the report, I just pushed a fix for this on the main Epoch mod workshop
