### ISSUE TITLE
Solar Generator Script Error

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#404]
Script error in relation to solar generator

Submitter
Dan Dalsted

Date Seen
10/17/15

Versions
0.3.4.0 (Mells House)

Bug Description
When running away from a solar generator, I got this script error on multiple occasions.
Unsure how to recreate (see attached screenshot for script error)

Severity
Minor
![ss 2015-10-19 at 04 25 58](https://cloud.githubusercontent.com/assets/4204940/10593186/b8268600-767e-11e5-82f6-6ccce1d21349.jpg)

**Comment by vbawol** [comment]
fixed for 0.3.5
