### ISSUE TITLE
Script Error Relating to Gutting Dead Animals , Interact Key wrong as well [EXP Build]

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#408]
Script Error related to gutting dead animals, interact menu wrong as well

Submitter
Dan Dalsted

Date Seen
10/19/15

Versions
Current Exp Build as of 10/19/15

Bug Description
Screenshot below shows the script error when gutting an animal.
Also, the key that shows up in the 3D Tutorial text says spacebar but it is still “I”

Severity

Minor

Steps to Reproduce
Kill an animal, approach it and gut it then press inventory right away- the error will appear some of the time.

When you approach an animal you have killed it says: “Press Spacebar. “ The key that works currently is still “I”

Actual Behavior
Script error occurs with animals occasionally when gutting
Interact Menu shows “Press Spacebar”

Expected Behavior
Script error will not occur

Key bind will be changed to spacebar
![ss 2015-10-19 at 04 46 47](https://cloud.githubusercontent.com/assets/4204940/10593521/b81c9372-7681-11e5-8470-8a9c708570e2.jpg)

**Comment by vbawol** [comment]
fixed for next build of 0.3.5
