### ISSUE TITLE
Lockboxes and safes - trouble unlocking and locking them

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#409]
I have no idea if this is intentional or if there is a timer - sometimes I can lock and unlock instantly, but most of the time I keep trying and trying - takes up to 30 seconds to get it locked or unlocked.

p.s. I saw that raymix is making a timer icon for future update, so maybe it is on a timer then?

**Comment by raymix** [comment]
its not really a timer, more like a current state detection. Icon shows when action is complete.

**Comment by vbawol** [comment]
I have recoded the way secure storage works again for 0.3.5 and can confirm this is  fixed and makes use of Raymix's new UI timer/cooldown system.
