### ISSUE TITLE
Hive weather/Static weather dont work. Missing "private" statement

### ISSUE THREAD

**Issue by Uranoxyd** [EpochModTeam/Epoch#412]
In `ChangeWeather.sqf` the checks for `isNil` like `if (isNil "_tempOVRD")` always fails because of the missing declaration with `private`.
Adding
```
private ["_tempOVRD", "_rainOVRD", "_fogOVRD", "_overcastOVRD", "_windOVRD"];
```
will fix this.
Greetings David

**Comment by vbawol** [comment]
Thanks David, I was actually under the the impression that execVM'ed scripts did not need a private array. I will go ahead and add this for 0.3.5 as it certainly will not break anything.
