### ISSUE TITLE
[Suggestion] Black Market Trader

### ISSUE THREAD

**Issue by XuanWuUnlimited** [EpochModTeam/Epoch#414]
Thought Process: After amassing copious amounts of Krypto I realized that there really is no "need" nor "want" for Krypto as everything can be looted enough to play the game. I also noticed that there are many wells for Krypto but no sinks. A Black Market Trader being implemented could potentially alleviate this issue by providing any item a player desires but at a premium.

Suggestion: Spawn 1 to X many Black Market Traders, X being relative to map size, in random locations across the map (unmarked).  Black Market Traders would have either limited or unlimited inventory but the items they sell would cost 2 or 3 fold more than their Trader counterpart.

Explaination: For instance you wanted a Lynx. You search the Traders on the map and find none. You are left with the option to either loot or search out the hidden Black Market Trader.  Both options requiring a little luck and a lot of time. The Black Market trader option would allow the player to get both the weapon and ammo they want but at a premium. Thus removing much Krypto from the server and giving Krypto some value. Say the Lynx could be purchased normally from a Trader at 400, a tax could be imposed of 100% or maybe 200% to increase it to 800 and 1200 Krypto respectively.  Hardly worth it but the player would be paying for convenience.  This system would most likely be more popular with ammo seeing as it would only jump from say 6 Krypto to 12 and 18 Krypto per.

Other Thoughts: I would personally use this for the 6.5 MX weaponry as magazines are consistently consumed by the server.  Also 40mm 3GL rounds and other grenade rounds (smokes and flares) are hard pressed to come by.  I would definitely throw away much of my Krypto to keep some on hand so I can actually use them against the hordes of aimbotty AI that spawn, have a smoke ready for a heli drop and to light up the night so that I can avoid using night vision and losing depth perception/getting blinded by swapping back and forth between night vision when I don't have a night vision capable optic.

**Comment by eedijs** [comment]
Post apocalyptic armored cars with remote controlled HMGs like Ifrits is all I want.

**Comment by vbawol** [comment]
This is a good idea and in line with what we have already done with DayZ Epoch so it makes sense to do it.
