### ISSUE TITLE
Script Error while looting (screenshot attached) [EXP Build]

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#416]
Script Error while looting

Submitter
Dan Dalsted

Date Seen
10/31/15

Versions
Current Exp Build as of 10/31/15

Bug Description
While looting I saw a script error 

Severity

Minor

Steps to Reproduce
Approach a shelf and loot, script error appears

Actual Behavior
Script error while looting

Expected Behavior
No script error while looting

Notes:
I had replaced my "Action" key "Space" with "E"
And I don't recall when this error happened, but I believe this was before I did that but it is worth mentioning.
![2015-10-31_00002](https://cloud.githubusercontent.com/assets/4204940/10865462/5d8bb8e4-7fd1-11e5-983f-476521c4ecb6.jpg)

**Comment by orangesherbet** [comment]
See attached screenshot for error

**Comment by raymix** [comment]
thanks for the submission, Dan. Fixed in my branch
