### ISSUE TITLE
Script error - client side - zero divisor

### ISSUE THREAD

**Issue by ScaRR-ZA** [EpochModTeam/Epoch#417]
Epoch version 0.3.4.050

12:07:44 Error in expression <
EPOCH_chargeRate = ceil(_totalCapacity / (count _players));
EPOCH_nearPower = t>
12:07:44   Error position: </ (count _players));
EPOCH_nearPower = t>
12:07:44   Error Zero divisor
12:07:44 File x\addons\a3_epoch_code\compile\setup\EPOCH_masterLoop.sqf, line 518

**Comment by vbawol** [comment]
should be fixed for 0.3.5
