### ISSUE TITLE
Floor Snap Foundation doesnt work right.  [Experimental 0.3.5.033]

### ISSUE THREAD

**Issue by GERDerDennis** [EpochModTeam/Epoch#419]
https://youtu.be/i0eWteJtkFU

**Comment by GERDerDennis** [comment]
Experimental Update: 

https://youtu.be/8C5X2tQlLlE

**Comment by vbawol** [comment]
Thanks for the report, this should be working now. I am actually in the middle of working on refining the snapping checks system.
