### ISSUE TITLE
CfgVehicles: Missing ';' at the end of line

### ISSUE THREAD

**Issue by viper179** [EpochModTeam/Epoch#423]
Showing this in the rpt for the client side @epoch

File x\addons\a3_epoch_config\Configs\CfgVehicles.hpp, line 3867: '/CfgVehicles/Spike_TRAP_EPOCH.armor': Missing ';' at the end of line

File x\addons\a3_epoch_config\Configs\CfgVehicles.hpp, line 3882: '/CfgVehicles/Metal_TRAP_EPOCH.armor': Missing ';' at the end of line
===============================================================================
making the safes and lock boxes not lock says they are locked but players still can access them. Code breaks before the pvar is sent to the server and locks it all the way.

**Comment by RC-Robio** [comment]
There are two lines with semicolon missing: Line 3868
class TRAP_EPOCH : Constructions_static_F {};
	class Spike_TRAP_EPOCH: Constructions_static_F
	{
		scope = 2;
		model = "\x\addons\a3_epoch_assets\models\sticks.p3d";
		displayName = "Spike Trap (SIM)";
		simulClass = "Spike_TRAP_SIM_EPOCH";
		staticClass = "Spike_TRAP_EPOCH";
		GhostPreview = "Spike_TRAP_EPOCH";
		ammoClass = "Spike_TRAP_AMMO_EPOCH";
		energyCost = 0.2;
		limitNearby = 2;
		bypassJammer = 1;
		armor = 0.1 <------------------------------------
	};

And Line 3883

class Metal_TRAP_EPOCH: Constructions_static_F
	{
		scope = 2;
		model = "\x\addons\a3_epoch_assets\models\sticks.p3d";
		displayName = "Metal Trap (SIM)";
		simulClass = "Metal_TRAP_SIM_EPOCH";
		staticClass = "Metal_TRAP_EPOCH";
		GhostPreview = "Metal_TRAP_EPOCH";
		ammoClass = "Metal_TRAP_AMMO_EPOCH";
		energyCost = 0.4;
		limitNearby = 2;
		bypassJammer = 1;
		armor = 0.1   <---------------------------------
	};

**Comment by RC-Robio** [comment]
Also are you using infistar? I am unable to reproduce the problem on a vanilla server.

**Comment by MGTDB** [comment]
Happens with or without infiSTAR, also pulling the vehicles.hpp into mission file and adding it to description.ext doesn't prevent the log, I would assume it would break armor?

**Comment by RC-Robio** [comment]
Was just able to reproduce the bug. Original person that lock the vehicle cannout access the inv. But any other player can.

**Comment by viper179** [comment]
Yea there you  go same issue here since I found it first hahahh , gg mgt ,
but Yeh even without infi like mgt said still having the issue

**Comment by vbawol** [comment]
The 052 server side fix should have sorted the inventory issues. This has been fixed but will require a new client build.

**Comment by vbawol** [comment]
If anyone is still having issues with this and is using custom Event Handlers need to make sure this is code is included at the end of the InventoryOpened EH

```
(locked (_this select 1) in [2, 3] || (_this select 1) getVariable['EPOCH_Locked', false])
```
