### ISSUE TITLE
Vehicle Limits

### ISSUE THREAD

**Issue by dnk-paul** [EpochModTeam/Epoch#425]
At the moment, the vehicle limit is set by the amount of vehicles set in the spawn options in the config.
This is ok, but it means that if you have a 3rd party trader system (the black market trader system), you  either can't buy the vehicle, or is randomly disappears on restart.

Can there be a soft limit (set by the vehicles spawned), and a hard limit (the maximum number of vehicles allowed on the server) instead of just having the one limit?

**Comment by vbawol** [comment]
There is a limit of how many vehicles can be on the traders, its default setting is 20 

to change this you can set the variable:
```
storedVehicleLimit = 10;
```
inside your CfgEpochServer config
