### ISSUE TITLE
Can't build walls inside of walls or floors anymore?

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#429]
Before the update you could e.g. place cinder walls inside a floor and it would stay that way but now when I do it, it comes out of ghost mode and jumps out of whatever I placed it inside of.

**Comment by eedijs** [comment]
I thought this happened only on my third floor but it seems so happen also in second floor and other places - seems random - some places I can place a wall inside wall (or anything e.g. stairs,floors) and it would stay that way in ghost mode until it's done building, but most of the places it just jumps out instantly. I hope this was not intended as of 0350.

**Comment by vbawol** [comment]
The snap points only check at the edges of walls and floors for contact, will see about making the checks cover the entire object instead.

**Comment by eedijs** [comment]
What I meant was - snap build or free build doesn't allow to build for example a wall half way into a floor most of the time - it jumps above it or away completely.

**Comment by vbawol** [comment]
should be for the most part sorted with the last commit. This will be live as of 0.3.9 b557.
