### ISSUE TITLE
Vehicles disappearing after restarts

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#430]
I guess you already know this, but I did not see an "issue" posted here so I'll do it.

As an admin of MGT told me:

 "Vehicles are best stored on the ground in a 1.5 wall high 3x3 cube on flat ground. Vehicles move a very small distance every time players move into the area or log into the game nearby."

But why? Is that an epoch bug that causes vehicles to disappear if placed on wooden floors? Even boats and submarines disappear in my base - I had them placed on water and at least 2 meters away from walls - disappeared anyway. And there is this weird thing going on - sometimes a vehicle disappears and reappears after a few restarts - sometimes I can access them, sometimes not.
I have even tried placing them exactly pointing north as I was told vehicles spawn pointing north and then rotate to last saved position - helps if the car is on the ground, but not when on the floor.

**Comment by sirkro** [comment]
This happens on the server I am playing on too (OX3). Also we see that vehicles dissappeared may respawn again randomly on restart.

See this with helies and cars, haven't tested with boats.

See this espesially if you build floors above water or rocks and then park the vehicle on floors.

At my current base, I've found that just moving the heli one floor in one direction is ok, moving it to center of base makes it explode (Ghost hawk).

**Comment by morgoth0** [comment]
I saw this happen the other day after server restart. Checking on a player's base TPed in to see a burning Bradley next to a wall. The problem with this is that players don;t know and think the vehicles have despawned and it's a server bug...

**Comment by vbawol** [comment]
this is reported fixed as of 0.3.9
