### ISSUE TITLE
Weight System from Arma 3 is much to high

### ISSUE THREAD

**Issue by GERDerDennis** [EpochModTeam/Epoch#434]
Weight System from Arma 3 is much to high. You can only carry a navid and a cinderblock in your bagpack. 

All these new commands doesnt work to bypass it. 

https://community.bistudio.com/wiki/Category:Introduced_with_Arma_3_version_1.54

**Comment by eedijs** [comment]
I'm wearing a full ghillie, GA carrier gl rig and a backpack + gm6 lynx - my vest is full, but my ghillie and backpack is empty and I cannot take anything more than that. This is no good in epoch.

**Comment by vbawol** [comment]
Thanks for the report, I will look into this asap.

**Comment by vbawol** [comment]
should be sorted for 0.3.6, if not please reopen.
