### ISSUE TITLE
Error Type String, expected Control EPOCH_getIDC.sqf, line 6

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#437]
10:37:28 Error in expression <e ["_in","_list","_out","_find"];
_in = param [0,controlNull,[controlNull]];
_li>
10:37:28   Error position: <param [0,controlNull,[controlNull]];
_li>
10:37:28   Error Type String, expected Control
10:37:28 File x\addons\a3_epoch_code\gui\scripts\EPOCH_getIDC.sqf, line 6

**Comment by raymix** [comment]
i've a feeling that new update ignores _this before param
so a solution will most likely be just that ... adding _this before param.

I'll merge latest beta when i get back from work, see what's going on

**Comment by raymix** [comment]
fixed using bis_fnc_param
