### ISSUE TITLE
Difficulty opening vehicles 3.5

### ISSUE THREAD

**Issue by northrivergeek** [EpochModTeam/Epoch#438]
I can't seem to get a vehicle option to get in as driver/pilot since this update, cant be just me.

**Comment by RC-Robio** [comment]
No issues unlocking or getting into vehicles. Make sure you unlock first by using spacebar, then you will get scroll wheel option. On certain heli's you will need to move around a bit but the option does show.

**Comment by vbawol** [comment]
should be sorted for 0.3.6, if not please reopen.
