### ISSUE TITLE
Please restore BIS_fnc_MP

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#442]
With the addition of the CfgRemoteExec class in 1.50 is it still necessary to leave BIS_fnc_MP commented in Epoch? Some popular mods that can work well alongside Epoch have reduced functionality (notably no attack animations with Ryan's Zombies & Demons) with their removal. 

Please consider uncommenting these functions and leave it to server owners to decide which remote functions to permission using the CfGRemoteExec class.

Cheeers,
Grahame

**Comment by raymix** [comment]
It's just a function - a script file that you can bring to mpmissions yourself.

**Comment by vbawol** [comment]
I will remove our overrides of BIS MP in the next udate 0.3.6

**Comment by morgoth0** [comment]
Hi,
   Thank you so much. I'm loving Epoch and the work you're doing. 

Cheers,
Grahame

**Comment by vbawol** [comment]
This should be fixed for 0.3.6. it is not in the release notes but I did remove the BIS function classes overrides in the functions pbo.
