### ISSUE TITLE
[v 0.3.6 exp] Carrying Lynx will cause fatigue to go to 1 and stay there

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#443]
I was slightly toxic (see attached screenshot) and looted a lynx out of a pelican case.  I proceeded to have 100% fatigue even though my stamina was fine.  I was able to recreate this by dropping the sniper and picking it back up. As soon as it is equipped your fatigue goes to 1.  Have not tested this on the live version but it exists in v0.3.6
![2015-12-09_00001](https://cloud.githubusercontent.com/assets/4204940/11697906/46beb2ee-9e79-11e5-93ea-3b0774278c47.jpg)

**Comment by 82ndab-Bravo17** [comment]
Fatigue seems to go to 1 as soon as you are carrying the max weight. If you drop anything so that you are below the max weight then it immediately goes to 0.

**Comment by orangesherbet** [comment]
I can confirm this ^^

**Comment by vbawol** [comment]
I am looking into the new stamina systems so we can figure out how to best sort issues like this out.

**Comment by vbawol** [comment]
This should be mostly fixed for 0.3.6
