### ISSUE TITLE
0.3.6.0 Lock Boxes / Safes unable to interact

### ISSUE THREAD

**Issue by Rhidalin-Bytes** [EpochModTeam/Epoch#451]
With the recent 0.3.6.0 patch I've had numerous reports from our players about not being able to enter their locked safes.

Almost all existing safes and lock boxes are only able to be inspected, the lock / unlock / pack dialog does not appear. ~~I have placed two lock boxes post 0.3.6 and I am able to interact with those two.~~ This occurs through multiple client reconnects and has been consistent with which items are rendered inoperable. I've included some reference pictures to possibly aid in duplicating the issue and to clarify the extent of the problem.
(update) After server restart the two accessible lock boxes became inoperable.

Inoperable means:
1. No inventory status circle appears whilst looking at the safe
2. The use action key prompts only the inspect / examine symbol
3. No lock / unlock / pack prompts ever appear

All these safes are inoperable.
http://steamcommunity.com/sharedfiles/filedetails/?id=577945720

http://steamcommunity.com/sharedfiles/filedetails/?id=577945766

http://steamcommunity.com/sharedfiles/filedetails/?id=577945793

~~These two lock boxes are accessible:~~
(update) These two are inoperable after server restart.
http://steamcommunity.com/sharedfiles/filedetails/?id=577945818

Let me know if I can include anything else that may be helpful.

Thanks,

**Comment by vbawol** [comment]
Thanks for the report, looking into it.

**Comment by sirkro** [comment]
New safes and lock boxes seems ok.
If an old safe was unlocked before the update, it will work.
If an old safe was locked before the update, it will not work

**Comment by RC-Robio** [comment]
Tested with old DB and New DB. They will all become inaccessible after a restart.

**Comment by sirkro** [comment]
Yes, found out now. Even if it worked before restart with new epoch version. It will be inaccessible after restart

**Comment by MGTDB** [comment]
Many of our players are reporting that they cannot gain access to their safes since 0.3.6.0

**Comment by MGTDB** [comment]
So I have a lot of players now with multiple safes that have gear in that they cannot use, any eta on a hotfix?

**Comment by vbawol** [comment]
From the sounds of it it could simply be the addition of enableSimulationGlobal false on these objects at first spawn. However that was added with 0.3.5.055 server build.

I have commented out these lines and repacked the pbo found here: https://github.com/EpochModTeam/Epoch/blob/experimental/Server_Install_Pack/@epochhive/addons/a3_epoch_server.pbo?raw=true

Please give this a test and let me know if that does anything.

Thanks!

**Comment by RC-Robio** [comment]
Yep, seems to be working fine.

**Comment by Rhidalin-Bytes** [comment]
This appears to have resolved the issues, thanks for the prompt intercession.

Rhid
