### ISSUE TITLE
Snakes biting through floors and open doors

### ISSUE THREAD

**Issue by MGTDB** [EpochModTeam/Epoch#456]
[2015-12-26 | 19:07:31] (Side) gumboots_smithy: i never knew snakes could open doors!
[2015-12-26 | 19:07:55] (Side) [x] Trident: it must be solid snakes

**Comment by andgregor** [comment]
Plisskens.

**Comment by RC-Robio** [comment]
They can bite through floors no matter the height and now I have to watch Escape from New York.

**Comment by vbawol** [comment]
Snakes opening doors is nothing new... but we maybe able to do something about them biting through floors.

**Comment by Necrous** [comment]
Actually it's the same with the dogs...I mean about opening doors. Even if there is a Cinder Block Garage Door before the "common door".

**Comment by vbawol** [comment]
for 0.3.7
[Fixed] Snakes now require line of sight to bite player.

The opening door part still needs looking into
