### ISSUE TITLE
Anyone can lock your vehicle from outside and you can't unlock it anymore

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#457]
Until the timer expires. They don't even have to get in - they run up to your car, lock it and that's it.

**Comment by vbawol** [comment]
just put in a change in for 0.3.7 that makes it possible for the driver or passengers of a vehicle without a driver to also control the locks. This should make it impossible that you can get locked inside a vehicle.

**Comment by eedijs** [comment]
It's already possible for the driver and passengers to lock/unlock from inside, the problem is that complete strangers run up to your vehicle and are able lock it.

**Comment by vbawol** [comment]
I made a few changes that should account for this. Basically if the target vehicle is occupied you must already be the owner to control the locks. Give it a test on 0.3.7 and let me know.
