### ISSUE TITLE
Tools are not working

### ISSUE THREAD

**Issue by Necrous** [EpochModTeam/Epoch#460]
Can't chop trees with the hatchet, salvage metal/cinder blocks with the sledgehammer, the same with the chainsaw/maul/crude hatchet/wooden club - no single tool is working correctly. Epoch version is 0.3.6.025.

**Comment by RC-Robio** [comment]
Need more info as to what map, addons,...ect.

**Comment by Necrous** [comment]
In my case it happens on Altis map, with RHS mod. I didn't try any other maps or playing without RHS.

**Comment by RC-Robio** [comment]
Tested on Exp and Stable and all the tools are working correctly.

**Comment by Necrous** [comment]
Testing right now without RHS mod on Altis map - Hatchet and Sledgehammer are not working...don't know what might be the issue...any other suggestions?

**Comment by RC-Robio** [comment]
Check your rpt for any errors. Animations are broke in 0.3.6, but have been fixed in Exp 0.3.7 but other then that they all work.

**Comment by Necrous** [comment]
What is rpt? Could you please explain what to do exactly? I'll try to manage that..

**Comment by RC-Robio** [comment]
.rpt is a file in your server config folder.

**Comment by vbawol** [comment]
animations are fixed for the next build and is due to be released soon.
