### ISSUE TITLE
[Bug]v3.7.0-Exp Still possible to access locked lockbox

### ISSUE THREAD

**Issue by KS-Epoch** [EpochModTeam/Epoch#463]
First i thougt it is fixed, but then i manage to get in.

Need to put item on ground (as always), then you press and HOLD i and then you are inside.

Edit: need to put at least 3 items

**Comment by vbawol** [comment]
just be be sure are you testing without admin?

**Comment by KS-Epoch** [comment]
I was at BulletBuffet. Don't have an admin. Il try to reproduce one more time now

**Comment by KS-Epoch** [comment]
1. I am owner of this lockbox, and its locked
2. You dont need to drop any item, you just go close and press and hold your invetory key (i) for atleast 3 seconds.

**Comment by vbawol** [comment]
Ok thanks, will see what I can do.

**Comment by eedijs** [comment]
I tried, but couldn't get the inventory. All I know is that now we can just drop something near the safe and then get it open still.

**Comment by MGTDB** [comment]
Gaining entry to locked storage is painfully easy, just move away enough so your inventory opens, then keep it open and move closer to the locked storage, drop an item, close inventory, then look at ground item until you get open inventory option, then you have access to the locked storage inventory. https://www.youtube.com/watch?v=4O9vqtKeZ-c

**Comment by vbawol** [comment]
Current build of Experimental has for the most part fixed this will look forward to feedback after release..
