### ISSUE TITLE
EXP 0.3.7.0 9mm 16rnd mag repack dupe

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#464]
Issue: 9mm 16rnd mags duping when you repack them

Date Seen 1/7/16 

Versions 0.3.7.0 Exp
Bug Description 9mm 16rnd magazines will duplicate when full by clicking repack in your inventory
Also requires 9mm pistol / smg to my estimation.
Severity: Major

Steps to Reproduce
Find 9mm weapon and at least one magazine of 9mm 16rnd ammo
Select magazine in your inventory
Click repack and the magazine will duplicate
Repeat until your inventory is full

Actual Behavior
9mm 16rnd magazine easily duplicated with repack feature

Expected Behavior
full 9mm magazine should not be able to be repacked / duplicated

Troubleshooting/Testing Steps Attempted
tested with many other weapon / ammo types (including 9mm 30rnd magazine)
Poulmba recreated the issue with the 16rnd magazine

Workaround
N/A

**Comment by vbawol** [comment]
Good catch thanks guys! got it fixed in the latest Exp build.
