### ISSUE TITLE
EXP 0.3.7.0 Boss Sapper Illuminati Confirmed (Disappears)

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#465]
Issue: Boss Sapper confirmed Illuminati

Date Seen 1/7/16

Versions 0.3.7.0 Exp
Bug Description Boss Sapper disappears (cleans up) before detonation

Severity: Moderate

Steps to Reproduce
Trigger a Boss Sapper
Watch the animation play and it cleans up and disappears

Actual Behavior
Boss Sapper disappears before detonation

Expected Behavior
RIP anyone near Boss Sapper
A single tear shed for lost gear

Troubleshooting/Testing Steps Attempted
Triggered the Boss Sapper on 3 different occasions
Disappeared like a fart in the wind every time

Workaround
N/A

**Comment by vbawol** [comment]
Should be fixed in current Exp build, please confirm. Also, what sort of delay was there?

**Comment by Pmba79** [comment]
We tried 3 times today..
There where no delay, the animation played and instead of blowing up he just disapeared.
I'll go try to trigger another one and see if it's fixed.

**Comment by orangesherbet** [comment]
Confirmed working, and RIP to my gear. I'll get you next time Sapper! *shakes fist*
![2016-01-07_00005](https://cloud.githubusercontent.com/assets/4204940/12180851/1f9c741a-b53c-11e5-8f7a-2021d2a0c3dd.jpg)

**Comment by orangesherbet** [comment]
Consider the case of the disappearing Sapper closed, good work gang!
