### ISSUE TITLE
EXP 0.3.7.0 Stairs Snapping Mode 3 broken

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#466]
Issue: Stairs Snapping mode broken

Date Seen 1/7/16

Versions 0.3.7.0 Exp
Bug Description: When using snap direction mode 3 with stairs, after placing the stairs it reverts to snap direction 1 
Severity: Minor

Steps to Reproduce
Place stairs with snap direction 3
Wonder if you forgot to use the right buttons
Remove stairs and try again
Realize that the game hates you and use build mode 2 instead

Actual Behavior
When attempting to use snap direction 3, the stairs will always place with snap direction 1 no matter how much you pout and make frowny faces at the screen

Expected Behavior
snap direction 3 will place stairs in the proper orientation

Troubleshooting/Testing Steps Attempted
Placed stairs on several occasions, same result each time

Workaround
Using Build Mode 2 I was able to place the stairs where I needed them to be

**Comment by eedijs** [comment]
It's also kind of broken in 0360 - stairs, for example, show that it will be placed one way but after pressing "build" it returns to previous direction. I think it used to be like this for cinder walls, haven't tried.
