### ISSUE TITLE
[Suggestion]v3.7.0-Exp Make info where you can see current client and server build

### ISSUE THREAD

**Issue by KS-Epoch** [EpochModTeam/Epoch#469]
Make info where you can see current client and server build- maybe some hotkey or...

**Comment by vbawol** [comment]
You can see the current version on the debug monitor ~ key
and if you press Esc you should see our Key config system in the menu

**Comment by KS-Epoch** [comment]
I mean i want to help to test expiremental builds but i don't know robio server is updated or not for example 

also i dont know do im using latest experimetal- it doesn't show client version just date its updated
i want to prevent this im reporting issues thats alredy fixed

**Comment by RC-Robio** [comment]
Not my server, bulletbuffet is vbawols. And if you use Arma 3 Workshop and it updates then his server will be running the latest update.

**Comment by KS-Epoch** [comment]
if its vbawols then i can close it i think
