### ISSUE TITLE
battleye kick after repack ammo

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#470]
I tryed to repack my ammo on exp server and kick.
Battleye Script Restriction #22

**Comment by Pmba79** [comment]
What ammo type was it ?

**Comment by baaljayjay** [comment]
i tested with 9mm 30 rnd, 7,62x51 mm 20rnd and 9mm 16rnd.

**Comment by Pmba79** [comment]
Wierd, I tested both 9mm a few days ago, worked fine..
Will try again..

**Comment by baaljayjay** [comment]
yesterday i had tested and the worked but today it doesn´t work.
Few minutes ago tested with 45 acp 9rn and 6,5 mm 30 rnd stanag and battleye kick me.
 Another player tried and was kick.
(sorry for my bad english because not so good in english)

**Comment by RC-Robio** [comment]
Is this your server? Did you update the battleye filters?

**Comment by baaljayjay** [comment]
no tested on epochmod.com/bulletbuffet

**Comment by RC-Robio** [comment]
Good then vbawol will have the info to correct it.

**Comment by vbawol** [comment]
Thanks for the report! This should be fixed, if not please reopen.

**Comment by baaljayjay** [comment]
the last update it isn`t work
