### ISSUE TITLE
Putting on a vest causes magazines to disappear from backpack

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#471]
This has happened also when I loot corpses. With a safe it goes like this - have magazines (for the gun you're having? not sure about that) in the backpack and right click or drag to wear a vest and suddenly your backpack doesn't have the magazines anymore.

Another Arma 3 1.54 bug or epoch?

**Comment by Kakysas666** [comment]
Noticed similar bug myself, but only when I remove vest and put it back on.

**Comment by vbawol** [comment]
not sure about how it could effect backpack but the vest issue should be sorted as of 0.3.7.045. If this happens again after 0.3.7 is released please open another issue with the steps required to reproduce this.
