### ISSUE TITLE
EXP 0.3.7 Fuel Barrel Siphoning Issue

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#473]
Issue: Siphoning Fuel Barrel w/o proper storage room will result in deleting the barrel

Date Seen 1/12/16

Versions 0.3.7.0 Exp
Bug Description: When siphoning fuel to fill a fuel barrel the item will be deleted if you do not have enough space to store a fuel barrel
Severity: Moderate

Steps to Reproduce
(Keep in mind that this happens only when you do not have a carryall backpack or larger pack enough to carry a fuel barrel)
Approach fuel source with empty fuel barrel in inventory
Siphon fuel by selecting the empty fuel barrel in inventory
Fuel barrel deletes from your inventory

Actual Behavior
Fuel Barrel deletes from your inventory if you do not have enough space when siphoning

Expected Behavior
Fuel Barrel will drop onto the ground as "overflow inventory"

Troubleshooting/Testing Steps Attempted
Tried with a vest / smaller backpack

Workaround
When you have a carryall backpack or larger pack siphoning works fine

**Comment by vbawol** [comment]
Thanks for the report, This is fixed in latest Exp build, 035
