### ISSUE TITLE
battleye kick after repack ammo #470

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#475]
the last update on exp server it isn´t work
I don´t know how my old thread reopen

**Comment by vbawol** [comment]
Is this on Bullet Buffet jayjay?

**Comment by baaljayjay** [comment]
yes,I play on bullet buffet

**Comment by vbawol** [comment]
Ok BE filters updated it should be good now, please confirm.

**Comment by baaljayjay** [comment]
In the moment the works but in the future when updates of battleye. They can problems
