### ISSUE TITLE
tie up a another player

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#476]
my idea is when i have a rope and press space to near another player so can he tie up.
he can themselves with lighter or another tools.
it`s a example

**Comment by eedijs** [comment]
I hope epoch doesn't turn into a role playing game...

**Comment by baaljayjay** [comment]
but the can save life

**Comment by vbawol** [comment]
thanks for the suggestion! it will be taken into consideration for future updates.
