### ISSUE TITLE
Male(Female) characters lose vest items after equipping opposite sex's vest

### ISSUE THREAD

**Issue by aruazif** [EpochModTeam/Epoch#48]
It appears that the items that you have dissappear when you have the dan clothing. (only dan clothing)

I've had the items on me dissappear in the dan clothing after trading and after equiping a vest. 

I tried it again and the same thing happend. Not sure if intentional (cause of dan clothing not having pockets) or if a bug.

Would be nice if someone else could also test this.

What I did is either trade while only having the dan clothing and some items on you.
Or have some items on you and equip a vest. !extra info! I bought the vest from the trader so it was in my dan clothing, after equipping it dissappeard.

**Comment by vbawol** [comment]
This sounds like the unisex vests if you equip a female vest as a a male it will wipe the inventory of the vest.

**Comment by vbawol** [comment]
fixed in 0.3.7.045
