### ISSUE TITLE
Building parts snap incorrectly, then revert into correct position after 15-20 seconds (0.3.7.0)

### ISSUE THREAD

**Issue by Kakysas666** [EpochModTeam/Epoch#484]
![2016-02-04_00002](https://cloud.githubusercontent.com/assets/14334163/12799719/fe4f71d8-cad8-11e5-911c-20f5afc0e6bc.jpg)

In this example, stairs after placing them moved. However after some time (15-20 seconds) they reverted back into correct position. Not a massive bug, but pretty annoying :)

**Comment by Ghostrider-DbD-** [comment]
I have seen this with stud walls. Initially they snap to the correct position. After starting build, the switch by 90 degrees for a while then finally move back to their correct, final position. I'll take screen shots if it see this behavior again.

**Comment by Rhidalin-Bytes** [comment]
Record of it happening with a full cinder wall. This happened with the upgrade.

![2016-02-06_00001](https://cloud.githubusercontent.com/assets/303356/12874097/11aae2ac-cd9b-11e5-947b-dd3b59748e41.jpg)
![2016-02-06_00002](https://cloud.githubusercontent.com/assets/303356/12874100/18acbbf2-cd9b-11e5-8e6c-08f25dac2d78.jpg)

**Comment by vbawol** [comment]
This is likely due to some changes in Arma engine but I will look into this more.

**Comment by vbawol** [comment]
This is fixed for 0.3.8
