### ISSUE TITLE
BattleEye script restriction on underwater loot

### ISSUE THREAD

**Issue by Rhidalin-Bytes** [EpochModTeam/Epoch#485]
Player action: Take loot
Server action: Kick player for Script restriction #21 
Steps to duplicate action:
          Travel to underwater sea chest
          Search sea chest
          Hit take button

Loot may or may not survive the kick process. It has been reported both ways.

-Rhid

**Comment by AporreaCodigo** [comment]
I fix it just adding in script.txt line#21 (starts with "7 addMagazine ="addMagazinegCargo...etc etc.") "!=player addMagazine[_x select 0, _x select 1];"

**Comment by Rhidalin-Bytes** [comment]
That worked a champ.

**Comment by vbawol** [comment]
That is correct, I had changed the format from
```
!="player addMagazine[(_x select 0), (_x select 1)];" 
```
to 
```
!="player addMagazine[_x select 0, _x select 1];" 
```
and failed to update the scripts.txt. 

This fix will be in the next hotfix:
https://github.com/EpochModTeam/Epoch/raw/13eedaba8777f3732f046dd9ddd34031cb1ed580/Server_Install_Pack/sc/battleye/scripts.txt
