### ISSUE TITLE
Boat Spawning on road??

### ISSUE THREAD

**Issue by TonyMedKniven** [EpochModTeam/Epoch#486]
Trying out A3 Epoch with some friends on my server and having fun! Tried the VIP taxi missions.
First attempt, Generals daughter refuses to leave my chopper.
Second attempt, drive ~10 km to slightly north of Kavala. Less than 1 km from destination this happens:

http://images.akamai.steamusercontent.com/ugc/311115421217011988/A612FB615B61BF813302A262F7E0D6DDEF801717/

That is clearly a bug. The boat spawned a few meters in front of me and fell to the ground, I rammed it at high speed. Car almost dead, I'm almost dead. Fixed the car and myself. The generals daughter is very much dead. I laughed my *behind* off, it's raining boats :-)

**Comment by TonyMedKniven** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=619285095

might work better :-)

**Comment by Kakysas666** [comment]
Those missions are Work In Progress so do not bother doing them for now :)

**Comment by TonyMedKniven** [comment]
So u r saying that its the generals daughters fault boat r raining from the
sky? 😂

On Tuesday, 9 February 2016, KPABATOK <notifications@github.com> wrote:

> Those missions are Work In Progress so do not bother doing them for now :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EpochModTeam/Epoch/issues/486#issuecomment-182014500>.
>


-- 
Sent from Gmail Mobile

**Comment by vbawol** [comment]
closing as this is outdated, as of 0.3.9 we are using Axemans new task based system.
