### ISSUE TITLE
Duplicated traders

### ISSUE THREAD

**Issue by Ghostrider-DbD-** [EpochModTeam/Epoch#489]
Ran across this duplicated trader this evening. The two traders were moving side to side independently. It was all rather freakish.

http://steamcommunity.com/sharedfiles/filedetails/?id=622012666

**Comment by Kakysas666** [comment]
I have seen such instances before. They just spawned in same location, they are not duplicate. Sometimes 3 traders spawn in same building.

**Comment by vbawol** [comment]
should be fixed as of this commit and 0.3.9 b557+: https://github.com/EpochModTeam/Epoch/commit/bb94bb429ed77dbb1cd333ecbe85be2775a8a8c3

Traders that have already spawned will need to be killed or left to expire.
