### ISSUE TITLE
Items spawning on roof

### ISSUE THREAD

**Issue by Jeff-Casual** [EpochModTeam/Epoch#491]
Hi,

Some items  like pallet are spawning on roof, you can open them but can't loot.

**Comment by Pmba79** [comment]
It is only that pallet and it's always on the roof of the same building type.
Axles did it and said, "Well, get a chopper then" ..
Oldschool trolling..

**Comment by vbawol** [comment]
I have reworked most of these, for the next update 0.3.8, that should be out in the next week or two.

**Comment by Jeff-Casual** [comment]
Nice, thx :)

**Comment by vbawol** [comment]
Should be mostly fixed once 0.3.8 is released, closing this issue for now. Please open another issue if you still notice any misplaced loot after 0.3.8
