### ISSUE TITLE
HS Trader improvement suggestion

### ISSUE THREAD

**Issue by Necrous** [EpochModTeam/Epoch#494]
Sometimes it becomes really annoying bying a lot of building materials (or ammo, whatever) by clicking your mouse like 200-300 times a row... :) 
Might there be something like a little menu/script/special function for typing number of items you need, or typing a sum of money equal for a quantity of specific item you want to buy instead of clicking 1000 times? :) This would be really helpful.

**Comment by vbawol** [comment]
A new trader menu is in the works for 0.4, stay tuned. @raymix check this one for feedback.
