### ISSUE TITLE
EXP 0.3.8 Error when looting a crate, pile, trash etc.

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#498]
Issue: Bool Error when looting

Date Seen 4/7/16

Versions 0.3.8.0 Exp
Bug Description: When looting crates / piles an error will appear (see attached screenshot).  Also, specifically piles of loot on the ground seem difficult to access in these cases. Certainly I thought this was a known issue but it was not listed on here as an issue.
Severity: Minor

Steps to Reproduce
Press inventory key (in my case "i") on a pile of loot or crate (vehicle, etc.) The error will appear more often than not

Actual Behavior
error appears when looting, piles of loot seem harder to access on first try

Expected Behavior
No script error when looting- better cursor targeting of loot piles (A3 issue?)

Troubleshooting/Testing Steps Attempted
looted many piles, crates

Workaround
You are still able to loot everything, just with script errors currently.
![20160406220920_1](https://cloud.githubusercontent.com/assets/4204940/14342407/bea343d4-fc56-11e5-8fac-6c6ae3e3139c.jpg)
![20160406221414_1](https://cloud.githubusercontent.com/assets/4204940/14342408/c373387e-fc56-11e5-9ef0-c686a22e05ea.jpg)

**Comment by Ghostrider-DbD-** [comment]
I was unable to interact with trash piles, mail boxes, or telephones running vanila ver 0.3.8.0 build 417 on a test server. Anyone else having these issues?

**Comment by vbawol** [comment]
[Changed] Trash looting is now done by interaction system only. Hold Space Bar and choose Examine.

**Comment by Ghostrider-DbD-** [comment]
Thanks - confirmed working using that method on our servers.
