### ISSUE TITLE
Upgraded Building Pieces rotate 90 deg temporarily

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#499]
Issue: Upgraded Building Pieces rotate 90 deg temporarily

Date Seen 4/7/16

Versions 0.3.8.0 Exp / earlier versions too
Bug Description: When upgrading a building piece (tested on walls) the piece will often rotate 90 degrees temporarily. I know this is a known issue- just posting this here so it will be fixed for 0.4 we hope!

Severity: Moderate

Steps to Reproduce
Place down a wall
Upgrade the wall
The wall will most likely rotate 90 degrees temporarily

Actual Behavior
Walls rotate 90 degrees when upgraded

Expected Behavior
Walls will stay in their original position when upgraded

Troubleshooting/Testing Steps Attempted
placed down wooden / cinder walls and each had the same issue

Workaround
Wait 5-10 seconds and the walls will return to their original position.

**Comment by vbawol** [comment]
still a known issue and will be worked on for 0.4, tracking here: https://github.com/EpochModTeam/Epoch/issues/583
