### ISSUE TITLE
0.3.8 Feedback (played CUP terrain Cherno)

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#500]
1. The fps I got on the Cherno server ranged from 35-60+ which is promising (lower fps in Elektro which is expected)

2. I only saw 3 sappers- no drones / cultists although I was porting around a bit with the admin tools

3. I could not get loot to spawn in the general store, firehouse, hospital. This was likely "just my luck" but that was disappointing to me.  I tried jogging around back and forth to try to get it to "trigger" but no luck this time

4. See the screenshot below- I was able to place a freq jammer at the edge of elektro.  This could get pretty interesting on some servers lol.  Would require some editing to have a protected frequency for areas like this 
![20160406235410_1](https://cloud.githubusercontent.com/assets/4204940/14342653/76c5f532-fc58-11e5-99a4-800e5dc6b63e.jpg)

5. The messages that appear when you loot something or change the volume can cover your whole screen and for me if I spammed the button I would get a temporary client fps drop. See screenshot:
![20160406234702_1](https://cloud.githubusercontent.com/assets/4204940/14342675/a5b41964-fc58-11e5-869d-8192d2aba973.jpg)

6. I was very excited to see the older vehicles (especially the old SUV) I'm glad to see this CUP support working. I know there is always room for improvement but it really made me want to get back into playing on Cherno. Cheers

**Comment by RC-Robio** [comment]
Drones and cultist did spawn for me. As well as the sappers. But they were few and far between. Epoch lootables seem to spawn fine for me as well.  Playing this morning on Cherno I was unable to loot any map objects. (trash bins, trash piles, metal scrap piles...)

**Comment by vbawol** [comment]
Thanks, hopefully we have sorted some of this for 0.3.9
