### ISSUE TITLE
EXP 0.3.8 - Admin Menu Healing Error

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#501]
Issue: Error when healing player

Date Seen 4/7/16

Versions 0.3.8.0 Exp

Bug Description: Error seen while healing a player via admin menu (screenshot below) 
I was on a quad bike at the time but I did reproduce this while not in a vehicle as well.  Your character is healed but the error pops up each time.

Severity: Moderate

Steps to Reproduce
open admin menu
select player to heal
click "heal player"

Actual Behavior
error when healing player via admin menu

Expected Behavior
ability to heal players via admin menu w/o errors

Troubleshooting/Testing Steps Attempted
tried healing self a few times, got error each time

Workaround
N/A , function to heal players works but no way to prevent script error
![20160406235126_1](https://cloud.githubusercontent.com/assets/4204940/14342823/f6acd896-fc59-11e5-965e-e84384b8e559.jpg)

**Comment by vbawol** [comment]
should be fixed with build 414
