### ISSUE TITLE
Community Made Assets

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#507]
I try to create weapons model but I'm learning yet.
Thus hardly unknowing have how it works accurate so give my first try at you maybe you can what started it.Maybe I can learn something from you little
my first moderl is a needle gun

https://en.wikipedia.org/wiki/Needle_gun
Download(blender files):
https://drive.google.com/file/d/0B2PXTFaiSMInREdrbW9fTWZSNFk/view?usp=sharing

**Comment by vbawol** [comment]
Nice, @baaljayjay We are adding a community pbo for 0.3.9+ 
https://github.com/EpochModTeam/EpochCore/tree/release/Sources/a3_epoch_community

**Comment by baaljayjay** [comment]
i have a new model.
This is a vz. 52/58 machine gun and use 7,62x39 mm.
https://drive.google.com/file/d/0B2PXTFaiSMInc09rVVdhZ2RYOG8/view?usp=sharing

you can read on wiki:
https://en.wikipedia.org/wiki/Vz._52_machine_gun

**Comment by baaljayjay** [comment]
this model is vg 2 (Volkssturmgewehr 2).
https://drive.google.com/file/d/0B2PXTFaiSMInelpfZzlEUEFibTg/view?usp=sharing
orginal use 10 rnd 7.92x57 mauser but we can use the rahim mags.
i have problem with size in o2 programm.It is to big.
maybe you can help me or complete the projects.

**Comment by vbawol** [comment]
@baaljayjay I can help or add them my self. The latter would take more time. 

The size in O2 should be controlled by your import scale. You can see how the A2 ported weapons we added to Epoch are made here: https://github.com/EpochModTeam/EpochCore/tree/release/Sources/a2_epoch_weapons

These p3ds are unbinarized ^

**Comment by baaljayjay** [comment]
try 2 with vg2 : https://drive.google.com/open?id=0B2PXTFaiSMIneWlYNWJWdGdaTlE
I learned the points of m107 but the eyes of the copied file I did not know how to do it.
maybe you can look over it if it is good.
I have so many ideas but the implementation is difficult.
I do not know how the values work whether by you must insert or create the program

**Comment by baaljayjay** [comment]
I did not know that the model for arma. 3 I think I'm stupid modelliern it. But I deal with little blender.
here the next idea:remington model 8  https://drive.google.com/file/d/0B2PXTFaiSMInMzN2ZnBPeDFSY1U/view?usp=sharing
wiki:https://en.wikipedia.org/wiki/Remington_Model_8

**Comment by baaljayjay** [comment]
how about if in epoch craftable weapons are and box of ammunition?
can you open and piece of cartridge in run.
or craftable rockets or mortar?
spear round with rope?
then it is the first human being who has all 7 mounted base in altis

**Comment by baaljayjay** [comment]
The one gun is a rolling block rifle but i don´t what the ammo need maybe later.
The second is a homemade pipe gun use 6x30 mm ammo.
this gun can craftable with pipes.
6x30 was developed by the company epoch armored inc. In the year 2028 and was brought to the civilian market.
The company itself was bought in 2025 by the Epoch Corporation.
The company also produces the license in m16 and 14.
Proofs on m14 epoch armored inc. Impressed.
I think if you see that again, you probably will not be jay again because of my many crazy ideas and so many topics open.

https://drive.google.com/file/d/0B2PXTFaiSMIna0NBa0ZrMWw0UEE/view?usp=sharing

**Comment by baaljayjay** [comment]
here copy of martini gun but crude (maybe i can not so good)
link:https://drive.google.com/file/d/0B2PXTFaiSMInZHNVQXZsSjlTdzA/view?usp=sharing (link updatet)
one is a pistol.
second is a carbine vesion like c96 carbine.
weapons use the 6x30 mm rounds (single shot)
here video copy martini pistol from forgotten weapons: https://www.youtube.com/watch?v=zTvxFNRLbiw
and for rollingblock rifle can use ammo .25 from remington model 8 (craft 5 x .25 to 5 rnd .25 and can use to remington model 8).
I do not know the weapons are suitable for epoch.

**Comment by baaljayjay** [comment]
I know I start but never manage to finish the thing.

Link: https://drive.google.com/file/d/0B2PXTFaiSMIncUc2Y0FuZ0E4cEU/view?usp=sharing

But before I forget the idea I prefer.
The one is bolt action rifle that should be 9mm ammo (10rnd, 16rnd, 30rnd mags).
Epoch should be so more civilian weapons (I think at that time, steampunk civil weapon cabinet created, but it fit well).
The second is a very old weapon sowas one built in medieval.
A hand cannon maybe a craftable weapon cheap under construction but the worst weapon.
Ammo for the handcannon is cratable from rock or/and metal (iron,copper,tin).
But better than nothing.
I also have other idees expample custom target tube or hotdogs salesstand (thus the carts hopefully you what I mean) which one can browse and eat finds.

**Comment by baaljayjay** [comment]
new idea:
2 custom telescopic sight for the custom weapon from me or for rollins rifle.
1: 1x-max 4x zoom
2:5x-max 9x zoom
Top hat: If you have a lot of money so you have to dress accordingly.
custom armor vest and helmet. this armor can craft with metal scraps(5-8) and have space for loot. may be If you live longer and are discovered by drone, you could have elite bandits spawned or sapper with it.
![epoch](https://cloud.githubusercontent.com/assets/16623990/20868024/ceae9bb6-ba51-11e6-9ed4-3a5921edb0ce.png)
![epoch2](https://cloud.githubusercontent.com/assets/16623990/20868025/ceaef372-ba51-11e6-872d-f425e877d6c0.png)

https://drive.google.com/file/d/0B2PXTFaiSMInd2NGME1xRU5pVTQ/view?usp=sharing
this was my idea.

**Comment by baaljayjay** [comment]
ideas for epoch:new lootable furniture because I miss the this in store and in the street

link: https://drive.google.com/file/d/0B2PXTFaiSMInbHZXMkpDenpBdUk/view?usp=sharing

Deep Freeze and Refrigerator for store,find some food.
I would like to apply as a hotdog seller so I can earn kryptos mr. vbawol ;)
Which are located in front of shops and at the beach can find some food too.
 
![hotdog1](https://cloud.githubusercontent.com/assets/16623990/20903266/f1bfc9ba-bb3a-11e6-8500-8ca4db092be9.png)
![hotdog2](https://cloud.githubusercontent.com/assets/16623990/20903272/f56af0c6-bb3a-11e6-9c8a-22e96727b905.png)
I would be very happy if I was accepted as a hotdog seller.

**Comment by baaljayjay** [comment]
here some idea 
one is a cart this can craft with lumber pack and plywood pack.
That can push and have storage
link:https://drive.google.com/file/d/0B2PXTFaiSMInNWhCYkRjV2ExQ3M/view?usp=sharing

another is a shack.
you can build in the world and when not a jammer near to shack so you can maintain with plywood or lumber.
link:https://drive.google.com/file/d/0B2PXTFaiSMInYXpuSnA2blZWWk0/view?usp=sharing
 
I think that in epoch once with looten survive or you can only survive nature playstyle speaks there are several ways to survive

**Comment by vbawol** [comment]
All our @epoch sources are now available via GitHub and LFS to use as examples and we welcome your game ready contributions on EpochCore Github: https://github.com/EpochModTeam/EpochCore

Install both: https://desktop.github.com/ and https://git-lfs.github.com/ clone the repo and you can see all of our work.

Tracking this here:
https://github.com/EpochModTeam/EpochCore/issues/5

**Comment by baaljayjay** [comment]
I do not know whether to write further here or not.
Therefore, I write first and wait for the first answer.
So I share my crazy idea first

de lisle carbine is suppressor carbine like asp kir and use .45 acp pistol mag.
Johnson m1941 is a WWII semi rifle use .30-06 ten rounds.
 M4 survialrifle use .22 hornet 4 round mag.
9mm pistol carbine use 16rnd, 30rnd 9mm mag.
snider-enfiedl rifle use .577 enfield single shot ammo(maybe ammo craftable).
.22 open bolt action(semi auto) rifle use 10rnd ruger mag.
A rifle is the magazine under the barrel and is bolt action use 5 rnd rollins rifle ammo(i have no name for this rifle maybe have you name for this rifle).
.25 ammo for rollins block rifle.

links:https://drive.google.com/file/d/0B2PXTFaiSMInbkxNaGVjZmZ4ZGs/view?usp=sharing

**Comment by baaljayjay** [comment]
type 63 is a chinese weapon (this was the third try and often change).
It is a mixture of sks and akm has full auto and exchangeable mag.
second gun is german vg1-5.This version use 7,62x39mm(original use 7,92x33mm kurz).
(mags is from akm and not from me)

https://drive.google.com/file/d/0B2PXTFaiSMInanZ3Tm56SF9jdTQ/view?usp=sharing

**Comment by baaljayjay** [comment]
Table saw to cut more efficiently wood.
The one has steam engine the other has an electromotor.
Steam engine has to build a lot of metal, scrap pelt, tin and wood for fire (villeicht you have to fill after each restart wood).
Which needs electromotor metal, tin (much because one the electronic componets to solder), electronic componets, enclosed battery,cable,copper and in the range a solar system to operate
(action menu start/stop engine)
https://drive.google.com/file/d/0B2PXTFaiSMInZEhJQkFjWFNSOXc/view?usp=sharing

i hope you see this

**Comment by baaljayjay** [comment]
I have once again modeled the ignition needle gun.
(The first model looks awful)
Then an ar7 should use 10 rnd. 22 ruger.
Matchlock and flintlock rifle with ammo. (Paper unit cartridges).
Then a WW2 exp bullpup assaultrifle use 7.62x39mm.
Then a simple singleshot rifle use 9mm or 6x30 epoch round.
Single shot pistol use .22 / 9mm / .45 acp.
From fun I have times m14 with akm mag joined together but looks interesting.
Could one later so skills install so metal processing or something?
Because in WW2 you have people from occupied countries for example from poland to england then the in the sten gun teaches then again back to polen smuggled up to build groups of resistance.
Because everywhere where the workshop for metalworking one could build the sten gun

https://drive.google.com/file/d/0B2PXTFaiSMInV2d2MjVRWGVnNzQ/view?usp=sharing
