### ISSUE TITLE
0.3.8 Cinder-block metal gate image 

### ISSUE THREAD

**Issue by Tigah** [EpochModTeam/Epoch#508]
The cinder-block metal gate image has a slight variance in color when you are about 4-5m away but does show the correct color once you get a bit closer. 

![107410_screenshots_20160410082454_1](https://cloud.githubusercontent.com/assets/10912575/14407342/4123bb26-ff19-11e5-89fe-624b2939f9ca.jpg)

**Comment by vbawol** [comment]
Thanks Tigah! this should be fixed in the experimental branch staged for next client release.

**Comment by eedijs** [comment]
Still seeing cinder block texture on gates.

**Comment by vbawol** [comment]
confirmed this is fixed,
