### ISSUE TITLE
Buying chest rigs/backpacks

### ISSUE THREAD

**Issue by Blindleader** [EpochModTeam/Epoch#51]
Noticed when trying to purchase a backpack or chest rig (if you don't already have one) the trader tries to put it in your inventory instead of on your player. Primary weapons and pistols automatically go into action slots. Most rigs and backpacks are too big to fit into other backpack/rigs so I'm not sure how we are supposed to purchase them. Ideally backpacks and chest rigs would go ON your toon after you complete your purchase if your toon isn't already wearing an item in that slot.

**Comment by vbawol** [comment]
this should be sorted since 0.3.6
