### ISSUE TITLE
Unable to unlock/lock some larger vehicles

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#512]
There seems to be a problem with certain larger vehicles when trying to unlock or lock them. This specifically affects at least the following CUP vehicles: Chernarus Fishing Boat, RHIBs and the C-47. It may affect other vehicles but I haven't personally tested those others. 

The issue in question also makes it tough to get the sweet spot for the unlock/lock mechanism and crate inventory on larger Epoch trucks and helicopters.

**Comment by Skaronator** [comment]
Probably need the same workaround as we did in A2 here: https://github.com/EpochModTeam/DayZ-Epoch/blob/479097e7a8c0bd310d1afb63027cb12c58959586/SQF/dayz_code/compile/fn_gearMenuChecks.sqf#L8

**Comment by morgoth0** [comment]
Thanks Skaronator. I'm assuming, but not sure, that the equivalent A3 code would be in this file: https://github.com/EpochModTeam/Epoch/blob/master/Sources/epoch_code/compile/vehicles/EPOCH_client_gearVehicle.sqf

The line I'm looking at is 	

_vehicles = player nearEntities[["LandVehicle", "Ship", "Air", "Tank"], 6]; 

but not sure whether some vehicle's location zones are really 18' away. There are a couple of other files I've been looking at but I'm just starting to get my head into the Epoch code.
