### ISSUE TITLE
Ladder/stairs sometimes turn invisible after placing

### ISSUE THREAD

**Issue by eedijs** [EpochModTeam/Epoch#516]
It happened once for me with stairs and now with a ladder - I placed to build it - it turned into physical mode and also became invisible. I can only see the shadow. I'm able to move/remove it though.
p.s. after it finishes building it is visible again. Haven't seen this happen again, probably because it hasn't turned into a physical object instead of staying in ghost mode while building.

**Comment by sirkro** [comment]
This happened a couple of times with me, but for floors.

Build floor: ok
Build floor: goes away, wait a bit and there it is

Looks like the bug where the pieces rotate slightly and then rotate back after a while. At least it takes about the same amount of time for them to spawn in again as with the rotate back

**Comment by vbawol** [comment]
this should be fixed in 0.3.9, it not please let us know.
