### ISSUE TITLE
Wrong build number

### ISSUE THREAD

**Issue by BetterDeadThanZed** [EpochModTeam/Epoch#526]
The build.hpp file says build=422; instead of build=436. I assume this is a typo and the files included in the current repo are 436?

**Comment by vbawol** [comment]
There are several build.hpp files for a release I increase the build number for all of them. 436 should be the build number for each

Sources/epoch_config/build.hpp <-- this is the one that players see.
Sources/epoch_server/build.hpp
Sources/epoch_server_settings/build.hpp
Sources/epoch_server_core/build.hpp

**Comment by BetterDeadThanZed** [comment]
The build.hpp in @epochhive\addons\a3_epoch_server_settings shows build 422. A player of mine who is rather vocal in pointing out problems with the server saw the build number 422 someplace when he logged into the server and thought we still weren't on the latest version.

**Comment by Ghostrider-DbD-** [comment]
We have not observed any issues. Have you compared your current server files to the source files from the github using diffmerge? This is how I have been ensuring that any changes from build to build get carried over to the files on my server.

**Comment by BetterDeadThanZed** [comment]
There's no issues. It's just that file in the Github has the wrong build number in that file and I thought I'd point it out. Check the Github. You'll see what I mean.

**Comment by vbawol** [comment]
Can provide you link to the file in question?

**Comment by BetterDeadThanZed** [comment]
https://github.com/EpochModTeam/Epoch/blob/master/Server_Install_Pack/%40epochhive/addons/a3_epoch_server_settings.pbo

build.hpp in the a3_epoch_server_settings.pbo file.

**Comment by vbawol** [comment]
When I download and open the settings pbo I see build 437 and that is correct since I bumped it once since 436 was released to add the FastNights script.
build.hpp
```
build=437; 
```

**Comment by BetterDeadThanZed** [comment]
I don't know then because I downloaded it yesterday and it said build 422.

**Comment by BetterDeadThanZed** [comment]
Well, here's the weird thing. I just checked my download on my PC and that file is showing 436. I was previously running 415, so I have no idea where the file with 422 came from.

**Comment by vbawol** [comment]
closing, please reopen if you still have issues
