### ISSUE TITLE
List of A3 Buildings missing from EPOCH loot spawn tables

### ISSUE THREAD

**Issue by Snitzle79** [EpochModTeam/Epoch#528]
I've posted this issue on the Epoch forums but haven't had a reply yet. I was suggested to also post it here by my server's admin @BetterDeadThanZed as well. So here it is: 
I used this [**webpage**](https://community.bistudio.com/wiki/Arma_3_CfgVehicles_EMPTY) to go through and search the [**Epoch building loot spawns**](http://pastebin.com/qaaEQQfB) I saved the list to PDF format and used the search there to find out which of all those A3 buildings listed on that webpage weren't on the loot spawn list. What I found is that there are quite a few buildings that are missing from the list. Most of them are worn and older looking or damaged versions of the originals but they all should still spawn loot like the others. The original pristine buildings are already in the building loot spawn list but these worn older looking versions were not. If you notice most of the buildings that are missing include the words "dam" in them which I can only assume means damaged. Most are not damaged but are more so just older and worn down looking version of the original. The reason this really stood out is because our server is running Esseker which uses those older looking worn buildings in most cases. The buildings weren't spawning loot and no one knew why. So after doing this research is when I discovered Esseker uses this different versions and they're not on the Epoch building loot spawns list/tables. Below is a list of the buildings I found missing from the Epoch building loot spawn table list. BetterDeadThanZed added them to our servers list. I haven't seen all of them spawn loot but I do know that since he added them I've personally seen a couple of them now spawning loot. It would be great if they could be added. Thanx for the time and good work with EPOCH

**A3 BUILDINGS MISSING FROM EPOCH LOOT SPAWN TABLES:**

- [x] Land_i_Garage_V2_dam_F

- [x] Land_i_Stone_HouseBig_V1_dam_F

- [x] Land_i_Stone_HouseBig_V3_dam_F

- [x] Land_i_Stone_HouseSmall_V1_dam_F

- [x] Land_i_Stone_HouseSmall_V3_dam_F

- [x] Land_Airport_Tower_dam_F

- [x] Land_Shed_Small_F

- [ ] Land_i_Barracks_V1_dam_F

- [ ] Land_i_Barracks_V2_dam_F

- [ ] Land_TentHangar_V1_F

- [ ] Land_TentHangar_V1_dam_F

- [ ] Land_Dome_Big_F

- [ ] Land_Dome_Small_F

- [ ] Land_GH_MainBuilding_entry_F

- [ ] Land_dp_smallTank_F

- [ ] Land_i_House_Big_01_V1_dam_F

- [ ] Land_i_House_Big_01_V2_dam_F

- [ ] Land_i_House_Big_01_V3_dam_F

- [ ] Land_u_House_Big_01_V1_dam_F

- [ ] Land_i_House_Big_02_V2_dam_F

- [ ] Land_i_Shop_01_V1_dam_F

- [ ] Land_i_Shop_01_V2_dam_F

- [ ] Land_i_Shop_01_V3_dam_F

- [ ] Land_u_Shop_01_V1_dam_F

- [ ] Land_i_Shop_02_V1_dam_F

- [ ] Land_i_Shop_02_V2_dam_F

- [ ] Land_i_Shop_02_V3_dam_F

- [ ] Land_u_Shop_02_V1_dam_F

- [ ] Land_i_House_Small_01_V1_dam_F

- [ ] Land_i_House_Small_01_V2_dam_F

- [ ] Land_i_House_Small_01_V3_dam_F

- [ ] Land_u_House_Small_01_V1_dam_F

- [ ] Land_i_House_Small_02_V1_dam_F

- [ ] Land_i_House_Small_02_V2_dam_F

- [ ] Land_i_House_Small_02_V3_dam_F

- [ ] Land_u_House_Small_02_V1_dam_F

- [ ] Land_i_House_Small_03_V1_dam_F

ALSO FOUND A2 BUILDING:

- [ ] Land_A_Hospital_dam

**Comment by vbawol** [comment]
These locations can be made with this tool: https://github.com/EpochModTeam/Epoch/blob/release/Tools/SQF/saveLootPositionsVector.sqf
