### ISSUE TITLE
BE error on ESC after Arma 1.58 hotfix

### ISSUE THREAD

**Issue by Rhidalin-Bytes** [EpochModTeam/Epoch#529]
It seems all users are being kicked after the Arma hotfix when they press ESC to show the exit menu / key config window. 

Current scripts.txt
`7 RscDebugConsole_watch !="RscDebugConsole_watchSave = [true,true,true,true];"`

Error
`29.04.2016 00:55:26: SGM.Rhidalin Bytes (99.91.237.114:2304) 71336581f2145ee17a50ff79bef7e691 - #4 " _x;
private _value = profileNamespace getVariable ["RscDebugConsole_watch" + str (_forEachIndex + 1), [true, ""]];
if !(_value "`

**Comment by jostster** [comment]
Yep same here

**Comment by vbawol** [comment]
Going to remove this filter, in next update.
