### ISSUE TITLE
New Player Death Options

### ISSUE THREAD

**Issue by andgregor** [EpochModTeam/Epoch#535]
Cannot morph near trader, but once attempted the detonate button is no longer active - Either remove morph button when near trader or allow detonate after failed morph.

Not sure if groan is working, add local groan.

Suggested by Awol: Make detonate different levels based on energy level. Maybe grenade for low / zero energy, two further levels spawn sapper bomb or boss sapper bomb ?

**Comment by vbawol** [comment]
Will leave this as is for now as we have not gotten much feedback about this topic.
