### ISSUE TITLE
Experimental Server Install Pack

### ISSUE THREAD

**Issue by andgregor** [EpochModTeam/Epoch#536]
All the PBOs are 1kb.

**Comment by vbawol** [comment]
Ok its likely the LFS. I wanted to test this for latter adding larger source files. Not really needed for this repo.

Just to test it out could you try installing lfs and see if you can access the files again?
1. Open in Git Shell  

```
git lfs install
```

**Comment by vbawol** [comment]
Forget that I see its even changing the source download, reverting this change now.

**Comment by vbawol** [comment]
fixed 
https://github.com/EpochModTeam/Epoch/commit/e23ee5dd31f865c9fec2b64fcc26444a36ea4a35
