### ISSUE TITLE
Loading Player Inventory

### ISSUE THREAD

**Issue by Ratl3r** [EpochModTeam/Epoch#541]
I am new to ARMA3 EPOCH so I do not know if this issue has been resolved, but for the past few days I have been experiencing that my game hangs on the "Loading Player Inventory" and then I get the message "BattlEye Variable Restriction #0" I haven't changed anything on my side, the client side, but if I need to do something please advise me on what to do. 

I have done checking the cache, I have varified the EPOCH files, I have deleted and reinstalled Battleye, I have even reinstalled the entire ARMA 3 and my display drivers.

If this issue has been resolved please send me the link.

**Comment by vbawol** [comment]
This should have been solved already with the latest server release. https://github.com/EpochModTeam/Epoch/releases

BattlEye Variable Restriction #0 what is the exact message that gets logged?
