### ISSUE TITLE
Small error in CUP Enabled logic

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#543]
Was making a couple of changes in server_init and I noticed the following two lines:

EPOCH_modCUPWeaponsEnabled = (getNumber (configFile >> "CfgPatches" >> "CUP_WheeledVehicles_Core" >> "requiredVersion") > 0);
EPOCH_modCUPVehiclesEnabled = (getNumber (configFile >> "CfgPatches" >> "CUP_Weapons_WeaponsCore" >> "requiredVersion") > 0);

This would  be a problem for those only using CUP Weapons since the patch check is reversed, i.e. WeaponsEnabled is set by the Vehicles addon and vice versa.

**Comment by vbawol** [comment]
Wow, I really need to get those glasses. This will be fixed in next experimental build. 

Thanks!
