### ISSUE TITLE
Change in description.ext

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#544]
Not sure whether you saw [the post on EpochMod.com](http://epochmod.com/forum/topic/42095-a3-160-epoch-038-440/?do=findComment&comment=277199) but, BIS changed the format for defining which channels are active and with which (chat/voice) that they're allowed:

`disableChannels[] = {channelID<number>, channelID<number>...}; // old syntax
Example:  disableChannels[] = {0,1,2};
disableChannels[] = {{channelID<number>, disableChat<bool>, disableVoice<bool>},{channelID<number>, disableChat<bool>, disableVoice<bool>},...}; // new syntax
Example:  disableChannels[]={{0,true,true},{1,true,false}...};
`

As always, hope this helps, and thank you for all your hard work

**Comment by vbawol** [comment]
Thanks, I think we will go with these settings as default: 

```
disableChannels[]={{0,true,true},{1,false,true},{2,true,true},{6,true,true}}; // allow text only on side chat
```
