### ISSUE TITLE
carnival loot spawn

### ISSUE THREAD

**Issue by DasWarlock** [EpochModTeam/Epoch#546]
better to show
[http://images.akamai.steamusercontent.com/ugc/440605165225554723/5B8B8535472CE6EEF74FE5C572B599EA19A06612/](url)

**Comment by vbawol** [comment]
whats the issue? that image does work.

**Comment by DasWarlock** [comment]
ahhh ok well the loot was spawning on top of each other

**Comment by vbawol** [comment]
ok thanks, going to make it only spawn 1 item for now.
