### ISSUE TITLE
Unable to join 0.3.8 since 1.60 Arma update

### ISSUE THREAD

**Issue by TheStainlessSteelRat** [EpochModTeam/Epoch#548]
Since the Arma 3 1.60 update i have been unable to join any Epoch server running 0.3.8. I can see servers and can join their lobby and download mission file but the game will then freeze on loading screen with the progress bar stuck about 1.5 inches from end. I have on my own re installed Arma 3 and unsubscribed to epoch and re installed, wiped mpmissioncache file and wiped saved profile files, then defragmented my hard drive. On trying to join i continue to have the freezing issue. Only way of being able to get out of frozen screen was via Windows Task Manager.

I can join other game modes in multiplayer some requiring no mods some like Epoch just one. I cannot join Epoch 0.3.8. and i also found i could not join Wasteland servers without game freezing.

I open a ticket with BI on their feed back tracker and was initially told it was faulty files in Arma 3 and to ensure after fresh re intall i verify the game cache integrity before trying to first play the game in Vanilla and then re adding mods, which should have also unsubscribed from workshop and then re installed. In addition I also wiped my C drive of any other Arma 3 and Epoch files it could find. I also at this stage chose to take my Epoch files from this website's download pages to see if i could get a different result than with workshop files.

Unfortunately this game freezing continues to be an issue with Epoch but not anything else including Epoch Experimental.

I cannot play in 0.3.8 and more importantly cannot help administer my community's Epoch server since 1.60.

After further prodding this week Bi now say the issue is with bad animation configs in the mod and that they have fix in works for next Arma update. I personally cannot verify their statement about this but hope that providing you with same rpt. files you can see if this is true and maybe let me know if there is an interim fix to continue to play and help my local Epoch community.

[ArmaReport_Log_20160604T091947_PaulXMoss.zip](https://github.com/EpochModTeam/Epoch/files/310684/ArmaReport_Log_20160604T091947_PaulXMoss.zip)

**Comment by vbawol** [comment]
0.3.9 is out, this should not be an issue anymore.
