### ISSUE TITLE
[Suggestion] Mosquito controls too sensitive

### ISSUE THREAD

**Issue by StianKruger** [EpochModTeam/Epoch#549]
I have many people complain about this and the Mosquito is the leading cause of player suicides on our server. It does provide a lot of laughter but also rage quits :)   Would it be possible to make the Mosquito controls less sensitive. I usually change the resolution on my mouse when flying it personally but most players don't and then crash and burn. It currently feels like flying a garden chair. Having a quad copter would be nice. :)

**Comment by vbawol** [comment]
They are made to be twitchy I guess you could say. But if others agree also we could look at toning them down a bit.

**Comment by Ignatz-HeMan** [comment]
We think the Mosquito should stay as it is.
It is very funny and also controllable with a bit practise

**Comment by vbawol** [comment]
Yes, I think we will keep this as it was setup this way by @sequisha. 

That said If you want to propose changes to the main @ Epoch mod configs you can do so here: https://github.com/EpochModTeam/EpochCore 

*We could have two or more versions that have different handling.
