### ISSUE TITLE
0.3.9 Animation Bugged(Missing) w/ Melee Weapons

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#550]
Tested on Epoch Exp 0.3.9 w/ Arma version Apex Preview on BulletBuffet Tanoa server

Hatchet, Sledge, Maul, (didn't test the Kruhm) all had missing animations.
Recreated issue a few times

**Comment by Tarabass999** [comment]
outdated issue... animations are working on 0.3.9 since some updates

**Comment by vbawol** [comment]
thanks for confirmation @Tarabass999
