### ISSUE TITLE
0.3.9 Tanoa Water crafting/hatching trees

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#551]
0.3.9.0 Tanoa water crafting is not working... no water source more near than 3 meters (it's shown red) even if I stand in front of a full waterbarrel

hatching trees don't make them fall + don't give loot (also chainsaw not working with trees)

**Comment by Tarabass999** [comment]
I added class Land_BarrelWater_F : Water {}; in WorldInteractions.hpp
now this water is working..

**Comment by Tarabass999** [comment]
also found missing entries for trash:     class Land_GarbageHeap_01_F : Trash {};
    class Land_GarbageHeap_02_F : Trash {};
    class Land_GarbageHeap_03_F : Trash {};
    class Land_GarbageHeap_04_F : Trash {};
    class Land_GarbageBin_01_F : Trash {};
    class Land_GarbageBin_02_F : Trash {};

But this is not working if I add...same with stone names. Looks like p3d names are needed to add

**Comment by Tarabass999** [comment]
SOLVED since build 530..

Thank you

**Comment by vbawol** [comment]
np, thanks for confirmation!
