### ISSUE TITLE
0.3.9 532 messaging

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#553]
since messaging folder is nomore in gui/scripts but in compile folder it's nomore showing up messages like item looted, maintained base or similar

**Comment by Tarabass999** [comment]
after adding lline from "Missing file reference for messaging" I still can't see messages

**Comment by andgregor** [comment]
I can confirm, is commented in the update.

**Comment by raymix** [comment]
I'm looking into this now guys, very weird bug, not getting any errors. Give me few mins to figure it out

**Comment by raymix** [comment]
Figured it out. a3_configs PBO under Epoch_Core needs to be PBOd again
UI is mising RMX_T1

Alternatively add this to your description for quick fix:
class rmx_t1
{
    text="";
    x=0;
    y=0;
    h=0;
    w=0;
    type=0;
    style=0x02;
    shadow=2;
    colorShadow[]={0,0,0,0.5};
    font="PolenticalNeon";
    SizeEx=0.05;
    colorText[]={1,1,1,1};
    colorBackground[]={0,0,0,0};
    linespacing=1;
    tooltipColorText[]={1,1,1,1};
    tooltipColorBox[]={1,1,1,1};
    tooltipColorShade[]={0,0,0,0.64999998};
};

**Comment by Tarabass999** [comment]
> Alternatively add this to your description for quick fix:
> class rmx_t1
> {
> text="";
> x=0;
> y=0;
> h=0;
> w=0;
> type=0;
> style=0x02;
> shadow=2;
> colorShadow[]={0,0,0,0.5};
> font="PolenticalNeon";
> SizeEx=0.05;
> colorText[]={1,1,1,1};
> colorBackground[]={0,0,0,0};
> linespacing=1;
> tooltipColorText[]={1,1,1,1};
> tooltipColorBox[]={1,1,1,1};
> tooltipColorShade[]={0,0,0,0.64999998};
> };
> 
> That didn't bring back the messages for me

**Comment by raymix** [comment]
You're right, weirdly enough description didn't work for some reason.
Anyway, Awol is updating epoch core PBO now

**Comment by Tarabass999** [comment]
Now it looks much better :) Thank you
