### ISSUE TITLE
0.3.9 Tanoa bole pile

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#554]
If you hatch woodpile on Tanoa you'll get wood logs, but they're spawning inside the woodpile-object and are not reachable to loot.

**Comment by Tarabass999** [comment]
ability to hatch them has gone since 542.. but there are enough of trees so :) if this is wanted it can get closed

**Comment by vbawol** [comment]
I have removed these, for next build 546
https://github.com/EpochModTeam/Epoch/commit/4405c12680af4c76e613e05befe6ba30c937765e
