### ISSUE TITLE
Testing Notes on Tanoa 0.3.9 (issues)

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#557]
Here are my notes from testing on 6/28/16 (for AWOL)
Version 0.3.9 Map: Tanoa
- [x]  Walls disappearing when upgrading (known issue)
- [x]  Any actions with hatchet / sledge are broken in this build (chopping trees etc.)
- [x]  HUD is hiding weapon information (supposed to be in bottom right)

**Comment by vbawol** [comment]
I think the first two should be fixed... hopefully you can confirm.

Will check the weapon hud changes (thought: it might just be a difficulty setting?)

**Comment by orangesherbet** [comment]
Confirmed the first two issues are fixed- Walls no longer disappear after upgrading and hatchet / sledge actions are working again. Progress! 

The Weapon HUD is still hidden however- not sure what is causing that

**Comment by Tarabass999** [comment]
new update of Arma SNEAK PV changed the not showing map contents issue.
cheers

**Comment by RC-Robio** [comment]
weaponInfo in sc.armaprofile is set to 1 (fadeout) should be 2 ,  And others that are true/false should actually be numbers.  reducedDamage should be 0 And I believe it is breaking the rest of the indicators below it
`Class DifficultyPresets
{
    class CustomDifficulty
    {
        class Options
        {
             // Simulation
             reducedDamage = 0; // Reduced damage

             // Situational awareness
             groupIndicators = 2; // Group indicators (0 = never, 1 = limited distance, 2 = always)
             friendlyTags = 0; // Friendly name tags (0 = never, 1 = limited distance, 2 = always)
             enemyTags = 0; // Enemy name tags (0 = never, 1 = limited distance, 2 = always)
             detectedMines = 0; // Detected mines (0 = never, 1 = limited distance, 2 = always)
             commands = 1; // Commands (0 = never, 1 = fade out, 2 = always)
             waypoints = 2; // Waypoints (0 = never, 1 = fade out, 2 = always)

             // Personal awareness
             weaponInfo = 1; // Weapon info (0 = never, 1 = fade out, 2 = always)
             stanceIndicator = 1; // Stance indicator (0 = never, 1 = fade out, 2 = always)
             staminaBar = 1; // Stamina bar
             weaponCrosshair = 1; // Weapon crosshair
             visionAid = 0; // Vision aid

             // View
             thirdPersonView = 1; // 3rd person view
             cameraShake = 1; // Camera shake

             // Multiplayer
             scoreTable = 1; // Score table
             deathMessages = 1; // Killed by
             vonID = 1; // VON ID

             // Misc
             mapContent = 0; // Extended map content
             autoReport = 0; // Automatic reporting
             multipleSaves = 0; // Multiple saves
        };

        //aiLevelPreset is counted from 0 and can have following values: 0 (AI Level Low), 1 (AI Level Normal), 2 (AI Level High), 3 (AI Level Custom).
        //When 3 (AI Level Custom) is chosen, values of skill and precision are stored to the class CustomAILevel.
        aiLevelPreset=2;
    };
    class CustomAILevel
    {
        skillAI=1;
        precisionAI=0;
    };
};`

**Comment by RC-Robio** [comment]
weaponInfo in sc.armaprofile is set to 1 (fadeout) should be 2 ,  And others that are true/false should actually be numbers.  reducedDamage should be 0 And I believe it is breaking the rest of the indicators below it

weaponInfo in sc.armaprofile is set to 1 (fadeout) should be 2 ,  And others that are true/false should actually be numbers.  reducedDamage should be 0 And I believe it is breaking the rest of the indicators below it
```weaponInfo in sc.armaprofile is set to 1 (fadeout) should be 2 ,  And others that are true/false should actually be numbers.  reducedDamage should be 0 And I believe it is breaking the rest of the indicators below it

version=1;
blood=1;
singleVoice=0;
gamma=1;
brightness=1;
difficulty="Custom"
Class DifficultyPresets
{
class CustomDifficulty
{
class Options
{
// Simulation
reducedDamage = 0; // Reduced damage

         // Situational awareness
         groupIndicators = 2; // Group indicators (0 = never, 1 = limited distance, 2 = always)
         friendlyTags = 0; // Friendly name tags (0 = never, 1 = limited distance, 2 = always)
         enemyTags = 0; // Enemy name tags (0 = never, 1 = limited distance, 2 = always)
         detectedMines = 0; // Detected mines (0 = never, 1 = limited distance, 2 = always)
         commands = 1; // Commands (0 = never, 1 = fade out, 2 = always)
         waypoints = 2; // Waypoints (0 = never, 1 = fade out, 2 = always)

         // Personal awareness
         weaponInfo = 1; // Weapon info (0 = never, 1 = fade out, 2 = always)
         stanceIndicator = 1; // Stance indicator (0 = never, 1 = fade out, 2 = always)
         staminaBar = 1; // Stamina bar
         weaponCrosshair = 1; // Weapon crosshair
         visionAid = 0; // Vision aid

         // View
         thirdPersonView = 1; // 3rd person view
         cameraShake = 1; // Camera shake

         // Multiplayer
         scoreTable = 1; // Score table
         deathMessages = 1; // Killed by
         vonID = 1; // VON ID

         // Misc
         mapContent = 0; // Extended map content
         autoReport = 0; // Automatic reporting
         multipleSaves = 0; // Multiple saves
    };

    //aiLevelPreset is counted from 0 and can have following values: 0 (AI Level Low), 1 (AI Level Normal), 2 (AI Level High), 3 (AI Level Custom).
    //When 3 (AI Level Custom) is chosen, values of skill and precision are stored to the class CustomAILevel.
    aiLevelPreset=2;
};
class CustomAILevel
{
    skillAI=1;
    precisionAI=0;
};
};```

**Comment by RC-Robio** [comment]
weaponInfo in sc.armaprofile is set to 1 (fadeout) should be 2 ,  And others that are true/false should actually be numbers.  reducedDamage should be 0 And I believe it is breaking the rest of the indicators below it
`version=1;
blood=1;
singleVoice=0;
gamma=1;
brightness=1;
difficulty="Custom"
Class DifficultyPresets
{
class CustomDifficulty
{
class Options
{
// Simulation
reducedDamage = 0; // Reduced damage

// Situational awareness
groupIndicators = 2; // Group indicators (0 = never, 1 = limited distance, 2 = always)
friendlyTags = 0; // Friendly name tags (0 = never, 1 = limited distance, 2 = always)
enemyTags = 0; // Enemy name tags (0 = never, 1 = limited distance, 2 = always)
detectedMines = 0; // Detected mines (0 = never, 1 = limited distance, 2 = always)
commands = 1; // Commands (0 = never, 1 = fade out, 2 = always)
waypoints = 2; // Waypoints (0 = never, 1 = fade out, 2 = always)
// Personal awareness
weaponInfo = 1; // Weapon info (0 = never, 1 = fade out, 2 = always)
stanceIndicator = 1; // Stance indicator (0 = never, 1 = fade out, 2 = always)
staminaBar = 1; // Stamina bar
weaponCrosshair = 1; // Weapon crosshair
visionAid = 0; // Vision aid

// View
thirdPersonView = 1; // 3rd person view
cameraShake = 1; // Camera shake

// Multiplayer
scoreTable = 1; // Score table
deathMessages = 1; // Killed by
vonID = 1; // VON ID

// Misc
mapContent = 0; // Extended map content
autoReport = 0; // Automatic reporting
multipleSaves = 0; // Multiple saves
};

//aiLevelPreset is counted from 0 and can have following values: 0 (AI Level Low), 1 (AI Level Normal), 2 (AI Level High), 3 (AI Level Custom).
//When 3 (AI Level Custom) is chosen, values of skill and precision are stored to the class CustomAILevel.
aiLevelPreset=2;
};
class CustomAILevel
{
skillAI=1;
precisionAI=0;
};
};`

**Comment by vbawol** [comment]
fixed weapon HUD info.
