### ISSUE TITLE
Testing Feedback 0.3.9 on Tanoa 

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#558]
Date: 6/28/16 Version 0.3.9
Here is some feedback from our testing (SLI and I) on Tanoa

New Text system can scroll a bit too fast when doing an action that prints a few messages at a time- such as drinking Whiskey Noodle

When crafting an item- can the slider be set to "1" by default? Might help newer players not used to the crafting menu.
- [x] Global vehicle limit does not send a message to the players- so when you buy a vehicle from a trader and it doesn't work there is no feedback to the player. Could use a message to tell you what is going on.
- [x] Is it possible to have a "splash effect" added to the bobber when fishing?  If you know to look for it- you can see the bobber move but otherwise it is very subtle.

Could use a different way to cook meat- using the crafting menu feels a bit weird- a "cook" button in the inventory?

The ATM / Phone Booth could use a tooltip to help players know how to use it.  If you were a new player you might not even know there is a banking system.

**Comment by vbawol** [comment]
- [ ] Orange just reported this minor errror with crafting system was caused by random input in the search box. @raymix 
  http://imgur.com/a/2Urgb
- [x] Zombies are in underwear to JIP players.
- [ ] vehicle anti wall check needs reworked.

**Comment by vbawol** [comment]
tracking freeback and issues here: https://github.com/EpochModTeam/Epoch/issues/583
