### ISSUE TITLE
0.3.9 546 Tanoa error message RyanZombie

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#562]
Players get some rare error message about Ryanzombies sound.
But Ryan zombies is not running at our server.
![unbenannt](https://cloud.githubusercontent.com/assets/19999334/16470961/ea2e22fe-3e59-11e6-8fc5-9671d343d84e.jpg)

**Comment by vbawol** [comment]
That is odd as we don't reference this sound class in the latest build. We did in some of the earlier test builds but Ryan has since removed these sound classes.

Zombies should also not spawn if his mod is not enabled, so I will double check that.
