### ISSUE TITLE
BattlEye kicks when player places frequency jammer

### ISSUE THREAD

**Issue by StianKruger** [EpochModTeam/Epoch#581]
#8 "ole_EPOCH", "PlotPole_SIM_EPOCH"]) then {

_alljammer = allmissionobjects 'PlotPole_EPOCH';
_c = 0;
{
if ((_x getVariable["BUILD_"

Tried adding this to the allMissionObjects BE filter but no joy. It should work

7 allMissionObjects !="_alljammer = allmissionobjects 'PlotPole_EPOCH';"

**Comment by vbawol** [comment]
that should work, are you certain you reloaded your scripts after?

just noticed you said "allMissionObjects BE filter" that does not exist it needed to be added to scripts.txt

**Comment by vbawol** [comment]
pushed the fix in #582
