### ISSUE TITLE
Server auto restart

### ISSUE THREAD

**Issue by Chickenw** [EpochModTeam/Epoch#585]
Hello The server auto restart is Broken. Could be cause im running 2 Servers one altis life and one Epoch but i was hoping to not have to worry about BEC for this one but it looks like im have no choice... Server will run over 9hours even if its set to 4hour restarts. It is set to True...

**Comment by vbawol** [comment]
Do you have the correct rcon information in your epochServer.ini?
https://github.com/EpochModTeam/Epoch/blob/release/Server_Install_Pack/%40epochhive/EpochServer.ini#L5-L7

**Comment by Chickenw** [comment]
Yes my port is 2444 for Game port. My Password matches my RConPassword testtesttest which is set on port 2307
BEServer.cfg
RConPort 2307
RConPassword testtesttest

IP = 104.153.108.69
Port = 2444
Password = testtesttest

**Comment by vbawol** [comment]
change Port in the [EpochServer] section to what you have set in your BEServer.cfg. From what you posted that looks to be 2307

**Comment by Chickenw** [comment]
i have this testing right now:P

**Comment by Chickenw** [comment]
Well it restarted it at the 4hour mark but did not start it back up xD it closed it.

**Comment by vbawol** [comment]
You still need to use a process manager to restart the server, like http://www.firedaemon.com/ or a batch file 
http://epochmod.com/forum/topic/29546-arma3epochbat/ 
http://epochmod.com/forum/topic/29166-tool-to-restart-the-server-and-bec-after-shutdown/?do=findComment&comment=174116

**Comment by Chickenw** [comment]
Ah okay Thank you:) Then this issue is fixed:P Maybe we could change where its asking for PORT to maybe rconport so people know xD
