### ISSUE TITLE
[Suggestion]? Will you ever make it so we can build anywhere?

### ISSUE THREAD

**Issue by Chickenw** [EpochModTeam/Epoch#586]
So i notice on my Server players can't build in Kava Hospital & Couple other small locations. Will this ever be removed so people can build anywhere? I already did the cfg to allow them to build in military bases

**Comment by vbawol** [comment]
This is a configurable setting server side, are you a server admin?

**Comment by Chickenw** [comment]
Yes i been looking for the settings and i cant find em

**Comment by vbawol** [comment]
it should be this config: https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_config/Configs/CfgEpochClient/Altis.hpp#L17-L25

**Comment by Chickenw** [comment]
class Altis {
        blockedArea[] = { //[POS],radius
    };
    // Trash config
    TrashClasses[] = { "Trash", "TrashSmall", "TrashVehicle", "PumpkinPatch", "TrashFood", "HempFiber" };
};
Still does same thing.

**Comment by vbawol** [comment]
Make sure you have buildingNearbyMilitary set to 1 in your cfgEpochClient config also. Other than that it is likely this restriction: https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_code/compile/building/EPOCH_isBuildAllowed.sqf#L181

**Comment by Chickenw** [comment]
Thank you i removed that hole line area and works great:P
