### ISSUE TITLE
attachTo BE Filters for Vehicle Loading

### ISSUE THREAD

**Issue by SamuelJBeer** [EpochModTeam/Epoch#589]
The release of APEX brought with it the ability to load vehicles into transport aircraft like the Blackfish, however doing so triggers the attachTo BE filter as is expected.

The following allows all Epoch and Apex ground vehicles, boats and karts to be loaded, while still kicking for attachTo events involving other objects (aircraft, static weapons, etc).

`!"[A-Z]_(G_)?(Offroad|Quadbike|Hatchback|SUV|Rubberboat|Van|Boat_Civil|SDV|MRAP|Truck)_([0-9]+_)?((box|transport|covered|mover|police|rescue|armed)_)?EPOCH" !"([A-Z]_)?[A-Z]+_(Boat|Scooter|Offroad|LSV)_((Transport)_)?[0-9]+_((unarmed|light)_)?F" !"K0(1|2|3|4)"`

To use, copy the contents of the code block above to the end of the first line in your attachTo.txt filter file.

Note: This does not whitelist any vehicles added by mods, i.e. CUP vehicles.

**Comment by vbawol** [comment]
Thanks @blkanaki will get this merged into the next build.
