### ISSUE TITLE
CUP System kick Player with Script Restriction #49

### ISSUE THREAD

**Issue by OJohny** [EpochModTeam/Epoch#590]
#49 " (!isNil "_code") then {

private _handler = _display displayAddEventHandler [_key, _code];
_x set [0, _handler];
};
} forEach _v"

**Comment by SamuelJBeer** [comment]
Add the following to the end of line 51 in your scripts.txt file (Include a space before the !=)

`!=" (!isNil \"_code\") then {\nprivate _handler = _display displayAddEventHandler [_key, _code];\n_x set [0, _handler];\n};\n} forEach _v"`

Line 51 of scripts.txt should start with `7 displayAddEventHandler`

**Comment by OJohny** [comment]
Thanks, dissabled script.txt to test Cup, at the Moment.

**Comment by vbawol** [comment]
Added this for next build 

```
!="private _handler = _display displayAddEventHandler [_key, _code];"
```

https://github.com/EpochModTeam/Epoch/commit/6f0025f8c94fe395fe76818ec5b30d4c85223798

:+1:
