### ISSUE TITLE
Upgraded Fireplace change position and is bugged in the Ground

### ISSUE THREAD

**Issue by Ignatz-HeMan** [EpochModTeam/Epoch#592]
When upgrading a Fireplace to Fireplace on, The Fireplace on is bugged into the Ground.
The Center Position (circle) of the FIreplace on is higher, then the circle of Fireplace of.
Tested on Tanoa

**Comment by vbawol** [comment]
Hey @Ignatz-HeMan, could you please provide a screenshot?

**Comment by Ignatz-HeMan** [comment]
![20160808001420_1](https://cloud.githubusercontent.com/assets/6589278/17465631/511a4d5a-5cfd-11e6-9ef1-7e80e03ae446.jpg)
Both Fireplaces was build onto the Wooden Floor. The Left one is only upgraded

**Comment by vbawol** [comment]
This should be fixed in 0.4, if not please report back
