### ISSUE TITLE
coconut from coconuttree

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#593]
when a coconut tree falls then spawns even coconut besides wood.
you can open the coconut you can drink stage 2 you break the full or empty coconut with hatchet or sledge.
then you eat the coconut meat

**Comment by vbawol** [comment]
@baaljayjay could you make the assets? If so I would be glad to add this.

**Comment by baaljayjay** [comment]
can you give me one model.cfg and .cpp data from food or drinks (example purple nurple,scam) please ?
maybe i can learn it from this data.

**Comment by vbawol** [comment]
Yes, I will try to post some community assets I have made and/or have permission to change the license on with the next 0.4 update in hopes to encourage more contributions.

**Comment by baaljayjay** [comment]
As I said in other topics I am just stupid, but I give the raw files ever. Until I understand is dayz, epoch and 7dtd already finished game.

link:https://drive.google.com/file/d/0B2PXTFaiSMInT0wySElvYVB0RDQ/view?usp=sharing

**Comment by vbawol** [comment]
tracking here: https://github.com/EpochModTeam/EpochCore/issues/5
