### ISSUE TITLE
TerainGrid settings

### ISSUE THREAD

**Issue by Ghostrider-DbD-** [EpochModTeam/Epoch#600]
Epoch 0.3.9.0 
I just noticed that for most configurations terrainGrid = 10 which may explain some of the issues with low client FPS a while back.

suggestion: alter as follows:
        class Standard
        {
            viewDistance = 1600; // Standard Preset = 1600
            viewDistanceObects = 1300; // Standard Preset = 1300
            terrainGrid = 30; // Standard Preset = 25
        };
        class High
        {
            viewDistance = 2200; // High Preset = 2200
            viewDistanceObects = 1800; // High Preset = 1800
            terrainGrid = 25; // High Preset = 12.5
        };
        class VeryHigh
        {
            viewDistance = 3000; // Very High Preset = 3000
            viewDistanceObects = 2600; // Very High Preset = 2600
            terrainGrid = 17.5; // Very High Preset = 6.25
        };
        class Ultra
        {
            viewDistance = 3800; // Ultra Preset = 3800
            viewDistanceObects = 3200; // Ultra Preset = 3200
        terrainGrid = 10; // Ultra Preset = 3.125
        };

**Comment by vbawol** [comment]
We ended up using 10 as it is the default for MP in Arma 3. Any higher and you start to notice issues with gaps under objects at a distance.  Also our forced quality settings are only enforced on players not admins.
