### ISSUE TITLE
craftable toxic gasgrenade

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#608]
craftable gasgrenade for baserape or defense of base.
gas mask protects for gas.
you can heal with Autoinjector 2mg Atropine or better 2mg Atropine+220mg Obidoxime(maybe reduce toxity)
https://en.wikipedia.org/wiki/Atropine

**Comment by vbawol** [comment]
Thanks for the suggestion, have added the toxic grenade and may add the Atropine Autoinjector.
