### ISSUE TITLE
farming

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#609]
in epoch some food not healthy because can of food not good,so we need fresh vegetables and fruits.
to plant gourds, corn, potatoes or apple tree (there are apple and if you fall the tree there wood) but I know can not technically implement.

**Comment by baaljayjay** [comment]
ideas for farming: small garden shovel and digging stick for prepare the field.(digging stick craftable with 2 sticks)
wheat,Beetroot,Mangelwurzel modell.
maybe when with action menu search and look to ground have small chance of Seeds found

link:https://drive.google.com/file/d/0B2PXTFaiSMInZkJ2NUtFV0dwQUE/view?usp=sharing

**Comment by Helion4** [comment]
would this be easier if growing food was restricted to some kind of grow box? Will growing progress be saved over restarts?
![900b162353737ae81aeff6bb61e29c2d](https://user-images.githubusercontent.com/29925182/27980051-a1717bd0-6372-11e7-92d5-a740a063c010.png)

Where will the seeds come from? Adding packets of seed into the loot table?

**Comment by baaljayjay** [comment]
This is very good idea. Perhaps in the size like quarterwood floor.
Maybe you could first test for pumpkins and plant spawn from the server say that there 100% chance pumpkin spawn

**Comment by vbawol** [comment]
I think that would work @Helion4 we can easily persist the growing states just by treating it as an insecure storage device. It would be one single object with visible weapon holders (similar to our loot objects). The server could check these gardens and exchange the seeds for the more mature items.

We currently have: Poppy, Goldenseal, Pumpkin.
https://github.com/EpochModTeam/EpochCore/blob/experimental/Sources/a3_epoch_configs/Configs/CfgVehicles.hpp#L10193-L10246

Need "Seed" magazine item:
- [x] Poppy
- [x] Goldenseal
- [x] Pumpkin

We could also add:
- [ ] Corn (Note: We have canned corn already - sweetcorn_epoch)
- [ ] Potatos 
- [ ] Wheat
- [x] Hemp Plant (already have 1 klio magzine item - ItemKiloHemp )

Needed Changes:

- [ ] Craft a harvested plant item into seeds, these seeds are placed into the cargo space of the garden.
- [x] Slow loop on the server side control the state of all gardens by swapping out the seed after X time with the mature item.

For Trees like Apple, Pecans, etc. we could maybe have a single tree object that once mature would have weaponholders to see the fruit as it was grown (i.e. generate apples periodically).

**Comment by baaljayjay** [comment]
I do not know what the pecan is exactly and how it tastes.
What to do with the pecan?

**Comment by Helion4** [comment]
Pecan is a type of nut that grows on lush green trees, it has many health benefits.

**Comment by vbawol** [comment]
Ok closing this to track the required changes here https://github.com/EpochModTeam/Epoch/issues/798, we can always add more options after we get the framework built.
