### ISSUE TITLE
special trader(blackmarket)

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#610]
special trader like blackmarket he has everthing but is expensive and not market on map so you must search for him.
when the server restart he is other position on the map.
(sorry for this much ideas)

**Comment by Ignatz-HeMan** [comment]
Please not! :(

**Comment by vbawol** [comment]
Thanks for the suggestions, While server admins can add this already. I do think it is better to only have traders sell what was sold to them, to create a "loot" economy of sorts. This way everything on a trader should represent the time it took that person to find. That said I do think we should look at having black market traders that only deal in certain "bad" items at higher prices. 

tracking this here https://github.com/EpochModTeam/Epoch/issues/583
