### ISSUE TITLE
fireplace and cooking

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#611]
in the current version can be cooked only with campfire.
this can cause problems because for campfire one needs 1 ast, 2 stone and wood block, so you need hatchet and hammer slegde.
at the beginning when you have meat, you can not cook because of the lack of resources, energy and to restart disappears the campfire.
could cook for meat and fish is indeed a disposable grill use, which has a limiting durability (5 mins)
this can be found in loot but not suitable melt it there for metal.
for that you need a campfire.
later if you have a campfire so you can get a kitchen stove produced from metal and rock.
the remains after restart and must with wood fill after so about 10 minutes.
with the stove you can cook and perhaps melt metal.

**Comment by baaljayjay** [comment]
Here are my approximate idea as it might look. If you like it you can take I give gladly my right off.

link:https://drive.google.com/file/d/0B2PXTFaiSMInNEJmbG1HcktkcFU/view?usp=sharing (update)

**Comment by baaljayjay** [comment]
small campfire.
crafttable with 10 sticks.
maybe can harvest sticks with action menu.
link:https://drive.google.com/file/d/0B2PXTFaiSMInSmwwbTVQbDZ2azg/view?usp=sharing

**Comment by Vampurica** [comment]
What if we added meat drying instead? Players can gather Sea Salt (without tools) and use that to make dried meat.

In end-game we could add drying racks to allow large amounts to be done at a time instead of a (presumably) long timed single item crafting recipe.

**Comment by Helion4** [comment]
A small campfire and/or disposable grill would still require a lighter, no?  

How about a one use - self lighting - fire kit.....it's the future! Should only last as long as cooking meat, then becomes useless. 
Can be found in loot drops, requires no other tools, cannot be used for anything other than cooking meat for a low duration.
A quick concept render -
![firekit_concept](https://user-images.githubusercontent.com/29925182/27978898-2b1ec530-636a-11e7-8a9b-df2d1546b81e.png)

Drying racks for end game is a cool idea.

**Comment by baaljayjay** [comment]
My idea epoch goes in two direction the one tries to build with the remnants of civilization what to build and others return the back to go the path of nature.
For your sache needs since you  water because of the chemicals like mre
Or is because this phase-change material?
(ps you can good model)

**Comment by vbawol** [comment]
Just to note, We do have a fireplace (KitFirePlace) = (2 Rock + 1 Stick) and a Lighter but never made the lighter_epoch a requirement.

I like the instant fire idea but it needs to be easier to craft or find than making the existing fireplace.

For smelting, it could be done with any fire source via the crafting system and just require special items like a smelting toolkit with items such as a crucible, etc.

It does strike me that maybe we just need to make it easier to harvest rocks and sticks. A simple solution could be to add sticks and rocks to the "Trash" loot tables.

**Comment by vbawol** [comment]
tracking here: https://github.com/EpochModTeam/Epoch/issues/583
