### ISSUE TITLE
 performance increase drugs

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#612]
maybe you can paste it.
for example steroid can sprint faster and better but for higher blood pressure,
poisoning.
afterwards so (5 minutes) stamina generated bad more hungry and thirsty.
Methamphetamine not suffer fatigue, might damaging 3x more.
after less stamina, fatigue, feeling pain maybe instead of 1 as 0.8
more hungry and thirsty,higher blood pressure. the body needs to regenerate.
be 5 minutes god and his 3 hours sinner, that's really it.

perhaps for you

**Comment by vbawol** [comment]
We may add more items like this. The system should already allow this for the most part, items can give any attributes and affect blood pressure. 
for example, this is the configs for Whiskey Noodle:  https://github.com/EpochModTeam/Epoch/blob/experimental/Sources/epoch_config/Configs/CfgItemInteractions.hpp#L160
