### ISSUE TITLE
sapper explode too early

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#614]
when a sapper spawn tries to pursue the target,but the explode 50m away from me . 
So it is not a threat

**Comment by vbawol** [comment]
I think this is part working as intended as if he gets stuck or cannot find you he will blow up due to his frustration, I have adjusted the setting to make him a little less prone to get frustrated and blow up.

https://github.com/EpochModTeam/Epoch/commit/260f6b031a89674196f4985673423cf699e01abf
