### ISSUE TITLE
EPOCH_load_vehicles.sqf and ImmuneVehicleSpawn

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#615]
Is there any chance that we could add back the ImmuneVehicleSpawn and immuneVehicleSpawnTime functionality to EPOCH_load_vehicles.sqf. Not asking for it to replace the initial spawn protection in the new script, simply as an addition as to how long vehicles are God Moded.

_Rational: On my server, and I am sure others, people spend a lot of time, effort and crypto in obtaining vehicles for their groups, especially the larger groups. Unfortunately, there are muppets around who seem to take delight in griefing people's bases and destroying all their vehicles, especially when the group members are offline. Even with admins on as much as possible, it is only possible to fix the problem _after_ the vehicles, sometimes loaded with building supplies are destroyed.
I was forced to revert to the old vehicle spawn script and use the ImmuneVehicleSpawn mechanism to God Mode vehicles until they were unlocked for the first time after restart. This change has helped and saved me from losing two large and competent groups from my server._

It would be really appreciated, if the ability to specify a time in which vehicles would be God Moded after restart in order to reduce vehicle griefing while also being able to deploy the latest version of EPOCH_load_vehicles.sqf.

Cheers,
Grahame (from EpochMod.com forums)

**Comment by vbawol** [comment]
I think I have a solution with this push: https://github.com/EpochModTeam/Epoch/commit/14058cb832ece9639483f3bcce7917afef9f1c0e

Basically if you lock a vehicle in your base it will stay immune to damage provided it is within the jammer range until it is unlocked by the owner or the lock status expires.
