### ISSUE TITLE
Feedback 0.4

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#616]
In version 617 the inventory layout does not work.
So you die because you can not drink and eat.
On tanoa I have not found telephone cell or atm so you can with the trader money withdraw and deposit with high fees and longer time.
The drone mission when you finish the drone remains on the map and is marked.

**Comment by morgoth0** [comment]
Re: ATMs/phones in Tanoa... they are just not basically on the standard ARMA map. On our server we added an ATM at every gas station to make up for that. Not really an Epoch issue as such. If VBAWOL wants our coords for them would be happy to contribute

If they want our trader camps for Tanoa, also happy to contribute

**Comment by vbawol** [comment]
Thanks @baaljayjay should be fixed now. That would be great @morgoth0 

propose the changes here: https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_server_settings/configs/maps/tanoa.h or simply share the positions in a new issue.
