### ISSUE TITLE
 Drink with the hands

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#643]
I think it is good to start with less food and drink.
Thus food and drink search is already a high priority at the beginning.
So you can with the action menu actually so drink water tanks?
So with the hands for example gets 100 thirst points and random toxicity.

**Comment by Ignatz-HeMan** [comment]
Added to Experimental and coming at least with 0.6
https://github.com/EpochModTeam/Epoch/pull/755

**Comment by baaljayjay** [comment]
Really good Ignatz_HeMan.
Now I have a question
Is that what the larger water tank?

**Comment by Ignatz-HeMan** [comment]
All Items, where you can fill a water bottle will also work with this.
It is the same config.

**Comment by baaljayjay** [comment]
You can´t drink when bigger water tank and water tank on top

**Comment by Ignatz-HeMan** [comment]
Is it possible to fill bottles there?
As I said, it use the same config as the filling for bottles

**Comment by baaljayjay** [comment]
can it write in german?
yes

**Comment by Ignatz-HeMan** [comment]
You can write me in Discord or Epoch forum a private message. If I can fix it, I will do...

**Comment by vbawol** [comment]
Thanks for adding this @Ignatz-HeMan !
