### ISSUE TITLE
uav have tws

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#645]
when first person in uav can change optic in tws.
this problem when you controlled the uav mission after complete the mission

**Comment by vbawol** [comment]
Thanks for the report, I just added changes to fix this. b638 > https://github.com/EpochModTeam/Epoch/commit/4f50c4513b8a10e734573fa0b7cca078aebcaef2

We should be able to simply use _unit disableTIEquipment true; on the UAV's that we spawn via missions. Note: If the UAV is spawned with another method this won't do anything.
