### ISSUE TITLE
HALO teleporting still happens

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#648]
Out of the changelog:
[Fixed] Increased anti-teleport range that should hopefully allow for proper HALO spawning.

It still teleports players back in the air, after landing with parachute from HALO spawn script.
Fresh Experimental DL 3.11.16

**Comment by vbawol** [comment]
ok, will take another look at the code.

**Comment by Tarabass999** [comment]
antihack_maxTravelDistance = 30; // anti-teleport max travel distance
antihack_TPcenterDistance = 30; // anti-teleport distance from start

shows no effect for HALO spawn teleport. 
Edit: Also Blackfish teleporting didn't take effect from those entries

**Comment by vbawol** [comment]
thanks for testing, I will see about a total rewrite to the anti TP function next.

**Comment by Tarabass999** [comment]
when I change line 847 in epoch_server\init\server_securityfunctions.sqf to

	if (((_distance/(_curTime-_lastTime)) > "+str _maxTravelDistance+") && _notNearbySpawn && (player == vehicle player) && animationState player != 'halofreefall_non') then {

it (Teleporting) wasn't happening for halv halo script anymore today... maybe I'll see something else in rtp logs tomorrow.. and maybe there someone 'll find the possibility to add the Blackfish?		
But if you still work on an update for the AH I won't disturb just informate you.. :)

**Comment by Tarabass999** [comment]
Seems like that worked till build 672... Today I added 675 and it's nomore working, still teleporting players with halo spawn back in the air.. sometimes with opened para aslong as they fly, sometimes without parachute (after landing) and just fall down

**Comment by Vampurica** [comment]
I took a look through the code and it appears fine although `antihack_maxTravelDistance` should be clarified that it is basically max meters per second travel.

Would checking that the player is in a Halo animation be a valid exemption?

Example code (untested) for `server_securityfunctions.sqf`
This is at line 875.

```
if !(animationState player == 'halofreefall_non') then {
	if (isNil '"+_skn_antiTeleportPVC+"') then {
		[format['[TEST] TP from %1 to %2, %3 meters, now at %4', _lastPos, _curPos, round _distance, getPosATL player],1] call "+_sknBanANDSleep+";
		vehicle player setPosATL _lastPos;
		_cntBan = _cntBan + 1;
		if (_cntBan > 4) then {

		};
	} else {
		uiSleep 10;
		_lastPos = getPosATL vehicle player;
		_lastTime = diag_tickTime;
		_notNearbySpawn = false;
	};
};
```

I understand that allowing someone in a specific animation to avoid AntiTP would be bad practice. I'm not sure if the player by default reverts out of the animation when contacting the ground.

Or maybe it would be a better idea to check for distance2d moved and then check for the height moved seperately?

Maybe something like this to exempt Z travel for players in that animation state?
```
if !((animationState player == 'halofreefall_non') && (_lastPos distance2d _curPos < "+str _maxTravelDistance+") && (_curPos select 2 > 50)) then {
```

The AntiTP in the should only be applying to players not in a vehicle so I'm not sure why the Blackfish would be effected, or players who are piloting a parachute.
```
if (((_distance/(_curTime-_lastTime)) > "+str _maxTravelDistance+") && _notNearbySpawn && (player == vehicle player)) then {
```
Hence the `(player == vehicle player)`

**Comment by Tarabass999** [comment]
> I took a look through the code and it appears fine although antihack_maxTravelDistance should be clarified that it is basically max meters per second travel.

OMG maybe that's the only problem.. because players fall down with 240 km/h before parachute is opening.. so I changed antihack_maxTravelDistance  to 300 without changing anything in server_securityfunctions.sqf.

Worked fine on testserver... I will try in public, watch rtp and reply soon

**Comment by Tarabass999** [comment]
no errors or test TP messages till now... for both: blackfish and Halospawn... 

maybe till tomorrow.. but it looks good

**Comment by Vampurica** [comment]
At 240km/h that's 66.66~ MP/S.

I was able to hit 565km/h in the blackfish in the editor which is 157mp/s.

Maybe setting the Anti-TP to 180 will be a good value. There will still be issues if someone is using a jet however.

**Comment by Tarabass999** [comment]
The only thing a TP happend to players again was when they used ejector seat from new jets

**Comment by Tarabass999** [comment]
Ok I didn't get some errors anymore after changing that.. Thank you for your explaining SMVampire and sorry for wasting your time with that vbawol..

**Comment by Ignatz-HeMan** [comment]
I have not really followed this "problem", but what about checking:
if (((getpos player) select 2)) >100) then {do nothing};
Of course, first check if in Vehicle and check max vehicle speed
