### ISSUE TITLE
0.4+ BE kicks 

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#651]
Please report any BE kicks here

**Comment by SirDice** [comment]
I have a bunch of them due to CUP and CBA being loaded. These are the ones I had to add:

```
Script restriction #10:
7 moveIn !="\"\CUP\WaterVehicles\CUP_WaterVehicles_Core\functions\fnc_moveInCargo.sqf\"" !="CUP_fnc_moveInCargo"

Script restriction #11:
7 attachTo !="_l1 = createVehicle [_class,_ship,[],0,"NONE"];\n_l1 attachTo [_ship,[-4,_x,_height],_pos];\n_lights pushBack _l1;" !="ciws_1 = createVehicle [_ciws,[0,0,0],[],0,\"NONE\"];\n_ciws_1 attachTo [_ship,[-8.4,-21.3,5]];" !="_tempVar attachTo [_veh,[-4,_x,_height],_temppos];" !="ciws_1 = createvehicle [_ciws,[0,0,0],[],0,\"NONE\"];\n_ciws_1 attachto [_veh,[-8.4,-21.3,5]];" !="_unit setposASLW _newPos;\n_unit attachTo [_vehicle, [_xpos,_ypos,0], [_xpos,_ypos,0], _position];" !="_object = \"CUP_LHD_Monitor\" createVehicle [0,0,0];\n_object attachTo [_vehicle, [0,0,0], _virtualVehicleAction];" !="} foreach CUP_WATERVEHICLES_FOLDABLE;\n\n_cargo attachTo [_vehicle, [0,0,1], _position];" !="_helipad = \"HeliH\" createVehicle [0,0,0];\n_helipad attachTo [_ship,[0,0,0],_x];\n} forEach _heliPads;" !="call CUP_fnc_attachTow" !="\"cup\vehicles\cup_vehicles_towing\functions\fnc_attachTow.sqf\"" !="\"CUP_fnc_attachTow\""

Script restriction #24:
7 addMissionEventHandler !="CBA_clientID = [0, 2] select isMultiplayer;\naddMissionEventHandler [\"PlayerConnected\", {\nparams [\"_id\", \"_uid\", \"_name\"" !="addMissionEventHandler [\"EachFrame\", cba_common_fnc_onFrame];"
```

 I may run into a few more, I haven't been able to test everything yet.

**Comment by SirDice** [comment]
Hitting ESC to exit:

```
03.11.2016 22:44:39: SirDice (12.34.56.78:60142) deadbeeff00ddeadbeeff00ddeadbeaff00d - #60 "sition _exePos;
_exe ctrlCommit 0;

_prevButton = _display ctrlCreate ["RscButtonMenu", 90110, _dbg];

_x = 0 * (((safezoneW / s"
```

**Comment by vbawol** [comment]
Please keep the kick scripts.log lines coming and I will update the BE filters as soon as I have the time. 

Please note that you have one filter above that does not escape the double quotes on the text "NONE" should be \"NONE\" 

```
!="_l1 = createVehicle [_class,_ship,[],0,"NONE"];\n_l1 attachTo [_ship,[-4,_x,_height],_pos];\n_lights pushBack _l1;"
```

Because of this kind of typo, the filter line may stop working after this point. This is the main issue we had before 0.4. As some rules did not escape double quotes properly and caused inconsistencies in how they worked.

This is the regex filter I came up with that finds all properly formatted strings and makes it easy to find formatting issues. Search with this filter below (ctrl+F) in an editor that supports regex when editing scripts.txt and it might help prevent this.

```
!=([\"'])(?:\\\1|.)*?\1
```

**Comment by Ghostrider-DbD-** [comment]
EDIT:

To createvehicle.txt line 0
!"SmokeLauncherAmmo"

To deletevehicle.txt
Added !"Epoch_(Male|Female)_F)" 
Changed: !="[0-9]:[0-9]{1,4}" to !="[0-9]{1,2}:[0-9]{1,4}"

**Comment by SirDice** [comment]
> Please note that you have one filter above that does not escape the double quotes on the text "NONE" should be \"NONE\" 

Good one.

> Because of this kind of typo, the filter line may stop working after this point. This is the main issue we had before 0.4. As some rules did not escape double quotes properly and caused inconsistencies in how they worked.

Thanks for the heads up on that. When I fixed the rules I immediately got another kick of course.

```
04.11.2016 22:09:07: SirDice (12.34.56.78:65243) deadbeeff00ddeadbeeff00ddeadbeaff00d - #11 "lectionPosition _position);
_unit setposASLW _newPos;
_unit attachTo [_vehicle, [_xpos,_ypos,0], _position];

detach _unit;

_ne"
```

No quotes needed for this one :)

```
!="_unit setposASLW _newPos;\n_unit attachTo [_vehicle, [_xpos,_ypos,0], _position];\n\ndetach _unit;"
```

**Comment by vbawol** [comment]
@SirDice is that also from CBA/CUP? 

@Ghostrider-DbD- can you please also provide the kick log messages so I can be 100% certain where this code is from. 

Just to note: we are only looking for kicks from Arma 3, Epoch, or CUP/CBA.

**Comment by baaljayjay** [comment]
A sapper died( from Sapper Migration Event) so kick battleye me from server restriction 11
(bullet buffet server)

**Comment by 82ndab-Bravo17** [comment]
` #50 "

_control = _display displayctrl         37305; 
_control ctrladdeventhandler ["buttonclick","with uinamespace do {['dlcButtonClicke"`

I used !="dlcButtonClicke"

`#34 " 1) then {

_sapper moveTo _garrPos;

}else{

_nestMate = createAgent ["Epoch_Sapper_F", _garrPos, [], 0, "FORM"]; 
_bomb = crea"`

used !="_nestMate = createAgent [\"Epoch_Sapper_F\", _garrPos, [], 0, \"FORM\"];"

**Comment by Ghostrider-DbD-** [comment]
In case this is useful, I thought I would mention that Apex added ghex variants of the carryall and fieldlpack and three new backpacks. I am using the following (think I have these right). 

!"B_Bergen_(mcamo|dgtl|hex|tna)_F" !"ViperHarness_(blk|ghex|hex|khk|oli)_F" !"ViperLightHarness_(blk|ghex|hex|khk|oli)_F"  !"B_Carryall_(cbr|khk|mcamo|ocamo|oli|oucamo|hex|ghex)" !"B_FieldPack_ghex|(blk|cbr|khk|ocamo|oli|oucamo)"

**Comment by baaljayjay** [comment]
battleye kick me when i die.
script restriction 0
(tested on bullet buffet)

**Comment by vbawol** [comment]
please open a new issue if there are any false kicks
