### ISSUE TITLE
Pikes Peak Express bug

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#652]
When you start the mission and break it again, the mission does not really stop.
So you take the mission 9 x and break it off again.
Then takes the 10 x the mission and takes a document with brings the other dealer so gets 10 rewards for all 10 missions.
In the end you have a big loot heap.

**Comment by vbawol** [comment]
@baaljayjay  How are you breaking out of the mission?

**Comment by Ignatz-HeMan** [comment]
"Reset Mission" on Mission selection

**Comment by Ignatz-HeMan** [comment]
Fixed:
https://github.com/EpochModTeam/Epoch/pull/748
