### ISSUE TITLE
effect range from wooden club

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#657]
on bullet buffet i tried kill zombies with crude hatchet because i had this time no ammo for gun.
this worked fine so i create the wodden club and i use it.
Felt range of the hatchet 3 meters and the wooden clube less than 1 meter

**Comment by vbawol** [comment]
How does the sledgehammer feel in comparison? The wooden club did have a lower Time-To-Live so I have changed it to match the sledgehammer albeit still with a lower hit damage.
