### ISSUE TITLE
Zeus vehicles disappear

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#662]
After I spawn a armed vehicle with zeus, it disapears after a few seconds and only AI-Units stay back.

**Comment by vbawol** [comment]
Normally when the server spawns a vehicle it needs to run this command:

```
_vehObj call EPOCH_server_setVToken;
```

However, with Zeus you are creating the vehicle client side so you cannot really do that. We may be able to hook specifically to allow Zeus created vehicles. However, I need to look further into the code and report back.

Does this also result in BE kicks or have you sorted them already?

**Comment by vbawol** [comment]
Just pushed a fix for this issue with this commit: https://github.com/EpochModTeam/Epoch/commit/c86d4577e43907d7db247784d21016372c4cbb2f to allow vehicles that are spawned with Zeus available since b657 from here: https://github.com/EpochModTeam/Epoch/tree/experimental

**Comment by Tarabass999** [comment]
Zeus vehicle spawning now works again. Thank you vbawol :)
