### ISSUE TITLE
REQUEST: Rationalise male and female characters to BLUFOR

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#663]
Hi Aaron,
   I was wondering whether it would be possible to rationalize male and female characters into using just the one side. The changes necessary would be:

**epoch_server/init/server_init.sqf**
Change lines 94 and 95 from:
EAST setFriend[WEST, 1];
WEST setFriend[EAST, 1];
to
WEST setFriend [EAST, 0];
EAST setFriend [WEST, 0];

**CfgWeapons**
Change side = 0 to side = 1 in Epoch_Man)base_F definition
Optionally add modelSides[] overrides for all standard ARMA3 uniforms to allow BLUFOR to wear them. If you agree with the overall change then I will provide the code for this to add to CfgWeapons.

Given that the definition for male and female characters does not depend on the side, this change would free up OPFOR for a second AI faction (for examine allowing zombie vs bandit interaction).

**Comment by vbawol** [comment]
Actually, all players (male and female) are on created and joined to the west group:
https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_server/compile/epoch_player/EPOCH_server_loadPlayer.sqf#L135

The only reason females are on another side is to prevent males from wearing the female clothes. If Epoch_Man had side = 1 like the females do then they would also be able to put on the female clothes.

I would like to someday integrate the female models into Arma 3 properly. However, that would take a lot of work and may need some engine support to ever fully work correctly. 

Also, modelSides settings to allow the males to wear more of the available clothes in Arma are certainly welcome contributions: https://github.com/EpochModTeam/EpochCore/blob/release/Sources/a3_epoch_configs/Configs/CfgVehicles.hpp#L391-L427

**Comment by morgoth0** [comment]
First things first, I will be willing to provide any help necessary to get this implemented as you will see below. Before that, I'd like to respond to your observations to provide greater clarity.

"Actually, all players (male and female) are on created and joined to the west group:"
Very true, however the issue is not to do with the group container that players are in, it is a specific issue with the siding of males and females. By using two sides for gender Epoch has removed one for adversaries, preventing the interaction of roaming AI with infected (for example) leading to immersion issues when the adversaries refuse to react badly towards each other. As you know, I have dealt with this in a workaround on my servers and, for those, people love it when they are fighting AI and infected, who are fighting each other. I realize that many server owners (and players) may not want this, but as a really good sandbox environment I'd like to see Epoch continue to grow and support the full vista of possibilities from pure survival to heavily militarized apocalypse servers like mine.

"The only reason females are on another side is to prevent males from wearing the female clothes. If Epoch_Man had side = 1 like the females do then they would also be able to put on the female clothes."
That's very 1950s of you ;) On a more serious note, on my server they can now if they want. If they put on male clothing then they get their male profile head back, if not then they remain female. But for the blocking of males wearing female's clothing we remove a side for adversaries.

"I would like to someday integrate the female models into Arma 3 properly. However, that would take a lot of work and may need some engine support to ever fully work correctly."
True, ARMA should have provided this in engine but to allow what we need for Epoch I think it would not require many changes. The identification of male/female is stored in a variable within the model so the side identification is not really needed other than to prevent males wearing female clothing... 

"Also, modelSides settings to allow the males to wear more of the available clothes in Arma are certainly welcome contributions: https://github.com/EpochModTeam/EpochCore/blob/release/Sources/a3_epoch_configs/Configs/CfgVehicles.hpp#L391-L427"
This is how I can help to some extent. On my server, players can still only (in the field) put on NATO and Tryk's uniforms based on them all being BLUFOR. As you may have read I use Haljv's old spawn gear and black market scripts and they forceAdduniform onto the player so they can wear any uniform unless they take it off. In addition to ensure that these uniforms persist through a revive, log or server restart I changed the addUniform calls to forceAdduniform in the player_load and player_respawn scripts.

In order to get modelSide changes we would have to have them in the CfgVehicles.hpp and it is really easy, just an override definition for the uniform classes. I would be completely willing to provide these to you for standard ARMA3, Apex and CUP uniforms to allow all these to be worn, no matter what the side.

That said, I want to reiterate again that the issue here is about freeing a side for adversaries, not for freeing up uniforms for wear, though in concert with the siding change I will provide you the code for CfgVehicles.hpp to do that.

**Comment by vbawol** [comment]
I am all for additional options for clothes any PR's for that would likely be accepted, we just need to make sure we still prevent females from changing gender with just a clothing change. Ideally, Female/Male support would be implemented deeper into Arma. Should Arma add proper female support we should look at changing our setup.
