### ISSUE TITLE
Build 657 use inventory

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#665]
In Build 657 players can't use stuff from inventory. They can't drink,eat or heal themselfs..

**Comment by vbawol** [comment]
@Tarabass999 thanks for the report. Can you tell me what was the last build that did work for you?

**Comment by Tarabass999** [comment]
Build 655 works fine..

**Comment by vbawol** [comment]
Ok, sounds like a typo then, any rpt errors?

**Comment by vbawol** [comment]
Not able to reproduce this on my dev server with 657. maybe you are missing the new function Epoch_returnConfigV2?

Check out all the changes since stable here:
https://github.com/EpochModTeam/Epoch/compare/experimental

**Comment by Tarabass999** [comment]
yes, that was exactly what was missing... sorry for my issue dude. And thanks again
