### ISSUE TITLE
A3 1.66 Admin Player count

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#666]
Since Arma 3 Update 1.66 Players in Admintool are nomore shown. They also don't count or are shown. 0/2 players

**Comment by Skaronator** [comment]
Fixed via https://github.com/EpochModTeam/Epoch/commit/8e614b0b78ef67a230af3acf69787918de9a144f#diff-afb8d0634f60e6020fcef240832a2b2fL1385
