### ISSUE TITLE
668 - Can't Eat or Drink

### ISSUE THREAD

**Issue by ReDBaroN1** [EpochModTeam/Epoch#670]
Hi chaps, since the 668 build and crafting menu fix, can't eat or drink again..

**Comment by morgoth0** [comment]
FYI: Not having that issue on my server after 668 update.

**Comment by vbawol** [comment]
@ReDBaroN1 double check you have merged all the changes as there are a few new files.
changes since 655: https://github.com/EpochModTeam/Epoch/pull/669/commits
@morgoth0 thanks for reporting in 👍

**Comment by ReDBaroN1** [comment]
@vbawol huge apologies, I did post in discord but, forgot to reply in here and close. I found i was missing a new file in the latest build called EPOCH_returnConfigV2.sqf in epoch_code\compile\functions
