### ISSUE TITLE
668 - Server.rpt Error

### ISSUE THREAD

**Issue by ReDBaroN1** [EpochModTeam/Epoch#671]
Getting this since update to 668
`20:35:36 Error in expression <yerUID _playerUID;
};
};
if (_playerUID != '') then{
'epochserver' callExtension>
20:35:36   Error position: <!= '') then{
'epochserver' callExtension>
20:35:36   Error Generic error in expression
20:35:36 File epoch_server\compile\epoch_server\EPOCH_serverCommand.sqf, line 28
`

**Comment by vbawol** [comment]
I think this maybe due to some of the 1,66 issues also but I did put in some fixes for this issue as if the player object was null it could have thrown this error, now it won't at least throw the error. 

However, please make sure that 1.66 hotfix didn't already fix it and please report back.

**Comment by vbawol** [comment]
fixed with: https://github.com/EpochModTeam/Epoch/commit/4f86c913d8b28be288605274c32b3f4bda1d8ed4
