### ISSUE TITLE
A3 1.66 death

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#672]
when i die so i get to lobby with no selection for respawn.
 so can`t revived or "revenge"

**Comment by morgoth0** [comment]
Have you or your server owners updated to the new build released today?

[https://github.com/EpochModTeam/Epoch/releases](url)

Cheers,
morgoth0 (Grahame from EpochMod.com)

**Comment by baaljayjay** [comment]
i tested on bullet buffet because i have no server

**Comment by baaljayjay** [comment]
ok it`s working.
Thanks to the great creator vbawol
