### ISSUE TITLE
669 Command menu AH

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#676]
If players use command menu F3 for bot/Player 3 as example they get a ban called:

commandMenu: RscMenuCombatMode

**Comment by vbawol** [comment]
Sorry for my lack of knowledge here, Is this F3 a feature of Arma? 

Either way, you should be able to allow this by adding it to the array found in server settings .pbo here: https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_server_settings/configs/security/security_checks.h#L88

**Comment by Tarabass999** [comment]
Thank you... this would just be to communicate directly with bots in your team, and it's not needed for epoch, just a arma thing.

**Comment by vbawol** [comment]
Np, 

since this is for something custom will consider this case closed for now.
