### ISSUE TITLE
APEX / CfgPricing

### ISSUE THREAD

**Issue by Ghostrider-DbD-** [EpochModTeam/Epoch#677]
In case it is useful in the future, below is our pricing for APEX items and weapons.

	///////////////////////////////////////////////////////////////////////////////
	// Apex Items & Weapons
	///////////////////////////////////////////////////////////////////////////////
	class hgun_Pistol_01_F            { price = 65;  };
	class hgun_P07_khk_F              { price = 65;  };
	class SMG_05_F					  { price = 150;  };
	class LMG_03_F					  { price = 300;  };
	class arifle_MX_khk_F             { price = 150;  };
	class arifle_MX_GL_khk_F          { price = 150;  };
	class arifle_MXC_khk_F            { price = 135;  };
	class arifle_MXM_khk_F            { price = 150;  };
	class srifle_LRR_tna_F            { price = 185;  };
	class srifle_GM6_ghex_F           { price = 190;  };
	class srifle_DMR_07_blk_F         { price = 175;  };
	class srifle_DMR_07_hex_F         { price = 175;  };
	class srifle_DMR_07_ghex_F        { price = 175;  };
	class arifle_AK12_F               { price = 165;  };
	class arifle_AK12_GL_F            { price = 170;  };
	class arifle_AKM_F                { price = 140;  };
	class arifle_AKM_FL_F             { price = 140;  };
	class arifle_AKS_F                { price = 135;  };
	class arifle_ARX_blk_F            { price = 190;  };
	class arifle_ARX_ghex_F           { price = 190;  };
	class arifle_ARX_hex_F            { price = 190;  };
	class arifle_CTAR_blk_F           { price = 145;  };
	class arifle_CTAR_hex_F           { price = 145;  };
	class arifle_CTAR_ghex_F          { price = 145;  };
	class arifle_CTAR_GL_blk_F        { price = 145;  };
	class arifle_CTARS_blk_F          { price = 145;  };
	class arifle_CTARS_ghex_F         { price = 145;  };
	class arifle_CTARS_hex_F          { price = 145;  };
	class arifle_SPAR_01_blk_F        { price = 140;  };
	class arifle_SPAR_01_khk_F        { price = 140;  };
	class arifle_SPAR_01_snd_F        { price = 140;  };
	class arifle_SPAR_01_GL_blk_F     { price = 150;  };
	class arifle_SPAR_01_GL_khk_F     { price = 150;  };
	class arifle_SPAR_01_GL_snd_F     { price = 150;  };
	class arifle_SPAR_02_blk_F        { price = 155;  };
	class arifle_SPAR_02_khk_F        { price = 155;  };
	class arifle_SPAR_02_snd_F        { price = 155;  };
	class arifle_SPAR_03_blk_F        { price = 160;  };
	class arifle_SPAR_03_khk_F        { price = 160;  };	
	class arifle_SPAR_03_snd_F        { price = 160;  };					
	class muzzle_snds_H_khk_F         { price = 5;  };
	class muzzle_snds_H_snd_F         { price = 5;  };
	class muzzle_snds_58_blk_F        { price = 2;  };
	class muzzle_snds_m_khk_F         { price = 1;  };
	class muzzle_snds_m_snd_F         { price = 1;  };
	class muzzle_snds_B_khk_F         { price = 5;  };
	class muzzle_snds_B_snd_F         { price = 5;  };
	class muzzle_snds_58_wdm_F        { price = 2;  };
	class muzzle_snds_65_TI_blk_F     { price = 7;  };
	class muzzle_snds_65_TI_hex_F     { price = 7;  };
	class muzzle_snds_65_TI_ghex_F    { price = 7;  };
	class muzzle_snds_H_MG_blk_F      { price = 2;  };
	class muzzle_snds_H_MG_khk_F      { price = 2;  };
	class optic_Arco_blk_F            { price = 10;  };
	class optic_Arco_ghex_F           { price = 10;  };
	class optic_DMS_ghex_F            { price = 15;  };
	class optic_Hamr_khk_F            { price = 20;  };
	class optic_ERCO_blk_F            { price = 12;  };
	class optic_ERCO_khk_F            { price = 12;  };
	class optic_ERCO_snd_F            { price = 12;  };
	class optic_SOS_khk_F             { price = 20;  };
	class optic_LRPS_tna_F            { price = 30;  };
	class optic_LRPS_ghex_F           { price = 30;  };
	class optic_Holosight_blk_F       { price = 5;  };
	class optic_Holosight_khk_F       { price = 5;  };
	class optic_Holosight_smg_blk_F   { price = 5;  };
	class bipod_01_F_khk              { price = 2;  };	
	class 30Rnd_9x21_Mag_SMG_02						{ price = 3;};
	class 30Rnd_9x21_Mag_SMG_02_Tracer_Red          { price = 2;  };
	class 30Rnd_9x21_Mag_SMG_02_Tracer_Yellow       { price = 2;  };
	class 30Rnd_9x21_Mag_SMG_02_Tracer_Green        { price = 2;  };
	class 30Rnd_580x42_Mag_F                        { price = 2;  };
	class 30Rnd_580x42_Mag_Tracer_F                 { price = 2;  };
	class 100Rnd_580x42_Mag_F                       { price = 2;  };
	class 100Rnd_580x42_Mag_Tracer_F                { price = 2;  };
	class 20Rnd_650x39_Cased_Mag_F                  { price = 2;  };
	class 10Rnd_50BW_Mag_F                          { price = 4;  };
	class 150Rnd_556x45_Drum_Mag_F                  { price = 8;  };
	class 150Rnd_556x45_Drum_Mag_Tracer_F           { price = 8;  };
	class 30Rnd_762x39_Mag_F                        { price = 3;  };
	class 30Rnd_762x39_Mag_Green_F                  { price = 3;  };
	class 30Rnd_762x39_Mag_Tracer_F                 { price = 3;  };
	class 30Rnd_762x39_Mag_Tracer_Green_F           { price = 3;  };
	class 30Rnd_545x39_Mag_F                        { price = 2;  };
	class 30Rnd_545x39_Mag_Green_F                  { price = 2;  };
	class 30Rnd_545x39_Mag_Tracer_F                 { price = 2;  };
	class 30Rnd_545x39_Mag_Tracer_Green_F           { price = 2;  };
	class 200Rnd_556x45_Box_F                       { price = 9;  };
	class 200Rnd_556x45_Box_Red_F                   { price = 9;  };
	class 200Rnd_556x45_Box_Tracer_F                { price = 9;  };
	class 200Rnd_556x45_Box_Tracer_Red_F            { price = 9;  };
	class 10Rnd_9x21_Mag							{ price = 2;  };	
	class B_Bergen_mcamo_F                  {  price = 40; };
	class B_Bergen_dgtl_F                   {  price = 40; };
	class B_Bergen_hex_F                    {  price = 40; };
	class B_Bergen_tna_F                    {  price = 40; };
	class B_AssaultPack_tna_F               { price = 10; };
	class B_Carryall_ghex_F                 {  price = 30; };
	class B_FieldPack_ghex_F                {  price = 12; };
	class B_ViperHarness_base_F             { price = 25; };
	class B_ViperHarness_blk_F              { price = 25; };
	class B_ViperHarness_ghex_F             { price = 25; };
	class B_ViperHarness_hex_F              { price = 25; };
	class B_ViperHarness_khk_F              { price = 25; };
	class B_ViperHarness_oli_F              { price = 25; };
	class B_ViperLightHarness_base_F        {  price = 20; };
	class B_ViperLightHarness_blk_F         {  price = 20; };
	class B_ViperLightHarness_ghex_F        {  price = 20; };
	class B_ViperLightHarness_hex_F         {  price = 20; };
	class B_ViperLightHarness_khk_F         {  price = 20; };
	class B_ViperLightHarness_oli_F         {  price = 20; };

**Comment by vbawol** [comment]
@Ghostrider-DbD- Thanks for the contribution!
