### ISSUE TITLE
l85 elcan visible bug

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#678]
when wear full ghillie or big vest or big backpack so can´t not really use elcan optic because the view is to far as the others sight

**Comment by vbawol** [comment]
Hey @baaljayjay ! could you provide a screenshot?

**Comment by baaljayjay** [comment]
![20161210153711_1](https://cloud.githubusercontent.com/assets/16623990/21074030/bd0832fe-beee-11e6-9c9d-d692c96cd55e.jpg)
![20161210153715_1](https://cloud.githubusercontent.com/assets/16623990/21074029/bd080964-beee-11e6-9490-a9416e3581d5.jpg)
![20161210153600_1](https://cloud.githubusercontent.com/assets/16623990/21074033/c8d1ee0e-beee-11e6-94bd-76b8a36fb25b.jpg)
![20161210153604_1](https://cloud.githubusercontent.com/assets/16623990/21074034/c8faa376-beee-11e6-9bb3-2e4aae35f155.jpg)
![20161210153634_1](https://cloud.githubusercontent.com/assets/16623990/21074035/c8fa8a9e-beee-11e6-8222-f030cc9cd141.jpg)
 
so you can see it the problem!

**Comment by vbawol** [comment]
tracking here: https://github.com/EpochModTeam/EpochCore/issues/5
