### ISSUE TITLE
AH F5 delete nomore works

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#679]
F5 nomore kicks you out of the game, but delete function disappears after half a second, so I can't delete anything anymore..

**Comment by vbawol** [comment]
Anyone else having this issue? I tested the changes to Epoch AH F5 action and it worked for me. However, I will double check again next time I am on the dev server.

**Comment by Tarabass999** [comment]
So it was depending on Arma 3 controls. F5 is occupied with team order command.
Since i changed control settings it works for me again..

**Comment by vbawol** [comment]
Thanks for reporting back, will consider this closed for now.
