### ISSUE TITLE
Sorted TraderItems

### ISSUE THREAD

**Issue by Ignatz-HeMan** [EpochModTeam/Epoch#682]
Not a bug, more a proposal.
There should come a new Trader Menu in 0.4, what unfortunately is not implemented yet.
If this will take more time, I could pull my items sorting for the Trader Menu.
It is working for us since a few month without any problems.

![20161211164929_1](https://cloud.githubusercontent.com/assets/6589278/21081214/2d173300-bfc2-11e6-941b-91fb3dd330b8.jpg)
![20161211164934_1](https://cloud.githubusercontent.com/assets/6589278/21081216/2fc48648-bfc2-11e6-8e4f-c6de9d314c3d.jpg)
![20161211164937_1](https://cloud.githubusercontent.com/assets/6589278/21081218/31a5cbc0-bfc2-11e6-9585-871a411e2580.jpg)
![20161211164941_1](https://cloud.githubusercontent.com/assets/6589278/21081221/338f1e5a-bfc2-11e6-8ccd-28880a92eb24.jpg)
![20161211164945_1](https://cloud.githubusercontent.com/assets/6589278/21081222/3515c6de-bfc2-11e6-87b1-f030cbc2852c.jpg)
![20161211164949_1](https://cloud.githubusercontent.com/assets/6589278/21081224/368add60-bfc2-11e6-9db4-adbcb30ffd25.jpg)
![20161211164953_1](https://cloud.githubusercontent.com/assets/6589278/21081225/384d015a-bfc2-11e6-84d5-ac4ced3cb7c8.jpg)
![20161211164956_1](https://cloud.githubusercontent.com/assets/6589278/21081227/39e2e138-bfc2-11e6-854c-31d7f6d818bf.jpg)

**Comment by vbawol** [comment]
@Ignatz-HeMan Looks good! This would be a welcome change.

**Comment by Ignatz-HeMan** [comment]
Okay,  I will sort it a bit and make a Pull

**Comment by raymix** [comment]
That looks great @Ignatz-HeMan 
Yes, the trader menu will take a while due to my stressful work schedule and the fact that my cat broke my monitor, there's no way in hell I'm doing anything on my 21" backup screen apart from some bug fixes. Should get a new monitor after Christmas though.

Thanks for looking after current trader menu, man.
