### ISSUE TITLE
Build 673 traders

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#689]
in build 673 epoch traders don't show items anymore

**Comment by Ignatz-HeMan** [comment]
Oh, that's a change from me. I will have a look at it.
Are you playing on your own Server or on a dev-server?
Have you added the new config cfgitemsort.cfg and added it to the sandbox_config.hpp?

**Comment by Ignatz-HeMan** [comment]
Okay, just installed vanilla Epoch and it works!
There must be a problem in your updated files, I think.
Please doublecheck it and report again!

These files have been changed for the Trader Menu:

epoch.xxxxx\epoch_code\compile\traders\EPOCH_NPCTraderMenuFilter.sqf
epoch.xxxxx\epoch_code\compile\traders\EPOCH_startNPCTraderMenu.sqf
epoch.xxxxx\epoch_config\sandbox_config.hpp
epoch.xxxxx\epoch_config\Configs\CfgItemSort.hpp

**Comment by Tarabass999** [comment]
no i'm playing on own server..
damn.. I apologize cfgitemsort.cfg was not in sandbox_config..
it works fine with that.. thank you

**Comment by Tarabass999** [comment]
The categories at the traders are great btw :) 
Thank you for that
