### ISSUE TITLE
Gear not Saving 

### ISSUE THREAD

**Issue by usgharry** [EpochModTeam/Epoch#692]
Dear Reader,

I recently set up a Epoch server using all the most recent files, the server launches and everything works and players can connect.

However players gear does not save I tested for around 25 mins of looting I then disconnected and its brings me back to the beginning where I pick a gender. This is the same for all players who have tested it.

If anyone has a fix or suggestions please send it this way.

Many Thanks
Harry

**Comment by Ignatz-HeMan** [comment]
Hi Harry,
make sure you have started the redis db and have set the same passwords here:

DB\redis.conf
requirepass **yourpassword**

@epochhive\EpochServer.ini
[Redis]
IP = 127.0.0.1
Port = 6380
DB = 0
Password = **yourpassword**

He-Man
