### ISSUE TITLE
Repack Energy Pack not possible

### ISSUE THREAD

**Issue by Ignatz-HeMan** [EpochModTeam/Epoch#698]
If choose "repack" for Energy packs, "use" is executed.
Checked the codes a bit and it seems it is caused, because it has a config in CfgItemInteractions AND is a magazine with bullet count.
Prio -> Low (I think)

**Comment by vbawol** [comment]
@Ignatz-HeMan Can you confirm that this https://github.com/EpochModTeam/Epoch/commit/40949a09b9862a8820a0f35fffb3107b4d776931 change fixed it?

**Comment by Ignatz-HeMan** [comment]
Will test it tomorrow and give feedback here.

**Comment by Ignatz-HeMan** [comment]
Tested it and it works!
ammo repack -> ok
Crafting -> ok
healing -> ok
Energy (small + large) repack -> ok
Energy (small + large) use -> ok
Energy (small + large) craft -> ok.

Now you could add to the repack code:
player playMove 'AinvPknlMstpSnonWrflDnon_medic0';
player playMove 'AinvPknlMstpSnonWrflDnon_medicEnd'; 	

:))
