### ISSUE TITLE
Snap on tilted Elements incorrect

### ISSUE THREAD

**Issue by Ignatz-HeMan** [EpochModTeam/Epoch#702]
If snapping building elements on tilted elements, the snapping do not work correct.
So it is not possible to place a wall correct on a tilted Floor.
![20170221194717_1](https://cloud.githubusercontent.com/assets/6589278/23179691/10f82e1e-f86f-11e6-805a-cfd744eb36e5.jpg)

**Comment by Ignatz-HeMan** [comment]
Now after working a lot on the Vector Building, I am pretty sure it is nearly not possible to fix this.
The problem is, that vectorup and vectordir rotates on the world-axis and not on the element axis.
I found no solution to recalculate it.
If nobody else has an idea how to handle it, we can close it. But with Vector Building, we can now place the elements very exact in free build.

**Comment by vbawol** [comment]
Should be fixed thanks to this https://github.com/EpochModTeam/Epoch/commit/df8346af2c1fb4101e67ca1eb9f098e1bb335413 commit by @ravmustang
