### ISSUE TITLE
Since Arma 3 1.68 Update - Upgrading any building part causes CTD

### ISSUE THREAD

**Issue by e3drigs** [EpochModTeam/Epoch#710]
As above.

Happening for multiple people using both 32 and 64bit client.

Upgrade menu works ok but when you click the green upgrade icon you get a divide by zero crash.

[Arma3_x64_2017-03-17_22-49-58.txt](https://github.com/EpochModTeam/Epoch/files/852344/Arma3_x64_2017-03-17_22-49-58.txt)

**Comment by Ignatz-HeMan** [comment]
https://epochmod.com/forum/topic/43507-epoch-arma-168-compatible/?do=findComment&comment=288612
These changes fix it

**Comment by vbawol** [comment]
Will try to get this fix out soon.
