### ISSUE TITLE
Since Arma 3 1.68 update Players cannot unlock garage doors

### ISSUE THREAD

**Issue by RJL1100** [EpochModTeam/Epoch#711]
Some players cannot unlock their base garage doors. If you remove and replace the door you can unlock and open the door, however you can't close the door.
The boom gate at Mine will not open as well.

**Comment by vbawol** [comment]
Sounds like simulation is being disabled on some prop objects. Base building objects should not have this issue are you using anything that would disable simulation?

**Comment by RJL1100** [comment]
No, this issue is also occurring in Exile where a player is unable to unlock or open a door that has been crafted or built, so is a Arma 3 update glitch

**Comment by ReDBaroN1** [comment]
enableDynamicSimulation true;

This is new in 1.68 and allows to interact with objects you need to interact with when a player is within 50m
