### ISSUE TITLE
Dynamic Simulation

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#727]
https://community.bistudio.com/wiki/Arma_3_Dynamic_Simulation

- [x] simplify our server monitor fsm by removing our own vehicle simulation handler.
- [x] make sure dynamic simulation is enabled properly on all vehicles and working better than old method.

**Comment by vbawol** [comment]
First test enable on vehicles: https://github.com/EpochModTeam/Epoch/commit/b2354dc5a641e047d546dbdedb0e83bd68737afd

**Comment by vbawol** [comment]
this maybe complete as of this PR: https://github.com/EpochModTeam/Epoch/pull/780

**Comment by ravmustang** [comment]
Config settings added.
https://github.com/EpochModTeam/Epoch/pull/782

**Comment by vbawol** [comment]
Performance seems good, but we wont really know till players get ahold of it so closing this for now.
