### ISSUE TITLE
CfgDisabledCommands

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#728]
https://community.bistudio.com/wiki/CfgDisabledCommands

Way to add extra security by disabling unused commands and enforcing specific syntax usages.

Pros: 
- [x] Can enforce the usage of more secure command syntaxes like global init in createUnit Alternative Syntax.

Cons: 
- [x] Will make it harder to add custom mods and addons as some commands may only work in a certain syntax or not at all.
- [x] Maybe harder to setup and manage for updates that include code from the community.

**Comment by Vampurica** [comment]
I think this could be very useful as long as it is used sparingly. Things like remoteExec and other such "dangerous" commands.
Attempting to remove every command not used be vanilla epoch instead would be pretty detrimental to mod makers.

**Comment by vbawol** [comment]
Ya, this is likely better left up to the server admins that want the extra security. It would just slow down modding as BE filters already do.
