### ISSUE TITLE
MPmissions contain syntax errors

### ISSUE THREAD

**Issue by SirDice** [EpochModTeam/Epoch#746]
Running experimental branch. Tested with epoch.Tanoa map but looking at the sources I suspect all mission files are affected.

Actual error:
` 5:18:50 File mpmissions\__cur_mp.Tanoa\epoch_config\Configs\cfgPricing.hpp, line 4508: '/CfgPricing/revolver01.price': Missing ';' prior '}'
5:18:50 File mpmissions\__cur_mp.Tanoa\epoch_config\Configs\cfgPricing.hpp, line 4509: '/CfgPricing/VG_sawed_off_01.price': Missing ';' prior '}'
5:18:50 File mpmissions\__cur_mp.Tanoa\epoch_config\Configs\cfgPricing.hpp, line 4510: '/CfgPricing/Devastator_01.price': Missing ';' prior '}'
5:18:50 File mpmissions\__cur_mp.Tanoa\epoch_config\Configs\cfgPricing.hpp, line 4511: '/CfgPricing/in005_1Rnd_12Gauge_Pellets.price': Missing ';' prior '}'
5:18:50 File mpmissions\__cur_mp.Tanoa\epoch_config\Configs\cfgPricing.hpp, line 4512: '/CfgPricing/in005_1Rnd_12Gauge_Slug.price': Missing ';' prior '}'
5:18:50 File mpmissions\__cur_mp.Tanoa\epoch_config\Configs\cfgPricing.hpp, line 4513: '/CfgPricing/H_MM_Buzzard_Gasmask_01.price': Missing ';' prior '}'
5:18:50 File mpmissions\__cur_mp.Tanoa\epoch_config\Configs\cfgPricing.hpp, line 4514: '/CfgPricing/H_MM_Helmet_01.price': Missing ';' prior '}'
5:18:50 File mpmissions\__cur_mp.Tanoa\epoch_config\Configs\cfgPricing.hpp, line 4515: '/CfgPricing/V_MM_Vest_01.price': Missing ';' prior '}'

`

Looking at epoch_config\Configs\cfgPricing.hpp, lines 4517 to 4524 are missing a semicolon.

**Comment by vbawol** [comment]
scratch that, the error exists in b749 and I see the issue. This should be fixed as of the most recent experimental release: b754 soon to be released.

**Comment by SirDice** [comment]
Ah. I fixed my server over the weekend. Now I see a commit from yesterday.  But it's still there:
`
  class revolver01                        { price = 55 };
  class VG_sawed_off_01                   { price = 120 };
    class Devastator_01                     { price = 180 };
    class in005_1Rnd_12Gauge_Pellets        { price = 5 };
    class in005_1Rnd_12Gauge_Slug           { price = 5 };
    class H_MM_Buzzard_Gasmask_01           { price = 65 };
    class H_MM_Helmet_01                    { price = 75 };
    class V_MM_Vest_01                      { price = 20 };
`
Grr. Edits fail. Missing some linefeeds here.

**Comment by SirDice** [comment]
According to epoch_config/build.hpp I have build 753. I fixed it for my own server, easy enough.  I'll wait for the update.

**Comment by vbawol** [comment]
Thanks for the report, this has been fixed with this commit: https://github.com/EpochModTeam/Epoch/commit/fe3c4644724268c0f669acdbc07c60d986399464 and is a part of b754:
https://github.com/EpochModTeam/Epoch/commit/3317b8f25dc9dd58b8b38d7d584d04d0cf52f4e0

**Comment by SirDice** [comment]
Yes, that's fixed now.
