### ISSUE TITLE
variable mixup in epoch_server/compile/epoch_missions/EPOCH_Server_createObject.sqf

### ISSUE THREAD

**Issue by SirDice** [EpochModTeam/Epoch#747]
Latest build; 754. Variable mixup in epoch_server/compile/epoch_missions/EPOCH_Server_createObject.sqf lines 25-26:
```
_lootTableIndex = if (EPOCH_modCUPVehiclesEnabled) then {if (EPOCH_mod_madArma_Enabled) then {3} else {1}} else {if (EPOCH_mod_madArma_Enabled) then {2} else {0}};
_allowedVehicleListName = ["allowedVehiclesList","allowedVehiclesList_CUP","allowedVehiclesList_MAD","allowedVehiclesList_MADCUP"] select _allowedVehicleIndex;
```

Line 25 uses _loot_TableIndex but line 26 _allowedVehicleIndex. 
Judging by the code I'm assuming these variables should be the same. It throws an error because _allowedVehicleIndex is unknown.

**Comment by vbawol** [comment]
Thanks @SirDice, just fixed this with https://github.com/EpochModTeam/Epoch/commit/b5584ffbfe3419a71ff048909063118837215c2e
