### ISSUE TITLE
CfgPricing.hpp

### ISSUE THREAD

**Issue by Ghostrider-DbD-** [EpochModTeam/Epoch#750]
The logs show an error for some entries in CfgPricing.hpp like this one:

22:48:41 File mpmissions\__cur_mp.Altis\epoch_config\Configs\cfgPricing.hpp, line 4508: '/CfgPricing/revolver01.price': Missing ';' prior '}'

I think that lines 4516-4524 are missing a semicolon and should be:

    // MAD ARMA
    class revolver01                        { price = 55; };
    class VG_sawed_off_01                   { price = 120; };
    class Devastator_01                     { price = 180; };
    class in005_1Rnd_12Gauge_Pellets        { price = 5; };
    class in005_1Rnd_12Gauge_Slug           { price = 5; };
    class H_MM_Buzzard_Gasmask_01           { price = 65; };
    class H_MM_Helmet_01                    { price = 75; };
    class V_MM_Vest_01                      { price = 20; };

**Comment by vbawol** [comment]
Thanks @Ghostrider-DbD- This is already in the experimental files, just not pushed to stable yet.

**Comment by vbawol** [comment]
fixed as of https://github.com/EpochModTeam/Epoch/releases/tag/0.5.0.0757 release, if not please reopen.
