### ISSUE TITLE
Build 777 Events

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#759]
Wrecked vehicles spawn events also spawn them on airports, what makes it impossible to start/land a plane.

Trash from em can also get examined for unlimited times to get soiled very quick without any loot

**Comment by Tarabass999** [comment]
I saw some wrecked Vehicles and trash also spawn up on trees.

**Comment by vbawol** [comment]
This should be fixed, just needed to tweak the start and stop positions for the surfaceNormal and intersect.
Also, I added a bit of code that should prevent this debris from spawning within 100m of the Airport location.
