### ISSUE TITLE
weapon holding bug (1.72)

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#768]
I have times the weapons tested when I've seen the epoch weapons I'm afraid.
I show the times on pictures.
![20170624124834_1](https://user-images.githubusercontent.com/16623990/27509283-634e9e42-58f9-11e7-8818-45a187dd17e8.jpg)
![20170624124901_1](https://user-images.githubusercontent.com/16623990/27509285-6605b4f4-58f9-11e7-9336-923e345c6f0c.jpg)
![20170624124941_1](https://user-images.githubusercontent.com/16623990/27509287-6b16ce6a-58f9-11e7-84d0-ee297f6a9c2e.jpg)
![20170624124951_1](https://user-images.githubusercontent.com/16623990/27509288-6b34e4f4-58f9-11e7-813f-c83471739386.jpg)
![20170624125000_1](https://user-images.githubusercontent.com/16623990/27509290-6b35f4ac-58f9-11e7-8c3d-deeaf57fb5fc.jpg)
![20170624125007_1](https://user-images.githubusercontent.com/16623990/27509291-6b36d250-58f9-11e7-9f9e-8cc11b9b5aea.jpg)
![20170624125017_1](https://user-images.githubusercontent.com/16623990/27509289-6b35c086-58f9-11e7-871e-17f226f3b2f9.jpg)

(Maybe that could be a new monster)

**Comment by vbawol** [comment]
@baaljayjay is this with stable or experimental Epoch or both?

**Comment by baaljayjay** [comment]
experimental epoch. in stable it work fine.

**Comment by baaljayjay** [comment]
now it work fine!

**Comment by vbawol** [comment]
Thanks, @baaljayjay
