### ISSUE TITLE
kick when i try to built quarter wood floor

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#776]
i try to build quarter wood floor and when i in preview build so battleye kick me.

**Comment by Vampurica** [comment]
Knowing what the message was is important.
Likely a createVehicle kick I'm guessing?

**Comment by vbawol** [comment]
I think I got it with https://github.com/EpochModTeam/Epoch/commit/734dc5d2009af9e091b5a1b6fd015e957c20e6ae

**Comment by baaljayjay** [comment]
nope It has become worse now I can not build a wall, ramp and floor
create vehicle restriction 1

**Comment by ravmustang** [comment]
@baaljayjay 
This has been resolved and waiting for approval.
https://github.com/EpochModTeam/Epoch/pull/802

The combination of all the ghost elements was causing the conflict.
Ghost pieces split up and the wood types in their own != like the sim and epoch ones are done below it.
