### ISSUE TITLE
kick bevor select a gender, BattlEye: Script Restriction #49

### ISSUE THREAD

**Issue by T4ss** [EpochModTeam/Epoch#778]
10.07.2017 14:50:08: Tass (ip.bla.bla) guidblabla - #49 "wnControlsMap_ctrlHeaderRespawnButton", controlNull]) ctrlAddEventhandler ["ButtonDown",{		
["[RESPAWN] Main respawn button used"

temp fix:

https://epochmod.com/forum/topic/43948-fresh-install-battleye-kicks-script-restriction-49/

plz fix in be filters

**Comment by vbawol** [comment]
This should be already fixed in experimental, if not please open another issue.
