### ISSUE TITLE
zeroring the elcan optic

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#779]
The fine tuning of the elcan scope is not right.
500-600 m is 300m
800m is 500m
tested in virtual arsenal

**Comment by vbawol** [comment]
This is the configs for the elcan optics, https://github.com/EpochModTeam/EpochCore/blob/experimental/Sources/a3_epoch_configs/Configs/CfgWeapons.hpp#L5405-L5487 any suggested changes?

**Comment by baaljayjay** [comment]
I think the eye is set too low because I believe the eye is the center point

**Comment by ravmustang** [comment]
Thanks for the info on this one bud.
Took this one under my wing today and I feel I was successful.
Take a look here and give it some more testing
https://github.com/EpochModTeam/EpochCore/pull/36
