### ISSUE TITLE
Losing crafting components

### ISSUE THREAD

**Issue by GeneralTragedy** [EpochModTeam/Epoch#78]
Twice since the last update I've lost crafting materials when crafting because I didn't have enough room in my inventory for the resulting item.  This happened once when trying to turn two empty jars into jars of water (selected "2" because I had 2 empty jars... one completed, the second failed due to space and I lost the empty jar).  Also had this happen when combining vehicle repair parts and scrap metal to make a vehicle repair kit.  Didn't have room for the resulting kit, and lost both crafting components. (Both times I looked all over on the ground, but didn't see the items anywhere so I don't think they dropped...)

**Comment by vbawol** [comment]
0.3.4 should have fixed this, if not please reopen.
