### ISSUE TITLE
missing item for crafting

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#785]
There are missing data in the prescription for vehicle upgrade system and fuel bomb barrel
Either missing or misspelling errors.
It lacks prescription for pipes
Ps for jerrycan times tried a prescription but I did not know how to fill a pull reqeuest #647 

![20170723030041_1](https://user-images.githubusercontent.com/16623990/28495636-60acc5ac-6f55-11e7-8845-e69971a8e88f.jpg)
![20170723030037_1](https://user-images.githubusercontent.com/16623990/28495635-60aaba64-6f55-11e7-8d47-e1dec725f700.jpg)

**Comment by raymix** [comment]
Hey, problem with your item is exactly the same as problem with Vehicle upgrade kits.
The script basically expects you to define items inside recipe[] as kits, items or parts.
If your item is only used as a part to create other items and is not crafted on it's own, you ***MUST*** define it at least as a "part".
See line 90: https://github.com/EpochModTeam/Epoch/blob/experimental/Sources/epoch_config/Configs/cfgCrafting.hpp#L90

For your specific problem - you simply need to define "ItemBarrelE" as a new part below (add new class)

Vehicle upgrade parts has the same problem - need to define: "ItemVehDoc1", "ItemVehDoc2", "ItemVehDoc3", "ItemVehDoc4", "SpareTire" and "ItemPipes" as new parts at the bottom of the config.

As for 3D previews being too big, launch DEV mode, there you can adjust sizes live and export config into RPT log that you can copy/paste over.
Dev mode is enabled on Line 36: https://github.com/EpochModTeam/Epoch/blob/experimental/Sources/epoch_config/Configs/cfgCrafting.hpp#L36

@ravmustang @Ignatz-HeMan

**Comment by raymix** [comment]
```
	class ItemBarrelE: part 
	{
        usedIn[] = {"BarrelBomb_EPOCH_Remote_Mag","BarrelBomb2_EPOCH_Remote_Mag"};
        previewPosition[] = {0.8,1,0.42};
        previewScale = 0.5;
        previewVector = 0;
	};
```

**Comment by raymix** [comment]
Forgot to mention, I will do the commit in few, just wanted to explain
