### ISSUE TITLE
Tons of bone and player mass errors

### ISSUE THREAD

**Issue by raymix** [EpochModTeam/Epoch#786]
Hey folks, what am I missing here? It was working fine yesterday, this morning can't run my server, nothing was changed.
Clean DB, latest experimental files, latest game files.
Just getting black screen (ESC works) and tens of thousands of errors. Google has nothing on them.

I have deleted about 80k lines to keep the log clean - https://pastebin.com/KwU87p2p

It starts with bone errors
```
11:19:39 Error: Bone forehead_l doesn't exist in skeleton OFP2_ManSkeleton
11:19:39 Error: Bone cheek_rb doesn't exist in skeleton OFP2_ManSkeleton
```

and ends up tens of thousands of these errors:
```
11:19:42 "DEBUG: Final Player mass check: FAILED (298 != 302)"
11:19:42 "DEBUG: Pos check: [4088.39,4599.4,0.00419888] == [4088.39,4599.4,-3.38485]"
```

By doing an "educated guess", I think second errors are caused by first error.
Happens on multiple maps.

Any clues?

**Comment by ReDBaroN1** [comment]
It's a known issue, @vbawol is looking into it. We've tried a number of things but, can't solve it.

The only known workaround is to the delete the character in redis from player data

**Comment by raymix** [comment]
Hey ya
I am using fresh database (copied .SO files over from Server_Install_Pack several times), still getting it.
While on the subject, I don't have any frontend tool to access redis, never done it before, what are you using?
***edit***: Did a bit of digging, while I see a lot of people have bone errors, at least they can actually access the server. I am literary stuck at the black screen. This could mean that both errors have nothing to do with each other after all, hmm.
***edit 2***: LMAO I am retarded. Just remembered that .SO files are linux binaries, duh! Deleted redis dump file from .\DB\ folder and I am back in the game now.

**Comment by ReDBaroN1** [comment]
nice 👍

**Comment by vbawol** [comment]
The bone errors do not affect anything that I am aware of. The DEBUG errors are an issue I am trying to fix but it is not easy as it is hard to reproduce that exact issue so far.

**Comment by raymix** [comment]
@vbawol Looks like I still have the corrupt database file (didn't delete it, just moved to recycle bin) if you want to look at it.
Not sure if this will help you or not, but I understand that the error is tied to my steam ID, right?
See if it helps at all.
Map is epoch.Stratis, not sure if relevant.

https://raimonds.me/dump.zip
