### ISSUE TITLE
Bug in some item configs?

### ISSUE THREAD

**Issue by raymix** [EpochModTeam/Epoch#790]
```
21:33:40 Error in expression < = param [0,[0]];
if !(typeName (_arrIn select 0) isEqualTo "CONFIG") exitWith {>
21:33:40   Error position: <select 0) isEqualTo "CONFIG") exitWith {>
21:33:40   Error Generic error in expression
21:33:40 File mpmissions\__CUR_MP.VR\epoch_code\gui\scripts\craftingv2\EPOCH_crafting_getConfig.sqf, line 21
21:33:40 Error in expression < = param [0,[0]];
if !(typeName (_arrIn select 0) isEqualTo "CONFIG") exitWith {>
21:33:40   Error position: <select 0) isEqualTo "CONFIG") exitWith {>
21:33:40   Error Generic error in expression
21:33:40 File mpmissions\__CUR_MP.VR\epoch_code\gui\scripts\craftingv2\EPOCH_crafting_getConfig.sqf, line 21
```
This only happens to few items, but affects other items up in cfgCrafting hierarchy, too. Looks like configs for these items are either incomplete or have errors.

**Errors on following items:**
KitVehicleUpgradeII_100_EPOCH
KitVehicleUpgradeII_200_EPOCH
KitVehicleUpgradeII_300_EPOCH
KitVehicleUpgradeIII_100_EPOCH
KitVehicleUpgradeIII_200_EPOCH
KitVehicleUpgradeIII_300_EPOCH
ItemVehDoc1
ItemVehDoc2
ItemVehDoc3
ItemVehDoc4
SpareTire

***Affects:***
Tank Trap
Shelf Kit
ItemAluminumBar10oz
Burlap
Metal Scraps
Wire Cables
Electronic components
Jerry can

***Other:***
 displayName for all kit upgrade tiers (mass) needs to be updated, it's the same for multiple items

**Comment by raymix** [comment]
```
21:42:17 Error in expression < (_x >> "descriptionShort")} else {_arr select 2};
_cModel = if (isText (_x >> ">
21:42:17   Error position: <select 2};
_cModel = if (isText (_x >> ">
21:42:17   Error Zero divisor
21:42:17 File mpmissions\__CUR_MP.VR\epoch_code\gui\scripts\craftingv2\EPOCH_crafting_getConfig.sqf, line 32
21:42:17 Error in expression <en {getText (_x >> "model")} else {_arr select 3};


_cPriority = getNumber (_x >
21:42:17   Error position: <select 3};


_cPriority = getNumber (_x >
21:42:17   Error Zero divisor
21:42:17 File mpmissions\__CUR_MP.VR\epoch_code\gui\scripts\craftingv2\EPOCH_crafting_getConfig.sqf, line 33
21:42:17 Error in expression <select 1),_x select 1];
_ingredientCTRL lbSetPictureRight [_idx,(_data select 2)>
21:42:17   Error position: <lbSetPictureRight [_idx,(_data select 2)>
21:42:17   Error Type Any, expected String
21:42:17 File mpmissions\__CUR_MP.VR\epoch_code\gui\scripts\craftingv2\EPOCH_crafting_LB_click.sqf, line 42
```

**Errors on following items:**
KitVehicleUpgradeIII_100_EPOCH
KitVehicleUpgradeIII_200_EPOCH
KitVehicleUpgradeIII_300_EPOCH

**Comment by raymix** [comment]
Full Briefcase (Silver) - ***CRASHES GAME!***

```
21:47:02 Warning Message: Shape \x\addons\a3_epoch_community\models\briefcase_brown.p3d not found
21:47:02 Warning Message: Cannot open object x\addons\a3_epoch_community\models\briefcase_brown.p3d
```

**Comment by raymix** [comment]
@ravmustang @Ignatz-HeMan  any clues, guys?
Are these items ported from Arma 2 Dayz? Must be missing something.
As for briefcase, I think this is an old issue that was never reported and fixed.

**Comment by ravmustang** [comment]
@raymix hey bud, no problem let's work this out.
Are these errors while doing the crafting of the kits?

**Comment by raymix** [comment]
@ravmustang 
Actually as soon as you open crafting menu and every time you click affected items.
![image](https://user-images.githubusercontent.com/7531643/28545425-d88efba2-70be-11e7-98ba-5b6bb3314e86.png)

**Comment by ravmustang** [comment]
roger that, im starting up my test instance.
will make right what is wrong as soon as possible

**Comment by raymix** [comment]
Thanks man. Please don't forget to grab latest CfgCrafting.hpp from experimental branch otherwise you'll run into issues that were fixed and were not related to this :)

**Comment by ravmustang** [comment]
was just looking at the commit now ;)

**Comment by raymix** [comment]
Hmm
Not sure if relevant to the issue, but I can't seem to find "Vehicle Upgrade X Kits" under admin menu.
Is this because they are not defined as items?
Although I do not get any errors while clicking them. Only getting errors when clicking on items that are using "Vehicle Upgrade X kit".
I have a wild suspicion that these kits need to be defined elsewhere, similar to how documents were added.

![image](https://user-images.githubusercontent.com/7531643/28546113-723879ca-70c1-11e7-9726-7d44f51f28e4.png)

**Comment by ravmustang** [comment]
Those new kits are in configs on EPOCH experimental branch.
https://github.com/EpochModTeam/EpochCore/pull/22

**Comment by ravmustang** [comment]
First error is with ItemPipes, looks like a descriptionShort issue. Will investigate further.

```
17:32:34 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/ItemPipes"
17:32:34 Error in expression < (_x >> "descriptionShort")} else {_arr select 2};
_cModel = if (isText (_x >> ">
17:32:34   Error position: <select 2};
_cModel = if (isText (_x >> ">
17:32:34   Error Zero divisor
17:32:34 File mpmissions\__CUR_MP.Altis\epoch_code\gui\scripts\craftingv2\EPOCH_crafting_getConfig.sqf, line 32
```

Second error is with ItemBarrelE
```
17:32:34 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/ItemBarrelE"
17:32:34 Error in expression <CTRL lbAdd (_x select 1)
};
_recipeCTRL lbSetPictureRight [_idx,(_x select 2)];
>
17:32:34   Error position: <lbSetPictureRight [_idx,(_x select 2)];
>
17:32:34   Error Type Any, expected String
17:32:34 File mpmissions\__CUR_MP.Altis\epoch_code\gui\scripts\craftingv2\EPOCH_crafting_LB_defaults.sqf, line 34
```

**Comment by ravmustang** [comment]
First error fix
ItemPipes is actually ItemPipe.

https://github.com/EpochModTeam/Epoch/pull/791

**Comment by ravmustang** [comment]
Fixed ItemPipe in the cfgCrafting menu and now we are left with a couple of errors only.
This is only opening the menu first and trying to remove the errors present here.
If you look closely it repeats itself from CSGAS forward for 5 entries and throws those 2 errors that should only trip upon calling the function, not after the loop has started...

```
19:18:16 Error in expression < = param [0,[0]];
if !(typeName (_arrIn select 0) isEqualTo "CONFIG") exitWith {>
19:18:16   Error position: <select 0) isEqualTo "CONFIG") exitWith {>
19:18:16   Error Generic error in expression
19:18:16 File mpmissions\__CUR_MP.Altis\epoch_code\gui\scripts\craftingv2\EPOCH_crafting_getConfig.sqf, line 21
```

EDIT:
This error IMHO is not related to anything in the CfgCrafting.hpp.

**Comment by raymix** [comment]
It's not, no. I think it's more to do with actual item configs - cfgMagazines or whatever is used, can't lookup now.

**Comment by ravmustang** [comment]
Ive done a thorough debug of the getConfig and this is the end result.
On opening of crafting menu only, no clicking on menu done yet.
No errors for any of the pulled info until it duplicates its search for 5 items.
This is the output

```
19:48:32 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/ItemBarrelE"
19:48:32 "[expochDebug]crafting_getConfig - _arrIn:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/CSGAS"
19:48:32 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/CSGAS"
19:48:32 "[expochDebug]crafting_getConfig - _arrIn:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/KitVehicleUpgradeIV_100_EPOCH"
19:48:32 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/KitVehicleUpgradeIV_100_EPOCH"
19:48:32 "[expochDebug]crafting_getConfig - _arrIn:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/KitVehicleUpgradeIV_200_EPOCH"
19:48:32 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/KitVehicleUpgradeIV_200_EPOCH"
19:48:32 Error in expression <rrIn:%1",_arrIn];
if !(typeName (_arrIn select 0) isEqualTo "CONFIG") exitWith {>
19:48:32   Error position: <select 0) isEqualTo "CONFIG") exitWith {>
19:48:32   Error Generic error in expression
19:48:32 File mpmissions\__CUR_MP.Altis\epoch_code\gui\scripts\craftingv2\EPOCH_crafting_getConfig.sqf, line 22
19:48:32 "[expochDebug]crafting_getConfig - _arrIn:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/KitVehicleUpgradeIV_300_EPOCH"
19:48:32 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/KitVehicleUpgradeIV_300_EPOCH"
19:48:32 Error in expression <rrIn:%1",_arrIn];
if !(typeName (_arrIn select 0) isEqualTo "CONFIG") exitWith {>
19:48:32   Error position: <select 0) isEqualTo "CONFIG") exitWith {>
19:48:32   Error Generic error in expression
19:48:32 File mpmissions\__CUR_MP.Altis\epoch_code\gui\scripts\craftingv2\EPOCH_crafting_getConfig.sqf, line 22
19:48:32 "[expochDebug]crafting_getConfig - _arrIn:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/BarrelBomb_EPOCH_Remote_Mag"
19:48:32 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/BarrelBomb_EPOCH_Remote_Mag"
19:48:32 "[expochDebug]crafting_getConfig - _arrIn:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/BarrelBomb2_EPOCH_Remote_Mag"
19:48:32 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/BarrelBomb2_EPOCH_Remote_Mag"
```

**Comment by raymix** [comment]
I'll try to debug EPOCH_crafting_getConfig in the morning, see what arguments it is not happy about. Looks like it has issues pulling something from config for those few items.
Thanks for the log, nice job

**Comment by ravmustang** [comment]
I have traced it back to the config_load function.
FYI, My logs show that the errors are happening after the menu loads and then it does its search for the items that can be built with the item you selected in inventory > craft

**Comment by ravmustang** [comment]
```19:56:55 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/ItemVehDoc3"
19:56:55 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/ItemVehDoc4"
19:56:55 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/SpareTire"
19:56:55 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/ItemPipe"
19:56:55 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/BarrelBomb_EPOCH_Remote_Mag"
19:56:55 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/BarrelBomb2_EPOCH_Remote_Mag"
19:56:55 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/ItemBarrelE"
19:56:56 "[expochDebug]crafting_getConfig - _arrIn:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/CSGAS"
19:56:56 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/CSGAS"
19:56:56 "[expochDebug]crafting_getConfig - _arrIn:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/KitVehicleUpgradeIV_100_EPOCH"
19:56:56 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/KitVehicleUpgradeIV_100_EPOCH"
19:56:56 "[expochDebug]crafting_getConfig - _arrIn:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/KitVehicleUpgradeIV_200_EPOCH"
19:56:56 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/KitVehicleUpgradeIV_200_EPOCH"
19:56:56 Error in expression <rrIn:%1",_arrIn];
if !(typeName (_arrIn select 0) isEqualTo "CONFIG") exitWith {>
19:56:56   Error position: <select 0) isEqualTo "CONFIG") exitWith {>
19:56:56   Error Generic error in expression
19:56:56 File mpmissions\__CUR_MP.Altis\epoch_code\gui\scripts\craftingv2\EPOCH_crafting_getConfig.sqf, line 22
19:56:56 "[expochDebug]crafting_getConfig - _arrIn:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/KitVehicleUpgradeIV_300_EPOCH"
19:56:56 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/KitVehicleUpgradeIV_300_EPOCH"
19:56:56 Error in expression <rrIn:%1",_arrIn];
if !(typeName (_arrIn select 0) isEqualTo "CONFIG") exitWith {>
19:56:56   Error position: <select 0) isEqualTo "CONFIG") exitWith {>
19:56:56   Error Generic error in expression
19:56:56 File mpmissions\__CUR_MP.Altis\epoch_code\gui\scripts\craftingv2\EPOCH_crafting_getConfig.sqf, line 22
19:56:56 "[expochDebug]crafting_getConfig - _arrIn:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/BarrelBomb_EPOCH_Remote_Mag"
19:56:56 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/BarrelBomb_EPOCH_Remote_Mag"
19:56:56 "[expochDebug]crafting_getConfig - _arrIn:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/BarrelBomb2_EPOCH_Remote_Mag"
19:56:56 "[expochDebug]crafting_getConfig - _this:mpmissions\__CUR_MP.Altis\description.ext/CfgCrafting/BarrelBomb2_EPOCH_Remote_Mag"
```

Notice the constant _this.
That shows me its in the loop from the original _recipeConfigs sent from crafting_load.
Then its doing its search for what it can craft into...
More searching to be done, I will continue on

**Comment by raymix** [comment]
lol I figured it out... you were spot on about those 2. Looks like there's either a bug or limitation. I remembered that to be able to read inherited data you have to use [configProperties ](https://community.bistudio.com/wiki/configProperties)command, where a similar [configClasses ](https://community.bistudio.com/wiki/configClasses)command would fail in similar fashion.

Fix - don't inherit from existing items, define them all as individual kits.

**Comment by raymix** [comment]
Thanks for help @ravmustang!

**Comment by ravmustang** [comment]
I have produced an error free opening up of the crafting menu.
Modification used:
EPOCH_crafting_getConfig.sqf
Remove _arrIn = params[0,[0]];
Added _arrIn = _this; and a debug line of code.

```
_arrIn = _this;
diag_log format["[expochDebug]crafting_getConfig - _arrIn:%1",_arrIn];
if !(typeName (_arrIn select 0) isEqualTo "CONFIG") exitWith {[]};

_type0 = []; _type1 = []; _type2 = []; _type3 = []; _out = [];
```

**Comment by ravmustang** [comment]
I have no errors popping and still have the inherited crafting configs.
I have tested the issue was the use of params[0,[0]];
As soon as the erroneous data trying to be looped was removed we have no issues.
Please look this over in the morning.
THX

**Comment by raymix** [comment]
If you look below, you can see that _this is used with forEach command already. The reason we use **param** command is to try to avoid wrong input params .. which could also cause errors.

But that seems to break convenience of having inherits. I like your fix better to be honest.
Would you like to proceed with the pull request?

**Comment by ravmustang** [comment]
That will be fine sir!
Thank you for your time and energy through this as well.
I will do several more tests in the morning to confirm my tests from last night.
