### ISSUE TITLE
briefcase_brown.p3d CTD during crafting

### ISSUE THREAD

**Issue by raymix** [EpochModTeam/Epoch#792]
Hi @vbawol 

Sorry if I am missing something and this has already been resolved.
There's an error message with **briefcase_brown.p3d** coming from **CfgMagazines.hpp line 389** which causes game to CTD.
I have checked **EpochCore\Sources\a3_epoch_community\models** and can verify the source file exists.
However it does not exist in a .PBO file, please see below:
![image](https://user-images.githubusercontent.com/7531643/28553426-7533f8fa-70eb-11e7-939e-3851de24fb37.png)

Is this intended?

**Comment by vbawol** [comment]
Oh my fault, I did not repack that pbo yet. Will get it pushed here soon.

**Comment by ravmustang** [comment]
LOL I just realized why as well guys!
Community PBO to the rescue

This will clear up any issues with the 100ozSilver Briefcase and the Top Secret Document.
VBAWOL please push the Languages PBO as well, I saw an error for the stringtable.xml dealing with the top secret document as well

**Comment by vbawol** [comment]
All pbo's repacked and pushed to experimental

**Comment by raymix** [comment]
Thanks buddy!

**Comment by ravmustang** [comment]
Super fast! Gonna call you flash from now on ;)
