### ISSUE TITLE
Radiation

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#796]
TODO:
- [x] Out of bounds detection adding radiation
- [x] Geiger counter sounds 
- [x] play Geiger sounds based on rad level.
- [x] Screen effect when taking radiation damage, see: [Epoch_setRadiation](https://github.com/EpochModTeam/Epoch/blob/e16ee710ae7cd909fa4f9b1eae569a182e8cc10d/Sources/epoch_code/gui/scripts/post_process/Epoch_setRadiation.sqf ) 
- [ ] Digital Geiger Counter HUD
- [x] Geiger Counter functionality (distance and intensity)
- [x] Ambient Radiation zone config 
- [x] Event to find nearby radioactive objects - (using markers for now)
- [ ] Radiation sickness management system (see wiki)
- [x] Radiation Treatment: Alcohol - absorb radiation by small amount (additive)
- [x] Radiation Treatment: Tin canned foods - increases radiation by small amount (additive)

**Comment by vbawol** [comment]
see #846

**Comment by baaljayjay** [comment]
I actually wanted to start a medi issue but maybe a part here purely I have times with blender tablet models of other medicine junk.
I think you can use it.

https://drive.google.com/file/d/0B2PXTFaiSMInZVA3M0pTbGU0X0U/view?usp=sharing

**Comment by vbawol** [comment]
The basic functionality of this feature should be mostly complete, 
- [ ] Add a way to activate the Geiger Hud.
- [ ] Geiger should have an option mute sound and just use radiation gauge via on-screen hud.

**Comment by vbawol** [comment]
tracking last few things here: https://github.com/EpochModTeam/Epoch/issues/919
