### ISSUE TITLE
New Food/Plant Items:

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#797]
"Seed" magazine items for #798 :
- [ ] Poppy
- [ ] Goldenseal
- [ ] Pumpkin
- [ ] Hemp

We could also add:
- [ ] Sunflower Seeds (Food)
- [ ] Hot Axe Brand "Hot Sauce" http://thefreezer.co.uk/EpochMod/hotaxesco.jpg
- [ ] 100 Krypto "Candy Bar" (Snooters reskin?) http://i.imgur.com/yQJlqps.png
- [ ] Sub Zero Ice Cream (Freeze Dry)
- [ ] Gyro Wrap (Freeze Dry)
- [ ] Burger (Red Burger / Blue King) (Freeze Dry)

**Comment by baaljayjay** [comment]
Could one also paste rotten food? For example on inflated cans one gets ill blurred vision like alcohol and loses to hunger and thirst because one vomits
Milk the goat milk (needs empty jar) and mix with milk powder with water

**Comment by vbawol** [comment]
this is it for 1.0, we can always add more in future updates. see #846
