### ISSUE TITLE
Farming

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#798]
Persist the growing states just by treating it as an insecure storage device. It would be one single object with visible weapon holders (similar to our loot objects). The server could check these gardens and exchange the seeds for the more mature items.

Needed Changes:
- [Rejected] Speed of growth based on a factor of https://community.bistudio.com/wiki/accTime
- [x] Craft a harvested plant item into seeds, these seeds are placed into the cargo space of the garden.
- [x] Slow loop on the server side control the state of all gardens by swapping out the seed after X time with the mature item.
- [x] Prevent other unwanted items from being placed inside plot with put handler.

For Trees like Apple, Pecans, etc. we could maybe have a single tree object that once mature would have weaponholders to see the fruit as it was grown (i.e. generate apples periodically).

Ref to: https://github.com/EpochModTeam/Epoch/issues/609

**Comment by vbawol** [comment]
Models:
see Farm Plot #846

**Comment by vbawol** [comment]
Optional: 
For Trees like Apple, Pecans, etc. we could have a single tree object that once mature would have weaponholders to see the fruit grown on the tree (i.e. generate apples periodically).

**Comment by andgregor** [comment]
Could we have a separate process that ripens the harvest via database values, taking the work away from the game server ? Plants are then only updated to their current state as a player moves within range.

**Comment by vbawol** [comment]
Sure, we could have more realistic stages. 

I was just thinking one would simply plant a seed in the farm plot and have the server track it from the last save.  Farms would then be pushed to an array (EPOCH_FARMS) added via the storage save code. 
This array could then be used via the existing event loop server side checking for plots that have seeds and have not been saved within x minutes.  So, If the soil is undisturbed for say 45 minutes it grows to a mature item. Also, as with other storage devices if a farm is left unattended for too long the object and contents will expire.

We could change to immature items for the different states or just jump to fully mature. I guess it all depends on how realistic we want it to be.
