### ISSUE TITLE
Flip motorcycle => dead

### ISSUE THREAD

**Issue by Nasdero** [EpochModTeam/Epoch#80]
Hey guys,

I had an accident with the motorcycle, after that, the motorcycle was upside down, I used the option to flip it, I died and the vehicle was heavily damaged.

Regards,
Nasdero

**Comment by vbawol** [comment]
This code is the main mod not the gamemode and maybe solvable, with a workaround to the flip vehicle code.

The current code is:
https://github.com/EpochModTeam/EpochCore/blob/9e91ecb65d46d81a9af51c3f5d339bfd30d90156/Sources/a3_epoch_configs/Configs/CfgVehicles.hpp#L4001

tracking here: https://github.com/EpochModTeam/EpochCore/issues/5
