### ISSUE TITLE
battleye kick´s

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#806]
When i do nothing so kick battleye me  (Battleye: Script restriction 1).
battleye kick me when i open the inventory (Battleye: Script restriction 43) and when i press 1 so kick me 
(Battleye: Script restriction 6, probably it's at the Favorites Bar).

Best Regards
jayjay

**Comment by raymix** [comment]
Hi jayjay
Thanks for reporting this. Favbar has been developed without filters to avoid hindering progress and has been patched quite a bit lately. Once we can confirm it's in a good shape, we can go on and set up filters for it. Although I am not good with filters (been years), so I will gladly accept any help with them :)

**Comment by vbawol** [comment]
I will see if I can find some time to sort these filters out here soon.

**Comment by ravmustang** [comment]
Hey guys I gotcha covered since this new feature is going to be just WOW!
So this morning I have gotten us to the next stage of eXperimental testing of @raymix FavBar!

https://github.com/EpochModTeam/Epoch/pull/811

@baaljayjay 
The above was merged today, please continue testing the fav bar! THX for your reports!

**Comment by baaljayjay** [comment]
it works.
But for that a new problem has found namely when one builds and physik gains so component falls down or collitates with other component and moves. battleye kick me.
(Battleye: create vehicle restriction 1)

**Comment by ravmustang** [comment]
Any chance you could recreate and post the full log of that kick. I believe I mentioned an example in another one of your issues posts :)
It will be in your create vehicle.log in the battleye folder with the filters

**Comment by ravmustang** [comment]
@baaljayjay 
Kicks for simulated physx objects falling down when built have been fixed.
Tested with Large Wall and Wood Floor and Wood Stairs.
I do encourage more testing! thanks for your report!
https://github.com/EpochModTeam/Epoch/pull/815

**Comment by vbawol** [comment]
Looks like @ravmustang  has this handled 👍 
```
these are the most recent CreateVehicle logs just in case: 
04.08.2017 14:51:15: jayjay (x.x.156.150:2304) bfe9133191466d2567776402eae70512 - #1 "WoodRamp_SIM_EPOCH" 3:37 [8085,9091,34]
04.08.2017 14:53:03: jayjay (x.x.156.150:2304) bfe9133191466d2567776402eae70512 - #1 "WoodLargeWall_SIM_EPOCH" 4:14 [8089,9079,35]
04.08.2017 15:35:24: jayjay (x.x.156.150:2304) bfe9133191466d2567776402eae70512 - #1 "WoodQuarterFloor_SIM_EPOCH" 6:8 [8096,9088,41]
```
