### ISSUE TITLE
I can access to locked Quad inventory

### ISSUE THREAD

**Issue by arjona00** [EpochModTeam/Epoch#81]
Arma 3 1.32.127795
Epochmod 0.2.0.1
Official CPC Hardcore Server 

When I approached to my Quad, I pressed "I" to access to the main menu (lock, unlock, inspect, etc), but it didnt appear,  and I could see the inventory inside.

I probed it two or three times with the same result, but after that, main menu became. 

It occurred one or two times

**Comment by vbawol** [comment]
fixed in next build
