### ISSUE TITLE
Description.ext:  add showHUD[] = ...

### ISSUE THREAD

**Issue by Ghostrider-DbD-** [EpochModTeam/Epoch#822]
One of the quirks of v0.5.0 and below has been that certain number keys open the command menu.
This can be suppressed by setting that parameter in description.ext.
Doing so opens up additional possibilities for key mapping those numeric keys.
A link for this parameter definition is: https://community.bistudio.com/wiki/Description.ext#showHUD
An example I have started using on our server is shown below:
showHUD[] =
{
    true,   // Scripted HUD (same as showHUD command)
    true,   // Vehicle + soldier info
    true,   // Vehicle radar
    true,   // Vehicle compass
    true,   // Tank direction indicator
    false,  // Commanding menu
    false,  // Group Bar
    true,   // HUD Weapon Cursors
    false   // Squad Radar
};

**Comment by vbawol** [comment]
Thanks @Ghostrider-DbD- !
