### ISSUE TITLE
Vehicle Damage On Spawn

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#824]
Might be going mad but I noticed that none of the spawned vehicles were actually being damaged despite the code looking okay. I altered line 66 of EPOCH_spawn_vehicle from:

			_vehObj setHitIndex [_forEachIndex,random(_maxDamage)];

to:

			_vehObj setHitIndex [_forEachIndex,((random 1 max 0.1) min _maxDamage)];

and that seemed to do the trick...

I can add this to Experimental if other people see that it was not working before... pretty sure I am not going mad though?

Cheers,
Grahame (from EpochMod.com forums)

**Comment by vbawol** [comment]
Thanks! got this merged.

**Comment by morgoth0** [comment]
Actually I was somewhat going mad. The original code in EPOCH_spawn_vehicle.sqf is fine (I thought it was). On further testing the vehicles are **spawned** with damage. The issue is that the damage is not applied in EPOCH_load)vehicles.sqf because at the time that the damage is applied, the vehicle has allowdamage false on it. 

The solution is to back out the change I suggested and change lines 172-186 from:
						_vehicle setDamage _damage;
						_allHitpoints = getAllHitPointsDamage _vehicle;
						_hitpoints = _arr select 3;
						if !(_allHitpoints isEqualTo []) then{
							_actualHitpoints = _allHitpoints select 0;
							if ((count _actualHitpoints) == (count _hitpoints)) then{
								{
									_dmg = _hitpoints param [_forEachIndex,0];
									if (_x in ["HitFuel", "HitEngine"]) then {
										_dmg = _dmg min 0.9;
									};
									_vehicle setHitIndex [_forEachIndex, _dmg];
								} forEach _actualHitpoints;
							};
						};
to:
						// set damage and hitpoints
						_vehicle allowDamage true;
						_vehicle setDamage _damage;
						_allHitpoints = getAllHitPointsDamage _vehicle;
						_hitpoints = _arr select 3;
						if !(_allHitpoints isEqualTo []) then{
							_actualHitpoints = _allHitpoints select 0;
							if ((count _actualHitpoints) == (count _hitpoints)) then{
								{
									_dmg = _hitpoints param [_forEachIndex,0];
									if (_x in ["HitFuel", "HitEngine"]) then {
										_dmg = _dmg min 0.9;
									};
									_vehicle setHitIndex [_forEachIndex, _dmg];
								} forEach _actualHitpoints;
							};
						};
						_vehicle allowDamage false;

I have tested this and the vehicles are loaded with damage applied on the second restart after a DB wipe. They were not prior to this code change.

Cheers again,
Grahame.

**Comment by vbawol** [comment]
Funny as the wiki states "The command does not prevent object from taking scripted damage such as setHit, setHitIndex..." https://community.bistudio.com/wiki/allowDamage

**Comment by morgoth0** [comment]
Agreed, but I tested it properly this time. I was actually pointed at the problem/solution from the second note on this: https://community.bistudio.com/wiki/setHitPointDamage

**Comment by vbawol** [comment]
True but we are not using setHitPointDamage but setHitIndex. I will simply move the setdamage and setHitIndex calls above the allowdamage false, that should get it.

**Comment by morgoth0** [comment]
Yep, that would work. I sort of assumed that if one was "broke" (setHitIndex) then the other would be too - since the note was added in 2016 and the original docs in 2013...

**Comment by vbawol** [comment]
https://github.com/EpochModTeam/Epoch/commit/94c5fee87779eed4cc4130c3c08e17aafa045826
