### ISSUE TITLE
Vehicle Damage on Spawn - Corrected...

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#825]
Re: Issue 824

Actually I was somewhat going mad. The original code in EPOCH_spawn_vehicle.sqf is fine (I thought it was). On further testing the vehicles are spawned with damage. The issue is that the damage is not applied in EPOCH_load_vehicles.sqf because at the time that the damage is applied, the vehicle has allowdamage false on it.

The solution is to back out the change I suggested and change lines 172-186 of EPOCH_load_vehicles.sqf from:
_vehicle setDamage _damage;
_allHitpoints = getAllHitPointsDamage _vehicle;
_hitpoints = _arr select 3;
if !(_allHitpoints isEqualTo []) then{
_actualHitpoints = _allHitpoints select 0;
if ((count _actualHitpoints) == (count _hitpoints)) then{
{
_dmg = _hitpoints param [_forEachIndex,0];
if (_x in ["HitFuel", "HitEngine"]) then {
_dmg = _dmg min 0.9;
};
_vehicle setHitIndex [_forEachIndex, _dmg];
} forEach _actualHitpoints;
};
};

to:

// set damage and hitpoints
_vehicle allowDamage true;
_vehicle setDamage _damage;
_allHitpoints = getAllHitPointsDamage _vehicle;
_hitpoints = _arr select 3;
if !(_allHitpoints isEqualTo []) then{
_actualHitpoints = _allHitpoints select 0;
if ((count _actualHitpoints) == (count _hitpoints)) then{
{
_dmg = _hitpoints param [_forEachIndex,0];
if (_x in ["HitFuel", "HitEngine"]) then {
_dmg = _dmg min 0.9;
};
_vehicle setHitIndex [_forEachIndex, _dmg];
} forEach _actualHitpoints;
};
};
_vehicle allowDamage false;

I have tested this and the vehicles are loaded with damage applied on the second restart after a DB wipe. They were not prior to this code change.

Cheers again,
Grahame.

**Comment by vbawol** [comment]
this should have fixed it: https://github.com/EpochModTeam/Epoch/blob/experimental/Sources/epoch_server/compile/epoch_vehicle/EPOCH_spawn_vehicle.sqf#L29-L38 if not please reopen
