### ISSUE TITLE
Tents - buildable, deployable and temp storage

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#829]
So, since I basically was told that everything I was thinking about for Epoch 1.0 was already covered, I thought I would make sure there were issues raised to ensure that they were. 

The first is a deployable tent (A-frame and Ridge) that would act as temporary storage in the same way that Tipis and Lockboxes do. Would need a packed model for each so that they can be found as loot or crafted (but that side of things *is* beyond my abilities, I don't know graphics or 3D modeling) but the CfgVehicles additions for the tents themselves would be:

    class TentA_EPOCH : Buildable_Storage
    {
        author = "whoever";
        scope = 2;
        model = "\A3\Structures\Civ\Camping\TentA_F.p3d";
        displayName = "$STR_EPOCH_TentA";
        maximumLoad = 800;
    };
    class TentDome_EPOCH : Buildable_Storage
    {
        author = "whoever";
        scope = 2;
        model = "\A3\Structures\Civ\Camping\TentDome_F.p3d";
        displayName = "$STR_EPOCH_TentDome";
        maximumLoad = 1200;
    };

Additions to the stringtable for these items would be: 

	<Key ID="STR_EPOCH_TentA">
            <Original>A small one-person tent</Original>
        </Key>
	<Key ID="STR_EPOCH_TentDome">
            <Original>A spacious camping tent</Original>
        </Key>

Cheers,
Grahame.

**Comment by morgoth0** [comment]
And oops... this really should be an issue on EpochCore... my apologies... opening there. Please close this one...

**Comment by vbawol** [comment]
Added, just need a packed tent magazine item and to setup the crafting + kit
@Helion4 could you add a packed tent model as the magazine item for these? see #846
