### ISSUE TITLE
Pumpkin missing from CfgPricing.hpp

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#837]
Just a small one. The pumpkin is missing from CfgPricing.hpp which causes the looting of pumpkin patches to not actually generate one.

Cheers,
Grahame.

**Comment by vbawol** [comment]
Got it sorted with this commit https://github.com/EpochModTeam/Epoch/commit/9028cec8df6eb94c126c54a1dd6cc14ed4e9665d, Pumpkin, Poppy and Goldenseal added to CfgPricing, 

Thanks for the heads up!
