### ISSUE TITLE
Launched in to air when exiting "Camo Assult Boat" please add auto deployable parachute

### ISSUE THREAD

**Issue by LaggedToDeath** [EpochModTeam/Epoch#85]
Got killed by scriptkiddy on vert01 when I got out of assault boat was launched  up in the air, I logged with the hope is was like arma2 ie place me on the ground, but I was still in the air and fell to my death when I logged back in.

Got back to body ant it was missing wetsuit and rebreather, coun't get any thin off body as it was under water at night time, and couldn't see body to get what gear was left ={

So please Add auto deployable parachute, if only to mess with the scriptkiddy's Fun.

P.S Lost a lot of gear Again.

**Comment by vbawol** [comment]
Arma bug, please make a issue here if this still happens https://feedback.arma3.com/view_all_bug_page.php
