### ISSUE TITLE
Plot Pole size

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#863]
Is there any chance that the size of the Plot Pole could be reduced so that it would fit inside a 1x1x1 wall/floor cube? At the moment the Plot Pole is just over 1.5 cinder/wooden walls high. In order to fully enclose it you have to build two full walls on top of each other and cannot actually put a roof on the space from the ground (you have to build stairs since the PGUP move stops before it reaches the top of the second full wall section. If the plot pole was reduced in size (proportionally, not talking about a new model or look for it) then it would be a lot more convenient to enclose it within a smaller base.

Hopefully this would not be a lot of work but if it is then don't worry about it for now.

Cheers,
Grahame.

**Comment by Ignatz-HeMan** [comment]
Added within EpochMod 1.3.1.0

Upgradeable PlotPoles (S/M/L/XL/XXL) with different Range / Limits
https://plays.tv/video/5c9925a6770ac037e4
