### ISSUE TITLE
Some config file updates

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#864]
Hi folks,
   Hopefully these will be useful. Below please find the CfgItemInteractions.hpp entries for some of the new food and drink (including canteens and bottled water and excepting the rice, cereal and powdered milk - not sure whether you have ideas for crafting anything new from them), a change to the CfgBaseBuilding entries for tents to return a kit on deconstruction and the CfgCrafting entries for bottled water and canteens.

**CfgItemInteractions.hpp:**

    class ItemBakedBeans : Food_TinCan_base
    {
        interactAttributes[] = {{"Hunger",800}};
    };
    class gyro_wrap_epoch : Food_base
    {
        interactAttributes[] = {{"Hunger",600}};
    };
    class icecream_epoch : Food_base
    {
        interactAttributes[] = {{"Hunger",200},{"Stamina",20}};
    };
    class redburger_epoch : Food_base
    {
        interactAttributes[] = {{"Hunger",600}};
    };
    class bluburger_epoch : Food_base
    {
        interactAttributes[] = {{"Hunger",600}};
    };
    class krypto_candy_epoch : Food_base
    {
        interactAttributes[] = {{"Hunger",500},{"Stamina",50}};
    };
    class ItemBottlePlastic_Clean : Drink_base 
    {
        interactAttributes[] = {{"Thirst",500},{"Stamina",50}};
        interactReturnOnUse = "ItemBottlePlastic_Empty";
    };
    class ItemCanteen_Clean : Drink_base 
    {
        interactAttributes[] = {{"Thirst",1000},{"Stamina",50}};
        interactReturnOnUse = "ItemCanteen_Empty";
    };

**CfgBaseBuilding.hpp**

	class TentDome_EPOCH  : Default
	{
		removeParts[] = {{"KitTentDome",1}};
		GhostPreview = "TentDome_Ghost_EPOCH";
		staticClass = "TentDome_EPOCH";
		simulClass = "TentDome_SIM_EPOCH";
		limitNearby = 2;
		bypassJammer = 1;
	};

	class TentA_EPOCH  : Default
    {
        removeParts[] = {{"KitTentA",1}};
        GhostPreview = "TentA_Ghost_EPOCH";
        staticClass = "TentA_EPOCH";
        simulClass = "TentA_SIM_EPOCH";
        limitNearby = 2;
        bypassJammer = 1;
    };
	
**CfgCrafting.hpp**

    class ItemBottlePlastic_Empty : Part
    {
        usedIn[] = {"ItemBottlePlastic_Dirty"};
        previewPosition[] = {0.807346,1,0.43035};
        previewScale = 2.5;
    };
    class ItemBottlePlastic_Dirty : Item
    {
        usedIn[] = {"ItemBottlePlastic_Clean"};
        nearby[] = {{"Water source","","water",{2,{"water"}},3,1,0,0}};
        recipe[] = {"ItemBottlePlastic_Empty"};
        previewPosition[] = {0.807346,1,0.43035};
        previewScale = 2.5;
    };
    class ItemBottlePlastic_Clean : Item
    {
        usedIn[] = {};
        recipe[] = {"ItemBottlePlastic_Dirty","ItemWaterPurificationTablets"};
        previewPosition[] = {0.807346,1,0.43035};
        previewScale = 2.5;
        displayName = "Clean Water in a plastic bottle";
    };

	class ItemCanteen_Empty : Part
    {
        usedIn[] = {"ItemCanteen_Dirty"};
        previewPosition[] = {0.807346,1,0.43035};
        previewScale = 2.5;
    };
    class ItemCanteen_Dirty : Item
    {
        usedIn[] = {"ItemCanteen_Clean"};
        nearby[] = {{"Water source","","water",{2,{"water"}},3,1,0,0}};
        recipe[] = {"ItemCanteen_Empty"};
        previewPosition[] = {0.807346,1,0.43035};
        previewScale = 2.5;
    };
    class ItemCanteen_Clean : Item
    {
        usedIn[] = {};
        recipe[] = {"ItemCanteen_Dirty","ItemWaterPurificationTablets"};
        previewPosition[] = {0.807346,1,0.43035};
        previewScale = 2.5;
        displayName = "Clean Water in a canteen";
    };

Note, not currently made the canteens or water bottles usable in the recipes for items that the jars of water work for... not totally sure whether you can dupe the recipes to be able to do so atm. Also makes more sense for water purification pills for these since fire would melt the containers (and gives a use for purification pills) ;)

Cheers again,
Grahame.

**Comment by morgoth0** [comment]
Note, just edited to add a plastic bottle and canteen base class (derived from drink_base) to return the empty versions when the water is consumed

**Comment by Ignatz-HeMan** [comment]
Very nice!

**Comment by morgoth0** [comment]
Trying to work out at the moment how to make a canteen a proper magazine with, say, four uses where you get less thirst recovered for each use...

**Comment by morgoth0** [comment]
Also, missed two entries for dirty water in the new containers (I mod the code to only use clean water from water sources, as in DayZ: SA...):

**CfgItemInteractions.hpp**

    class ItemBottlePlastic_Dirty: Drink_base
    {
        interactAttributes[] = {{"Thirst",500},{"Toxicity",5,1},{"Stamina",50}};
    interactReturnOnUse = "ItemBottlePlastic_Empty";
    };

    class ItemCanteen_Dirty : Drink_base
    {
        interactAttributes[] = {{"Thirst",1000},{"Toxicity",5,1},{"Stamina",50}};
    interactReturnOnUse = "ItemCanteen_Empty";
    };

Cheers,
Grahame.

**Comment by ravmustang** [comment]
Will be in my pull merge request this evening

**Comment by morgoth0** [comment]
Really appreciate it. Would have added a pull request but I sort of assume you folks are working on a lot of it anyway and I don't want to jump on things you are already doing...

**Comment by ravmustang** [comment]
@morgoth0 no problem bud.
You did a good job on this so it was an easy add.

In the future don't hesitate to get involved.
Just do a fresh fork when you are ready.
Create a new branch from the experimental branch and name it.
Commit your changes to your branch.
Create the pull request to the epoch experimental branch and watch it for comments!

**Comment by morgoth0** [comment]
Will do so. Cheers again

**Comment by ravmustang** [comment]
just noticed an error for the Drink_base inherit.
What do you have defined for drink_base if you dont mind :)

**Comment by ravmustang** [comment]
Ah ok, looks like I need to spruce them up a bit as you have a mix of ItemInteractions and Crafting config entries wrapped up into one.

Alright no biggie, will straighten this one out the best I can

**Comment by ravmustang** [comment]
@vbawol can be closed when available

**Comment by vbawol** [comment]
Thanks, guys! @morgoth0 @ravmustang
