### ISSUE TITLE
Proper Malden Support

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#877]
- [x] Phone booths, ATM need to be added to ATM configs.
- [ ] Add loot positions for new buildings
- [x] rework spawn areas with proper props for the area or move to flatter ground.

**Comment by morgoth0** [comment]
Is anyone working on this? If not, I'll take a bash at it...

Cheers,
Grahame.

**Comment by vbawol** [comment]
Go for it @morgoth0

**Comment by morgoth0** [comment]
On it. Won't take long. And it's Grahame from the forums ;)

**Comment by Tarabass999** [comment]
class Land_ATM_01_malden_F : bankTerminal {};
	class Land_ATM_02_malden_F : bankTerminal {};
	class phonebooth_01_malden_F_p3d : bankTerminal {};
	class phonebooth_02_malden_F_p3d : bankTerminal {};

	class land_phonebooth_01_malden_F_p3d : bankTerminal {};
	class land_phonebooth_02_malden_F_p3d : bankTerminal {};
	class Land_atm_01_malden_F_p3d : bankTerminal {};
	class Land_atm_02_malden_F_p3d : bankTerminal {};

Have all in worldinteractions.hpp but think only the last 4 entries are needed, just didn't check anymore

**Comment by morgoth0** [comment]
This is all you need. Have it in the files I'm working on: 

`    class Land_ATM_01_malden_F : bankTerminal {};
    class Land_ATM_02_malden_F : bankTerminal {};
    class Land_PhoneBooth_01_malden_F : bankTerminal {};
    class Land_PhoneBooth_02_malden_F : bankTerminal {};
`

**Comment by Tarabass999** [comment]
sorry code ?!?

**Comment by morgoth0** [comment]
I've got three new ones coming that include one where boats can be bought and sold:

![20170929140225_1](https://user-images.githubusercontent.com/16226987/31045647-6c93196a-a5b6-11e7-9c45-0700386e82ef.jpg)

**Comment by Tarabass999** [comment]
cool.. I'm looking forward to those :)

**Comment by morgoth0** [comment]
Had to move a couple of them. Here's what I'm uploading for Malden: https://www.youtube.com/watch?v=U_vZ-vXjjgo

**Comment by vbawol** [comment]
Hey, @morgoth0 did you finish with the new trader cities for Malden yet?

**Comment by vbawol** [comment]
Oh nevermind, I just popped on the dev server and see that you did get them added, Thanks!
