### ISSUE TITLE
Testing Report 9/27

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#878]
- [x] createvehicle BE kick for TentDome_SIM_EPOCH and TentA_SIM_EPOCH
- [x] createvehicle and attachto kick on metal and cinder tower ghost models. CinderTower_Ghost_EPOCH MetalTower_Ghost_EPOCH.  https://github.com/EpochModTeam/Epoch/commit/d12c6f83ce6c10d6c22ab4801bdfa89aa5a37797 https://github.com/EpochModTeam/Epoch/commit/1a20d9ada320bb23df4f4df66687c7ac2a904fc4
- [x] be kick for BarrelBomb_EPOCH_Remote_Ammo
- [x] Animation source nwall,swall,ewall,wwall not found in MetalTower_Ghost_EPOCH 
- [x] crashed satellite missing geo lod and textures. https://cdn.discordapp.com/attachments/143142240762593281/362705592713740288/20170927160013_1.jpg
- [x] Cinder Tower has wood supports instead of concrete. https://cdn.discordapp.com/attachments/201718014582718464/362716938557980682/20170927234704_1.jpg
- [x] Cinder tower ghost preview has support is not transparent with wood texture: https://cdn.discordapp.com/attachments/201718014582718464/362717871077588995/20170927235009_1.jpg
- [x] Metal Tower ghost preview not transparent and has wood texture on support. https://cdn.discordapp.com/attachments/201718014582718464/362718210765619201/20170927235200_1.jpg
- [x] blood pressure is falling to 0 instead of normal level.
- [ ] godmode player stats are not updating properly anymore.
- [x] Ore nodes not returning loot.
- [x] Female ghillie seems to have transparency issues again: https://cdn.discordapp.com/attachments/143142240762593281/362702595824812043/20170927155039_1.jpg
- [x] radioactive sites not working
- [x] fix nuisance stat not increasing
- [x] Bunker doors are not open on after first generation.
- [x] Bunkers cannot spawn loot because they are simple objects that are not found with a class.

**Comment by ravmustang** [comment]
Helion is aware of the conder and metal towers support being wood and was going to revisit it after jury duty.

 I will place the animation sources not found on owers ghost on my to do this weekend

**Comment by vbawol** [comment]
For the animation sources not found, see the wood tower ghost preview as an example,  
Base_Tower_Frame.p3d has a model.cfg with animations defined and Base_Tower_Frame_Ghost.p3d does not.

**Comment by Helion4** [comment]
ya, ghosts dont need any anim-sources in the cfg and therefore a model.cfg isnt needed either. As for the tower centres and their textures, I'll get them sorted this weekend along with crash. sat. changes.

**Comment by vbawol** [comment]
most of this is fixed, and started a new issue for the godmode https://github.com/EpochModTeam/Epoch/issues/891
