### ISSUE TITLE
EXP Test Issues 10/3/17

### ISSUE THREAD

**Issue by orangesherbet** [EpochModTeam/Epoch#886]
Version 1.0 Exp , 10/3/17 12am CST

- [x] All base building items give the error createvehicle #1 and kicks the player trying to place the item.
Items tested: frequency jammer , tents , lockbox , fireplace

- [x] ATM / Phone Booths not working for banking system

- [x] Cultist not affecting players' blood pressure

- [x] Cannot build some base parts due to build option not present when double clicking in inventory.  Items known to have this issue right now:  Cinder Floor, Garden Plot

- [x] Cannot use Atropine- double click in inventory does nothing

- [x] Are the boulders in Malden different than the boulders present on other A3 maps?  Sledge did not seem to salvage rocks from the boulders on Malden.  Sledge worked to break the car wrecks, other things.  Hatchet works for trees.

- [x] Using the #3 slot on favorites is a little weird if you have a sledge equipped.  I tried to put my hatchet in that favorite slot w/ sledge equipped and I couldn't equip it because it was trying to pull my sledge out instead.  Other slots work for the hatchet.

- [x] Fresh Vehicles still seem to be exploding when you approach them, but not consistently.  We had one E-Bike explode without anyone touching it today.

Feedback on Barrel Bombs- it's strange that you just drop them on the ground to use them.  I was quite confused.  I would like to see a different way to use them- similar to satchel charges w/ the mousewheel?

**Comment by morgoth0** [comment]
(1) Cannot replicate the createvehicle error on my dev server (running last night's build). Can you pastebin your createvehicle BattlEye filter.
(2) Malden ATMs and phones, plus some other additions to World Interactions config coming this morning.
(3) I'll add Cinder Floor, Garden Plot etc to the mission configs since I'm doing an update for the new building parts this morning. Will also look at atropine and any other added CAMag items
(4) Not sure about the Malden boulders. Will have to check that one out.
(5) Cannot replicate Hatchet issue. Have you disabled the default ARMA Apex weapon key mapping, i.e. 1=primary, 2=secondary, 3=launcher. If not that could be the issue I suppose.

**Comment by morgoth0** [comment]
Just checking the configs for Malden. I assume that the rocks you are talking about are the new limestone ones? If so am adding them now. There are also two new bushes and five new trees that I'll add.

**Comment by morgoth0** [comment]
Regarding phones and ATMs, there is an issue with the ones that Bohemia has placed on the map. These are not recognised by the new WorldInteractions definitions, neither does infiSTAR recognise them as objects that can be deleted or detected. Editor placed ATMs and phones are fine. I will update the prop position array with those I have already deployed in towns and at gas stations.

**Comment by vbawol** [comment]
@morgoth0 try cursorObject and getModelInfo to get the p3d names, then replace any spaces " " and periods "." with underscore "_" and add to the WorldInteractions.

**Comment by morgoth0** [comment]
@vbawol Yep, thanks. That did the trick. Models added in new pull request

**Comment by vbawol** [comment]
tracking last issue here: https://github.com/EpochModTeam/Epoch/issues/892

**Comment by orangesherbet** [comment]
Lingering issues:  Cannot build Cinder Floor / Garden Plot still - Video:  https://youtu.be/bKQHGng6dHA

Error upon joining: attached screenshot

Error building Metal Tower: attached screenshot
![20171004202358_1](https://user-images.githubusercontent.com/4204940/31208679-e2343b28-a943-11e7-9091-b91123245d45.jpg)

![20171004203240_1](https://user-images.githubusercontent.com/4204940/31208682-e899b81c-a943-11e7-9fff-9797486dabec.jpg)

**Comment by vbawol** [comment]
Next build should sort most of these, it happens nightly at 12am cst.
