### ISSUE TITLE
Known Issue: player stats are not updating when godmode is enabled

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#891]

**Comment by vbawol** [comment]
should be resolved with https://github.com/EpochModTeam/Epoch/commit/bdb168ba50b359de7490036055e4d7954f8617a8

**Comment by ravmustang** [comment]
experiencing an issue with the EPOCH_GMODE var.
Tested working with this correction:
https://github.com/EpochModTeam/Epoch/commit/b62a029d66b1df5eb2e2e1d2d55137572a511431

**Comment by vbawol** [comment]
Thanks @ravmustang !
