### ISSUE TITLE
Possible FavBar issue with apex key mapping (1,2,3 keys)

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#892]
from @orangesherbet:  Using the #3 slot on favorites is a little weird if you have a sledge equipped. I tried to put my hatchet in that favorite slot w/ sledge equipped and I couldn't equip it because it was trying to pull my sledge out instead. Other slots work for the hatchet.

Possible workaround from @morgoth0  is to disable the default ARMA Apex weapon key mapping, i.e. 1=primary, 2=secondary, 3=launcher

**Comment by orangesherbet** [comment]
will try this out later tonight, thanks guys

**Comment by orangesherbet** [comment]
All seems well here- just conflicting key binds.  3 = Launcher (Sledge in this case) by default.  Disabling the default keybinds does solve the issue.

**Comment by Ignatz-HeMan** [comment]
https://github.com/EpochModTeam/Epoch/commit/8a4ab15fd178b02f000486600137b9f31b8541ae
This should fix it.
If FavBar slot is empty, default Arma Action will be executed
If FavBar slot has an item, default Arma Action will be overwritten

**Comment by raymix** [comment]
You can also remap all favbar keys in Epoch ESC menu, doesn't have to be 12345. Mapped tiles will also change their names to your keyboard key
