### ISSUE TITLE
hitpoints may not be reporting correctly

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#902]
I am seeing players with hitpoints in the database all the same as the damage of the player so either we are using setDamage after setHit somewhere or https://community.bistudio.com/wiki/getAllHitPointsDamage may not report correctly when used on the server.

**Comment by Ignatz-HeMan** [comment]
getallhitpointsdamage seems to work correctly
![20171006223743_1](https://user-images.githubusercontent.com/6589278/31297741-8251c450-aae7-11e7-86f8-4b7982a570c6.jpg)

**Comment by Ignatz-HeMan** [comment]
I will test a bit tomorrow

**Comment by Ignatz-HeMan** [comment]
Another reason could be... 
If the Player have only "damage", not "Hitpointdamage" and you setdamage, all hitpoints have the same value!

**Comment by vbawol** [comment]
Right anytime we do a setDamage (that is not 0 or 1) we need to also reset the hitpoints. Normally we only use setDamage to heal the player once all other hitpoints are at 100% but I am not sure what changes you guys have related to that.

**Comment by Ignatz-HeMan** [comment]
setdamage 0 > all Hitpoints also goes to 0
But I will try a bit tomorrow with the current experimental build

**Comment by Ignatz-HeMan** [comment]
Tested a bit and thi should fix it:
https://github.com/EpochModTeam/Epoch/commit/b1775a68ba290e5c44cadf3c3367c2eaa61d1d48
