### ISSUE TITLE
get|setUnitLoadout issues

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/Epoch#904]
We have an issue with get|setUnitLoadout, that is causing players inventory to sometimes be saved (getUnitLoadout) to the database with some overfilled containers (uniform, vest, backpack).

When this happens the player cannot log in and get a black screen. 

@Ignatz-HeMan had a workaround https://github.com/EpochModTeam/Epoch/blob/experimental/Sources/epoch_server/compile/epoch_player/EPOCH_server_loadPlayer.sqf#L330-L331 that is currently commented out in the form another round of get|setUnitLoadout, however, in testing, we found even with this the issue was persisting with a noticeable duplication of items eventually causing the same issue.

I have a hunch this is related to the server and the client seeing different items, possible propagation issues.

**Comment by Ignatz-HeMan** [comment]
Please try again:
https://github.com/EpochModTeam/Epoch/commit/e4fdf4d6a03134c75dcfafd1f8af59db7c993a1d

**Comment by morgoth0** [comment]
I installed the fix on EpochZ: Bandit Country this morning. Will report if the black screen happens again

**Comment by Ignatz-HeMan** [comment]
Please use the current file. I have also added a second fix!
https://github.com/EpochModTeam/Epoch/commit/4660975b05e77ba7c2e346262d9e54d478da206b

**Comment by morgoth0** [comment]
Will update at the next restart (1400EDT). Thanks again @Ignatz-HeMan 

_UPDATE: New code is now running on the server._

**Comment by vbawol** [comment]
Seems like @Ignatz-HeMan 's last round of workarounds may have gotten this resolved.
