### ISSUE TITLE
1.0 exp feedback

### ISSUE THREAD

**Issue by baaljayjay** [EpochModTeam/Epoch#906]
1:battleye kick me when i tried to built a garden plot (create vehicle restriction 1).
2: i tried to snap floor on wall but is it does not work properly.
![20171008011024_1](https://user-images.githubusercontent.com/16623990/31312543-5356756c-abc6-11e7-8485-472ab6f32ef4.jpg)
![20171008011034_1](https://user-images.githubusercontent.com/16623990/31312544-549128b4-abc6-11e7-8de2-bff82987f3e9.jpg)
3:in the crafting menu shows the inventory instead of the melting tool.
![20171008011124_1](https://user-images.githubusercontent.com/16623990/31312550-86c1e79c-abc6-11e7-8e5d-9e1a3e31ce28.jpg)

**Comment by morgoth0** [comment]
I tried the half-floor a little while ago today and it would not snap to a wooden floor too. Could not see anything obviously wrong in CfgBaseBuilding.hpp

**Comment by ravmustang** [comment]
The half and quarter floors were arma 2 assets ported forward recently.
I can take a closer look as to what's wrong there but as they are different sizes from the full floor they were only setup when I tested them for snapping to themselves. Half floor to half floor and quarter floor to quarter floor.

The other things mentioned were not missed, will try to report back on those asap

**Comment by morgoth0** [comment]
@ravmustang One other data point from testing today is that even when I manually moved it into _exactly_, well as close as I could make it, in position against the wooden floor that was already placed, when I hit 1 to build it raised itself into position (not the issue after build is finished) it just chose to be in a different place as soon as I hit 1 and stayed in that position after build...

**Comment by vbawol** [comment]
Thanks for the feedback, Kicks should be sorted as of now. Also, snapping issues and smelting tools issues are now known and tracked in another issue: https://github.com/EpochModTeam/Epoch/issues/918
