### ISSUE TITLE
Experimental Bornholm spawn issue

### ISSUE THREAD

**Issue by KRDucky** [EpochModTeam/Epoch#908]
I spawned in Bornholm on Experimental. I was in the debug chamber for selecting gender. I selected male and was now in the chamber where you select the teleport to use. Problem is, there is no teleport at all. There is no exit to the chamber. You are essentially stuck till you eventually die.

**Comment by morgoth0** [comment]
You were looking for the manhole covers on the floor yes? Cause the code in epoch_server_settings/configs/maps/bornholm.h is the same as for any other Epoch-supported map so should just place the TP manhole covers:

`			{ "Transport_C_EPOCH", { -0.415527, -7.05298, -10.3098 }, "", { 14121.2, 11331.5, 0.000305176 } },
			{ "Transport_W_EPOCH", { -14.4316, 0.112793, -10.3098 }, "", { 1322.18, 8733.92, 0.0136757 } },
			{ "Transport_E_EPOCH", { 13.5127, 0.410156, -10.3098 }, "", { 15639.3, 191.995, 0.000153065 } }`

**Comment by KRDucky** [comment]
Do I then have to place spawn markers somewhere? And where do I place that code?

**Comment by xDrokZ** [comment]
You dont need to place spawn markers to be able to teleport. Try "Land_InfoStand_V1_F " instead of the Transport_ Epoch stuff. Maybe they just spawn to deep and you wont see them in the chamber. Happened to me on redux

**Comment by KRDucky** [comment]
Can you give me an example?

Also is is possible to edit the Spawn trader area? I want to place billboards or white boards with important information for new players.

The 3 manhole covers in code are Transport_C_epoch, Transport_W_epoch and Transport_E_epoch.
Are there different InfoStands for each direction?

**Comment by xDrokZ** [comment]
Its just an example you can use alot of other objects for that... try to replace al manholes with it and see what happens

**Comment by KRDucky** [comment]
But how will they be able to determine which direction they go?

**Comment by morgoth0** [comment]
Well, you could just use this instead... https://epochmod.com/forum/topic/34896-custom-spawn-dialog-with-gear-halo-selection-moving-map-credits-custom-spawns-and-more

**Comment by morgoth0** [comment]
PS: That script allows you also to put posters on each of the four walls easily...

**Comment by KRDucky** [comment]
hmm. does it include instructions on how to replace the existing Experimental spawn
?

**Comment by xDrokZ** [comment]
well i do like this https://imgur.com/a/qtgaL

**Comment by KRDucky** [comment]
There is no image there

**Comment by morgoth0** [comment]
Read the docs... it automatically replaces the manhole covers with infoboards

**Comment by xDrokZ** [comment]
got some net issues... will reupload after restarting the router

**Comment by morgoth0** [comment]
It's a replacement system that allows you to add four choices of location or 50... players choose their destination - that's how they know. **Really** worth just **reading** the first post on the thread, which sort of answers those questions...

**Comment by KRDucky** [comment]
ill get around to it. At work ATM on a work domain so going to a game site is not advised. ^_^

**Comment by KRDucky** [comment]
followed the instructions......didnt work.

**Comment by morgoth0** [comment]
Works on all four of my servers... Any errors in the RPT file?

**Comment by vbawol** [comment]
Is this sorted after you rebuilt your server @KRDucky?

**Comment by KRDucky** [comment]
no. cant tell. I cant spawn into the server. I keep getting the Authentication Error after selecting Gender

**Comment by morgoth0** [comment]
Remove the initial gear setup - if there is an issue with how that is set up you will not be able to log in and you will get an authentication error...

**Comment by vbawol** [comment]
This should be fixed as of https://github.com/EpochModTeam/Epoch/commit/7bed205d02cef6a1004ca9f1a6f35839d0683502
