### ISSUE TITLE
Bad Conversion Bool RPT

### ISSUE THREAD

**Issue by KRDucky** [EpochModTeam/Epoch#910]
I am getting this spammed error on all the maps I have tried so far : Altis and Bornholm. 

23:32:44 "Epoch: Init Variables"
23:32:44 "Loading config..."
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool
23:32:44 Bad conversion: bool

Here is my recent RPT: https://pastebin.com/gqHqg2GK
That server has Bornholm, ACE3, CBA, and ACRE2. 

Here is the Altis RPT. It is stock Experimental. No additional mods. 
https://pastebin.com/1BHTutwf

**Comment by vbawol** [comment]
This should not happen with the latest builds. 

The packed files on the GitHub are not updated automatically with the nightly builds, you will need to pack them your self or get them from here http://steamcommunity.com/sharedfiles/filedetails/?id=558243173
```
@ECHO OFF
SET STEAMUN=yourUsername
SET STEAMPW=yourPassword
SET ARMASVRPATH=C:\Arma3Server
SET ARMAAPPID=107410
SET ARMAWORKSHOPID=558243173
:: update workshop mod
START "" /WAIT steamcmd.exe +login %STEAMUN% %STEAMPW% +workshop_download_item %ARMAAPPID% %ARMAWORKSHOPID% validate +quit
:: copy files back to server
xcopy /s/e/y/q/i "steamapps\workshop\content%ARMAAPPID%%ARMAWORKSHOPID%" "%ARMASVRPATH%@EpochHive"
:: copy battleye files to live
xcopy /s/e/y/q/i "%ARMASVRPATH%@EpochHive\sc\BattlEye" "%ARMASVRPATH%\SC\BattlEye"
:: update mission files
xcopy /s/e/y/q/i "%ARMASVRPATH%@EpochHive\MPMissions" "%ARMASVRPATH%\MPMissions"
```
that is the .cmd/bat script I use to auto update my server each time it restarts.
