### ISSUE TITLE
Empty lootcontainers

### ISSUE THREAD

**Issue by xDrokZ** [EpochModTeam/Epoch#911]
Found that some containers arent filled with loot when searching them. Tarps looked fine so far but chairs, lockers and more been empty

**Comment by xDrokZ** [comment]
Trash also gives no lootdrop

**Comment by morgoth0** [comment]
Re: Trash loot, I can confirm that while it says I have found something I cannot find it. Note that when trash is looted I now see this:

![20171011140023_1](https://user-images.githubusercontent.com/16226987/31458430-1511c0ac-ae8e-11e7-9613-4706511733ee.jpg)

Am running latest commits up to this morning's garden fix ("fix usage"). Will update the Taviana server to use the debug code I just noticed that @vbawol put up together with @Ignatz-HeMan 's login 3.0

**Comment by vbawol** [comment]
@morgoth0 It looks like that's just the way those are configured to be destroyed for that map. I looted trash today on Malden and everything works normally minus this missing loot issue.

**Comment by vbawol** [comment]
Latest build 1007 fixes the empty loot containers from my tests.
