### ISSUE TITLE
Building Items flipping out of the ground

### ISSUE THREAD

**Issue by xDrokZ** [EpochModTeam/Epoch#912]
Building Items flipping out of the ground (some areas worked but some dont)

**Comment by Pmba79** [comment]
Like when you are placing building parts partly inside the ground ?

**Comment by xDrokZ** [comment]
Yes. This worked until todays/yesterdays update

**Comment by xDrokZ** [comment]
Was told just now that they also fly off of snapped building items

**Comment by Pmba79** [comment]
Thanks for the info, I'll go try to replicate it asap..

**Comment by xDrokZ** [comment]
I reverted these changes https://github.com/EpochModTeam/Epoch/compare/976baf9660b4...28340c23113f 
and it works again

**Comment by vbawol** [comment]
Should be fixed with https://github.com/EpochModTeam/Epoch/commit/63fc23b8cb2ed5b0a40037d0e79545f32f6c5dfe
