### ISSUE TITLE
Cant server restart

### ISSUE THREAD

**Issue by kubosov** [EpochModTeam/Epoch#920]
**# Epoch server does not restart.**
**Branch**: experimental
**OS**: Windows 10 pro

**Reproducibility**: every time.

**Reproduction procedure**:
in epochconfig.hpp
`serverRestart         = "true"; `
`forceRestartTime      = 1200;`  // testing param. every 20 minutes restart.

**Result**:
server is running 12h over.
no messages and logging. 

**Another reproduction procedure**:
RCON command (from localhost battleWarden/EPM)
- shutdown SUCCESS  process is killed
- restart NOP

**Comment by vbawol** [comment]
You need to make sure you have the Battleye rcon information set in your EpochServer.ini

https://github.com/EpochModTeam/Epoch/blob/release/Server_Install_Pack/%40epochhive/EpochServer.ini#L6-L8

Note: IP needs to be accessable if rcon is only running on external IP, then use that.

**Comment by kubosov** [comment]
my EpochServer.ini and server.cfg

EpochServer.ini
BattlEyePath = C:\Arma3Server\SC\BattlEye
InstanceID = NA123
LogAbuse = 1
LogLimit = 999
IP = 192.168.0.XXX     // LAN IP address.
Port = 2306
Password = RconPASS
 :
-------
server.cfg
 :
passwordAdmin = "RconPASS";
 : 
--------

RCON( from EPM) 
IP 192.168.0.XXX:2306 logged in is SUCCESS,  list up Admins.
 shutdown : SUCCESS
 **restart : NOP**

AND epochconfig.hpp 
`serverRestart ="true"`
`forceRestartTime = ttttt`
Is this feature IGNORE?

**Comment by xDrokZ** [comment]
You should read the comment. It says 
// true sends #shutdown command to server after the time specified in ForceRestartTime

It will not restart your server it will shut it down in the given time. To start your server up again you need another program/tool/batchfile.

I use this one for redis, server and bec

http://www.softpedia.com/get/System/File-Management/Restart-on-Crash.shtml

**Comment by xDrokZ** [comment]
You should check the forum or ask in discord before you create new issues here since these arent issues on the developers end

**Comment by morgoth0** [comment]
What xDrokZ said, and if you do not mind spending $50 then FireDaemon is well worth the investment, especially if you will be running multiple Epoch and REDIS servers (together with BEC for the shutdown and warning messages for each)

**Comment by kubosov** [comment]
about "serverRestart"
I misunderstood that it is a specification bug where comments and functions are inconsistent.

The mystery was solved. Thank you.
