### ISSUE TITLE
Misaligned Chernarus MAP.

### ISSUE THREAD

**Issue by kubosov** [EpochModTeam/Epoch#921]
# **The map coordinates of Chernuthus are deviated in the WEST half**
EPOCH:1.0 Experimental b826
CUP Terrains map: 1.4

**Symptom**

1. The map has a refueling icon, but the vehicle can not be refueled at the gas station.
 Exp.Zelenogorsk, Vybol, WEST Chernarus

1. Kozlovka fixed trader is not exist.

_Should I use AIATP?_

**Comment by xDrokZ** [comment]
AIATP doesnt work. Gas stations are disabled now by default in epoch configs. 
Not sure why the trader doesnt show up but they do for me

**Comment by kubosov** [comment]
East gas station, exp. Elektro, Berezino is working, It's strange.

South west static NPC position is not changed since V0.5 .
It is judged that it is not arranged because the NPC mark is not drawn on the map.
Separately, initialize the DB and try to see if the NPC is initially placed.

**Comment by xDrokZ** [comment]
in epochconfig.hpp check line 52 and set

disableAutoRefuel = "true";

to false

**Comment by vbawol** [comment]
Thanks for the report but you maybe better off contacting CUP devs about this issue, as we have no control over this map.
