### ISSUE TITLE
User Chat messages are not displayed on the console

### ISSUE THREAD

**Issue by kubosov** [EpochModTeam/Epoch#922]
# **User Chat messages are not displayed on the console**
**EPOCH:**1.0 Experimental b826
**OS:** Windows 10 Pro

**Symptom**
User chat messages  are not displayed on the console, and RCON.
I confirmed that the next channel.  "side/group/direct"

Messages via RCON are displayed on the console, and RCON  (as expected)
RCON is running at localhost.  and software firewall is disabled.

**Comment by vbawol** [comment]
Not sure this is an Epoch issue, seems like more of an Arma thing
