### ISSUE TITLE
Today's map marker update sort of removes AI mission markers

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#927]
The changes to the marker system today are fantastic (the one change would be to shrink them a little more when scrolled in) but they have a negative impact on map markers from third party mission systems (specifically noted with BlckEagle's, SEM and Wicked AI).

The new code is removing the circular map markers from the map as shown in the images below. This first shows a SEM mission. The arrow should be accompanied with a circle with crosses in it:

![20171018150446_1](https://user-images.githubusercontent.com/16226987/31737541-e515de1e-b415-11e7-9382-4a1b559a1839.jpg)

This second shows the Wicked AI mission. Although the inner circle of crosses is shown they keep blinking in and out, which they did not do before this morning's changes:

![20171018150504_1](https://user-images.githubusercontent.com/16226987/31737700-5233b19c-b416-11e7-8d02-5fde919867dc.jpg)

The final image shows a BlckEagle's mission which should have a circle of hash marks (of different colours depending on the mission difficulty from blue through orange indicating the difficulty of the mission:

![20171018150511_1](https://user-images.githubusercontent.com/16226987/31737760-78a810f2-b416-11e7-964a-1f139f46a724.jpg)

Full map image to show when scaled out:

![20171018150345_1](https://user-images.githubusercontent.com/16226987/31737836-b9407e2e-b416-11e7-9069-abaa2c810caf.jpg)

Hope this helps,
Cheers,
Grahame.

**Comment by ravmustang** [comment]
no emoji shows my feelings right now. 
So words will do it.
Ive got it laid out and will be home for lunch to work and test.

**Comment by morgoth0** [comment]
@ravmustang Just pull requested a complete fix... I'd been working on it this morning...

Tested on one of my EpochZ 1.0 servers. All working now.

**Comment by morgoth0** [comment]
@ravmustang And nice catch on that. I had missed the definition required for the incrementing local markers. Thanks!

**Comment by vbawol** [comment]
@morgoth0 @ravmustang is #929 ready to merge?

**Comment by morgoth0** [comment]
With @ravmustang 's change I think so, but it's his final call. I have tested on one of my servers though and all seems okay now

**Comment by ravmustang** [comment]
Roger that, looks good on that merge THX!

**Comment by ravmustang** [comment]
I will add a config option for hosts to turn the onZoomMapScaling off after merge.
