### ISSUE TITLE
Building guides (Request)

### ISSUE THREAD

**Issue by KRDucky** [EpochModTeam/Epoch#930]
It would be nice to have a virtual visible guide when lining up base parts. Especially when on a hill or something where when you use Snap building, often the base part snaps into a hill where you cant see it. Especially in the case of Foundations. Some form of visual guide to show you if it is lined up or not because sometimes it wont snap to anything near you. Even more useful for FreeBuidling. 

I guess similar to how a backup camera works with how it shows virtual lines to guide you when you back up. Something like that would be nice.

**Comment by Ignatz-HeMan** [comment]
I have added some visual helpers on snapping:
https://github.com/EpochModTeam/Epoch/commit/12e5746c82fbfc825ea4283259c0c8317ecaa149
