### ISSUE TITLE
Malden Teleporter at spawn is glitched

### ISSUE THREAD

**Issue by KRDucky** [EpochModTeam/Epoch#931]
The Northern manhole cover spawns you underneath the spawn area. It is glitched.

**Comment by vbawol** [comment]
Thanks for the report, with https://github.com/EpochModTeam/Epoch/commit/f39a79a7d2853eb1a70749ada42a7b45ee9840b6 it should be sorted.

**Comment by morgoth0** [comment]
Sorry about that @vbawol Thought I had tested them all... obviously not

**Comment by vbawol** [comment]
No problem @morgoth0 it should have worked but you know Arma 💯
