### ISSUE TITLE
server_securityfunctions.sqf

### ISSUE THREAD

**Issue by natoed** [EpochModTeam/Epoch#932]
It all still works as far as I can tell thou it throws the below errors in the server rpt log.
I'm pretty sure that I'm the only one using the default AH btw.....

`16:26:40 "Loading config..."
16:26:40 Error in expression <Token = _skn_t1+_skn_t2+_skn_t3+_skn_t4+_skn_t5;
EPOCH_server_Authed = compileFi>
16:26:40   Error position: <_skn_t5;
EPOCH_server_Authed = compileFi>
16:26:40   Error Undefined variable in expression: _skn_t5
16:26:40 File epoch_server\init\server_securityfunctions.sqf, line 251
16:26:40 Error in expression <th{};
	if (_array select 0 isEqualTo '"+_skn_AH_rndVarAHInitCheckToken+"') then >
16:26:40   Error position: <_skn_AH_rndVarAHInitCheckToken+"') then >
16:26:40   Error Undefined variable in expression: _skn_ah_rndvarahinitchecktoken
16:26:40 File epoch_server\init\server_securityfunctions.sqf, line 611
16:26:40 "Epoch: Start Hive, Instance ID: 'NA123'"`

hope it helps

**Comment by vbawol** [comment]
Thanks for the report @natoed 
Fixed with this commit: https://github.com/EpochModTeam/Epoch/commit/0bb4c7f985f9a9592c50998985be55db6ce9317a
