### ISSUE TITLE
PublicVariable Restriction #0

### ISSUE THREAD

**Issue by KRDucky** [EpochModTeam/Epoch#936]
The latest Experimental build causes Public Variable #0 kicks. No other mods running on server. Just Epoch Experimental.

**Comment by KRDucky** [comment]
From the RPT:
22:17:22 "Epoch: Loading NPC traders"
22:17:23 No speaker given for Idi Iwu
22:17:24 No speaker given for Lucas Scott
22:17:25 Error in expression <tVariable["MARKER_REF",""];
if (_marker != "") then {
deleteMarker _marker;
_pos>
22:17:25   Error position: <!= "") then {
deleteMarker _marker;
_pos>
22:17:25   Error !=: Type Array, expected Number,String,Not a Number,Object,Side,Group,Text,Config entry,Display (dialog),Control,Network Object,Team member,Task,Location
22:17:25 Error in expression <tVariable["MARKER_REF",""];
if (_marker != "") then {
deleteMarker _marker;
_pos>
22:17:25   Error position: <!= "") then {
deleteMarker _marker;
_pos>
22:17:25   Error !=: Type Array, expected Number,String,Not a Number,Object,Side,Group,Text,Config entry,Display (dialog),Control,Network Object,Team member,Task,Location
22:17:26 Error in expression <tVariable["MARKER_REF",""];
if (_marker != "") then {
deleteMarker _marker;
_pos>
22:17:26   Error position: <!= "") then {
deleteMarker _marker;
_pos>
22:17:26   Error !=: Type Array, expected Number,String,Not a Number,Object,Side,Group,Text,Config entry,Display (dialog),Control,Network Object,Team member,Task,Location
22:17:26 Error in expression <tVariable["MARKER_REF",""];
if (_marker != "") then {
deleteMarker _marker;
_pos>
22:17:26   Error position: <!= "") then {
deleteMarker _marker;
_pos>
22:17:26   Error !=: Type Array, expected Number,String,Not a Number,Object,Side,Group,Text,Config entry,Display (dialog),Control,Network Object,Team member,Task,Location
22:17:27 Error in expression <tVariable["MARKER_REF",""];
if (_marker != "") then {
deleteMarker _marker;
_pos>
22:17:27   Error position: <!= "") then {
deleteMarker _marker;
_pos>
22:17:27   Error !=: Type Array, expected Number,String,Not a Number,Object,Side,Group,Text,Config entry,Display (dialog),Control,Network Object,Team member,Task,Location
22:17:27 Strange convex component202 in a3\structures_f\households\house_small01\d_house_small_01_v1_f.p3d:geometryView
22:17:27 Strange convex component203 in a3\structures_f\households\house_small01\d_house_small_01_v1_f.p3d:geometryView
22:17:28 Error in expression <tVariable["MARKER_REF",""];
if (_marker != "") then {
deleteMarker _marker;
_pos>
22:17:28   Error position: <!= "") then {
deleteMarker _marker;
_pos>
22:17:28   Error !=: Type Array, expected Number,String,Not a Number,Object,Side,Group,Text,Config entry,Display (dialog),Control,Network Object,Team member,Task,Location

**Comment by KRDucky** [comment]
22:20:17 "Epoch: Server Start Complete: 398.456 seconds"

**Comment by KRDucky** [comment]
20.10.2017 21:56:31: KRDucky - #0 "PLAYER_BADHIVE" = true
20.10.2017 21:57:09: KRDucky  - #0 "PLAYER_BADHIVE" = true
20.10.2017 21:59:08: [MXI]Ghost - #0 "PLAYER_BADHIVE" = true
20.10.2017 22:07:47: KRDucky  - #0 "PLAYER_REJECT_NotReady1" = true
20.10.2017 22:17:17: KRDucky  - #0 "PLAYER_REJECT_NotReady1" = true
after the server completed startup, we could spawn in
but fuck, it took 398 seconds to start

**Comment by vbawol** [comment]
This error looks to be from the trader fsm https://github.com/EpochModTeam/Epoch/blob/experimental/Sources/epoch_server/system/Trader_brain.fsm#L416-L465 and is related to changes in the usage of MARKER_REF

**Comment by ravmustang** [comment]
Should be handled with https://github.com/EpochModTeam/Epoch/commit/555e350b5d40dfc1f6946927e7c22196c3c51f64
