### ISSUE TITLE
Minor issue in cfgItemInteractions.hpp

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#937]
Getting this error in the RPT after latest updates:

`10:00:45 Warning Message: File mpmissions\__cur_mp.Taviana\epoch_config\Configs\CfgItemInteractions.hpp, line 980: .CfgItemInteractions: Member already defined.
`

Which is this entry:

`	class adrenaline_epoch : Drink_base
    {
        interactText = "USE"; // todo digest system to give attributes over time
		interactAttributes[] = {{"Thirst",-50},{"Stamina",120},{"BloodP",20},{"Toxicity",5}};
    }; <-- Line 980
`

Is this because of the redefinition of interactText with Drink_base?
Thinking that adrenaline, atropine and the anti-rad stuff should be Default, not Food and Drink_base, but not 100% certain...

**Comment by morgoth0** [comment]
Yeah... it's not the definition as Drink_base. Changed to Default and still get that warning. Same line

**Comment by ravmustang** [comment]
Ive looked through the itemInteractions file and recent commits and have found nothing that would throw it off as such.

The error" .CfgItemInteractions: Member already defined." 

To me this means that CfgItemInteractions is being defined a second time.
Could ya repack you mission file from vanilla and try it out again ?
Not able to test for ya as Im prepping for a flight back home this afternoon 😉

**Comment by morgoth0** [comment]
Yeah, I waded through and am at a loss to find a dupe so far. Assuming the line numbers ignore the comments at the beginning then it would indicate the error is thrown on the closing of the class cfgItemInteractions {} pair...

Will try a vanilla MPMission file to verify

**Comment by morgoth0** [comment]
Oops... my bad... Bizarrely actually copied the CfgItemInteractions.hpp code into CfgItemSort.hpp. Sorry for wasting your time... 
grepwin is your friend ;)

**Comment by ravmustang** [comment]
Dont worry we all make little goofs here and there
Thank Grahame for the extra test to verify, gonna close this one up 😉

**Comment by morgoth0** [comment]
Thing is that I customize quite a bit in epoch_code and epoch_config so it actually is easier to copy the files across individually and edit from the file changes where necessary. First time I have done this though... misclicked the mouse on the wrong file at 0600...
