### ISSUE TITLE
Serialization warnings in RPT

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#938]
Wondering whether these warnings in the server RPT 

`10:48:29 Performance warning: SimpleSerialization::Write 'epoch_radioactivelocations' is using type of ',LOCATION' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
`

are Epoch's issue related to the 

`	radioactiveLocations[] = {"NameCityCapital", "NameCity", "Airport"}; // used for random radioactive locations and to suppress animal spawns within cities.
`

line in CfgEpochClient.hpp or whether it is specific to the map (Taviana) in use in the server in question?

**Comment by ravmustang** [comment]
This error was brought up in dev chat a few days ago.
Yes this has to do with the new radiation system being done up as we chat here.
We should have this one sorted out soon 

and No it does not have to do with Taviana or any map at this time 😉

**Comment by vbawol** [comment]
These are from the radiation system, @raymix is reworking it so this may get solved. Also, it is just a warning, not an error.

**Comment by vbawol** [comment]
@ravmustang solved this 🥇
