### ISSUE TITLE
geiger_radiation.paa not found

### ISSUE THREAD

**Issue by natoed** [EpochModTeam/Epoch#942]
Error on screen ingame and also in rpt log
Warning Message: Picture x\addons\a3_epoch_assets_1\pictures\geiger\geiger_radiation.paa not found

Had a look in a3_epoch_assets_1\pictures\geige\
no .paa file named geiger_radiation

**Comment by morgoth0** [comment]
Yeah... that paa appears to be in x\addons\a3_epoch_code/Data/UI/buttons/ not a3_epoch_assets_1 assuming it is in fact the same image.

If so, the lines in CfgActionMenu_self.hpp need to be changed to the correct path...

`class geiger_menu
 {
 	condition = "'ItemGeigerCounter_EPOCH' in dyna_assigneditems";
     icon = "x\addons\a3_epoch_code\Data\UI\buttons\geiger_radiation.paa";
 	tooltip = "Geiger counter settings";
 
 	class geiger_toggle
 	{
 		condition = "true";
 		action = "call epoch_geiger_show_hide";
         icon = "x\addons\a3_epoch_code\Data\UI\buttons\geiger_toggle.paa";
 		tooltip = "Toggle HUD";
 	};
 	class geiger_counter_mute
 	{
 		condition = "!EPOCH_geiger_mute_counter";
 		action = "EPOCH_geiger_mute_counter = !EPOCH_geiger_mute_counter";
         icon = "x\addons\a3_epoch_code\Data\UI\buttons\geiger_volumeoff.paa";
 		tooltip = "Mute counter";
 	};
 	class geiger_counter_unmute
 	{
 		condition = "EPOCH_geiger_mute_counter";
 		action = "EPOCH_geiger_mute_counter = !EPOCH_geiger_mute_counter";
         icon = "x\addons\a3_epoch_code\Data\UI\buttons\geiger_volumeon.paa";
 		tooltip = "Unmute counter";
 	};
 	class geiger_warning_mute
 	{
 		condition = "!EPOCH_geiger_mute_warning";
 		action = "EPOCH_geiger_mute_warning = !EPOCH_geiger_mute_warning";
         icon = "x\addons\a3_epoch_code\Data\UI\buttons\geiger_alarmoff.paa";
 		tooltip = "Mute warnings";
 	};
 	class geiger_warning_unmute
 	{
 		condition = "EPOCH_geiger_mute_warning";
 		action = "EPOCH_geiger_mute_warning = !EPOCH_geiger_mute_warning";
        icon = "x\addons\a3_epoch_code\Data\UI\buttons\geiger_alarmon.paa";
 		tooltip = "Unmute warnings";
 	};
`

You want to give that a go @natoed 

Cheers,
Grahame.

**Comment by morgoth0** [comment]
Pull request submitted in the meantime

**Comment by vbawol** [comment]
Thanks guys!
