### ISSUE TITLE
Blacklist of locations for radioactive locations

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/Epoch#944]
Loving the new radiation stuff but I had to turn it off for the moment. Have an A2/Epoch-style safe zone in Stary Sabor and a radioactive location was put right next door. In addition it seems from the code that the radiation zone could be dumped on someone's base if they happen to have it in a capital, city or airport. 

Probably need a check of nearby jammers or protection zone invisibles, plus a blacklist variable in EpochConfig.hpp that specifies places (map markers maybe) where the rad zones should not be placed. Does not have to be a big exclusion area in each case but a player's base and a safe zone should be safe, even if you may get a few rads on your way there.

If you agree then I will start banging this out in the morning...?

![20171022170543_1](https://user-images.githubusercontent.com/16226987/31866333-45550276-b74c-11e7-89ec-3dca795d2e3f.jpg)

**Comment by raymix** [comment]
Totally agree, this whole thing was rushed without taking any balance in consideration, the concept on its own took some planning and research, just wanted to get it out asap.
Initial idea actually was to allow reducing radiation over time in trader zones or maybe ask traders via chat menu to help the player out by reducing radiation level a small bit.
Currently nanite items reduce radiation instantly, but I think only injection should be instant (while damaging player's health a bit), pills should work over time and cream should add protection layer.

Think I'm gonna have to implement a buff/debuff system for this.

**Comment by morgoth0** [comment]
I do love the concept and the work so far is great! I especially like the new geiger counter HUD interface. I will work on the "exclusion zones" for radiationlocations[] tomorrow afternoon (just remembered I have a work meeting at 1000EDT tomorrow morning). 
For pills and injection, maybe something like the Ryan's injectors and pills where the injector removes all radiation effects permanently but the pills are a temporary fix with the rads returning after a server defined time (default say 10-15 mins) giving them time to get an injector? Then the cream could just reduce the accumulation of rads in the player's body.

**Comment by morgoth0** [comment]
At least until the player stats interface has a timed effect functionality like has been talked about for digestion... maybe 1.1?

**Comment by raymix** [comment]
I am not sure about player stats bar thing, but seeing how popular it is I might implement our own some day using dynaHUD.
btw fun fact - geiger counter was designed after this guy here: https://www.youtube.com/watch?v=uGILagd_Bh4

**Comment by morgoth0** [comment]
Watched the video... yes, so I see. Good job anyway. Love the Epoch Corp markings!

Re: Status Bar, that's @Ignatz-HeMan 's which was modified by @xDrokz to leave the FavBar space clear and have new icons. Most important thing for me on a status bar is the ability to turn it off which @Ignatz-HeMan 's has. Still looking for an A3/Epoch one that would just dupe the simplicity, look and placing of the A2/DayZ one... Only just added them to my servers since I personally am not a big fan of them (thus the importance of being able to turn them off)

**Comment by ravmustang** [comment]
Blacklisted Objects array and distance config entries 😉 
https://github.com/EpochModTeam/Epoch/commit/431e10ee582df19e2b9a9969b4dee284a3bda090

**Comment by morgoth0** [comment]
Tested on my servers this morning. Seems to be working well. Thanks @ravmustang and @raymix

**Comment by ravmustang** [comment]
It was a team effort between everyone IMHO, I believe AWOL, Raymix, Helion and I all had our hands in the cookie jar for this one but the credits still go out to the everyone for their hard work, testing and patience getting us to 1.0 release!
To you too Grahame for your testing, suggestions and contributions to Epoch past, present and future!

Have a great week ahead bud 😜

**Comment by vbawol** [comment]
Thanks for all your contributions!
