### ISSUE TITLE
Shipwrecks

### ISSUE THREAD

**Issue by natoed** [EpochModTeam/Epoch#947]
updated to the latest this morning, errors in server rpt, thou markers are displayed (including the bottom left of the screen) 

heres a pic

https://imgur.com/a/yLRhw

` 9:55:48 "Epoch: Loading static loot"
 9:55:48 Error in expression <OATLOOT) then {
_markers = ["Shipwreck",_wreck] call EPOCH_server_createGlobalMa>
 9:55:48   Error position: <_wreck] call EPOCH_server_createGlobalMa>
 9:55:48   Error Undefined variable in expression: _wreck
 9:55:48 File epoch_server\compile\epoch_looting\EPOCH_server_spawnBoatLoot.sqf, line 29
 9:55:48 Error in expression <hipwrecks;
_shipwrecks = _shipwrecks - [_wreck];
_item = createVehicle["containe>
 9:55:48   Error position: <_wreck];
_item = createVehicle["containe>
 9:55:48   Error Undefined variable in expression: _wreck
 9:55:48 File epoch_server\compile\epoch_looting\EPOCH_server_spawnBoatLoot.sqf, line 25
 9:55:48 Error in expression <OATLOOT) then {
_markers = ["Shipwreck",_wreck] call EPOCH_server_createGlobalMa>
 9:55:48   Error position: <_wreck] call EPOCH_server_createGlobalMa>
 9:55:48   Error Undefined variable in expression: _wreck
 9:55:48 File epoch_server\compile\epoch_looting\EPOCH_server_spawnBoatLoot.sqf, line 29
 9:55:48 Error in expression <hipwrecks;
_shipwrecks = _shipwrecks - [_wreck];
_item = createVehicle["containe>
 9:55:48   Error position: <_wreck];
_item = createVehicle["containe>
 9:55:48   Error Undefined variable in expression: _wreck
 9:55:48 File epoch_server\compile\epoch_looting\EPOCH_server_spawnBoatLoot.sqf, line 25
 9:55:48 Error in expression <OATLOOT) then {
_markers = ["Shipwreck",_wreck] call EPOCH_server_createGlobalMa>
 9:55:48   Error position: <_wreck] call EPOCH_server_createGlobalMa>
 9:55:48   Error Undefined variable in expression: _wreck
 9:55:48 File epoch_server\compile\epoch_looting\EPOCH_server_spawnBoatLoot.sqf, line 29
 9:55:48 Error in expression <hipwrecks;
_shipwrecks = _shipwrecks - [_wreck];
_item = createVehicle["containe>
 9:55:48   Error position: <_wreck];
_item = createVehicle["containe>
 9:55:48   Error Undefined variable in expression: _wreck
 9:55:48 File epoch_server\compile\epoch_looting\EPOCH_server_spawnBoatLoot.sqf, line 25
 9:55:49 "Loaded Server FSM"
 9:55:49 "Loading Settings for VIP event..."`

**Comment by vbawol** [comment]
That last commit should fix this.

**Comment by natoed** [comment]
yep its fixed wow that's was fast thx

**Comment by vbawol** [comment]
Nice, thanks for the confirmation. 👍
