### ISSUE TITLE
Jet ejector seat

### ISSUE THREAD

**Issue by Tarabass999** [EpochModTeam/Epoch#959]
ejector seat from jets teleports players to the end of the map. ( Where the first sapper has been placed )
That makes ejector seat unusable.

Use Epoch Mod 1.0 build(1077) + default Epoch AH

**Comment by ravmustang** [comment]
I was looking at this when you originally posted the issue, but have not the time yet to do any testing.
I can however provide an open view of the ejection function in the meantime.
Im sure more eyes on this function will help get it fixed quicker.

https://pastebin.com/WqfuQzEz

**Comment by Tarabass999** [comment]
Thank you DirtySanchez. I really have no knowledge about how to fix this. Just could imagine that it has something to do with that:

  //make pilot invulnerable for the transition time
    private _wasVulnerable = isDamageAllowed _pilot;
 
    if (_wasVulnerable) then
    {
        _pilot allowDamage false;
    };

But it wouldn't make sence with the situation the teleport happens. It teleports me everytime exactly in that moment, the ejectorseat-parachute opens.
So maybe there are some more qualified eyes than mine to look at it aswell.

**Comment by morgoth0** [comment]
I have ejection seats only from CUP and use infiSTAR... just tested and ejection seats with those do not have this problem...

**Comment by Tarabass999** [comment]
No I only use Epoch AH.. not infistar.
But I didn't check it with CUP only the Jet DLC ones

**Comment by Tarabass999** [comment]
I tested now the ejector seats from RHS. Those are triggering aswell but when the parachute is open, it disappears and lets me fall down. No teleport happens with RHS ejector seats.

**Comment by Tarabass999** [comment]
That player teleport to the border of the map still happens after ejecting seat opens parachute in Epoch 1.1

**Comment by Ignatz-HeMan** [comment]
Is there something in Logs from Antihack?

**Comment by Tarabass999** [comment]
Real life work was calling.. will take another look to it tomorrow morning and report about rtp

**Comment by Tarabass999** [comment]
So the only entry i can find after that is:
"ADMIN: Invalid Vehicle detected and deleted B Alpha 1-1:1 (Tarabas) REMOTE with B Alpha 1-1:1 (Tarabas) REMOTE driving"

**Comment by Ignatz-HeMan** [comment]
Can you try to change this line:
https://github.com/EpochModTeam/Epoch/commit/4df4a3f684bc708ce7d9eee81f6bad7f04219e7b

**Comment by Tarabass999** [comment]
That fixed it.. I tried 3 times.. would be cool to add this :)

Thank you He-Man (closed)

**Comment by Tarabass999** [comment]
I just leave it open after I saw you're testing with it. It can get closed for me. :)


Edit : Tested on different servers. Works fine

**Comment by Ignatz-HeMan** [comment]
Okay, thx for testing and the feedback.
I have added it to the experimental files
