### ISSUE TITLE
RPT spam after MoneyDrop init

### ISSUE THREAD

**Issue by REALMWTH** [EpochModTeam/Epoch#966]
Log:
 

> 7:37:32 "EPOCHDebug: createGlobalMarkerSet -2- not a class markerClass, nothing to create"
>  7:37:32 Error in expression < pushBack (getMarkerColor _x);
> }forEach _markers;
> 
> 
> if!(getNumber(_cfgEpoch >> ">
>  7:37:32   Error position: <_markers;
> 
> 
> if!(getNumber(_cfgEpoch >> ">
>  7:37:32   Error Undefined variable in expression: _markers
>  7:37:32 File epoch_server_settings\EpochEvents\MoneyDrop.sqf, line 77
>  7:37:32 Error in expression <yTime * _timeMultiplier), _showMarkers, _markers, _originalColors, _decayMarkerC>
>  7:37:32   Error position: <_markers, _originalColors, _decayMarkerC>
>  7:37:32   Error Undefined variable in expression: _markers
>  7:37:32 File epoch_server_settings\EpochEvents\MoneyDrop.sqf, line 97
>  7:37:34 Error in expression <edColor;
> };
> }else{
> if ((getMarkerColor (_markers select 0)) isEqualTo _interacte>
>  7:37:34   Error position: <_markers select 0)) isEqualTo _interacte>
>  7:37:34   Error Undefined variable in expression: _markers
>  7:37:39 Error in expression <edColor;
> };
>

**Comment by Ignatz-HeMan** [comment]
Have you added the changes into these files?

https://github.com/EpochModTeam/Epoch/blob/47cce77649174deff6147a383aab80bfb81d078f/Sources/epoch_config/Configs/CfgMarkerSets.hpp#L205-L211

https://github.com/EpochModTeam/Epoch/blob/47cce77649174deff6147a383aab80bfb81d078f/Sources/epoch_server_settings/config.cpp#L140-L148

**Comment by Ignatz-HeMan** [comment]
Please also check this last fix (just changed):
https://github.com/EpochModTeam/Epoch/commit/7822902e0f22c5448ec07f785d994c91f03cba0f

**Comment by REALMWTH** [comment]
now fixed
