### ISSUE TITLE
Dynamic Vehicles Respawn Time

### ISSUE THREAD

**Issue by Vampurica** [EpochModTeam/Epoch#975]
Currently dynamically spawned vehicles are respawned up to the max slots on a server every restart.

What if instead vehicle slots were "timed out" after a dynamic vehicle is killed so that it takes a configurable amount of time before another vehicle could dynamically spawn in that slot?

The slot should still be usable if a player were to purchase a vehicle to prevent issues.

**Comment by Ignatz-HeMan** [comment]
In my opinion it is okay as it is. I think there is no need for a timeout. 
Why do you think it is needed? 
At the end, admins can not adjust the number of wanted vehicles correctly as it is random based on destroyed vehicles. If you want / need it, feel free to do a pull request. 
Of course we are open to add prepared scripts into Epoch if we think it makes sense for all servers or it is configureable.
