### ISSUE TITLE
Equality check of array against code

### ISSUE THREAD

**Issue by mr-guard** [EpochModTeam/Epoch#979]
https://github.com/EpochModTeam/Epoch/blob/3cdc78e2680c20c5ceca504309a852adb06a735b/Sources/epoch_server/compile/epoch_player/EPOCH_server_savePlayer.sqf#L47

Has to be ".. isEqualTo call EPOCH_defaultVars_SEPXVar.." instead

Otherwise compares code to array which is always false.

IDK if there is something more complex going on before to make this a valid check for edge cases.
If so definitely needs a comment

**Comment by Ignatz-HeMan** [comment]
Yeah, you are right.
I have fixed it in the experimental files.
Many thanks!
https://github.com/EpochModTeam/Epoch/commit/0d06bbfba1ee5d8a6a08d782b905359cae116c23
