### ISSUE TITLE
Penalty for killing a player

### ISSUE THREAD

**Issue by BetterDeadThanZed** [EpochModTeam/Epoch#98]
Dayz has humanity. If you kill a player, you lose humanity. Since A3 Epoch doesn't have humanity, I'd like to suggest a variable that could be set by a server admin to take away krypto for killing a player. By default it would be 0 since I know not everyone agrees with this idea. In time, perhaps a reputation system or an alternate penalty system could be developed.

**Comment by vbawol** [comment]
I do have a Karma system planned, and the feedback in that thread is great. Might be in for 0.3 we will see.

**Comment by ZNUfisk** [comment]
http://epochmod.com/forum/index.php?/topic/27346-bounty-hunting-mechanism/
