### ISSUE TITLE
[Question] Zombiespawn Rate, Ryanzombie etc.

### ISSUE THREAD

**Issue by BrutalBirdie** [EpochModTeam/Epoch#980]
I can't find a proper documentation how to increase/decrease Zombie-spawn rates. Also a general guide for Windows and Linux servers for Ryanzombie Mod would be very good.

I had to read one hour of useless forum posts until I found an information that seems to be right, https://board.nitrado.net/support-de-german-only/support-gameserver/arma/arma-3-epoch-mod/84263/zombie-rate/

but thees options did nothing.
// Antagonists
antagonistChanceTrash = 1.0;
antagonistChancePDeath = 1.0;
antagonistChanceLoot = 1.0;

I even set the antagonistChances[] in [CfgEpochClient.hpp](https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_config/Configs/CfgEpochClient.hpp) to 0.50 each and still no zombie spawn what so ever.

Please give me some advice. (and yes, the @ ryanzombies mod is loaded properly, and yes I checked if ryanzombies is enabled in [CfgEpochClient.hpp](https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_config/Configs/CfgEpochClient.hpp))

**Comment by vbawol** [comment]
Hello, @BrutalBirdie this was changed a bit.

The chance is here: https://github.com/EpochModTeam/Epoch/blob/fc45cb8f69dae78c76b26fc563182752df3d9b9c/Sources/epoch_config/Configs/CfgEpochClient.hpp#L88

And limit here:

https://github.com/EpochModTeam/Epoch/blob/fc45cb8f69dae78c76b26fc563182752df3d9b9c/Sources/epoch_config/Configs/CfgEpochClient.hpp#L102


Hope that helps, if you have any more questions please let us know.

Also, just to be sure you need to have the ryanzombies mod enabled both server and client side.

**Comment by BrutalBirdie** [comment]
Hey @vbawol thanks for answering but I already set "EPOCH_RyanZombie_1",0.50 and ["EPOCH_RyanZombie_1",25]
and yes @ryanzombie is loaded properly.

```
addons[]=
{
        "A3_epoch_config",
        "a3_map_altis",
        "a3_characters_f",
        "Ryanzombies"
};
-mod=@Epoch;@ryanzombies

0:23:00                            Ryan's Zombies & Demons |         @ryanzombies |      false |             GAME DIR | a8e40ba92bbdc0eed3beaad1536a841396a2083d |  62057cac | /opt/server/serverfiles/@ryanzombies
```
bikey also added to keys etc. etc. etc. etc
Is there a way to spawn the Ryanzombies, Zombies, etc. for debugging?

Maybe I should note then I am running a Linux server, since a Windows Server is not an option for me.

**Comment by vbawol** [comment]
Do you see 
"Epoch: Ryanzombies detected"
in your servers RPT?

**Comment by BrutalBirdie** [comment]
Jup ```server.log:266: 0:23:42 "Epoch: Ryanzombies detected"```
But the point is, not even normal zombies spawn more then normal even tho I increased the spawns.

**Comment by BrutalBirdie** [comment]
@vbawol I unpacked epoch.altis.pbo and edited the files then repacked it and uploaded it to the server. I gues that the right way, or not?

**Comment by vbawol** [comment]
Yes, those changes to the CfgEpochClient.hpp are in the mission file.

**Comment by BrutalBirdie** [comment]
jup, thats what I did. Still no changes in the spawn rates what so ever...

**Comment by BrutalBirdie** [comment]
So far nothing helped...
Can I use MCC with Epoch to test if I can spawn Zombies etc.?

**Comment by vbawol** [comment]
Ok, I will take a look at it on the dev test server. What sort of spawn numbers are you attempting?

**Comment by BrutalBirdie** [comment]
I tried from normal, normal x2, to 0.50 to 1.0

**Comment by BlackhatEspeed** [comment]
I'm also having problems as well with this, my server needs more zombies 🗡

**Comment by Ignatz-HeMan** [comment]
Our next Update (EpochMod 1.3.3.1) will have an build in RyanZ Spawner.
We are going to push it within the next days!
