### ISSUE TITLE
Wrong params

### ISSUE THREAD

**Issue by mr-guard** [EpochModTeam/Epoch#981]
https://github.com/EpochModTeam/Epoch/blob/a9dc9f044b58894f536b8dffbcc9ee013dc6ea8d/Sources/epoch_code/compile/functions/EPOCH_client_updatePlayerStat.sqf#L44

first and second args of EPOCH_fnc_updatePlayerStats are of type "object"

a fix could be:

[player, objNull, _statType, _adjust, false, Epoch_personalToken] remoteExec ["EPOCH_fnc_updatePlayerStats",2];

However, it could be you need to edit some filters (e.g. Remoteexec or so)

**Comment by vbawol** [comment]
Thanks for the fix!
