### ISSUE TITLE
Battleye speedup

### ISSUE THREAD

**Issue by mr-guard** [EpochModTeam/Epoch#982]
Battleye filters are known to be a huge performance bottleneck.
Since there are a lot of script commands that you simply kick for in any case, why not remove them from BE filters and use:
https://community.bistudio.com/wiki/CfgDisabledCommands
instead

This way battleye does not need to scan for them.

**Comment by mr-guard** [comment]
A full list of said commands
`
loadFile
setFriend
setAmmo
enableFatigue
setUnitRecoilCoefficient
callExtension
enableCollisionWith
removeAllItems
removeAllActions
createTeam
forceAddUniform
removeAllMPEventHandlers
setDammage
displaySetEventHandler
addMPEventHandler
removeAllMissionEventHandlers
ctrlClassName
ctrlModel
ctrlModelDirection
ctrlModelSide
ctrlModelUp
setGroupIconsVisible
setGroupIconsSelectable
setGroupIconParams
addGroupIcon
`

**Comment by Ahriana** [comment]
this has been suggested in the past #728

**Comment by vbawol** [comment]
@RZSenfo This does sound like a good reason to make use of CfgDisabledCommands, and I am all for removing scripts.txt filters lines. If you want please make a pull request against the experimental branch to add these changes. 👍

**Comment by vbawol** [comment]
Thanks for the suggestion and the pull request https://github.com/EpochModTeam/Epoch/pull/983
